### ISSUE TITLE
Incorrect guidelines/colors/usage documentation for $inverse-support-04

### ISSUE THREAD

**Issue by timmawson** [carbon-design-system/carbon-website#100]
On guidelines/color/usage the documentation of `$inverse-support-04` for the White and Gray 10 themes incorrectly states it uses the color token **Blue 40** (`#408BFC`). 

**Blue 40** is in fact defined as `#6EA6FF`, the correct color token for `$inverse-support-04` should be **Blue 50** which is `#408BFC`, as specified.

Incorrect token Blue 40:
![image](https://user-images.githubusercontent.com/51777005/60669183-9a5a3780-9e65-11e9-81af-2361debd3a4d.png)

Correct token Blue 50 (as used by `$interactive-04` for the White theme):
![image](https://user-images.githubusercontent.com/51777005/60669285-e0170000-9e65-11e9-877c-ba25b66fce9d.png)

**Comment by aagonzales** [comment]
This has been fixed (maybe a while ago).
