### ISSUE TITLE
[Notification]: code tab, component example mobile bug - Chrome

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon-website#1002]
## Detailed description

> Describe in detail the issue you're having.

In mobile view, the notification text is running off of the actual notification box.
In desktop view, it seems like the text is also too close to the edge, needs more padding.
This might be just because it's in the demo container.

> Is this issue related to a specific component?

Notification

> What browser are you working in?

Chrome (dev tools to view mobile)
![notification code-mobile](https://user-images.githubusercontent.com/32556167/52499746-b9e48100-2ba1-11e9-8c11-ec134a7ee18e.png)
![notification code](https://user-images.githubusercontent.com/32556167/52499747-b9e48100-2ba1-11e9-814a-d340f98d7fbf.png)

**Comment by asudoh** [comment]
Saw removing below style in DOM inspector will fix the problem:

```css
.component-example .bx--inline-notification__subtitle {
  min-width: 300px;
}
```

@alisonjoseph Can you recall what [the code](https://github.com/carbon-design-system/carbon-website/pull/637/files#diff-9c9bc0982475ca0b227a978fd65443c7R102) is for? Thanks!
