### ISSUE TITLE
Number Input: Arrows position is off

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon-website#1006]
Arrows placement is above the input. Could be a component that is not updated:

Website: 
<img width="742" alt="screen shot 2019-02-08 at 1 02 16 pm" src="https://user-images.githubusercontent.com/12533409/52500096-bdc4d300-2ba2-11e9-834a-e425ef881bd2.png">

Component: 
<img width="1346" alt="screen shot 2019-02-08 at 1 06 55 pm" src="https://user-images.githubusercontent.com/12533409/52500142-e0ef8280-2ba2-11e9-9aa0-a1f57a17ea06.png">

**Comment by emyarod** [comment]
this should have been resolved in https://github.com/IBM/carbon-components/pull/1622, but let me know if the website's dependencies are indeed up to date
