### ISSUE TITLE
Incorrect glossary entry

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-website#101]
Seems the definition of `run` needs to be updated:

<img width="596" alt="Screen Shot 2019-07-08 at 10 23 36 AM" src="https://user-images.githubusercontent.com/11928039/60830437-13120a00-a16c-11e9-8cb7-b5c0b616ccb8.png">

**Comment by alisonjoseph** [comment]
@connor-leech @janchild fyi

**Comment by connor-leech** [comment]
Assigned myself! Thanks, Alison

**Comment by connor-leech** [comment]
This has been addressed: https://www.carbondesignsystem.com/guidelines/content/action-labels/#run
