### ISSUE TITLE
[tabs] update docs to have 1px inbetween tabs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1011]
The docs currently say we have 2px between tabs, but we actually have 1px.
- [x] Updated in code
- [ ] Update style table
- [ ] Update image

**Comment by gillibrand** [comment]
The React implementation seems to have 2px. Which is right again?

**Comment by laurenmrice** [comment]
There should be 1px space, not 2px. so that must be a code bug as well.

**Comment by gillibrand** [comment]
Any chance of getting this fixed sooner that later? Small thing, but it's causing inconsistencies for teams updating existing UI toolkits to a Carbon-look.

**Comment by laurenmrice** [comment]
@gillibrand  https://github.com/carbon-design-system/carbon/issues/5774 I made an issue to update in code, and will tackle docs once the component fix is made.

**Comment by laurenmrice** [comment]
Fixed in code and in the documentation on our website 👍🏻
