### ISSUE TITLE
Fix spelling in image

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#1013]
![image](https://user-images.githubusercontent.com/20912642/52503313-cae5c000-2baa-11e9-9567-1c289e529d98.png)

https://next.carbondesignsystem.com/patterns/disabled-states#hidden

Tooltip text in image has a typo: should be "explaining"

**Comment by chrisconnors-ibm** [comment]
fixed https://www.carbondesignsystem.com/patterns/disabled-states#additional-warning
