### ISSUE TITLE
QA: Guidelines>Motion - Under "Entrance easing", both tabs bring a user back to the top of the page

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#1014]
## Detailed description

> Describe in detail the issue you're having.
When clicking either tab under "Entrance easing" a user is driven back to the top of the page

> What browser are you working in?
Firefox

> What version of the Carbon Design System are you using?
10

## Steps to reproduce the issue

1. Click on either tab under "entrance easing"

**Comment by connor-leech** [comment]
This also happens with tabs below "Exit easing"

**Comment by alisonjoseph** [comment]
this was fixed
