### ISSUE TITLE
"Vanilla JS" should read "JavaScript"

### ISSUE THREAD

**Issue by Culip** [carbon-design-system/carbon-website#1017]
Some _"Code"_ pages lay out HTML 5 snippets with different JavaScript methodologies. Here is an example: https://www.carbondesignsystem.com/components/tooltip/code/. There are tabs reading _"Vanilla JS"_ followed by _"React"_, _"Angular"_, and so on. HTML snippets without no JavaScript lines at all are shown in code blocks that start with _"Copyright IBM Corp."_

![image](https://user-images.githubusercontent.com/459585/76698340-57dd3180-6667-11ea-8227-81e20e80033e.png)

_"Vanilla JS"_ is no more than a joke which might fail to meet the IBM corporate documents standards. As of March 25, 2020, I search the IBM site for this term and only see 11 results.

![image](https://user-images.githubusercontent.com/459585/76698475-f4540380-6668-11ea-9e5a-bc5e2ed2e45e.png)

I propose that we rephrase those labels by _"Carbon (required)"_, _"Carbon"_ (followed by _"Carbon & Angular"_, and so on) or something that clearly indicates generic JavaScript with standard functions but without (third-party) libraries.

**Comment by vpicone** [comment]
Considering React and Angular are also "JavaScript", that name doesn't really make sense. 

"vanilla js" is just a way to refer to native (standards-based, non-extended) JavaScript. Generally in context it is a term to contrast with using libraries and frameworks (jQuery, React, etc).  Although websites like http://vanilla-js.com/ like to play with the name, it's what we've called our non-framework library for the entirety of it's existance so changing it right now isn't really an option.


We're in  the process of removing the vanilla code snippets anyway, so I'm going to close this for now. Let me know if you have any more questions!
