### ISSUE TITLE
[docs] Inconsistent documentation on modal design

### ISSUE THREAD

**Issue by chchwil** [carbon-design-system/carbon-website#102]
## Detailed description

There seems to be some slight disagreement on spacing between the modal header and body on this page of the website: https://www.carbondesignsystem.com/components/modal/style#structure

In the 'Structure' table of styles, the margin-bottom for the `bx--modal-header` class is set at `8 / 0.5`.

But in each example diagram below, the space between the header and body of the modals is 16 pixels.  Which is the correct spacing?

Screenshots:
![Screen Shot 2019-07-08 at 2 37 21 PM](https://user-images.githubusercontent.com/40363109/60837599-23d37780-a18e-11e9-81f3-b53a50853d85.png)
![Screen Shot 2019-07-08 at 2 39 15 PM](https://user-images.githubusercontent.com/40363109/60837613-30f06680-a18e-11e9-98ed-1f15fae7cbf7.png)
![Screen Shot 2019-07-08 at 2 40 05 PM](https://user-images.githubusercontent.com/40363109/60837648-4c5b7180-a18e-11e9-8f02-2aee48ca0505.png)
![Screen Shot 2019-07-08 at 2 40 09 PM](https://user-images.githubusercontent.com/40363109/60837652-4d8c9e80-a18e-11e9-9cdd-ff7869d93b70.png)

**Comment by aagonzales** [comment]
This has been update (awhile ago) and now reflects the same value of the correct 16px of the header margin-bottom.
