### ISSUE TITLE
Code demo - theme bugs

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#1037]
![image](https://user-images.githubusercontent.com/2753488/77438649-17428e00-6db4-11ea-8eca-2cecc6513b6f.png)

fyi @jnm2377

**Comment by aagonzales** [comment]
Adding other theming bug issues.

- [ ] **Code snippet bug**
The code snippets themes aren't rendering correctly for `singe` and `multi-line`. Themes effected: Gray10, Gray 90, Gray100

- What it's showing:
![image](https://user-images.githubusercontent.com/11670886/78405329-e2111980-75c5-11ea-8a51-f44cd5f32779.png)

- What it should be:
![image](https://user-images.githubusercontent.com/11670886/78405434-1be22000-75c6-11ea-95b6-14a99ddfa8ba.png)

**Comment by aagonzales** [comment]
- [ ] **Data table:** Zebra stripes aren't rendering correctly

![image](https://user-images.githubusercontent.com/11670886/78406224-d1fa3980-75c7-11ea-95e2-18127f354da6.png)

**Comment by aagonzales** [comment]
- [ ] **Date picker** Themes not rendering correctly in the calendars
![image](https://user-images.githubusercontent.com/11670886/78406459-48973700-75c8-11ea-90d3-3a93489046d8.png)

**Comment by aagonzales** [comment]
- [ ] **Pagination:** Theming bug "items per page" not changing color.

![image](https://user-images.githubusercontent.com/11670886/78407364-34ecd000-75ca-11ea-886b-d0de55d887f2.png)

**Comment by aagonzales** [comment]
- [ ] **Radio buttons**: label text not rendering correctly 

![image](https://user-images.githubusercontent.com/11670886/78407418-65cd0500-75ca-11ea-9f20-326352fc9977.png)

**Comment by aagonzales** [comment]
- [ ] **Tooltip:** default tooltip popup not rendering correctly in Gray 90 and Gray 100 themes. Icon and definition tooltip are correct. 

Is showing:
![image](https://user-images.githubusercontent.com/11670886/78407778-2eab2380-75cb-11ea-810e-82627e20fce0.png)

Should be:
![image](https://user-images.githubusercontent.com/11670886/78407730-1804cc80-75cb-11ea-8964-97ff6ec5bca8.png)
