### ISSUE TITLE
QA - Select (usage tab) - Link broken because the page doesnt exist

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1039]
The 'Cards' link isnt linking to a page because Cards doesn't currently exist? Should we just take this out?

![Screen Shot 2019-02-08 at 4.31.31 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/9205134e-f4c6-4821-bc94-1956922a837d)

**Comment by connor-leech** [comment]
Cards are referenced multiple times on the page. I'm adjusting language to remove theses references, as we no longer support Cards (last supported version was V7.)
