### ISSUE TITLE
Inline code snippet missing background when pulled in from ibm/carbon-components

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1040]
Inline code snippet is missing background sometimes
Eg. on **Checkbox/Style** https://next.carbondesignsystem.com/components/checkbox/style

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/504c9488-ce57-402d-a850-e8b292598d62)

**Comment by jnm2377** [comment]
Is this more like a large scale inconsistency you're pointing out that requires going in and checking all component docs? @shixiedesign I saw that as well. It seemed like most didn't have inline code snippet styles for the tables in the docs, but some did. Wondering how it should be? Anything that is a css class should be inline code? Selectors should not? @alisonjoseph @claycrenshaw I can go in and check all the docs/update, but this is in a different repo.

**Comment by shixiedesign** [comment]
I understand now! I will make a different issue for docs update in components repo! Thanks @jnm2377
