### ISSUE TITLE
QA - [global] in mobile: the anchor links on top of pages have too much spacing above and below links.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1044]
I think it should be 48px but check with @jeanservaas @shixiedesign 

<img width="526" alt="screen shot 2019-02-09 at 8 19 10 am" src="https://user-images.githubusercontent.com/32881239/52521869-8823f680-2c43-11e9-8d73-a0edd51b496f.png">

**Comment by shixiedesign** [comment]
When on mobile spacing should always adjust to be smaller. Above & below anchor links, usually (`md` - `max` breakpoint) 80px is correct. On `sm` breakpoint, we can change to use 48px. 👍
