### ISSUE TITLE
QA - [Layout]: Too much space above and below large images/videos

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1047]
@jeanservaas @shixiedesign 

<img width="665" alt="screen shot 2019-02-09 at 8 45 09 am" src="https://user-images.githubusercontent.com/32881239/52522161-26fe2200-2c47-11e9-9d53-9e9bf97498de.png">

**Comment by mjabbink** [comment]
<img width="778" alt="screen shot 2019-02-09 at 8 45 05 am" src="https://user-images.githubusercontent.com/32881239/52522164-2c5b6c80-2c47-11e9-8d41-f9890aea7f43.png">

**Comment by mjabbink** [comment]
<img width="694" alt="screen shot 2019-02-09 at 8 44 33 am" src="https://user-images.githubusercontent.com/32881239/52522165-31b8b700-2c47-11e9-8668-5071c7d8e43c.png">

**Comment by mjabbink** [comment]
<img width="867" alt="screen shot 2019-02-09 at 8 44 28 am" src="https://user-images.githubusercontent.com/32881239/52522171-37160180-2c47-11e9-9f3e-03c43259bbbb.png">

**Comment by alisonjoseph** [comment]
duplicate

**Comment by jeanservaas** [comment]
#1000
