### ISSUE TITLE
QA - [Components / Status]: The green in “check icon” is too light

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1049]
@jeanservaas @shixiedesign 

<img width="807" alt="screen shot 2019-02-09 at 8 50 38 am" src="https://user-images.githubusercontent.com/32881239/52522228-f2d73100-2c47-11e9-82b5-627d42ed7797.png">

**Comment by alisonjoseph** [comment]
This page is getting redesigned, there won't be check marks anymore.
