### ISSUE TITLE
fix: Redirects for removed pages

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1050]
We need some redirects for three of the items in Experimental. These pages were removed (because the content was way out of date) and so we will redirect the old links to the latest version on the PAL site. 

https://www.carbondesignsystem.com/experimental/cards/usage should go here: https://pages.github.ibm.com/CDAI-design/CDAI-design-website/components/card/usage/

https://www.carbondesignsystem.com/experimental/dashboard-widgets/usage should go here: https://pages.github.ibm.com/CDAI-design/CDAI-design-website/components/widget/usage/

https://www.carbondesignsystem.com/experimental/order-summary-template/usage should go here: https://pages.github.ibm.com/CDAI-design/CDAI-design-website/patterns/order-summary/usage/

**Comment by vpicone** [comment]
closed by https://github.com/carbon-design-system/carbon-website/pull/1051
