### ISSUE TITLE
QA- [component / date picker]: broken in mobile Safari

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1052]
@joshblack @jeanservaas

**Comment by mjabbink** [comment]
![img_2348](https://user-images.githubusercontent.com/32881239/52522367-1b602a80-2c4a-11e9-8d4a-97a25c4230bf.jpg)

**Comment by mjabbink** [comment]
![img_2347](https://user-images.githubusercontent.com/32881239/52522375-2b780a00-2c4a-11e9-9a6a-3b3b8ba1547a.jpg)

**Comment by alisonjoseph** [comment]
todo: move this to carbon-components repo

**Comment by asudoh** [comment]
Moved to: http://IBM/carbon-components#1775
