### ISSUE TITLE
>2 Tabs change to dropdown on mobile

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1054]
When there are 3 or more Tabs on top banner, they need to switch to dropdown. Pages like Accessibility have this issue: 

![image](https://user-images.githubusercontent.com/15144993/52525993-e2d74580-2c77-11e9-957d-2e3f2c4fdd61.png)

**Comment by asudoh** [comment]
Seems that page tabs style has its own style, rather than inheriting Carbon tabs style. We need to see whether we should start inheriting Carbon tabs style or we should add dropdown support to website tabs style.

**Comment by alisonjoseph** [comment]
this is a duplicate #578
