### ISSUE TITLE
[docs] Data Viz section: Advanced charts and dashboard updates

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1058]
## [docs] Data Viz section: Advanced charts and dashboard updates

<br>

- [ ]  Advanced charts page; double check the images to be correct. Is Alluvial correct for example? Heat map? All the static images in advance charts should be double checked to be correct use of color and chart anatomy specs. Alluvial, heatmap, tree, choropleth map, proportional symbol, connecting lines

<br>

- [ ] Dashboard page needs love, samples, etc.

<br>

- [ ] Clean up Shixie's master charts file and add it as a downloadable resource

<br>

- figure out where to put it

- may be ok to remove the palette download since it's included in the chart file

- jan or connor proofread / spell check

**Comment by mjabbink** [comment]
Correct me if I’m wrong @jeanservaas 

Enable cards and add “design only” tags for: Heatmap, Parallel coordinates and tree map and link to Advanced page:

parallel coordinates: https://www.carbondesignsystem.com/data-visualization/advanced-charts#parallel-coordinates

heat maps: https://www.carbondesignsystem.com/data-visualization/advanced-charts#heat-maps

tree maps: https://www.carbondesignsystem.com/data-visualization/advanced-charts#tree-maps

**Comment by mjabbink** [comment]
@jeanservaas should this be closed?

**Comment by vpicone** [comment]
@jeanservaas this one good?

**Comment by mjabbink** [comment]
@jeanservaas Closing this and create new issue when you get back into the dashboard business.
