### ISSUE TITLE
Search results are lacking

### ISSUE THREAD

**Issue by joshhus** [carbon-design-system/carbon-website#1060]
## Detailed description

> Describe in detail the issue you're having.

Wanted to look up capitalization for Abbreviations. Specifically, QTY or Qty or Qty. or don't abbreviate. Searched on "Abbreviations" on home page 
https://www.carbondesignsystem.com/
and on:
https://www.carbondesignsystem.com/guidelines/content/general

No results for Abbreviations. or abbreviations

So I thought I would try "Acronyms" and "acronyms" even though QTY is not an acronym, just to check search. No results on Acronyms, so I'm left to browse. 

> What did you expect to happen? What happened instead? What would you like to see changed?

Basic search should work. If "Acronyms" and "Abbreviations" standards don't exist, and that's why they aren't found, they should be added. 

> What browser are you working in?

Firefox on Windows 10

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes
![image](https://user-images.githubusercontent.com/16542757/77956056-3e5efb00-729f-11ea-9de2-fde018c9b974.png)

**Comment by vpicone** [comment]
@joshhus I'm confused, if the guidelines don't exist, how would the search have picked them up?

Is this issue really "search results are lacking" or should it be "no guidelines for acronyms" instead?

**Comment by vpicone** [comment]
@joshhus the guidelines you're looking for are [here](https://www.carbondesignsystem.com/guidelines/content/guidance/#when-to-use-capital-letters). Searching for 'capitalization' would get you there.

Unfortunately it looks like our search didn't pick up that instance of acronym. We use a client-side search library. It has some limitations, but unfortunately we're unable to improve that mechanism without more heavy duty/3rd party solutions like algolia.

We're gonna log this into feature requests and close this for now, thanks for raising the issue!

**Comment by joshhus** [comment]
> 
> 
> @joshhus the guidelines you're looking for are [here](https://www.carbondesignsystem.com/guidelines/content/guidance/#when-to-use-capital-letters). Searching for 'capitalization' would get you there.
> 
> Unfortunately it looks like our search didn't pick up that instance of acronym. We use a client-side search library. It has some limitations, but unfortunately we're unable to improve that mechanism without more heavy duty/3rd party solutions like algolia.
> 
> We're gonna log this into feature requests and close this for now, thanks for raising the issue!

Try adding search terms to the page meta data, e.g.. Where there's a will there's a way.
