### ISSUE TITLE
QA- [Layout page / breakpoints section]: repeat text and make caption 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1060]
@jeanservaas @shixiedesign

Make "For best results, test designs and code at each of these standard breakpoints." a caption size with caption spacing under table.

Under table remove this text "Create custom breakpoints to accommodate special needs, by writing your own media queries and CSS rules. Refer to the grid code package for more information."  — it is a duplicate of the copy above the table in main body copy.

<img width="1139" alt="screen shot 2019-02-10 at 4 42 54 pm" src="https://user-images.githubusercontent.com/32881239/52540070-7c275a00-2d53-11e9-87bf-024cc57dcce1.png">

**Comment by shixiedesign** [comment]
Currently table doesn't take caption styling. We'd have to make that an enhancement for later. 
Duplicate sentence is fixed. 
https://github.com/carbon-design-system/carbon-website/pull/1064

**Comment by mjabbink** [comment]
you can add this sentence into the body copy above table as well. So all copy is in the body. no caption.

**Comment by shixiedesign** [comment]
@mjabbink it's already in the body above! 👍
