### ISSUE TITLE
QA: Spacing Page fixes

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1067]
Bug:
Can't get inline svgs to be the right color (even though it says they're right in the markdown (See spacing-02 and spacing-03 and layout-03)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/1c6e30a4-38d3-4ba4-a5b7-f16e97c18e23)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/8e1aa819-4af1-4563-900c-36026e5935eb)

Need to top-align in-line svg blocks with type (right now type is bottom aligned and svgs are top aligned in the fields.:

Enhancement:
![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/5d871b8d-ac2c-4b56-9ea1-dfbb3c23f94b)

**Comment by jeanservaas** [comment]
Hey @alisonjoseph this was another fix I wanted to prioritize... at least to get those misaligned colors fixed... Mike thought we specifically changed the colors to emphasize certain spacers... he didn't realize it was a mistake. Just don't want to confuse people.

**Comment by alisonjoseph** [comment]
👍 moved it to to do this sprint
