### ISSUE TITLE
QA - [Layout and Motion]: animations should go back to beginning with play button

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1083]
@shixiedesign right now all videos end on a dark screen but I think they should revert to the same start frame with play button again.

Also, any plans to have the DL play button soon?

<img width="1199" alt="screen shot 2019-02-11 at 7 51 36 pm" src="https://user-images.githubusercontent.com/32881239/52603984-24621f00-2e37-11e9-8d64-2cf8f2475556.png">

**Comment by shixiedesign** [comment]
Changed vimeo setting of **After Video** to **Loop**! It worked 🎉
