### ISSUE TITLE
[Pattern - Filtering]: Icon usage for overflow menu

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-website#1083]
## Detailed description

In the filtering pattern (https://www.carbondesignsystem.com/patterns/filtering), the icon `settings--adjust` is used across all screenshots that show an overflow menu. Is this intentional or should we use the `filter` icon for implementation?

## Additional information

![image](https://user-images.githubusercontent.com/28265588/78267462-4caf5000-7507-11ea-99da-885294769838.png)

![image](https://user-images.githubusercontent.com/28265588/78267375-373a2600-7507-11ea-88b5-d50c7ee4d44b.png)

![image](https://user-images.githubusercontent.com/28265588/78267352-30131800-7507-11ea-9447-660fa744470f.png)

**Comment by laurenmrice** [comment]
@janhassel Yes, this should be showing the filter icon and not the settings adjust icon. We need to update that. 👍🏻

**Comment by janhassel** [comment]
@laurenmrice Thanks for the clarification! 👍
