### ISSUE TITLE
QA - [Motion]: Two animations should be wider I think.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1084]
@shixiedesign Should the two animation in "Easing" be wider? If you want them this size disregard but tit seems odd these two are singled out to be smaller.

Also, the spacing between them seems tight. 

<img width="724" alt="screen shot 2019-02-11 at 8 00 27 pm" src="https://user-images.githubusercontent.com/32881239/52604259-1f519f80-2e38-11e9-893f-dbb40e3456c2.png">

<img width="445" alt="screen shot 2019-02-11 at 8 01 26 pm" src="https://user-images.githubusercontent.com/32881239/52604264-22e52680-2e38-11e9-816e-92e5bff7c139.png">

**Comment by mjabbink** [comment]
These also all go to dark replay screen versus the same start screen and play button.

<img width="1199" alt="screen shot 2019-02-11 at 7 51 36 pm" src="https://user-images.githubusercontent.com/32881239/52604286-44dea900-2e38-11e9-9d20-6ff6862ee890.png">

**Comment by shixiedesign** [comment]
The dark screen is a vimeo issue 😢 so won't be resolved until we get our custom video component. 

I just added more space in my PR from today: https://deploy-preview-1077--carbon-website.netlify.com

About the 2 easing videos being 8 col, I was talking about it with @jeanservaas . I thought they were such simple content and felt too horsy at 12 col width, and if we do 8col we can fit both videos on screen so the do-don't comparison is clearer. However, I agree this is quite weird being the only ones getting this treatment. Lemme know which you'd prefer. It's an easy fix! @mjabbink

**Comment by mjabbink** [comment]
The dark screen can be removed without custom component I believe. DL did it I believe. Ask Sadek.

**Comment by shixiedesign** [comment]
Ah you are right Mike!!! I double checked vimeo and found a setting that made video loop....should have done this earlier 👍 
Now I'm triple checking the qualities. A lot of videos' playback is blurry.

**Comment by shixiedesign** [comment]
Accidentally clicked close button

**Comment by shixiedesign** [comment]
Fixed in PR https://github.com/carbon-design-system/carbon-website/pull/1311
