### ISSUE TITLE
QA: Getting started>Developers>Vanilla - Getting started index links loops to top of page

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#1087]
## Detailed description

At [this address](localhost:8000/getting-started/developers/vanilla), the What's included index link brings a user back to the top of the page.

> What browser are you working in?

Firefox

> What version of the Carbon Design System are you using?

10

## Steps to reproduce the issue

1. Step one
Visit the aforementioned page and click the "What's included" index link

**Comment by alisonjoseph** [comment]
@connor-leech if you want to take a stab at fixing this, the anchor links are auto-generated for the headings and special characters are stripped out. so instead of linking to `what's-included` it should link to `whats-included`

**Comment by connor-leech** [comment]
Will do, thank you
