### ISSUE TITLE
Homepage video

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1089]
- [x] Need 4 style frames for 4 shots. Basically 11 seconds of Carbon B roll. 
- [x] Editing
- [ ] Make dev issue for posting video on homepage

**Comment by aagonzales** [comment]
This sprint:
- [ ] Talk to David about schedule
- [ ] Plan out script or shots

**Comment by jnm2377** [comment]
👀 fyi potential a11y issue re: video/other animations longer than 5 secs. https://github.com/IBM-Design/design-website/issues/355 Came up in `/design` site.

**Comment by shixiedesign** [comment]
## Carbon homepage video is ready for development!
Vimeo link:
https://vimeo.com/322021187
Don't forget the pause button 👍

**Comment by shixiedesign** [comment]
https://github.com/carbon-design-system/carbon-website/issues/1273
