### ISSUE TITLE
Please provide guidance about text line lengths

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon-website#1089]
## Summary
In a DUX review I was in this week I saw a product UI that had no maximum text line length set, so at full screen, sentences run from one side of the UI to the other. 
![image](https://user-images.githubusercontent.com/9316771/78385453-c4e34780-75d3-11ea-94ab-715cf23f54ee.png)

We know that this negatively affects readability, so it would be great if Carbon included guidance about setting sensible text line lengths.

FYI: I found this guidance on the  [DUX Design Heuristics](http://dux-program-website.w3ibm.mybluemix.net/about/design-heuristics/) page of the **DUX Program** micro-site:
> On content pages, line lengths are neither too short (<50 characters per line) nor too long (>100 characters per line) when viewed in a standard browser width window.

**Comment by jeanservaas** [comment]
@tomwaterton 

yes, I totally agree Carbon needs to include guidance on this specific to product because I'm seeing this too.

Here's what IDL has to say about it in the meantime.

https://www.ibm.com/design/language/typography/type-basics#comfortable-reading

**Comment by tomwaterton** [comment]
FYI: the Cloud, Data & AI **voice and tone guide** now includes guidance on this topic:
- [Set text line lengths](https://pages.github.ibm.com/cdai-design/guidance/voice-and-tone/content-principles#set-text-line-lengths)

(The guidance being the same as what is already shown on the [DUX Design Heuristics](http://dux-program-website.w3ibm.mybluemix.net/about/design-heuristics/) page)

**Comment by janchild** [comment]
Thanks, @tomwaterton. I have a draft underway for Carbon that will probably go into a bit more detail. I'll be working with Mike Abbink on it. This is good to see in the meantime.

**Comment by aagonzales** [comment]
From a technical standpoint, we can't actually set character counts. Normally, in carbon when we try to restrict the line length we'll set a max width (which could be a percentage of a page/container or a hard value).
