### ISSUE TITLE
Use $expressive-heading-03 NOT $heading-03 for our website H3 from now one

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1092]
Hey @alisonjoseph just wanted to let you know, @joshblack updated our type package and we need to update our H3 token now. 

$heading-03 has been removed... 

Our Website H3 needs to be $expressive-heading-03 from now on.

(if someone wants to use it in product as a fixed value, use $productive-heading-03)

**Comment by tw15egan** [comment]
We can update this once the newest version of `carbon-elements` is released
