### ISSUE TITLE
UI Shell header example doesn't show nav items.

### ISSUE THREAD

**Issue by wkeese** [carbon-design-system/carbon-website#1094]
https://www.carbondesignsystem.com/components/UI-shell-header/code shows a few examples that say they have navigation links (in the top black menubar), but they aren't showing up.

**Comment by jakubfaliszewski** [comment]
@jnm2377 
Please, overwrite styles of `.bx--header__nav` for this examples in your CodeSandbox projects.

**Comment by jnm2377** [comment]
@wkeese I'm not sure what example you're referring to. When I look at the examples, the ones that have nav items seem to be working fine.
<img width="1230" alt="Screen Shot 2020-04-09 at 3 55 54 PM" src="https://user-images.githubusercontent.com/32556167/78939986-bcc75400-7a7a-11ea-83a8-29177464d9c1.png">
<img width="1226" alt="Screen Shot 2020-04-09 at 3 56 00 PM" src="https://user-images.githubusercontent.com/32556167/78939992-bdf88100-7a7a-11ea-9008-9231e1b1b061.png">
<img width="1216" alt="Screen Shot 2020-04-09 at 3 55 48 PM" src="https://user-images.githubusercontent.com/32556167/78939995-bf29ae00-7a7a-11ea-8f2c-465c4245edea.png">

**Comment by jakubfaliszewski** [comment]
@jnm2377 
There's a media query that set `display: none` for `bx--header__nav` for screen with size below 66rem. Just try to open those examples in smaller window

**Comment by wkeese** [comment]
Yah exactly, you'll see the problem if you open the examples in a smaller window.  Like @jakubfaliszewski said you could avoid the confusion by adding CSS to the example to always show the nav items.   A second choice would be to add explanatory text to tell people to make their browser windows wider.
