### ISSUE TITLE
Support inline use-case for ComponentDemo

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#1097]
We currently are hoping to offer multiple code snippets per-component page to detail out scenarios in which someone could use the component. As a result, it seems like we need an inline variant of the `ComponentDemo` that has the following functionality:

- [ ] Ability to render without theme switcher
- [ ] Potentially a smaller spacing model / be more compact
- [ ] Pin component to top left instead of center center as certain components are jarring when pushed from center center (accordion)

**Comment by joshblack** [comment]
cc @aagonzales tagged with visual role based on our Slack convo!

**Comment by aagonzales** [comment]
I think it being odd on a few components is better than have set heights taking up excessive space with inline docs (A) or we'll need to set a couple of different height sizes to help balance it out (B).

A
![Component_Demo-sm-2](https://user-images.githubusercontent.com/11670886/78608433-8abdb400-7826-11ea-9805-e656839411ba.png)

B
![Component_Demo-sm-3](https://user-images.githubusercontent.com/11670886/78608450-914c2b80-7826-11ea-8b4f-e69f0e2df86e.png)

**Comment by joshblack** [comment]
Gonna close this actually pending on a decision for where this content should live 👀

**Comment by aagonzales** [comment]
@joshblack do you mean where does the coded component live or where the demo is used in context of the carbon website?

**Comment by joshblack** [comment]
@aagonzales totally ignore that last message! Was a mistake 😄

**Comment by alisonjoseph** [comment]
For most components the variable height I think makes the most sense. What about just adding a height prop if we need a larger min-height for a few specific cases? (accordion, expandable table etc).

**Comment by vpicone** [comment]
@aagonzales so for example here, opening the accordion would push the rest of the page content down?

**Comment by vpicone** [comment]
We'd tackle this with https://github.com/carbon-design-system/carbon-website/issues/870

**Comment by aagonzales** [comment]
Yes, it would push the content. I think accordion and data table would be the only components to have this problem.

**Comment by aagonzales** [comment]
Could accordion and data table (oh and tree view when it comes) demos just have different fixed demo window?

**Comment by vpicone** [comment]
@aagonzales I think it'd be weird to create a unique experience just for two components. The idea is to add an `inline` prop to the ComponentDemo now. Adding a `fixed` version gets weird.

They could just use the current implementation though, as opposed to reaching for the inline ComponentDemo prop when documenting those pages. The only real difference is it's a little bit taller.

**Comment by aagonzales** [comment]
Ok then let's to do the flexible one for all then.
