### ISSUE TITLE
Icon Library: Add sticky enhancement to search/category

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#110]

**Comment by vpicone** [comment]
We need a spec for desktop and mobile. 

For desktop the page tabs will also be stuck and so we should take that into account when mocking it up.

**Comment by jeanservaas** [comment]
@vpicone Mike mentioned that maybe Pete or Diana from the Brand team could take a design pass on the sticky enhancement. It's a unique case because they're input fields. 

I think the idea is to fold what they come up with there into the wedding cake spec for the icon library page.

**Comment by jeanservaas** [comment]
This issue is addressed here:
https://github.com/carbon-design-system/design-language-website/issues/183
