### ISSUE TITLE
No email to contact

### ISSUE THREAD

**Issue by ksurendra** [carbon-design-system/carbon-website#1103]
## Summary
Can you include a link or email to send an email about questions/feedback

## Relevant information
On the website https://www.carbondesignsystem.com/ by the footer section: 

![Screen Shot 2020-04-10 at 1 09 48 PM](https://user-images.githubusercontent.com/902972/79012757-ada0de80-7b2c-11ea-8109-e7a9e8afb68c.png)

But cannot find the email or a link to send questions/feedback. Although i can do on github

**Comment by aagonzales** [comment]
Should say "Email us at carbon@us.ibm.com or open ..."
