### ISSUE TITLE
[component demo] breadcrumb

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#1105]
The modifier "current page" should be changing the last/furtherest right breadcrumb not the first. This is a [ux/usage problem](https://ibm-studios.slack.com/archives/C0M053VPT/p1586865815395000) to show the other way. It is accurate in the [storybook](https://react.carbondesignsystem.com/?path=/story/breadcrumb--current-page).

![image](https://user-images.githubusercontent.com/11670886/79237323-a41cbc80-7e33-11ea-8936-7e5b22d63ee1.png)

**Comment by jnm2377** [comment]
The functionality for the knobs here works different than storybook. The knobs work by taking the code and running a function that looks for a match of the "prop owner" (the component name), and then it inserts the prop after that matched code. If there are multiple instances of the component name, it'll always be applied to the first instance of the component bc the function always returns the first match. Trying to specify an `nth` match could get very complicated to make it work for all of the demos. If we don't want it to be added to the first breadcrumb, then the easiest fix would be to remove the knobs for this demo and just hard code `isCurrentPage` on the second breadcrumb or just have one breadcrumb.

**Comment by jnm2377** [comment]
The storybook current page breadcrumb is hardcoded btw.

**Comment by aagonzales** [comment]
Hmm ok yeah showing on the first is just wrong so I guess we can just remove the prop because I think using `current page` is kind of an edge case anyways.
