### ISSUE TITLE
website ssl cert expires? 

### ISSUE THREAD

**Issue by myan9** [carbon-design-system/carbon-website#1108]
I saw the following in Safari:  https://www.carbondesignsystem.com

![Screen Shot 2020-04-15 at 4 23 58 PM](https://user-images.githubusercontent.com/21212160/79384783-83d52680-7f35-11ea-9f2b-ae579820df9a.png)

**Comment by starpit** [comment]
i see this, too

**Comment by vpicone** [comment]
Thanks! Looking into this.

**Comment by vpicone** [comment]
This is resolved now
