### ISSUE TITLE
Sidebar loses transition

### ISSUE THREAD

**Issue by nilooy** [carbon-design-system/carbon-website#1110]
I was structuring a dashbaord with three main components, (Sidebar, Topbar and Content)

I used HeaderContainer to share { isSideNavExpanded and onClickSideNavExpand } between Topbar and Sidebar.
Basically, Topbar is updating Sidebar's isSideNavExpanded but when i click the button in topbar, sidebar expands but without transition. Is there any workaround for that?

**App.js**
`      <HeaderContainer
        render={({ isSideNavExpanded, onClickSideNavExpand }) => (
          <>
            <TopBar
              isSideNavExpanded={isSideNavExpanded}
              onClickSideNavExpand={onClickSideNavExpand}
            />
            <SideBar isSideNavExpanded={isSideNavExpanded} />
            <Content>
              <h1>Dashboard</h1>
            </Content>
          </>
        )}
      />`

**TopBar.js**

`<Header aria-label="test">
    <SkipToContent />

    <HeaderMenuButton
      aria-label="Open menu"
      onClick={props.onClickSideNavExpand}
    />
  </Header>`

**Sidebar.js**

`    <SideNav
      isFixedNav
      expanded={isSideNavExpanded}
      isChildOfHeader={false}
      aria-label="Side navigation"
    >
{/* test.........content */}
   </SideNav>
`

Thanks in advance

**Comment by jnm2377** [comment]
Hi @theprogboy could you create a code sandbox replicating the issue? It'd be helpful for us to figure out what is going wrong. Thanks!
