### ISSUE TITLE
odd side scroll artifact at multiple browser widths

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1112]
## Detailed description

[Icon Library](https://www.carbondesignsystem.com/guidelines/icons/library) and [Pictogram Library](https://www.carbondesignsystem.com/guidelines/pictograms/library) seem to have picked up an odd side scroll artifact at multiple browser widths in Chrome and Safari (not firefox)

> What browser are you working in?
Chrome Version 81.0.4044.113 (Official Build) (64-bit)
Safari Version 13.1 (15609.1.20.111.8)

## Steps to reproduce the issue

1. got to https://www.carbondesignsystem.com/guidelines/icons/library
2. start to narrow the window
3. observe side scroll artifact
## Additional information

- Screenshots or code
https://ibm.enterprise.slack.com/files/W4BSKD8RK/F01280S449J/screen_recording_2020-04-17_at_11.16.20_am.mov

**Comment by vpicone** [comment]
use firefox

**Comment by vpicone** [comment]
jk

**Comment by chrisconnors-ibm** [comment]
<img width="1535" alt="Screen Shot 2020-04-17 at 11 15 52 AM" src="https://user-images.githubusercontent.com/35537391/79587426-8738f100-80a0-11ea-9e5e-cddc958c70b5.png">

**Comment by joshblack** [comment]
This seems to be addressed in latest, closing this out. Let me know if you are still observing this behavior!
