### ISSUE TITLE
Icons need meta data to facilitate search

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1117]
### Problem: 
Currently icons are only search-able by their file names, which is not friendly and users often doesn't know what key word to search for. 

### Task: 
We need to get together and write synonyms (or copy-paste synonyms) into the `metadata.yml` file in icon repo. This is a necessary step to make our icons search-able, and needed for implementing icon library design.

**Comment by designertyler** [comment]
Here's a list of the most commonly searched terms on the site. This should help figure out which popular terms are not showing any results and what to use for alternate meta data tags.

Most searched terms
https://ibm.box.com/s/lsohvlh5e8xxx8u1vxx2lhfzd0kazn7o

Most search terms that bring back no results
https://ibm.box.com/s/7fevcth5i8jey0qtu7jiepyguju03v2j

**Comment by shixiedesign** [comment]
Waiting for scaffold file to be created: https://github.com/carbon-design-system/carbon-website/issues/1180

**Comment by shixiedesign** [comment]
Josh will be doing a second pass of the yml scaffolding (https://github.com/IBM/carbon-elements/issues/464), then we can start filling in content of:
https://github.com/IBM/carbon-elements/blob/master/packages/icons/metadata.yml

**Comment by shixiedesign** [comment]
WIP right now.

**Comment by shixiedesign** [comment]
Done!
