### ISSUE TITLE
QA - [Components / Inline loading]: Instantiating header too close to code snippet

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1120]
https://next.carbondesignsystem.com/components/inline-loading/code

@shixiedesign @jeanservaas 

<img width="589" alt="screen shot 2019-02-13 at 8 46 20 pm" src="https://user-images.githubusercontent.com/32881239/52756793-8efa9280-2fd0-11e9-857b-6b6e247c2459.png">

**Comment by jeanservaas** [comment]
We are tracking all the code tab Read me formatting problems in this issue:

https://github.com/IBM/carbon-components/issues/1769
