### ISSUE TITLE
QA - [Components / Content switcher] Spacing issues in several places

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1121]
https://next.carbondesignsystem.com/components/content-switcher/code

@jeanservaas @shixiedesign some issues below with tight headers and text to snippets. as well as the head and next line of header being too confusing against each other. First image below on the top two with stacked header situation

<img width="673" alt="screen shot 2019-02-13 at 8 50 44 pm" src="https://user-images.githubusercontent.com/32881239/52756976-295ad600-2fd1-11e9-991e-15422173fa06.png">

—

<img width="823" alt="screen shot 2019-02-13 at 8 50 01 pm" src="https://user-images.githubusercontent.com/32881239/52756980-2eb82080-2fd1-11e9-97fc-e2c0e2dfc93a.png">

**Comment by jeanservaas** [comment]
This is a larger issue about all of the Read me documentation not being formatted correctly; we are tracking it here:

https://github.com/IBM/carbon-components/issues/1769

These are not issues that we can get to in markdown directly, so they're a little hard to clean up... it's on the roster for this sprint.
