### ISSUE TITLE
QA - [Components / Code snippet]: “Show more” in  Multi line code snippet

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1122]
https://next.carbondesignsystem.com/components/code-snippet/code

@jeanservaas @shixiedesign @aagonzales 
Shouldn’t the show more be like how you treat it in Carbon site code snippet with a line as a separator?

<img width="1093" alt="screen shot 2019-02-13 at 8 55 24 pm" src="https://user-images.githubusercontent.com/32881239/52757259-172d6780-2fd2-11e9-8454-7671544f95fe.png">

—

<img width="800" alt="screen shot 2019-02-13 at 8 55 28 pm" src="https://user-images.githubusercontent.com/32881239/52757263-1ac0ee80-2fd2-11e9-92d4-43003ae411e5.png">

**Comment by mjabbink** [comment]
Should be like this no?

<img width="1147" alt="screen shot 2019-02-13 at 8 58 38 pm" src="https://user-images.githubusercontent.com/32881239/52757286-2ad8ce00-2fd2-11e9-9892-6765f1a8af9c.png">

**Comment by jeanservaas** [comment]
Yes, we have an issue for it:
https://github.com/carbon-design-system/carbon-website/issues/908
