### ISSUE TITLE
combine Digital and Carbon design kit page

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon-website#1126]
### Summary
The [Carbon Design kit page](https://next.carbondesignsystem.com/getting-started/designers) is currently pointing to the [Digital Design kit page](ibm.com/standards/web/design-kit) for the box implementation. It may be better to combine these into one experience so that all designers get the same on-boarding treatment. This needs design, content and dev.

Mike is requesting a re-recording of the box setup instructions (because I have an outdated desktop screen design 😞 ) and we need to add a video and instructions for people to self-service add themselves to the design kit box folder. This would be a good time to do this change.

### Justification
There are currently 2 pages and we want to combine them down to one. We can also take the burden and time off Anna and I to add people to the box folder if it turns self service.

### Desired UX and success metrics
Success means IDL, Carbon & Digtial can point to the same place to get designers setup with the kit

### "Must have" functionality
Instructions for:
- Box drive
- Sketch cloud
- Github download

### Specific timeline issues / requests
No specific timeline requests, sooner would be better since the video needs to be re-done.

### Available extra resources
The Digital Design kit page can be used as a draft starting point and feel free to add/edit it.

**Comment by connor-leech** [comment]
At the moment, the Getting Started page shows three different methods to get set up with Sketch. We also mention a separate process for internal users, a form of guidance we want to move away from.

The new Getting Started page should focus only on cloud-based Sketch libraries and we should discourage users straying from this method of getting the kit.

The page should also feature a breakdown of the contents of each library that make up the kit, and a section of resources to reach out to.

**Comment by connor-leech** [comment]
Working on this via https://github.com/carbon-design-system/carbon-website/pull/1288

**Comment by eraymond25** [comment]
Discouraging any other method beyond sketch cloud will:
1. not allow teams to create a place for add-ons to be hosted (especially for those teams that have internal only patterns)
2. not allow a place for assets like .ase, .clr, .ai files (and any new tooling files other than .sketch) to be hosted

**Comment by chrisconnors-ibm** [comment]
we can link to the repos, but not describe them as as a way to install the sketch kit. we can also expand our contribution guidance to include the details needed for that use case
