### ISSUE TITLE
Need to add fluid spacing in website

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1127]
Problem:
Right now if we have an 80px margin bottom / top in desktop, we have the same amount of space in mobile, which is too much. 

James from the digital team has contributed a fluid spacing scale that we could try out. 

https://github.com/IBM/carbon-elements/blob/master/packages/layout/scss/_spacing.scss#L27-L43

We need to:

- [ ] try out these fluid spacers  -- @joshblack is up for giving these a test drive to see how they respond.

- [ ] if they're too problematic, then we need to decrease some vertical spacing values at breakpoints

Most important: All 80px spacers become 48px spacers at tablet and below.

**Comment by jeanservaas** [comment]
Hey @alisonjoseph I think even if we don't use the fluid spacers, I think we still need to change our 80px spacings to 48px at 672 and below relatively soon. Mike's also got an open issue about it too.

https://github.ibm.com/duo/website/issues/1363#event-43202785

**Comment by alisonjoseph** [comment]
Whoever grabs this issue should sync up/pair with @jeanservaas on the correct values.

**Comment by vpicone** [comment]
NOT STALE

**Comment by vpicone** [comment]
Strictly fluid spacing is usually an accessibility issue as it's not kind on zooming interactions. Happy to add the media queries if this isn't already handled in the theme.
