### ISSUE TITLE
[Page] Glossary page redesign

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1134]
Mike gave [some feedback](https://github.com/carbon-design-system/carbon-website/issues/569#issuecomment-462982464) on the current Glossary page design. In summary, explore design variations that include: 
- large type leading selected alphabetic zone. Maybe even has a small horizontal rule that spans one or two columns
- make sure the beginning of the letter nav is aligning to the type on the left
- the alphabet could also be horizontal and be sticky along the top

>You were on to something with the large type leading the selected alphabetic zone. Other than it being outlined, blue and maybe too large it’s a good idea. Bringing scale into help a user anchor is always good and in this case visually nice as well. If one did start to scroll those large letters would be useful. I would love to see you explore this one more time with the large letter in black. A bit smaller and reduce some of the spacing around it. Maybe even has a small horizontal rule that spans one or two columns and hangs out to left like the containers do. Could be a nice touch.

>Also make sure the beginning of the letter nav is aligning to the type on the left (either "common Actions" or the large letter) in some way. Right now there is no relationship which is a design/typography no no.

>the alphabet could also be horizontal and be sticky along the top like the sticky labels or sticky content switcher component.

**Comment by jeanservaas** [comment]
I gave them this spec for the moment so we could push something clean through... definitely think we could have more fun with it, but i don't want it sitting up there much longer in its current state.

I like the idea of rules in our site, but there are a few places i'd like to put them in

![glossary_hierarchy](https://user-images.githubusercontent.com/43144260/52870307-2a911d80-310d-11e9-8d70-be8cb3e30ad3.png)
