### ISSUE TITLE
Broken link for UI shell

### ISSUE THREAD

**Issue by Emily1799** [carbon-design-system/carbon-website#114]
If you go to components, then overview, and scroll down and click UI shell, you are sent to  https://www.carbondesignsystem.com/experimental/ui-shell, which isn't a valid route, so you get 404 not found.

**Comment by connor-leech** [comment]
This is fixed in our [rebuilt site]. We'll be making the switch soon, but you can see it over at https://carbondesignsystem.now.sh/components/overview.
