### ISSUE TITLE
What's New content update

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1142]
Do we want to update or hide some of this What's new content?

If we want to keep it, there are a lot of broken links... could do with a content pass; it's a little janky.

**Comment by aagonzales** [comment]
- [ ] determine intention of "what's new" page. 
- [ ] determine cadence of publications: (per major version, running content?, monthly updates?, auto releases from GitHub deployments?)

**Comment by designertyler** [comment]
Closing. @connor-leech addressed this in a new PR
