### ISSUE TITLE
[Carbon site] / Mobile: Plex Serif is being replaced by Times

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1146]
https://www.carbondesignsystem.com/guidelines/typography/overview#typeface:-ibm-plex

In mobile Chrome and Safari Times replaces Plex

![IMG_5753 (1).jpg](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/190bace2-48c9-491e-91eb-a1728e62111c)

**Comment by vpicone** [comment]
closed by #1147
