### ISSUE TITLE
Distorted icons on resource cards

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1148]
Icons on these resource cards are distorted on [Resource page](https://next.carbondesignsystem.com/resources). Top section icons looks pulled too tall, bottom section's icons look too squashed. How did this happen? 😂

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/aca021a6-a3d8-41a1-a0e0-9750aec0e5f5)

**Comment by alisonjoseph** [comment]
<img width="700" alt="screen shot 2019-02-19 at 2 55 51 pm" src="https://user-images.githubusercontent.com/2753488/53046777-79fd8380-3456-11e9-9e68-0b9333247245.png">

The css has the images set to 32x32 px. They look ok in chrome for me? What browser are you in where they look stretched?

**Comment by tw15egan** [comment]
They are sized at 32x32 in CSS, but the images themselves are not square (121x138). If we don't want them to get squished, we need square image assets.

<img width="444" alt="screen shot 2019-02-19 at 3 25 15 pm" src="https://user-images.githubusercontent.com/11928039/53048580-b59a4c80-345a-11e9-93ef-46895747670b.png">
