### ISSUE TITLE
Missing loading pattern page in v10

### ISSUE THREAD

**Issue by johnjesse** [carbon-design-system/carbon-website#115]
There used to be a pattern page for loading in v9, I had a quick discussion with @aagonzales about it on slack and the content is expected to still be relevant but it's missing from the v10 site. 

v9 - https://v9.carbondesignsystem.com/patterns/loading

**Comment by joshblack** [comment]
Should be available over in: https://www.carbondesignsystem.com/patterns/loading-pattern ! Let me know if this doesn't help and I can re-open the issue :smile:
