### ISSUE TITLE
[component demo] header on Loading component page

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1151]
Need to omit the `Loading` header on the Loading component page since we do not have a header on any other component page above the demo and it is inconsistent.

Screenshot:
<img width="1671" alt="Screen Shot 2020-05-01 at 3 25 42 PM" src="https://user-images.githubusercontent.com/43969356/80839094-293bfb80-8bc0-11ea-84cf-1c745b98e89a.png">

**Comment by laurenmrice** [comment]
@vpicone @jnm2377

**Comment by vpicone** [comment]
@laurenmrice if you click the `Edit in GitHub` link at the bottom of the page you can just delete the `## Loading` line. 

No need to tag individuals in issues, we'll triage and fix stuff as fast as we can.

**Comment by laurenmrice** [comment]
This was something I was going to mention in the dropdown pr today, but it was merged before I reviewed it.

**Comment by vpicone** [comment]
It's all good, we probably wanted a separate issue for it anyway.
