### ISSUE TITLE
Two h3 named 'Github repos', second anchor doesn't work

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1153]
URL: https://www.carbondesignsystem.com/resources/

There's two h3's named 'Github repos' so https://www.carbondesignsystem.com/resources/#github-repos links only to the first one.

**Comment by rayandasoriya** [comment]
Hi @jnm2377, I can work on this issue. Can you provide me some follow-up like do we need to change the IDs of these elements to make them unique or is there any other requirement for this issue?
