### ISSUE TITLE
[Carbon X] Pagination component is not rendered correctly

### ISSUE THREAD

**Issue by jendowns** [carbon-design-system/carbon-website#1163]
### Current 
The Carbon X `Pagination` component looks a bit strange in Firefox 65 and Chrome 72: https://next.carbondesignsystem.com/components/pagination/code/

![screen shot 2019-02-19 at 4 09 40 pm](https://user-images.githubusercontent.com/9057921/53051269-0d3bb680-3461-11e9-8e81-f5b1f6626bc3.png)

### Expected
I would expect it to look a bit closer the `Pagination` component in the Carbon X design kit:
![screen shot 2019-02-19 at 4 10 09 pm](https://user-images.githubusercontent.com/9057921/53051360-4f64f800-3461-11e9-8c8f-d7c00768c78f.png)

**Comment by alisonjoseph** [comment]
Thanks for pointing this out 👍 it looks correct over in our experimental storybook, so this is most likely an issue w/ some website styles interfering somehow.

http://react-experimental.carbondesignsystem.com/?selectedKind=Pagination&selectedStory=v2&full=0&addons=1&stories=1&panelRight=0&addonPanel=storybook%2Fstories%2Fstories-panel
