### ISSUE TITLE
Confusion regarding Angular components support and development on the Getting started page

### ISSUE THREAD

**Issue by cal-smith** [carbon-design-system/carbon-website#1164]
The wording in the banner on the "Getting started" page appears to be unclear to a number of users: https://carbondesignsystem.com/get-started/develop/angular/

I know there's a number of changes in progress as far as the definition of "community" vs. "core", and this seems to be another area of confusion - A number of people weren't aware that there is a team dedicated to maintaining `carbon-components-angular`!

I don't have specific wording in mind at the moment, but I definitely wanted to make sure this doesn't get lost. It would be ideal if there's some wording that would make it clear that there _is_ a team assigned and funded, since the current wording doesn't seem to be sufficient.

**Comment by laurenmrice** [comment]
We have fixed this with adding a notification that there is a dedicated team that maintains Angular https://carbondesignsystem.com/developing/angular-tutorial/overview/
