### ISSUE TITLE
Embedded video iframes: default max size style options

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon-website#1167]
Assumed default use-case of video is embedded into the primary column of text, and maximum-size rules are applied to suit thise

These maximum-sizing rules then need to be overwritten inside of particular components (see https://github.com/carbon-design-system/carbon-website/pull/1155 ) 

This keeps markdown authoring simple, but also means there's more maintenance to the Sass—adding this style override for any new component where it's needed. For releasing this as a generalized component in `website-addons`, i'm curious if we should put the max-sizing rules as an option/prop on the video component?

**Comment by alisonjoseph** [comment]
Would this be size, or is it aspect ratio that is throwing off the style? I agree would be good to give the video component more flexibility.
