### ISSUE TITLE
Sans-serif font isn't rendering on website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#1184]
https://next.carbondesignsystem.com/guidelines/typography/overview#typeface-ibm-plex

<img width="752" alt="screen shot 2019-02-22 at 2 26 17 pm" src="https://user-images.githubusercontent.com/2753488/53269214-e9b97b80-36ad-11e9-9659-af12a4b8e613.png">

"IBM Plex Serif" should be rendered as Plex, seems we aren't bringing this font in anymore.

**Comment by asudoh** [comment]
Some history in case it helps; In `v9` codebase we define something like `ibm-plex-sans`. `@carbon/type` defines something like `IBM Plex Serif`. That said, we need `@carbon/type` code to get `IBM Plex Serif` rendered.

**Comment by alisonjoseph** [comment]
we are importing `@import '@carbon/type/scss/font-face/serif';` and I thought this was working at some point. will look in to it more to see what's missing or what changed
