### ISSUE TITLE
Enhancement[Color swatches]: Change color swatches from squares to circles

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1188]
## Enhancement[Color swatches]: Change color swatches from squares to circles

**Why**
To add more softness to Carbon and Lanugage sites; the experience feels so rectilinear the designers were looking for one moment to use a circle that didn't seem like material.io

- [x] change all inline svg color swatches from squares to circles

- [x] change size of swatches (tables only) from 16px to 20px

<br>

**Where (components)**
- Color usage tab component (in the color token component)
- Table components on Color overview page and in the Component style tabs 

<br>

### Examples

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/0b04823d-0217-4051-a2c1-4361cf94f9a6)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/f43bd0fc-548c-4d72-8afb-cc0c1b9ee285)

**Comment by alisonjoseph** [comment]
- [ ] Move to add on repo

**Comment by jeanservaas** [comment]
@alisonjoseph @vpicone this is a change that Mike wants for IDL and Carbon
