### ISSUE TITLE
Move the Icons contribution page to "How to contribute" section

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1197]
To bring the Icons contribution page in line with changes being made to the Pictograms contribution page.. 
 
I spoke with @mjabbink and he agreed that this page (currently in a tab) could move to the "How to contribute" section on the Carbon website. Icons would sit underneath Components in the left nav IA. 

Corresponding issue and PR for pictograms is here:

- This PR and issue is attached to an IDL issue and PR that can be found below:

  - Issue: carbon-design-system/design-language-website#528
  - PR: carbon-design-system/design-language-website#551

**Comment by mjabbink** [comment]
@janchild @andreancardona The page should not move. The content can be replicated/updated in Carbon site but the issue created for IDL stays in IDL. It’s for the IDL site NOT Carbon site. So to be clear Do Not Move the page.
