### ISSUE TITLE
Add canonical urls to each page

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#1198]
> we need canonical URLs with carbondesignsystem.com baked into every page so even if somebody clones, self-hosts, and doesn't not modify, google ranking would know it's duplicate content and attribute all traffic to our domain.

possible solution? https://www.gatsbyjs.org/packages/gatsby-plugin-canonical-urls/

**Comment by mattrosno** [comment]
Another easy option would be to pass `location` into the `Meta` component if it's not already, as well as the site URL, and use React Helmet to set the canonical `<link>`.
