### ISSUE TITLE
Markdown exposed in rendered page

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1199]
## Title line template: [Title]: Markdown exposed in rendered page @ /experimental/ui-shell/usage

-->

## Detailed description

![image](https://user-images.githubusercontent.com/35537391/53365181-9e51d800-390e-11e9-8d5e-9dcee4659a2b.png)

## Steps to reproduce the issue

1. Navigate to https://next.carbondesignsystem.com/experimental/ui-shell/usage
2. Observe 
![image](https://user-images.githubusercontent.com/35537391/53365230-bde90080-390e-11e9-96dc-c027a83c1d4e.png)

## Additional information

- Screenshots or code
- Notes

**Comment by josefaidt** [comment]
Hi Chris! Is there a space between the header's `###` declaration and the text? Perhaps that may be the issue.
