### ISSUE TITLE
inconsistent side nav styling

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1204]
## Inconsistent Side Nav Styling: Dark on homepage, light on interior pages

-->

## Detailed description

If you navigate to https://next.carbondesignsystem.com/, the side nav is dark; if you navigate to any child page (https://next.carbondesignsystem.com/getting-started/about-carbon) it is light. Shouldn't this be consistent?

## Steps to reproduce the issue

1. Navigate to https://next.carbondesignsystem.com/
2. observe dark side nav
3. Click on "Getting Started", and then "About Carbon"
4. observe light side nav.

## Additional information
<img width="1441" alt="screen shot 2019-02-26 at 9 50 46 am" src="https://user-images.githubusercontent.com/35537391/53422328-4322f280-39ad-11e9-8ec4-681cbcfe953d.png">
<img width="1441" alt="screen shot 2019-02-26 at 9 52 17 am" src="https://user-images.githubusercontent.com/35537391/53422340-4918d380-39ad-11e9-9e7f-5d1ec932c107.png">

**Comment by asudoh** [comment]
This is something I was wondering, if the team has any thoughts on where we'd go with it it'd be great!

**Comment by chrisconnors-ibm** [comment]
still an issue Stalebot
