### ISSUE TITLE
fix[type specs]: quote tokens are supposed to be serifs

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1204]
## fix[type specs]: quote tokens are supposed to be Plex serif but the examples are still in Sans

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/c30e8820-504f-4e22-a04a-811eb12fb2a8)

**Comment by laurenmrice** [comment]
This bug has been fixed. Serif type tokens are showing up as IBM Plex Serif ✅
