### ISSUE TITLE
Mobile search design

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1206]
Define specs for the site search on narrow and mobile screens.

**Comment by shixiedesign** [comment]
Current explorations:
Sketchfile: https://ibm.box.com/s/gjbics0p9bsn8nq0yey69jrw6a7o3io1
![image](https://user-images.githubusercontent.com/15144993/53653943-26d3bf80-3c12-11e9-903a-2f24625e21b1.png)

**Comment by designertyler** [comment]
@shixiedesign Awesome, glad you had these! I think the bottom left one fits the closest to the desktop search results, keeps the site title, and don't get confused with the app switcher on the right.

Let's go ahead with that one. I'll work with dev and get it spec'd out.

**Comment by designertyler** [comment]
Sketch file: https://ibm.ent.box.com/file/428878805259

![sm-320px-4 column copy 6](https://user-images.githubusercontent.com/19270502/55093398-55628000-5082-11e9-8756-b630997365ac.png)
![sm-320px-open-noresults-specs](https://user-images.githubusercontent.com/19270502/55093400-55628000-5082-11e9-9bb6-0a012e17dc10.png)
![sm-320px-open-specs](https://user-images.githubusercontent.com/19270502/55093402-55628000-5082-11e9-91b1-3ab23be44ec3.png)
![sm-320px-results](https://user-images.githubusercontent.com/19270502/55093403-55628000-5082-11e9-8fbe-0fb6c20bd233.png)

**Comment by shinytoyrobots** [comment]
This is not stop ship for v10. Am changing milestone to `v10-update`.
