### ISSUE TITLE
Create a "meet the team" section on the Carbon website

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#122]
We want Carbon to be a growing community.

A big part of growing a community is making sure it's about people, and not just about technology.

We should introduce the core Carbon team, with pictures and short bios, and contact information. This can include leadership, design, and devs.

**Comment by chrisconnors-ibm** [comment]
@designertyler

**Comment by chrisconnors-ibm** [comment]
@jeanservaas 
should include headshots/avatar, role, commits for each member of our team; and then a section for significant contributors.
