### ISSUE TITLE
Visual: Image size problem

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#1226]
This image on https://next.carbondesignsystem.com/getting-started/designers is too large--it is jarring in the context of the page. Possibly size down to 50% of current size?

![image](https://user-images.githubusercontent.com/20912642/53524286-9cba1880-3aa4-11e9-9f21-1dc47f971ef6.png)

@jeanservaas

**Comment by jeanservaas** [comment]
talk to lauren, i'm going to adjust these images.
 
----- Original message -----From: Clay Crenshaw <notifications@github.com>To: carbon-design-system/carbon-website <carbon-website@noreply.github.com>Cc: jeanservaas <jean.ann.servaas@ibm.com>, Mention <mention@noreply.github.com>Subject: [carbon-design-system/carbon-website] Visual: Image size problem (#1226)Date: Wed, Feb 27, 2019 3:34 PM 
This image on https://next.carbondesignsystem.com/getting-started/designers is too large--it is jarring in the context of the page. Possibly size down to 50% of current size?

@jeanservaas
