### ISSUE TITLE
data table header alignment issue (if isSortable is active) 

### ISSUE THREAD

**Issue by yaakov-trackmatic** [carbon-design-system/carbon-website#1226]
Hi,

I have noticed that when applying isSortable to a data table, the headers don't align anymore with items in the table. 

any Assistance to align them will be appreciated!

![Screenshot 2020-05-25 at 14 53 44](https://user-images.githubusercontent.com/65534199/82814721-f7a11200-9e97-11ea-856c-d96f88787c88.png)
![Screenshot 2020-05-25 at 14 53 54](https://user-images.githubusercontent.com/65534199/82814731-fcfe5c80-9e97-11ea-994b-73b5a8595553.png)

**Comment by laurenmrice** [comment]
This bug has been fixed, the header text is still aligned with the cell text when the `isSortable` prop is turned on. ✅
