### ISSUE TITLE
Update Design kit Design Language Library 20px icons

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon-website#1229]
## Detailed description
Not all of the icons have been re-drawn but we should at least update the ones that have.

No particular release date for this, just know that the 20px in the kit are simply scaled down from 32px ones.

## Steps to reproduce the issue
1. Use design kit
2. Open Design Language folder
3. Open Design Language library
4. See 20px icons

## Additional information

- Anna and Erica are the only ones with access to edit the design kit
- with Erica leaving we may need to add 1-2 other people so that the kit is maintained
- we don't want to add to many people because the editors change the kit for over 800 people so it's a big deal to mess something up

**Comment by chrisconnors-ibm** [comment]
this gets corrected by https://github.com/IBM/carbon-elements/issues/484
