### ISSUE TITLE
Search bar functionality

### ISSUE THREAD

**Issue by tsaitsaitsai** [carbon-design-system/carbon-website#1231]
Maybe there's a bug? Cannot find results for components. Example of searching for Notification below: 

<img width="1429" alt="screen shot 2019-02-28 at 2 44 45 pm" src="https://user-images.githubusercontent.com/25189046/53597518-018a7700-3b68-11e9-977a-5e0a1ecc60bf.png">

**Comment by designertyler** [comment]
Thanks for the issue @tsaitsaitsai 

This has been a known issue and we have it tracked in our repo here and might need to reopen an issue with Algolia. We thought it was resolved, but I guess it's not working again.

Closing this one and will continue to track here https://github.com/carbon-design-system/carbon-website/issues/667
