### ISSUE TITLE
SVG pictograms downloaded from the Carbon website are missing stroke/fill.

### ISSUE THREAD

**Issue by elycheea** [carbon-design-system/carbon-website#1232]
## SVG pictograms downloaded from the Carbon website are not rendering correctly.
Seems related to https://github.com/carbon-design-system/carbon/issues/6107 and https://github.com/carbon-design-system/carbon/pull/6109, but we’re seeing this issue again today.

## Detailed description
Downloaded pictograms from the [pictogram library](https://www.carbondesignsystem.com/guidelines/pictograms/library/) are missing color values. Upon brief investigation, it appears that stroke that was included in previous downloaded SVGs are not included in the current downloads. Adding the stroke color back seems to address the issue for our team members.

Our analysts reported that pictograms they downloaded last week were working as expected, but today they were “blank.”

| Previously behavior | Current behavior |
--|--
![image](https://user-images.githubusercontent.com/1717398/83190030-d04c7e00-a0ff-11ea-9e0b-e1624cbd8dc6.png) | ![image](https://user-images.githubusercontent.com/1717398/83190095-e8240200-a0ff-11ea-8fb5-a493f5351a4b.png)

> What browser are you working in?
Analyst and I were using Firefox and Chrome respectively and were both able to reproduce the issue.

Chrome 83.0.4103.61.

## Steps to reproduce the issue

1. Access Carbon design system [pictograms](https://www.carbondesignsystem.com/guidelines/pictograms/library)
2. Download the pictogram (Video was one of the pictograms in question but issue seems to affect all pictograms we’ve tried) using **Download SVG** button.
3. Open SVG in browser, Powerpoint, or Sketch.
4. SVG appears without a set/default stroke color.

## Additional information
Seems like this should have been addressed https://github.com/carbon-design-system/carbon/issues/6107 and https://github.com/carbon-design-system/carbon/pull/6109, but we’re seeing this issue again today.

**Comment by mjabbink** [comment]
This should be resolved.
