### ISSUE TITLE
Write metadata for component search

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1235]
Following a similar format as https://github.com/IBM/carbon-elements/blob/a1463cb2d1730cf808e81bcd34589fdfab322ab8/packages/icons/metadata.yml

- name
- alias
- category

**Comment by shixiedesign** [comment]
Josh will be doing a second pass of the yml scaffolding (https://github.com/carbon-design-system/carbon-website/issues/1428), then we can start filling in content.
