### ISSUE TITLE
Nested checkboxes pattern

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/carbon-website#1236]
## Summary

I documented a nested checkboxes pattern to outline the interactions that occur between the parent and children checkboxes, including the indeterminate state. This is mentioned briefly in the "When to use" section of the checkbox component under "Lists with sub-selections", but I went into more detail in my pattern. 

## Relevant information

It is documented in [this box note](https://ibm.box.com/s/3ncjxklfctgym5b0jddb5u8dlno11g37). My question is how to proceed with contributing, since it's already mentioned in the Checkbox page, could we go into more detail right there? Or does it make more sense to submit this as a separate pattern and maybe include a link to it in the "Lists with sub-selections" paragraph?

**Comment by garciaam** [comment]
@aagonzales @joshblack I am working David Levinson on this extension/pattern. Could you advise what is the best course of action based on the info I provided above?

**Comment by aagonzales** [comment]
@garciaam Hello! This is great content and we'd love to include it. Though I wouldn't actually classify this as a "pattern" those are normally a little meatier and involve flows. I think this would just live somewhere with the checkbox component [usage](https://www.carbondesignsystem.com/components/checkbox/usage) documentation. 

There are two ways to go about contributing this:
1. You can share the content like you already did and we can pick what content to add and where
2. Or you can open a PR where you've incorporated then content on your own. This is super easy to do, just scroll to the bottom of the component page and click "edit this page on Github."

@laurenmrice do you see an easy way to incorporate some of this content into the existing Checkbox documentation. Maybe add a "nested checkbox" section under behaviors?

**Comment by laurenmrice** [comment]
Yep, I think we can definitely add this in and it is a good expansion on what we reference in the "when to use" section.  Having a nested section under the behavior section would be a good place for it.

**Comment by garciaam** [comment]
@laurenmrice cool! so is this something you are easily able to do with the content I've provided in the box note? let me know how you'd like to proceed? I am open to submitting a PR if that's the fastest/easiest way!

**Comment by laurenmrice** [comment]
You can submit a PR with the content and images I pulled from your boxnote below. I think that would be the easiest. We can review the content and visuals further once the pr is up. 👍🏻

--------------------------------------------------------------------------------------------------

The “Nesting” section we are going to add can go under the “Behaviors” section and after “States”. The indeterminate state was introduced in the states section, so this would be a nice transition into nesting. 

Also we could look into using real content for the images if you have product examples of what the parent/child checkboxes would actually say. 

--------------------------------------------------------------------------------------------------

### Nesting
Checkboxes can be nested when a parent and child relationship is needed. Users can either select an entire set of options or only a subset.

Checking the parent checkbox will automatically check all its nested children checkboxes. Unchecking the parent checkbox will automatically uncheck all the children checkboxes.

![dropdown-usage-9a](https://user-images.githubusercontent.com/43969356/83461683-f723f080-a42e-11ea-82a2-167cc08c4338.png)

Checking a child checkbox, if at least one other child checkbox remains unchecked, will automatically check the parent checkbox in the indeterminate state. If all child checkboxes are already checked, will automatically check the parent checkbox in the default checked state.

![dropdown-usage-9b](https://user-images.githubusercontent.com/43969356/83461553-a613fc80-a42e-11ea-81a9-6df6de0ee405.png)

**Comment by andrea-gm** [comment]
@laurenmrice thanks! I've created [the PR](https://github.com/carbon-design-system/carbon-website/pull/1245)
