### ISSUE TITLE
The main page is not well aligned

### ISSUE THREAD

**Issue by nomadus** [carbon-design-system/carbon-website#1244]
When I navigate to https://www.carbondesignsystem.com/components/accordion/usage it is shown as in the attached picture

![image](https://user-images.githubusercontent.com/3382143/83354287-67703a80-a379-11ea-9f44-529c3e24b946.png)

**Comment by connor-leech** [comment]
Hi @nomadus! Can you please include what browser and OS you're using, as well as possible steps to recreate?

**Comment by nomadus** [comment]
Hi, it is Google Chrome is up to date
Version 83.0.4103.61 (Official Build) (64-bit). To re-create, you just need to browse to the above site.

**Comment by tw15egan** [comment]
Do you have any more info on how we can recreate this? I'm also running Chrome latest and not seeing this behavior. 

![website-bug](https://user-images.githubusercontent.com/11928039/83556850-73691300-a4c5-11ea-9e6f-d14727e16496.gif)

**Comment by nomadus** [comment]
It is ok with Firefox, I am on Windows 10, and this happens with latest MS Edge as well

**Comment by tw15egan** [comment]
Hmm, just tested on a Win 10 machine and didn't see any issues on Chrome or Edge...

Do you have any magnification settings set on the browser? 
Is there any display zoom set (right-click on the desktop --> display preferences)? 
Does this happen at all screen sizes?

Not sure where the issue could be coming from and unable to debug since I cannot reproduce

**Comment by nomadus** [comment]
When I resize the browser to 80%, it is OK, but does not work with 100% (default)

**Comment by emyarod** [comment]
I would need more details (screen resolution, etc) to try and reproduce the issue but I can't at the moment

![image](https://user-images.githubusercontent.com/8265238/83566665-fe5a0580-a4e5-11ea-8a5f-7b722d5c6b21.png)
