### ISSUE TITLE
UI shell thumbnail image is missing

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1246]
It missing, then added, and now it's missing. Could this be related to the mdx update?

![Screen Shot 2019-03-01 at 10.27.19 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/33681923-d2c2-488e-9023-d8e259bc9422)

**Comment by alisonjoseph** [comment]
this broke when I updated the component status page, I had it as "UI Shell" when it should be "UI shell".
