### ISSUE TITLE
Component demo theme switcher has animation style bug

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#1250]
When using the Component Demo with a connected mouse that has a scroll wheel, a user ends up seeing the scroll bar while the dropdown for theme switching is opened or closed.

![demo](https://user-images.githubusercontent.com/3901764/83691753-55300f80-a5b8-11ea-9f16-5cd59bd520ff.gif)

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
