### ISSUE TITLE
Homepage: Start designing & developing buttons are off grid

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1252]
The images next to the buttons are stopping short of the grid. They should be aligned with the buttons.

![Screen Shot 2019-03-04 at 11.34.15 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/3619522d-4177-44b3-a8cf-031115aa626f)

**Comment by alisonjoseph** [comment]
duplicate
