### ISSUE TITLE
bug[homepage cards]: Getting started cards are out of alignment / off grid

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1258]
These cards should be flush with the right edge of the graphic like they used to be, they are correct in Safari but off alignment in Chrome and Firefox.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/483104fd-469e-4bbb-be92-6d0554b8681f)

**Comment by alisonjoseph** [comment]
this is a duplicate of #1252
