### ISSUE TITLE
docs: Add mobile touch screen interactions

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1264]
Add mobile touch screen interactions to the component usage pages already updated:
- Accordion
- Breadcrumb
- Checkbox
-Date picker
- Dropdown
- Link
- Modal
- Notification

**Comment by laurenmrice** [comment]
This may have to be put on hold. From talking to devs, it seems that we don't offer specific changes to our touch interactions when it comes to mobile, components just become responsive. This may make more sense for petes carbon native mobile designs?

**Comment by janchild** [comment]
Shall we close, @laurenmrice?

**Comment by laurenmrice** [comment]
Yeah we can close and revisit/reopen when mobile is further along. I think this would be great content to have.
