### ISSUE TITLE
[component index] design refinement and spec

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#1266]
Remaining tasks:
- [x] define filters and sorting to include in MVP.
- [x] Quick audit on where kits are on the PAL sites
- [x] Create final spec.
- [x] Create component images

**Comment by aagonzales** [comment]
# Design spec

**Deliverables:**
- **Sketch file**: https://ibm.box.com/s/gwxmambgzbwk31uakytq27s2zz1zei66 (page "6/22 updates" has final designs)
- **Audit**: Kit audit is a page with in the Sketch file. Conclusion: no consistency across pal kits in kit location or kit structure. 
- **Data:** talk to @jillianhowarth for latest content.
- **Component images:** TBD work still needed to create asset

**File includes:**
- Responsive break points
- Filtering behavior
- Scrolling behavior
- Card spec

## Responsive behavior
See Sketch file for higher fidelity 

![image](https://user-images.githubusercontent.com/11670886/85633588-22b98580-b63f-11ea-931b-2f5122683bd9.png)

## Scrolling behavior
Sketch file has behavior at all breakpoints.

1. Start state
![image](https://user-images.githubusercontent.com/11670886/85633798-96f42900-b63f-11ea-893e-80931eb51a73.png)

2. Begin scrolling
![image](https://user-images.githubusercontent.com/11670886/85633844-b9864200-b63f-11ea-8dce-59657c15fd3a.png)

3. Search and sort tool bar sticks
![image](https://user-images.githubusercontent.com/11670886/85633889-d15dc600-b63f-11ea-9261-8b9df9b96cb8.png)

4. Filters scroll independent once they stick
![image](https://user-images.githubusercontent.com/11670886/85633944-f2beb200-b63f-11ea-9362-1e0c06d5c06d.png)

## Filtering behavior

### Large break points
- Filter exist in a right panel as checkbox lists.
- Select filters appear as purple tags in the sticky header bar beside sort

![image](https://user-images.githubusercontent.com/11670886/85633982-09fd9f80-b640-11ea-8b97-4b24f25f7b25.png)

### Smaller break points
- Filters combine into one long multi-select filter
- note: I have a design for categories in the dropdown if we think this is possible.

![image](https://user-images.githubusercontent.com/11670886/85634142-5f39b100-b640-11ea-90d1-8037c256a8e0.png)

**Comment by mjabbink** [comment]
Sweet

**Comment by aagonzales** [comment]
# Updates
Updates are based on the [user feedback](https://www.notion.so/carbondesignsystem/Component-Index-Research-a248561dcff240e6a9e8e318a6576f7f) sessions and feasibility concerns. Responsive behaviors and other interactions have largely stayed same as list above in the previous comment. 

1. Remove status from cards, filter and sort.
   - Status is applied inconsistently across PAL sites and need a cross system agreed status before adding. 
   - For the first round of community components they will all be "production ready." Only things that have design and code will be added for the initial mvp.
2. Filter content changes: 
   - Remove component type for now, may add back in future when categories become more clear, intuitive. 
   - Change "Source" to "Availability" 
3. Card structure and content updates. New cards structured as follows:
![Card specs](https://user-images.githubusercontent.com/11670886/88824316-cf7daa00-d18b-11ea-806a-93bd0b4883bb.png)

**Comment by kimberlyandersson** [comment]
@aagonzales This looks fantastic. Do you see any way of IBM business partners like Rocket getting access to these components for use in building IBM products?

**Comment by aagonzales** [comment]
@kimberlyandersson because these are community owned it will depend on if the teams who make them open source them or not. I know some orgs do have open source components so business partners could use those.

**Comment by vpicone** [comment]
Wondering if we want to use the same inline dropdown solution as the icon library rather than having the whole page width for the dropdown?
<img width="946" alt="Screen Shot 2020-08-07 at 11 38 15 AM" src="https://user-images.githubusercontent.com/4078018/89668406-507f2480-d8a3-11ea-9d62-6a032eb2eb7b.png">

**Comment by aagonzales** [comment]
@vpicone we talked about it, in fact it started that way but in the icon library search and the dropdown are related. In the component index they are two separate functions that aren't associated. It was also causing weird hierarchy issue with the filters as well. 

![image](https://user-images.githubusercontent.com/11670886/89679446-b6c17280-d8b6-11ea-9550-ab41bc1f4754.png)


We'll also be using the sort bar to show the filtered tags so it wont be completely wasted space.

![image](https://user-images.githubusercontent.com/11670886/89679553-f4be9680-d8b6-11ea-99e8-24258cd87178.png)

**Comment by joshblack** [comment]
Hey @aagonzales! 👋 

Going through the Zenhub pipelines and wanted to confirm if this was still in-progress or if we should move to another pipeline? 👀
