### ISSUE TITLE
Progress indicator examples

### ISSUE THREAD

**Issue by ivanbachev** [carbon-design-system/carbon-website#1267]
## Summary
The Progress indicator examples on the Usage and Style tabs show with a black background.
https://www.carbondesignsystem.com/components/progress-indicator/usage

## Relevant information
See the following screenshot
<img width="2672" alt="Screenshot 2020-06-09 at 15 20 08" src="https://user-images.githubusercontent.com/1560160/84146796-ea258380-aa64-11ea-9b01-8546e8b30b53.png">

**Comment by tw15egan** [comment]
A bug was found and fixed, changes should be deployed and rendering correctly now. Thanks for pointing it out! 👍
