### ISSUE TITLE
What do we do with Blank fields in a table?

### ISSUE THREAD

**Issue by SpencerReynolds18** [carbon-design-system/carbon-website#1269]
A few different groups have brought up questions about how to handle blank spaces in a table. Should it be blank? Should it have a em dash? 

Do we need guidance on this or should we just leave it up to teams to make the call?

**Comment by laurenmrice** [comment]
We recommend to use either a space or a dash to show an empty cell in a data table. If your PAL recommends one way over the other, use your PAL's guidance. Going to close.
