### ISSUE TITLE
Google Plus is no longer valid for social share links

### ISSUE THREAD

**Issue by bruce-jarvis** [carbon-design-system/carbon-website#1270]
Google Plus is no longer valid for social share links
Please remove from IBM Design Kit  
![image](https://user-images.githubusercontent.com/48285322/53884313-50f9f880-3fe9-11e9-99e7-00b468f44d87.png)

**Comment by aagonzales** [comment]
Thank you for posting, but please make sure you open issues in the correct repo. This one is for website specific issues. You can find the kit repo here: https://github.com/ibm/carbon-design-kit

**Comment by eraymond25** [comment]
updated in the IBM design kit
