### ISSUE TITLE
Website component [Content switcher]: Component Style Tab color themes

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1274]
## Website component [Content switcher]: Component Style Tab

> The Component Style Tab pages need a way to switch between themes... both the visual example and the default and interactive tokens below

> A sticky content switcher has already been built for the color usage page... but we are proposing this enhancement for it here; ultimately the same component should be used in both places
https://github.com/carbon-design-system/carbon-website/issues/1186

> I've spec'd this out so that our image component, in this instance, hangs like the content switcher so that we have a clean geometric relationship between the two when scrolling. This may not be possible / require too much extra effort, so I want to talk to the dev that picks it up about this.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/de0e3639-c970-4cc3-88f7-b34b979bed9a)

### Design specs

https://github.com/carbon-design-system/carbon-website/issues/648

**Comment by jeanservaas** [comment]
@alisonjoseph 

this is a really important feature to allow users to switch between themes on the style tab and get the relevant token info

**Comment by alisonjoseph** [comment]
not stale

**Comment by jeanservaas** [comment]
not stale

**Comment by jeanservaas** [comment]
not stale
