### ISSUE TITLE
Design: Add Migration callout to homepage

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#1278]
For launch, we need a prominent way to draw attention to the migration guide on the Carbon homepage.

Some options:

- Move Migration Guide link to top level in left nav (just after Getting Started)
- Upon GA, replace blue notification banner text (top of page) with a link to Migration Guide
- Add a visual tout of some sort to the "hero" space above the fold.

@jeanservaas @designertyler

**Comment by chrisconnors-ibm** [comment]
the scope of this proposal exceeds (by quite a bit) the two days left before we are meant to be in code freeze. I would be willing to entertain:

> replace blue notification banner text (top of page) with a link to Migration Guide

…but don't know that @alisonjoseph has any time allocated to anything relating to that banner beyond removing it (probably doesn't).

@jeanservaas @designertyler what do you think?

in broader terms why is this coming up only now?

**Comment by claycrenshaw** [comment]
Hey Chris, so I was told by Robin that there is no code freeze for the website content. 

I could move the side nav link in MD, that's very quick and doesn't require dev work.
I know that changing the text on the blue banner is trivial in terms of time required.

I'm happy to take either of the text/nav approaches if Jeannie and Tyler don't want to do something more visual.

**Comment by chrisconnors-ibm** [comment]
sorry I was unclear about this. Dev resources/time are not the blocker. It is unvetted by @designertyler, @jeanservaas, or myself, an i'm not willing to approve capricious changes to the navigation structure this close to our planned release date. 

I've agreed to 66% of the proposal (temporarily repurposing the blue banner, even though it hasn't been resourced or planned for, or vetted yet, and a callout section on the home page, even though no one has been tasked with creating the accompanying imagery found in those callouts - only guessing that's what's meant - and I'm not sure who would create that), against my better judgement from a process standpoint - this is astonishingly last minute - why would litigating the 3rd thing be a priority at this point?

**Comment by claycrenshaw** [comment]
Sounds good.

Carbon v10 is live! View the migration guide for help with upgrading from v9.

Inline link on Getting Started is a good idea too. Will sync with Connor on that.

**Comment by designertyler** [comment]
The lifecycle of the banner was hopefully going to be short until the news of v10 percolates, we've had our announcements and blogs, and users figured out how to get back to the v9 site as they wrap up v9 work.

I could see that happening after a few weeks and then we can remove that bright blue banner from the top of every page on the site. 

Migration is a topic that needs to stick around a lot longer. I see "Start designing", "Start developing", and "Start migrating" as equally important for v10.

I just talked with @claycrenshaw IRL this morning and he had and idea to have migration and v9 referenced from this top banner. I'd like to do that if we can and explore a more permanent way to discover migration after the top banner is removed.

**Comment by connor-leech** [comment]
Thoughts on "View the migration guide to upgrade from v9" instead of "View the migration guide for help with upgrading from v9"?

Shorter and more action-oriented.

**Comment by claycrenshaw** [comment]
Yep, agree. @connor-leech
