### ISSUE TITLE
[Carbon homepage]: BLM Banner design tweaks

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1279]
## [Carbon homepage]: BLM Banner design tweaks

- [x] Change banner height from 48px to 32px 

- [x] Left align type to Carbon Design System 

- [x] Font size 14px; BLM is semi-bold ($heading-01); link is not semi-bold ($body-short-01)

- [x] Add @mjabbink as reviewer on this... haven't gotten his approval yet

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/f1021f1e-e6ac-4a43-bd77-44d736c9ca34)

**Comment by vpicone** [comment]
@jeanservaas we can always merge it and tweak later

**Comment by vpicone** [comment]
@jeanservaas its at 48 wouldn't 40 make it _more_ tight?

**Comment by mjabbink** [comment]
40px is ok if you prefer. In mobile the type isn’t centered.

**Comment by jeanservaas** [comment]
I think we all agree that ideally it will say: "Black Lives Matter. Support the Equal Justice Initiative."

Can we make it say that in every breakpoint but mobile, and only remove "the" in mobile to save space so we can have the 16px padding? Unless someone has a better idea for how to save space in mobile? Open to ideas, but we need that left margin.

**Comment by mjabbink** [comment]
Agree to only remove in mobile.

**Comment by mjabbink** [comment]
In mobile it could also just be the Link.

**Comment by vpicone** [comment]
Not sure our padding should supersede the message. I'll just use the acronym for EJI on mobile.

**Comment by mjabbink** [comment]
Good idea. Message is already there Vince and don’t need reminding. And yes the padding holds or design another solution. Hacking is not what we do ever and that’s what was happening.
