### ISSUE TITLE
fix[component status]: change em dash to en dash

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1290]
Hate to ask... I can't get to it in markdown but can we change these em dashes  " — " in the table to en dashes " – " for consistency? They are en dashes on the component style pages.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/5e84f752-815c-46c1-8009-71322eb60c17)

**Comment by alisonjoseph** [comment]
this is done!
