### ISSUE TITLE
IE11: Issues with gatsby-mdx move

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-website#1292]
## Brief description

Found the following issues, causing the user-facing issue described below:

* [x] We seem to have started using [a separate bundle associated with `gatsby-mdx`](https://github.com/carbon-design-system/carbon-website/blob/75d4b36/gatsby-config.js#L22-L50), separate from the one that [`src/templates/page.js`](https://github.com/carbon-design-system/carbon-website/blob/e623923/src/templates/page.js) creates. While the latter [contains required polyfills](https://github.com/carbon-design-system/carbon-website/blob/e623923/src/templates/page.js#L1), the former doesn't, causing IE11 error complaining against missing `Object.values()` function.
* [x] I saw the same (or at least, similar) error described at: 
https://github.com/ChristopherBiscardi/gatsby-mdx/issues/301#issuecomment-468645772
* [ ] I saw the same (or at least, similar) error described at: https://github.com/gatsbyjs/gatsby/issues/11524

## Detailed description

> Describe in detail the issue you're having.

next.carbondesignsystem.com is not interactive with IE11.

> Is this issue related to a specific component?

No

> What did you expect to happen? What happened instead? What would you like to see changed?

e.g. Side nav in the site is interactive.

> What browser are you working in?

IE11

> What version of the Carbon Design System are you using?

next.carbondesignsystem.com

**Comment by vpicone** [comment]
Is there a reason we're doing this global scope thing as opposed to just importing the necessary components into the mdx files?

**Comment by asudoh** [comment]
@vpicone Is your question to some of my comments above or of a specific code...? 🤔

**Comment by vpicone** [comment]
@asudoh I was wondering if importing the components at the top of the mdx files would fix the double bundling issue and include the appropriate polyfills.

**Comment by asudoh** [comment]
@alisonjoseph Thoughts...? Thanks!

**Comment by josefaidt** [comment]
@asudoh and @vpicone I've been looking into this and can't get the sidebar to work in v9 either using IE11. For me it doesn't work in v9 or v10 on IE11. For clarification the interactiveness you are looking for is when clicking content categories the item should expand to show its pages?

I added the polyfills to the MDX global scope and it *does* fix some issues with MDX pages like "Resources", but the sidebar is still broken.

**Comment by aledavila** [comment]
@asudoh Commenting so this issue doesn’t close. Is there any update on this. The issue persists in www site now

**Comment by asudoh** [comment]
@alisonjoseph Do you think you'd have a chance to get in touch with Gatsby team on this, given the issue need Gatsby's internal knowledge for resolution? Thanks!

**Comment by vpicone** [comment]
@asudoh looks like this was fixed with https://github.com/carbon-design-system/carbon-website/pull/1504 checked with Edge and IE 11

We were importing the React library before this layout component. We could have included the polyfills at the gatsby config level, but this works as well.

**Comment by asudoh** [comment]
Good to hear - Thanks alot @vpicone for checking!
