### ISSUE TITLE
v10 website launch

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#1294]
Checklist of dev items to push website live when v10 launches

- [x] Update components to v10
- [x] Confirm component status table is up to date
- [x] Update search api key `apiKey: `296ea0c1d0e96b2b04900d0f4d1a6329`,`
- [x] Update circle CI to publish to `www` instead of `next` on merge
- [ ] Fix v9.carbondesignsystem.com https issue
- [x] Update top bannner text https://github.com/carbon-design-system/carbon-website/issues/1278
- [x] Update Internal website ~(can we auto-publish?)~
- [x] Update React links on all component pages 
- [x] Add codepen links https://github.com/carbon-design-system/carbon-website/issues/1295

**Comment by designertyler** [comment]
@alisonjoseph Instead of removing the top banner can we update the text and link back to v9 so people know how to find it for the first couple weeks?


> * [ ]  Remove top bannner (double check all "sticky" component styles"

**Comment by alisonjoseph** [comment]
@designertyler @claycrenshaw Do we have updated copy for the blue banner for launch? Just need it by wed-thurs this week.

**Comment by designertyler** [comment]
@alisonjoseph Yes, we'll get updated text today. I edited the top comment to reference this issue for that https://github.com/carbon-design-system/carbon-website/issues/1278

**Comment by shixiedesign** [comment]
Question on this, should we add
- change website homepage img to video https://github.com/carbon-design-system/carbon-website/issues/1273
- icon library (category update) https://github.com/carbon-design-system/carbon-website/issues/1325
- icon search bug https://github.com/carbon-design-system/carbon-website/issues/1132

**Comment by alisonjoseph** [comment]
No, let's keep those separate, we will get them in asap.

**Comment by shinytoyrobots** [comment]
I don't think the internal website is a stop-ship (if for any reason it proves problematic or time-consuming) for v10.

**Comment by alisonjoseph** [comment]
👍 agreed @shinytoyrobots -- it shouldn't be an issue anyway
