### ISSUE TITLE
Create v10 codepens

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#1295]
Create new v10 code pen links inside v10 collection, need to wait until v10 launches. 
https://codepen.io/collection/DQgmgY/

- [x] Accordion 
- [x] Breadcrumb 
- [x] Button 
- [x] Checkbox 
- [x] Code snippet 
- [x] Content switcher 
- [x] Data table 
- [x] Date picker 
- [x] Dropdown 
- [x] File uploader 
- [x] Form 
- [x] Inline loading 
- [x] Link 
- [x] List 
- [x] Loading 
- [x] Modal 
- [x] Multiselect 
- [x] Notification 
- [x] Number input 
- [x] Pagination 
- [x] Progress indicator 
- [x] Overflow menu 
- [x] Radio button 
- [x] Search 
- [x] Select 
- [x] Slider 
- [x] Structured list 
- [x] Tabs 
- [x] Tag 
- [x] Text input 
- [x] Tile 
- [x] Toggle 
- [x] Tooltip

**Comment by tw15egan** [comment]
### Accordion
- [Accordion](https://codepen.io/team/carbon/full/WWrNvp)

### Breadcrumb
- [Breadcrumb](https://codepen.io/team/carbon/full/yreLJv)
- [Breadcrumb with current page](https://codepen.io/team/carbon/full/LvGYxK)

**Comment by tw15egan** [comment]
@alisonjoseph List should be complete, will need to change the CSS src to point to `@latest` once that is v10 so that any CSS fixes can be brought in automatically.

**Comment by alisonjoseph** [comment]
Awesome, thanks @tw15egan! looks like we are good to update to `latest` whenever. We will also need to add the correct links to the website. 

```
<ComponentCode
    name="Accordion"
    component="accordion"
    variation="accordion"
    hasReactVersion
    hasVueVersion="accordion--default"
    codepen="WWrNvp"
    >
```

**Comment by tw15egan** [comment]
👍I can take care of that, is there any issue for that already?
