### ISSUE TITLE
Getting Started: Designers steps not complete

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1296]
## Detailed description

> The instructions describe two ways to install the carbon sketch kit, and one way to install the IDL design Kit, without describing the dependency between the kits or clearly stating the way you _should_ do it (the way that will be updated - Sketchcloud) 

> https://next.carbondesignsystem.com/getting-started/designers

> At the conclusion designers should have all of the kits required to start working. Designers are not getting or understanding the requirement for a separate IDL kit (as reported in Slack https://ibm-cloudplatform.slack.com/archives/C0M053VPT/p1552424212177600)

> browser: Chrome, but any

> version: 10 (next.carbondesignsystem.com)

## Steps to reproduce the issue

1. Navigate to https://next.carbondesignsystem.com/getting-started/designers
2. Follow the instructions; assuming they complete the first instruction (https://next.carbondesignsystem.com/getting-started/designers#sketch-shared-library-(preferred)) they are unlikely to continue to the second since they are presented as alternatives (https://next.carbondesignsystem.com/getting-started/designers#get-the-kit-via-box-(ibm-internal-only))

## Additional information
Expected: Instructions capture our clearly preferred install method, and make clear that there are two required kit installs. Retain a pointer to the containing repo if users want to inspect it - in understanding how to make a symbol for submission for example - but make clear that that file will be orphaned and never part of the automatic update regime

1: Install the IDL Kit, which includes fonts, colors, icons, and other resources shared across all embodiments of the IBM Design Language (card points to IDL in Sketchcloud now, `carbon-elements` kit when available)
2: Install the Carbon v10 kit(s) via Sketch cloud
3: details about setup in Sketch

**Comment by connor-leech** [comment]
Working on this via https://github.com/carbon-design-system/carbon-website/pull/1288
