### ISSUE TITLE
Icons shown on site not available in sketch libraries

### ISSUE THREAD

**Issue by lukefirth** [carbon-design-system/carbon-website#1298]
## Summary
It has been raised by our team that in a couple of cases, icons that are available via the site icon library https://www.carbondesignsystem.com/guidelines/icons/library are not available within the sketch libraries - causing confusion between design and non-design stakeholders.

Eg: 'Change catalog' is available through the site, but not in the IBM icons sketch libraries.

## Relevant information

Link to the internal issue raised by team: https://github.ibm.com/Watson-IoT/pal-tracking/issues/340

**Comment by aagonzales** [comment]
Hi @lukefirth! Yes, we've been having issues updating the Sketch kit. What is shown on the site is everything that's available to use.

**Comment by laurenmrice** [comment]
Going to close this issue because the Icon libraries in Sketch have been updated.
