### ISSUE TITLE
Data table: The code snippet is very large type size in MOBILE

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1310]
https://www.carbondesignsystem.com/components/data-table/usage/

current:

![File (1).jpg](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/d1ae9e53-7a82-47cd-9f01-9d97d489ff81)

**Comment by aledavila** [comment]
@mjabbink Hey Mike I'm not seeing the large font. I have iOS and tried both chrome and safari. Could this be user settings specific ?


![IMG_0952](https://user-images.githubusercontent.com/12533409/95490274-a03ea280-095d-11eb-8e2c-c35aa8fd6974.jpeg)
![IMG_0953](https://user-images.githubusercontent.com/12533409/95490278-a16fcf80-095d-11eb-8db9-2a708df1cfdc.jpeg)

**Comment by tw15egan** [comment]
@aledavila I see the same as you 👍

**Comment by alisonjoseph** [comment]
I also tested and this looks correct on my mobile device, this may either be a user setting issue or something that has been resolved with a different fix since this issue was opened. 

Going to close for now, please reopen if there is still an issue.
