### ISSUE TITLE
Motion and 2x Grid page need to have the blue Gatsby player button

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1313]
> For maintainers, Vince and I talked, and since these are short videos, it makes sense to just have the .mp4 files live in the carbon-website and use the <Video/> component with their relative path. They will need to be downloaded from our video account. Feel free to ping me on slack if you need the account info.
☝️ from @jnm2377 

https://www.carbondesignsystem.com/guidelines/motion/overview
https://www.carbondesignsystem.com/guidelines/2x-grid/overview

current:
![Screen Shot 2020-06-22 at 3.13.30 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fd4a83de-7293-48cf-9cd1-68454d41db72)

expected:

![Screen Shot 2020-06-22 at 3.14.33 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/8beb51a4-79f6-466f-9f43-31ed9606e3cd)

**Comment by jnm2377** [comment]
@mjabbink @vpicone our Gatsby video component will only use the blue button when it's a local video (lives in the source code and is either imported or uses a relative path to implement it). When we pull vimeo id's it uses the default vimeo controls. We need to either have these videos live in the source code as `.mp4`'s or refactor our video component to have custom pause/play controls if it's a vimeo video. Which is possible, I've done it for the homepage video component, but it'll remove all controls, including: time bar, volume, settings, and fullscreen button. It'll literally just be pause/play. Which are we trying to do here? I feel like refactoring the vimeo component could be a breaking change for anyone relying on having those additional controls for videos. Idk who has these video files though.

**Comment by jnm2377** [comment]
@vpicone any thoughts on this?

**Comment by jnm2377** [comment]
For maintainers, Vince and I talked, and since these are short videos, it makes sense to just have the .mp4 files live in the carbon-website and use the `<Video/>` component with their relative path.
