### ISSUE TITLE
User feedback for Migration Overview page

### ISSUE THREAD

**Issue by moonSTAR77** [carbon-design-system/carbon-website#1318]
## Summary
What is Carbon X ? Seems like a typo but I could be wrong. 

## Relevant information

<img width="610" alt="Screen Shot 2019-03-20 at 5 38 03 PM" src="https://user-images.githubusercontent.com/13539361/54723971-3e2e0a80-4b37-11e9-9604-172f09a9c2ed.png">

**Comment by claycrenshaw** [comment]
Thanks for catching that. It is a typo. We will get that fixed right away.
