### ISSUE TITLE
Sortable Data Table example renders incorrectly

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#1321]
When we visit the usage page for data table at https://www.carbondesignsystem.com/components/data-table/usage and we click the `isSortable` prop the styles are incorrectly being applied to column headers on hover.

![image](https://user-images.githubusercontent.com/3901764/85746807-5b537080-b6cc-11ea-81b4-08b0cd931302.png)

**Comment by tw15egan** [comment]
This has been fixed 👍
