### ISSUE TITLE
Improve website build and develop times

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-website#1326]
The build times for the website as well as the develop script are increasing linearly with the content we add to the site. The most major contributing factor seems to be our cache getting invalidated by Vercel do to 'one or more plugins changing' resulting in us generating image thumbnails from our source images.

Possible solutions
- [Parallel image processing ](https://www.netlify.com/blog/2020/02/25/gatsby-build-speed-improvements-with-parallel-image-processing/)
- [Cloudinary or some other image cdn](https://www.gatsbyjs.com/docs/using-cloudinary-image-service/)

**Comment by mattrosno** [comment]
With us not having the complexity of an external CMS, I like the Cloudinary approach. That removes image thumbnail generation from both local development and preview/production builds, right (assuming those thumbnails are already cached in Cloudinary)?

**Comment by vpicone** [comment]
@mattrosno I like Cloudinary as well. Ideally, neither of those would require a dev/designer interacting with a CMS (although Cloudinary _can_ be used that way). The Gatsby Cloudinary plugin does two things:

1. Detect and upload images referenced by URLs in MDX
2. Swap the paths for the corresponding Cloudinary URL

Like you mentioned, taking image processing out of the question all together seems preferable to the complexity of spinning it up on a remote server. It would also be a win for performance leveraging them as a CDN.
