### ISSUE TITLE
how to get permission to download grid template

### ISSUE THREAD

**Issue by zhenwan** [carbon-design-system/carbon-website#1331]
Clicking the link "Download the grid template" in following URL give me 403 error, saying I don't have permission to download the file:
https://next.carbondesignsystem.com/getting-started/designers#info

**Comment by connor-leech** [comment]
Thanks @zhenwan for pointing this out! It's a broken link and I just pushed a fix.

Until that goes live, you can get the grid template from the 2x Grid's [Sketch cloud page](https://sketch.cloud/s/ngV7z). Just select "Download Document" on the right-side panel and follow the instructions on the *Getting started* page from there.

Don't hesitate to reach out with any other questions!
