### ISSUE TITLE
[Color] Reference the notification background color values

### ISSUE THREAD

**Issue by half5cat** [carbon-design-system/carbon-website#1332]
In the docs for the notification styles, there are a set of color tokens referenced that cannot be found in the "Colors" section. The colors missing are: 

- $notification-error-background-color
- $notification-success-background-color
- $notification-warning-background-color
- $notification-info-background-color

**Comment by aagonzales** [comment]
Hi @half5cat! These are actually component level tokens. The color page will only show universal (top level) tokens. These colors are only specific to the notification component and can only be used there. It was a concious decision not to add them to the color page. Good eye though!
