### ISSUE TITLE
fix[Typography page]: Expressive Tab

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1333]
## fix[Typography page]: Expressive Tab

@alisonjoseph I only tagged you on this because I wasn't sure how to route it; it was with the IDL devs last sprint.

IDL devs built the breakpoint changer component for the Expressive type page and it looked good, but our Type content is structured differently than IDL's content. We have an "Expressive" and a "Productive" tab (IDL has Expressive and Productive type sets on the same page) so we don't need the sticky labels for these pages. 

- [x] put sticky breakpoint changer component back into the page (use spec to guide placement)

- [x] remove sticky labels (we are reverting to previous design after discussing some issues with @alisonjoseph) 

Sketch file:
https://ibm.box.com/s/uwrab23khh326xw4nud1dvkdt9n7ktg6

Design spec:
Productive page comp

![Type Specs_productive](https://user-images.githubusercontent.com/43144260/56316396-c5af6f00-611f-11e9-8664-c37187bcd9c9.png)

<br>

Design spec:
Expressive page comp

<br>

![Type Specs_Expressive](https://user-images.githubusercontent.com/43144260/56316435-df50b680-611f-11e9-9592-62884156b4cb.png)

Motion behavior expressive spec:
![Sticky_Behavior_TYPE Copy 2](https://user-images.githubusercontent.com/43144260/56316511-0dce9180-6120-11e9-903f-b430308382b1.png)

**Comment by mjabbink** [comment]
@jeanservaas I thought you were keeping the headers in there? (Caption & labels, Captions, Body, Headers, Productive)

**Comment by jeanservaas** [comment]
@mjabbink we were going to keep that, it was in the spec... I never got a review on this, someone else must've pushed it through while I was out. I also asked the other designers — everyone but shixie so far — and it seems that no one looked at this before it was merged. 

It's not to spec and I see a lot of mistakes... some dev, some in the token values and some in the content... let me revisit the spec and make a clear line-by-line issue for dev.

**Comment by mjabbink** [comment]
@jeanservaas aight and welcome back!
