### ISSUE TITLE
Content: Content pass and refresh on guidelines pages

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#1339]
## Summary
The content on our Guidelines pages should be reviewed and refreshed. On some pages, the content is scattered and somewhat mixed between marketing material, brand content, and guidelines. Some of the info is also contradictory, and much of it is incomplete.

Each of these pages should be revisited and refreshed where necessary. Our goals for each page:

* Content is product specific 
* Content is action oriented
* Content is accurate
* No paragraph should span more than three lines
* Each section leverages context where possible (linking to other guidance and components where relevant)
* Each page leverages tabs where possible to reduce cognitive load and improve clarity.

For extra-awesome and consistent copy, pass your words through the [Hemmingway Editor](http://www.hemingwayapp.com/).

## Approach

Each of these pages should be thoroughly reviewed, refreshed, and put out for team and peer review. The process should be documented (what worked, what didn't, best practices) to better enhance our content strategy in the future. Below is a list of each *Guidelines* page, and its corresponding issue.

- [ ] Accessibility #1340
- [ ] Content  #1341
- [ ] Color #1342
- [ ] Iconography #1343
- [ ] Layout #1344
- [ ] Motion  #1345
- [ ] Spacing #1346
- [ ] Themes  #1347
- [ ] Typography #1348

## Timeline

Timeline for this will remain TBD until underway. The focus should be on quality and accuracy, not on speed. That said, these pages are critical to our site experience and this project should remain a priority.

**Comment by jeanservaas** [comment]
@connor-leech thanks for putting this together! I completely agree with you that the content is stuck in a Twilight Zone between high-level brand speak and practical application (especially for product). 
I just have a couple of considerations to add about the Guidelines section in particular. 

## Guidelines structure

### Consistent naming / IA / tabs
It's really important that we have a structural North Star for this content — some kind of organizing principle that drives the guidance and that we stick to consistent nomenclature and tab structure throughout.

- The Type page has an Expressive and a Productive tab, if we follow this organizing structure there, we should follow it everywhere... I'm not married to this structure, but we need to be consistent about who are audience is — the Overview / Usage tab structure is another way to do it.

- Just had a convo with @mattrosno about how we need to better consider the relationship of what's in our repos to what's presented on our site. If the goal for the site is to serve up / explain our elements packages, then we're getting off track. One instance being the theme section v. the Color section: technically the themes package content is presented on the Color usage tab. Another example is the Grid package: it has demo content and developer guidance that's not represented on the site.

- **"Elements" vs. "Guidelines"** — @aagonzales brought up a great point, we refer to our Color, Type, Layout, Icons and Motion sections as "Elements" everywhere (IDL site, the repos, the essential courses) but in the Carbon side nav. This is confusing and it stems from folding in sections like "Content" "Accessibility" and "Themes" into the same section with the actual "Elements." 

## Site-wide structure

### Too many paragraph breaks  
In response to the _"No paragraph should span more than three lines..."_

- Concise is good (we talked about this yesterday) but more paragraph breaks don't always equal more clarity. I actually find them more disruptive, especially in a text heavy situation without a lot of visuals. You end up with a lot of paragraph breaks and headings that aren't very different in scale, in close proximity, and hierarchy starts to break down.  

- We agreed, the more visuals the better, we just don't always have them on hand, so we'll have to work on that collaboratively moving forward

### Dynamic bread crumbing / Tertiary-level side nav
This is Ice Box territory, I know, but your timeline is "TBD" so I'm throwing it in. I do really feel like would help with clarity in the long run v. the anchor links we have now.

- We've done a lot of design exploration / motion studies etc. around the side nav and I'd like to do more exploration around linking a tertiary side nav to a dynamic breadcrumb (Material does something similar with their anchor links)
