### ISSUE TITLE
Update icon and pictogram downloads to use source assets

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#1344]
Currently, when downloading icons from the icon or pictogram library a user will get the rendered SVG data instead of the source SVG data. As a result, there is some confusion when downloading an asset as the bounding box does not match the expectation for the asset being downloaded. For example, an icon would be expected to be 32x32 and a pictogram would be 48x48. Instead, the download asset dimensions match what is rendered in the SVG.

![image](https://user-images.githubusercontent.com/3901764/86606159-46e56280-bf6d-11ea-93b4-7c88c210ad99.png)

When downloaded and put into Sketch

![image](https://user-images.githubusercontent.com/3901764/86606184-52388e00-bf6d-11ea-930c-ba0ae1d342aa.png)

This issue is for updating the download for icons and pictograms to use the SVG source data instead of the rendered data for the download. This will preserve dimensions along with layer information encoded in the export from Adobe Illustrator.

**Comment by mjabbink** [comment]
Currently in some cases parts are missing or the icon is missing all together

**Comment by mjabbink** [comment]
Side note: 
This might be resolved once Michael Dudley replaces these pictograms with the latest but for now all the display pictograms are missing.


<img width="905" alt="Screen Shot 2020-07-15 at 1 17 07 PM" src="https://user-images.githubusercontent.com/32881239/87580835-b100b480-c69d-11ea-9342-729a40764539.png">
sing the type inside the screens.
