### ISSUE TITLE
Update nav spacing

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#1348]
Update the spacing around the divider in the nav (between community and design kit). This change will create consistency between spacing in Carbon and on the Language site. This should be the spacing rule between dividers going forward. 

## As is:
![image](https://user-images.githubusercontent.com/11670886/86816200-2559a900-c049-11ea-854d-0911897d5c5c.png)

## To be:
![image](https://user-images.githubusercontent.com/11670886/86816243-34405b80-c049-11ea-9d96-85a6d95d2801.png)

**Comment by mjabbink** [comment]
@aagonzales Can you place an image of the entire new left nav. Thanks!

**Comment by mjabbink** [comment]
![Carbon Left nav](https://user-images.githubusercontent.com/32881239/89330590-b96d5f00-d64d-11ea-8d32-d0d4e9c231bb.png)

**Comment by mjabbink** [comment]
@aagonzales I added.

**Comment by mjabbink** [comment]
@aagonzales oh, this isn't the fully reorganized one though. Can you or @janchild post that here or Slack me directly.

**Comment by janchild** [comment]
I can send it to you, @mjabbink. I'm just making some adjustments.

**Comment by mjabbink** [comment]
also related to: https://github.com/carbon-design-system/design-language-website/issues/679
