### ISSUE TITLE
Create meter tile for chart types page

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1355]
https://github.com/carbon-design-system/carbon-website/pull/1270#pullrequestreview-444840124

The meter and gauge tile will be broken up into separate tiles and the meter chart will now need its own thumbnail. At the same time remove the "design only" tag from both tiles.

![image](https://user-images.githubusercontent.com/19270502/86936537-c0af5480-c103-11ea-9b19-650b8330b974.png)

**Comment by laurenmrice** [comment]
This has been resolved https://carbondesignsystem.com/data-visualization/chart-types/#part-to-whole. Going to close.
