### ISSUE TITLE
fix[intro paragraph]: line length too long at tablet

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1355]
## fix[intro paragraph]: line length too long at tablet

To match IDL site:

- [x] Carbon's intro paragraph should only span 6 columns in tablet not all 8 columns.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/7924d5c1-e67c-4fa4-a61a-d37f2ab5c445)

**Comment by vpicone** [comment]
I’m going to poke at this and https://github.com/carbon-design-system/carbon-website/issues/1259 this morning.
