### ISSUE TITLE
New resource - Design System Developer Essentials courses

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/carbon-website#1367]
### Summary

Addition of new resource - Design System Developer Essentials courses

### Justification

Once course work has been built out for the [DS developer essentials project](https://github.com/carbon-design-system/developer-essentials), we will want to surface the recorded introductions and guided labs on the Carbon website, along with the tutorials being built out by @mattrosno . 

This could be part of an overhaul of the current "Resources" page experience

### Desired UX and success metrics

A developer can discover the Design System developer essentials courses.

### "Must have" functionality

Links to videos and lab assets 

### Specific timeline issues / requests

Would be nice to make this available externally prior to the internal IBM launch of May 28th.

### Available extra resources

Can submit a PR with the content.

**Comment by kellychurchill** [comment]
@mattrosno - any updates we can document on this issue?

**Comment by mattrosno** [comment]
We can close this issue. At this point we know where the tutorial is going to live and we're committed to building the tutorial steps so we can do PRs for those over the next couple weeks.
