### ISSUE TITLE
Determine source of out of memory errors and potential solutions

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#1367]
When running `yarn gatsby build` on the website, we run into an out of memory error that requires us to increase the heap size for the process:

![image](https://user-images.githubusercontent.com/3901764/87315750-6a1e8d80-c4ea-11ea-955d-dcd79abafcda.png)

This issue is for identifying the source of the issue and determining potential solutions for how we could tackle this.

**Comment by alisonjoseph** [comment]
Unable to duplicate any longer, going to chalk it up to being fixed with updates to Gatsby, plugins and node. will reopen if we run into this again.
