### ISSUE TITLE
Update text-02 hex colors on usage tab.

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1368]
Update `text-02` to show the correct hex colors for light themes.

White | G10
| --- | --- |
| Gray 70`#525252` | Gray 70 `#525252` |

**Comment by laurenmrice** [comment]
duplicate issue of  #1374 . going to close

**Comment by tw15egan** [comment]
Whoops, my bad! I didn't see this one 😄
