### ISSUE TITLE
[docs] There are two "Formatting" anchor links when using "multiple types" template.

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#1369]
There are two headers that are labeled "formatting" when using the using the "multiple types" component template. One is an H2 and one is an H3. You cannot directly link to the H3 link, it will redirect you to the H2. We need to change the anchor link for one of them. This could be a problem with other repeated heading in the "multiple types" templates.

https://carbondesignsystem.com/components/notification/usage#formatting

**To replicate problem:**
- Go to notification page and scroll down to [inline notification](https://carbondesignsystem.com/components/notification/usage#inline-notifications)
- Click on the link icon beside the h3 header for "formatting"
![image](https://user-images.githubusercontent.com/11670886/87335804-803a4700-c506-11ea-824c-032540fabfaa.png)

**First formatting anchor link:**
![image](https://user-images.githubusercontent.com/11670886/87335473-fbe7c400-c505-11ea-805d-5c4185edc277.png)

**Second formatting anchor link:**
![image](https://user-images.githubusercontent.com/11670886/87335445-f4281f80-c505-11ea-9607-fbc304475092.png)

@janchild FYI

**Comment by janchild** [comment]
Ah, good catch, @aagonzales. I'll work with @jillianhowarth on this one and then we'll update the template. Thank you.
