### ISSUE TITLE
Fix component examples

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#1370]
Styles are "off" for the following component examples, most likely getting some style from the website css

- [x] date picker https://github.com/carbon-design-system/carbon-website/pull/1396
- [x] tooltip https://github.com/carbon-design-system/carbon-website/pull/1396
- [x] tile (add grid) #1398 
- [x] tabs - #1395
- [x] overflow menu, related issue https://github.com/carbon-design-system/carbon-website/issues/1394

~blocked by https://github.com/carbon-design-system/carbon-website/pull/1369~

**Comment by alisonjoseph** [comment]
@aledavila components that need style fixes in the website, once https://github.com/carbon-design-system/carbon-website/pull/1369 is merged in

**Comment by aledavila** [comment]
Update to the overflow menu fixed issues. Going to close
