### ISSUE TITLE
Site Break Wen digit on search icon or scroll down page

### ISSUE THREAD

**Issue by MwSpaceLLC** [carbon-design-system/carbon-website#1372]
Link: 
> https://www.carbondesignsystem.com/guidelines/icons/library/

![image](https://user-images.githubusercontent.com/29952045/87353869-ebfbce80-c55d-11ea-8aa6-fc7de95cd261.png)

**Comment by ballefar** [comment]
Any progress on this?

I am experiencing the same issue, rendering the Icons page more or less useless. Very sad, the icons are beautiful.

**Comment by tw15egan** [comment]
@ballefar do you have any steps to reproduce? Not seeing any issues navigating the page, but want to ensure it is working properly for all

**Comment by ud-ux-thomas** [comment]
I also am experiencing this issue. I didn't see this bug before I created a new one with steps to reproduce and screen reacording:
https://github.com/carbon-design-system/carbon-website/issues/2448

**Comment by joshblack** [comment]
Closing this out as I believe this was addressed by the fix in #2448 and by updates for v11. Let me know if you're still experience this behavior and I can re-open!
