### ISSUE TITLE
Last edited time stamp info next to edit this page link

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1374]
This issue is the second part to the final experience outlined here https://github.com/carbon-design-system/carbon-website/issues/862#issuecomment-467622946 where there is a time stamp next to an edit link on each page. The Edit link has already been added https://github.com/carbon-design-system/carbon-website/pull/1364

This issue is to add the "Last Update" and time stamp.
![image.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/824c69fb-15c5-4849-81bb-4c2905a3e361)

**Comment by chrisconnors-ibm** [comment]
👀
