### ISSUE TITLE
[QA bug] Apps switcher shadow is back! 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1384]
I believe we fixed it before but the box shadow of app switcher is back. When app switcher is closed, there should not be a shadow peaking in from the right side of the page.

![image](https://user-images.githubusercontent.com/15144993/55110130-607ad780-50a5-11e9-8964-0b775d2f5b95.png)

**Comment by shixiedesign** [comment]
Not stale! Shadow is still there 😱 @jeanservaas

**Comment by jeanservaas** [comment]
Absolutely not stale, this is a quick fix, we had it fixed before, but somehow it's back

**Comment by tw15egan** [comment]
On it 🕵
