### ISSUE TITLE
Accessibility Audit - Carbon Website: Homepage

### ISSUE THREAD

**Issue by andreancardona** [carbon-design-system/carbon-website#1388]
This epic is tied to a larger "release" that is meant to track the progress of the Accessibility Audit for the [Carbon Website](https://www.carbondesignsystem.com/). We will audit all of the pages of the carbon website based on AVT 1, AVT 2, & AVT3 - which can be found [here](https://app.zenhub.com/workspaces/system-squad-593830641344b813db10934d/reports/release?release=5f185c45ccda2753d030c742).  

- AVT 1: will audit the site against the [IBM Accessibility Checker - browser extension](https://github.com/IBMa/equal-access)

- AVT 2: will audit the site against accessible keyboard interactions

- AVT 3: will audit the site against screen readers 

---------------------------------------------------------------------------

#### Legend:
-  🌶️ fully audited - on all three AVT levels
    - :one: 🔍 AVT 1 audited
    - :two: 🔍 AVT 2 audited
    - :three: 🔍 AVT 3 audited 
- :boom: issues and documentation - on all three AVT levels are complete
    - :one: 🚨 AVT 1 issues submitted
    - :two: 🚨 AVT 2 issues submitted
    - :three: 🚨 AVT 3 issues submitted
- :sparkles: tickets are triaged 
---

#### Current status of this page:

- [Homepage](https://www.carbondesignsystem.com/) - 28 issues reported: 
    - :one: 🔍 AVT 1 audited & 🚨 AVT 1 issues submitted

**Comment by dakahn** [comment]
THIS IS GREAT :tada:

**Comment by andreancardona** [comment]
Homepage issues are fixed - closing epic!
