### ISSUE TITLE
iPhone 5 Endless loading

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-website#1388]
From @reinisg at IBM/carbon-components#2185:

## Title: 
Endless loading in iPhone 5 when open https://www.carbondesignsystem.com

## Description: 
When I open https://www.carbondesignsystem.com page is reloading after 1 second, it is impossible to do something.

**Comment by asudoh** [comment]
From @reinisg at IBM/carbon-components#2185:

1. 'ServiceWorkers' option isn`t Experimental Features (there are 'constant properties', 'viewport fit' in green, but all other options are disabled (CSSdisplay: contents, CSS Spring Animations, Link Preload, Remove Legacy, Secure Contexts API, SubresourceIntegrity, Web Animations, WebGPU, Async Frame Scrolling))

2. the-carbon-components.netlify.com is working without reloads, but immediately I found some list of bugs (E.g. 'view full render' is over on side navigation, default tooltip is not opening - example demo video https://gofile.io/?c=Xz7y6c)
https://gatsby-netlify-cms.netlify.com, https://gcn.netlify.com - are working well.


PS - here is demo video with https://www.carbondesignsystem.com/ page endless reloading - https://gofile.io/?c=cOdXAj

**Comment by asudoh** [comment]
From @reinisg at IBM/carbon-components#2185:

It is iPhone S5
iOS Version: 11.2.6 (15D100) 
Model: ME337J/A 

So, on this version will not work? 
But I will upgrade to 12.2 version and check page.

**Comment by asudoh** [comment]
Not sure the team wants to support such old IOS version for website - Can be closed otherwise.

**Comment by chrisconnors-ibm** [comment]
I can't replicate in the iOS Simulator, Device = iPhone 5s, ios 12.2
https://ibm.box.com/s/kzsu032ywpidmz02sreskdvajasmim1m

**Comment by chrisconnors-ibm** [comment]
I can't replicate in the iOS Simulator, Device = iPhone 5s, ios 11.2 on either
www.carbondesignsystem.com
![image](https://user-images.githubusercontent.com/35537391/55361048-019dcf80-54a4-11e9-8b3a-622fb69689dc.png)

or
v9.carbondesignsystem.com
![image](https://user-images.githubusercontent.com/35537391/55361013-f3e84a00-54a3-11e9-8949-371082c789d0.png)
