### ISSUE TITLE
iconAsleep not loaded

### ISSUE THREAD

**Issue by naokorkym** [carbon-design-system/carbon-website#1401]
Hello, when I downloaded iconAsleep from Carbon Design System page and tried to load asleep.svg into browser, it failed with following messages.

```
XML Parsing Error: syntax error
Location: file:///C:/Users/xxxxxx/Downloads/asleep.svg
Line Number 1, Column 1:
[object Object]
```

**Comment by tw15egan** [comment]
Possibly website issue (something happening when downloading), if not then maybe a build problem on the icons. Wanted to see if y'all had any ideas first

**Comment by alisonjoseph** [comment]
confirmed this icon is now downloading correctly
