### ISSUE TITLE
docs: Consistent terminology. Helper text versus help text

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1402]
This issue is to address inconsistencies in terminology when referencing the text that appears underneath a field to provide additional context for a user.  It should be referred to as _helper text_, not _help text_. This will make it consistent with the Sketch kit, and happily falls in line with what product designers are calling it. 

Just to clarify, text that sits _inside_ the field is called placeholder text, and that does not change. 

1. Search the site for instances of help text and change to helper text, where needed.
2. Check for images of helper text to ensure that the helper text sits below the field. For example, on this page the image will need to be updated: https://www.carbondesignsystem.com/components/text-input/usage/
We need to check if there are other instances of the old positioning.

**Comment by tw15egan** [comment]
`helperText`: This is what we use in the React PropNames as well 👍
