### ISSUE TITLE
The 'Developers' section is inaccessible

### ISSUE THREAD

**Issue by mrintoul** [carbon-design-system/carbon-website#142]
Hi there - I'm getting a 404 when I try and access any of the pages related to development, including the links from the landing page and the navigation sidebar.

![Screen Shot 2019-08-22 at 4 36 42 PM](https://user-images.githubusercontent.com/18323154/63556850-2ea65980-c4fb-11e9-9bd4-3df4e43f0b64.png)

**Comment by alisonjoseph** [comment]
We recently pushed an update to the navigation, so you probably got caught in a caching situation. 

https://www.carbondesignsystem.com/get-started/develop/vanilla

It's "get started" now. Sorry about that!
