### ISSUE TITLE
Migration reference and link from hompage

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1424]
A user can discover the migration guide early in their introduction to v10 so they can quickly understand the process of migrating to the latest version.

The blue banner currently calling attention to migration will go away.

Ideas to explore:

- [x] Design a feature tile on the homepage banner to accommodate "Start migrating" content; card similar to "Start Designing" and "Start Developing" 

- [x] Card will replace redundant "Carbon Design System" text with a callout to migration; in turn, change "Inclusive, flexible and consistent" to "Carbon Design System"

- [x] Adjust aspect ratio of all tiles (every tile and featured article image should have an aspect ratio of 2:1 -- no 16:9s

- [x] Assign prescribed key heights to the Start Designing and Start Developing images specific to breakpoints so they don't look wonky while scaling responsively

- [x] Move pause button to accommodate new banner tile and to align with other sites' pause location

**Comment by jeanservaas** [comment]
## Design specs for new banner tile to replace blue migration bar & Aspect ratio updates

sketch file:
https://ibm.box.com/s/vdogvcnjin1uxxqn5hv8df06tzs7onxk

<br>

**1312**



![image](https://user-images.githubusercontent.com/43144260/57109345-d86a9c00-6cfa-11e9-8a08-f2f8b769612c.png)

<br>

**672**



![image](https://user-images.githubusercontent.com/43144260/57109384-f0dab680-6cfa-11e9-808f-1ca5c7b60993.png)

<br>

**Mobile**

![image](https://user-images.githubusercontent.com/43144260/57109417-064fe080-6cfb-11e9-82d0-ae335516e22c.png)


_Note: pause button moves to the left side to match IDL_ 

**pause on 1312 & mobile spec (16x16px)**

![image](https://user-images.githubusercontent.com/43144260/57109583-76f6fd00-6cfb-11e9-8478-5b56a04098ed.png)

**pause on 1672 spec (32px to align with type)**

![image](https://user-images.githubusercontent.com/43144260/57109635-97bf5280-6cfb-11e9-913b-8a6a4f6c00cb.png)


Aspect ratio specs

<br>

**1312**

![Homepage_Revised Copy](https://user-images.githubusercontent.com/43144260/57109692-c2111000-6cfb-11e9-9d59-1909325f8660.png)

<br>

**672**

![Homepage_672_Revised Copy](https://user-images.githubusercontent.com/43144260/57109722-d6550d00-6cfb-11e9-9810-215b0dcfafcf.png)

<br>

**mobile**

![Homepage_mobile Copy](https://user-images.githubusercontent.com/43144260/57109740-e4a32900-6cfb-11e9-807c-501e6ca050ce.png)

**Comment by chrisconnors-ibm** [comment]
moving spec to dev pipeline
