### ISSUE TITLE
Pictograms page > minimum size should be 48px not 32px. Please update text and image.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1432]
See IDL Pictogram specs, content and image.

https://www.ibm.com/design/language/iconography/pictograms/usage#sizing

@conradennis can you tackle in markdown? This needs to be addressed quickly as several teams are using pictograms at 32px and it does not work.

**Comment by conradennis** [comment]
For sure, will take care of it on Monday.

**Comment by conradennis** [comment]
@mjabbink PR is here: https://github.com/carbon-design-system/carbon-website/pull/1438
