### ISSUE TITLE
How can we reference the magenta use for Carbon Paper in the website. 

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1433]
![Screen Shot 2019-04-02 at 3.53.54 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/63406dbb-1c37-4c6f-b4cd-ed1664106937)

`would be cool to actually put this picture on our site somewhere too, as a tribute to our heritage`
https://www.nytimes.com/2015/02/27/arts/design/review-everything-is-design-showcases-paul-rand-master-of-brand-identity.html

**Comment by tw15egan** [comment]
Could that pink possibly be used as syntax highlighting around the site?

**Comment by designertyler** [comment]
Here are a couple of the closest language swatches if anyone was curious.
![Screen Shot 2019-04-03 at 8 26 34 AM](https://user-images.githubusercontent.com/19270502/55482505-4cc1fa80-55ea-11e9-8f89-b4e82ffec993.png)
