### ISSUE TITLE
Click on links from search bar result leads to blank page

### ISSUE THREAD

**Issue by ExiliumAeternum** [carbon-design-system/carbon-website#1439]
## Detailed description

the url https://www.carbondesignsystem.com/components/data-table/code#skip-to-content result in a blank page. This url came from search result after typing in `table`.

> What browser are you working in?

Chrome

## Steps to reproduce the issue

1. Go to Carbon home page
2. Expand search bar, type in `table`, then click on second link which should lead to url: https://www.carbondesignsystem.com/components/data-table/code#skip-to-content
3. Going to that URL results in blank page

**Comment by alisonjoseph** [comment]
Thanks for making the issue, we're working on getting our search updated with the content from the new website. It is still indexing our old content.

**Comment by alisonjoseph** [comment]
This should be fixed, we've updated the search index
