### ISSUE TITLE
missing icons

### ISSUE THREAD

**Issue by k2lh** [carbon-design-system/carbon-website#1440]
highly recommend confirming that whatever is in use in the site itself is also available in the actual system, otherwise it feels like the design system is busy ignoring (if not breaking) its own rules while insisting users follow those rules. 

frex: 
the site uses an icon to indicate an external link, but this icon isn't available in the library. 
the site uses tiles in a way that isn't discussed/explained in the grid or tile sections (and the actual tile example doesn't show up on the site, either)

**Comment by vpicone** [comment]
@k2lh the icon we use to indicate an outbound link is called 'Launch' it's available through `@carbon/icons` or whatever framework you prefer.

The website, like any other application built with Carbon, has some bespoke styles and components. These styles and components are build using primitives provided by Carbon: layout, color, typography, motion, etc.

Gonna close this one out, let me know if that wasn't the icon you were referring to.
