### ISSUE TITLE
Overflow menu example opens in random place in FF

### ISSUE THREAD

**Issue by zunan** [carbon-design-system/carbon-website#1459]
## Detailed description

In Carbon V10 website, [The overflow menu](https://www.carbondesignsystem.com/components/overflow-menu/usage) example opens from an unexpected place. (not next to the overflow menu icon)

Browser : In FireFox (60.6.1esr (64-bit)),

## Additional information

- Screenshots or code
<img width="1792" alt="Screen Shot 2019-04-05 at 8 20 02 AM" src="https://user-images.githubusercontent.com/4266726/55631139-f2a56e80-577c-11e9-9c2d-87a6d319a102.png">

**Comment by alisonjoseph** [comment]
Thanks for reporting, looking in to it 👀

**Comment by alisonjoseph** [comment]
@asudoh something you have time this week to look at maybe?
