### ISSUE TITLE
[Button] multiple bug issues

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#146]
- The 16px `add` icon is not pulling in correctly for all buttons. It looks really thick.
![Screen Shot 2019-08-22 at 2.00.13 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/cbf173c5-fdb5-4d2d-94ae-c658578173c0)

- The icon button should be a square

![Screen Shot 2019-08-22 at 2.03.26 PM.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/b6e521de-6f53-4855-8c5a-4f96f0d4eff7)

Spec:
![Artboard.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/3ec2e306-620c-4478-aa7f-2da7254805c0)

**Comment by alisonjoseph** [comment]
moving this to the website repo and taking a look

**Comment by alisonjoseph** [comment]
the icon button example should be fixed w/ my latest PR that was merged
