### ISSUE TITLE
Add Anchor Links to the code pages

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon-website#1461]
### Summary
The component pages on the Carbon (v9 and v10) website have anchor links on the section titles for the *Usage* and *Style* pages, but not the code pages. Adding anchor links on the code pages would allow me to link team members directly to the right part of the page. 

### Justification

It would make it easier to reference the Carbon documentation from other sources, and to link teammates directly to it. Particularly on the longer pages where things like the FAQ or documentation is far down the page. 

### Desired UX and success metrics

Duplicate this functionality: 
![image](https://user-images.githubusercontent.com/6569324/55637166-0e634180-578a-11e9-8b0c-d64756415ada.png)

On the section titles in the code pages: 
![image](https://user-images.githubusercontent.com/6569324/55637149-060b0680-578a-11e9-845e-8478e5bd1257.png)

### "Must have" functionality

On mouseover of the page subheadings on the component > code pages a link icon appears. Clicking that link appends a `#[title]` to the page URL creating a unique link that takes a user directly to that part of the page. 

By duplicating this on the code pages for things like the sub-component names, the documentation section, the FAQ and so forth I would be able to link directly to the relevant part of what can sometimes be very long pages.

**Comment by alisonjoseph** [comment]
Agreed this would be a nice add, should be relatively simple too. 👍

**Comment by tomlroach** [comment]
Bump - still would be nice!

**Comment by lovemecomputer** [comment]
re-opening due to request!

**Comment by alisonjoseph** [comment]
https://github.com/carbon-design-system/carbon-website/blob/master/src/components/ComponentCode/ComponentCode.js#L47 is where this would need to be added if anyone wants to grab this issue 😄

**Comment by tw15egan** [comment]
FYI @tomlroach, PR is up https://github.com/carbon-design-system/carbon-website/pull/1598
