### ISSUE TITLE
Update headline in Updates—> Release Information —> Known Issues tab

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1468]
@jeanservaas @claycrenshaw 
https://www.carbondesignsystem.com/updates/release-information/known-issues

change header from:
Carbon v10 identified bugs and issues

to:

Identified bugs and issues

The copy underneath and site communicates Carbon v10. Keep these short and sweet and no need to keep saying Carbon or v10 in headers unless absolutely necessary.

<img width="789" alt="Screen Shot 2019-04-06 at 7 01 23 PM" src="https://user-images.githubusercontent.com/32881239/55676253-4b6d2800-589f-11e9-882d-19520a154573.png">

**Comment by connor-leech** [comment]
Closed via #1469
