### ISSUE TITLE
[NextPrevious conversion to slug]: NextPrevious doesn't handle item names with more than one space

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-website#1472]
## Detailed description

> Describe in detail the issue you're having.

Minor issue I found while developing our own fork of carbon-website, NextPrevious links don't work for pages with more than one space in the name

> Is this issue related to a specific component?

NexPrevious

> What did you expect to happen? What happened instead? What would you like to see changed?

Pages with two or more spaces are not properly linked because slug conversion has a slight bug. The space to dash conversion should be global.

```
titleToSlug = string => {
  if (string) return string.toLowerCase().replace(/[ ]/g, '-');
};
```

**Comment by alisonjoseph** [comment]
Good catch, always welcome a PR to fix 😉

**Comment by tay1orjones** [comment]
I knew I'd forget about it without an issue 😅
