### ISSUE TITLE
Example select component doesn't layout well on mobile (Android/Chrome)

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon-website#1479]
## Detailed description

When I navigate to the carbon site on mobile, and interact with the select component, it's very hard to read due to a lack of styling, and positioning of dividers and general layout. 

Perhaps the example select content isn't a good showing for the component because it looks bugged due to the heavily wrapping text and the incoherent dividers. 

Perhaps we need to define a max character limit?

> Is this issue related to a specific component?

Select component

> What did you expect to happen? What happened instead? What would you like to see changed?

When I look at the UI Chrome renders for the select component, it's doesn't look pleasant or well laid out. 

> What browser are you working in?

Android 9, Chrome

> What version of the Carbon Design System are you using?

Current website

## Steps to reproduce the issue

1. Using an android phone, navigate to https://www.carbondesignsystem.com/components/select/code
2. Open the select component (first example)
3. View how it renders. 

## Additional information

- Screenshots
![Screenshot_20190410-135459](https://user-images.githubusercontent.com/6569324/55906075-0ac02800-5b99-11e9-9c17-93a07cefbf6b.png)

**Comment by emyarod** [comment]
hi @tomlroach thanks for reporting this! Our select component is using native `<select>` under the hood, and these component styles are entirely dependent on your OS and browser, so we are quite limited in what we can do to restyle Android `<select>` components. We could just modify the example content as you suggested, but that would probably be the extent of the changes we could make
