### ISSUE TITLE
Recent change to left nav behaving strangely 

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1480]
Per this pull request, https://github.com/carbon-design-system/carbon-website/pull/1456, I updated the left nav heading **Community** to **Community assets** but the change is not sticking. Not sure what's happening here.

In Chrome, the new heading initially shows and then disappears. See the attached Quicktime movie. 
[community asssets.mov.zip](https://github.com/carbon-design-system/carbon-website/files/5019149/community.asssets.mov.zip)

It works fine in Safari.

**Comment by tw15egan** [comment]
Seems like it's just a caching issue, I'm seeing the correct naming. Can you try holding `shift` and click the refresh icon? 

![Screen Shot 2020-08-04 at 11 34 09 AM](https://user-images.githubusercontent.com/11928039/89331402-91c6c880-d646-11ea-8c19-cdb2581cc34f.png)

**Comment by laurenmrice** [comment]
Closing because this issue has been resolved 👍
