### ISSUE TITLE
Inconsistency in capitalization guidance

### ISSUE THREAD

**Issue by scanlana** [carbon-design-system/carbon-website#1484]
## Summary

The Carbon content guidelines offer inconsistent advice about capitalization on this page:
https://www.carbondesignsystem.com/guidelines/content/guidance#capitalization

## Relevant information

Under the Sentence style header, it says "Use sentence-style capitalization in text and for all text elements in the UI, except for table/grid column headers, headings for groups of toggles, and product names. "
But then under the Headline style header, it says "Only use headline-style capitalization for table/grid column headers and product names. " 
What's happened to the advice on headings for groups of toggles? Which capitalization standard should be used on headings for groups of toggles? 

Additionally, on the page about the toggles component, no advice is given on the capitalization of headings: https://www.carbondesignsystem.com/components/toggle/usage

**Comment by connor-leech** [comment]
@scanlana thanks for pointing this out! We have all-new content guidelines in the works (woohoo!), but I went ahead and fixed the issues you pointed out.
