### ISSUE TITLE
Icon page cupcake experience 

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#1485]
Cupcake (4/25)
"As a product designer or developer I need to..."
- [x] see all icons so that I can know the icon I need exists
https://github.com/carbon-design-system/carbon-website/issues/1325

- [x] see the icons when I arrive on the icon page so that I know I'm in the right spot.  (smaller resource cards)
https://github.com/carbon-design-system/issue-tracking/issues/107

- [ ] link to the Sketch cloud library so that I can see all of the library while working in Sketch.
https://github.com/IBM/carbon-design-kit/issues/89

- [x] updated "no results" page https://github.com/carbon-design-system/carbon-website/issues/866

- [x] find the icon repository so that I... [specify goal].
- [x] navigate to the icon repo so that I can download the icons directly to make edits and contribute back.
- [x] can get automatic updates when the language/system team makes changes so the icons I use will always be up to date.

**Comment by designertyler** [comment]
## Cupcake Designs

### Default state
![Icon_Library_all](https://user-images.githubusercontent.com/19270502/56527949-12c28500-6514-11e9-9bfa-2d57f54933cc.png)

### Search results
![Icon_Library filtered](https://user-images.githubusercontent.com/19270502/56527972-1ce48380-6514-11e9-96be-0211ee753413.png)

### No results
![Icon_Library no results](https://user-images.githubusercontent.com/19270502/56527996-24a42800-6514-11e9-8bdb-c2217be49657.png)


### Spacing
![Icon_Library filtered_specs](https://user-images.githubusercontent.com/19270502/56528213-72b92b80-6514-11e9-8c7f-6cc73f474a6b.png)
![Icon_Library no results_specs](https://user-images.githubusercontent.com/19270502/56528214-72b92b80-6514-11e9-8e26-843e07c435f5.png)
![Icon_Library_all_specs](https://user-images.githubusercontent.com/19270502/56528215-72b92b80-6514-11e9-952e-8b252248a96b.png)

**Comment by chrisconnors-ibm** [comment]
get bent stale[bot]

**Comment by chrisconnors-ibm** [comment]
still active.

**Comment by joshblack** [comment]
![image](https://user-images.githubusercontent.com/3901764/59875583-bab6cc00-9366-11e9-92e3-0a06e9023fda.png)

Would this tile need to be renamed to our kit?

**Comment by joshblack** [comment]
@designertyler is there a loading pattern you want if this page takes a bit to load? I think we're going to have to chunk the icons since they are pretty large (~100kB)

**Comment by designertyler** [comment]
There's no loading/skeleton state spec'd for this page. I'm ok implementing without one and seeing if we need it. Or... any loading pattern that isn't a full-screen overlay 😄

**Comment by joshblack** [comment]
Closed by #1789, I believe 👍
