### ISSUE TITLE
The guidance for Interactive Tooltips seems to have been mixed up with the guidance for the definition tooltip

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon-website#1492]
https://www.carbondesignsystem.com/components/tooltip/usage

On this page, the guidance for the interactive tooltip seems to be replaced with a copy of the guidance for the definition tooltip. It's a copy and paste.

Here's the definition tooltip: 
![image](https://user-images.githubusercontent.com/6569324/56081551-37ac4f00-5dd4-11e9-8058-80a08c43e531.png)

And here's the interactive tooltip, note the first paragraph is identical and still refers to the "definition tooltip"
![image](https://user-images.githubusercontent.com/6569324/56081559-46930180-5dd4-11e9-831e-1c97c4f286dd.png)

In general, I'd appreciate more guidance about the interactive tooltip - where exactly should it be used? Can it be used without the label? 
If it should be used with the label - how? Like where would you actually put it on a page/use it in a screen? The examples just show it floating in space, it would be really helpful to see an example of how it might be used in a page, similar to how the definition tooltip examples shows an example of a form field.

If I want to provide help on a form field label, should I use the definition tooltip, or the interactive tooltip?

**Comment by connor-leech** [comment]
not stale, looking now

**Comment by connor-leech** [comment]
The redundant content has been fixed, but we still need to add more guidance on tooltip. Thanks Tom!
