### ISSUE TITLE
Tooltip Component

### ISSUE THREAD

**Issue by chriswalsh96** [carbon-design-system/carbon-website#1503]
## Detailed description

> Is this issue related to a specific component?

Tooltip

> What did you expect to happen? What happened instead? What would you like to see changed?

Tooltip not closing when you re-click on the tooltip icon after opening it

> What browser are you working in?

Chrome

> What version of the Carbon Design System are you using?

v10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

No product or project, was just checking out the library

**Comment by asudoh** [comment]
Moved to: IBM/carbon-components#2317
