### ISSUE TITLE
IE11 and Edge: Side Nav tabs do not open 

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon-website#1509]
## Detailed description

> Describe in detail the issue you're having.

Side Navigation menu items do not open on Edge and IE11. Therefore I cannot navigate the website

> What browser are you working in?

Microsoft Edge 
IE11

**Comment by vpicone** [comment]
Fixed with https://github.com/carbon-design-system/carbon-website/pull/1504
