### ISSUE TITLE
[content] Update homepage content

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1519]
Update the homepage messaging of Carbon as an open, service-oriented group to support ease of use and contribution by IBMers.

The first revision would leave the existing video in place, and work to accommodate both the first-time user path and items of interest for return users. 

For subsequent revisions, we will explore deeper layout work.

**Comment by jeanservaas** [comment]
## Homepage design concepts: Leading with community

### Banner animation sketches

![home_animation_1](https://user-images.githubusercontent.com/43144260/91579694-9ca50e00-e911-11ea-91e2-f8ba0c642132.png)

![home_animation_2](https://user-images.githubusercontent.com/43144260/91579706-a0d12b80-e911-11ea-9adc-005c73aaa2c2.png)

![home_animation_3](https://user-images.githubusercontent.com/43144260/91579707-a169c200-e911-11ea-85a5-81ae381b6923.png)

### Full homepage sketch

![Full_homepage_ideas](https://user-images.githubusercontent.com/43144260/91579989-045b5900-e912-11ea-9f09-4e1afa6fee7c.png)


### Incentivization

![Incentivization](https://user-images.githubusercontent.com/43144260/91580025-15a46580-e912-11ea-98c2-91f999e931e3.png)

### Meet ups

![Events](https://user-images.githubusercontent.com/43144260/91580081-2fde4380-e912-11ea-970c-0e2a381fac44.png)

### Feedback component

![usage_feedback_component](https://user-images.githubusercontent.com/43144260/91580150-45ec0400-e912-11ea-90c9-e9e8185a329d.png)

**Comment by shinytoyrobots** [comment]
Within the context of [Sprint 4](https://github.com/carbon-design-system/carbon/issues/6772), I think the primary deliverable should be;

- Clearly defined homepage purpose (summarized in 1-2 sentences)
- Desired action/s of visitors to homepage (perhaps personas?)
- Metrics for how we might measure homepage "success"

This will then allow us to break down work into more specific pieces of design and dev work over the next couple of sprints.
