### ISSUE TITLE
add Axure page to Getting Started guide

### ISSUE THREAD

**Issue by jeoffw** [carbon-design-system/carbon-website#1523]
Let's add a **Getting Started -> Axure** page for this Axure kit (can be marked Experimental at first).

From Csaba Sipos (UX Designer, IBM Budapest Lab)

I have created an Axure widget library of Carbon v10 for our upcoming project, and I think this Axure library would be useful for UX designers across IBM.

This library was crafted not only for wireframing but also to create interactive prototypes, modeling the behavior and functionality of Carbon components as much as Axure is capable of doing this. At this level of complexity, some guidance is useful, therefore I also created a detailed documentation.

Here you can see the documentation with all the information that is required to use the library: https://pages.github.ibm.com/Budapest-Studio/carbon-axure-library/

The library was also crafted with the Axure user in mind, using Axure best practices:
- [Widgets](https://pages.github.ibm.com/Budapest-Studio/carbon-axure-library/#g=1&p=library_index) have custom icons and short names so they appear properly in the Libraries pane of Axure.
- Shapes within widgets are named and organized, so that they make sense. This also helped documenting their usage, in some cases with step-by-step instructions.
- Functionality, behaviors were implemented using specific Axure widget types (dynamic panel, selection group, repeater etc.) that best suit the purpose. These elements are also explained in the documentation.
- etc.

As you can see, the aim of the documentation is that any experienced Axure user can use the library based on the information, without someone holding their hand. But I am happy to support it, e.g. answer question on a dedicated Slack channel (I already have one for my team, I only need to ask Slack admins to share it within the organization).

Should you have any comment, feedback, suggestion, I am also ready to add or modify elements in this library, so that it will best suit its purpose, to help Axure users in a proper way. 

I have 10+ years of experience with Axure. I keep challenging myself with pushing its limits, and I also like helping others to get the most out of it.

I plan to maintain & extend this library in the future. I would also add an "Examples" section with downloadable resource files (.rp) for more complex interactive examples (that just won't fit into the library as "widgets"). 

Look forward to hearing from you.

Best regards,
Csaba Sipos
UX Designer
IBM Budapest Lab
Andrassy ut 39, H-1061 Budapest

**Comment by csabasipos** [comment]
The Axure library file and its changelog are hosted on Box and shared with public links. Links are available from the documentation, too.
https://ibm.box.com/v/carbon-axure-library
https://ibm.box.com/v/carbon-axure-changelog

Releases in the changelog are marked "Experimental" until the Axure kit has this status.

**Comment by aagonzales** [comment]
Hello @csabasipos! This is awesome! I'm going to add you to our IBM Design Kit Guild slack group. The purpose of the guild is to build and maintain the Carbon kit in various tools and we want the tool experts like yourself to be the ones working on them. We met bi-weekly (I'll add you to the invite as well) and chat in the channel to talk about updates we're making to the various kits and hopefully keep them all in balance.

**Comment by connor-leech** [comment]
Not stale

**Comment by csabasipos** [comment]
I added a template (a pre-configured Axure file) to the resources and changed the title of the docs to "Carbon Axure Kit". The repo name and the docs URL was also changed: 
https://pages.github.ibm.com/Budapest-Studio/carbon-axure-kit/

There were updates in the library, too, for details see the [changelog](https://ibm.box.com/v/carbon-axure-changelog).

**Comment by werdnanoslen** [comment]
Not stale, please continue convo

**Comment by werdnanoslen** [comment]
Not stale, please continue convo

**Comment by aagonzales** [comment]
Update: I've been communicating with Csaba on Slack. We are working on how to release this kit as internal and experimental.
