### ISSUE TITLE
Mobile version Tab Dropdown issue - when we click on the Dropdown label "Tab label 1" unexpectedly it is jumping to top of the page

### ISSUE THREAD

**Issue by 581sudha** [carbon-design-system/carbon-website#1524]
Hi all. In the mobile version for Carbon Design System page, Tabs component is changed to dropdown based on Carbon code, we are facing issue when we click on the Dropdown label "Tab label 1" unexpectedly it is jumping to top of the page

There is an example (https://www.carbondesignsystem.com/components/tabs/usage/#top). (Please check the tab view in mobile to see the dropdown issue in mobile onclick )

Looking for solutions, team help on this issue  (please refer the attachment for the issue)
![Carbon React mobile version Dropdown issue onClick](https://user-images.githubusercontent.com/18533776/89522111-49eaa180-d7fe-11ea-9511-b20a736b86cd.png)

Thanks!

**Comment by Fullchee** [comment]
Although I'm not seeing a dropdown,

I'm also getting the jumping issue on desktop.

I use a mac using Catalina and I can reproduce this on Chrome and Firefox.

However, instead of jumping to the top, it's jumping down a bit.

https://www.carbondesignsystem.com/components/tabs/usage/

**Comment by laurenmrice** [comment]
We have changed our tab functionality at mobile to a horizontal scroll instead of changing it to a dropdown. So going to close this issue 👍
