### ISSUE TITLE
Tabs documentation is inconsistent

### ISSUE THREAD

**Issue by MarkFalconbridge** [carbon-design-system/carbon-website#1528]
## Summary
The documentation or at least the screen shots used are inconsistent on the tabs page - https://www.carbondesignsystem.com/components/tabs/usage/

The overview section has an image of Container type tabs and the content below has a white background.
![image](https://user-images.githubusercontent.com/20678943/89630003-a3061400-d896-11ea-84ff-30610da67504.png)

Then in the variations section there are instructions that the Container type tab "is always paired with an attached background container" and show a grey content area in the image.
![image](https://user-images.githubusercontent.com/20678943/89630104-c630c380-d896-11ea-9976-b0fc008501ae.png)

There also seem to be inconsistencies with the implementations of container style on the various tech stacks, React and Vue appear to apply a background color to the tab panel whereas the Angular and Vanilla JS ones don't (at least that's what I observe when looking at the storybook examples for each linked to from here - https://www.carbondesignsystem.com/components/tabs/code/#live-demo.

**Comment by laurenmrice** [comment]
We have updated our Tab documentation and these images have been replaced. Our Tab component has been updated with our v11 release in code. If you are still experiencing problems with React implmentation please feel free to re-open.
