### ISSUE TITLE
Submit an issue via a form, rather than via GitHub

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#1531]
From a discussion about encouraging active engagement with Carbon...

...if someone isn't comfortable with GitHub, they won't engage in terms of opening an issue even if they notice a problem or want to ask for something new. 

Is there value in making it an easier experience by providing a more user friendly option - a website form, which will then create a GitHub issue on the back end (potential for auto labeling, etc)? @aledavila had made a suggestion to me along these lines probably a year or more ago.

Really dependent on how much of a blocker we think this might be to obtaining feedback or engagement in the first place. And whether the effort to do so would have a worthwhile impact.

**Comment by andreancardona** [comment]
@shinytoyrobots we now have the feedback component - do we feel that resolves this issue?

**Comment by joshblack** [comment]
Hey there! We're going through this issue during proposal grooming and noticed this hasn't been active in a couple of weeks. Going to close this out now, but feel free to re-open!
