### ISSUE TITLE
Your guidance contradicts your examples in Links

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon-website#1532]
Under the Structure > Recommended section of your [link component guidanc](https://www.carbondesignsystem.com/components/link/style)e, you state
> Links can be grouped horizontally or vertically and must be underlined. 

yet the examples that follow a few lines later are not underlined

<img width="834" alt="image" src="https://user-images.githubusercontent.com/14298245/89684002-6d6d2500-d8ae-11ea-8de3-a2f4903b5c0e.png">

On your usage tab, you show them underline
<img width="230" alt="image" src="https://user-images.githubusercontent.com/14298245/89684101-9c839680-d8ae-11ea-989b-04c15dd86f2a.png">

and then not underlined in the following samples. The accessibility tab shows them all consistently underlined. It would be useful to have consistency.

**Comment by laurenmrice** [comment]
@mbgower We have updated our Link style tab page with new images. We are now showing that there are two variants of Link (standalone and inline) in the first image and showing the states per variant in the second image. For the [Structure image](https://carbondesignsystem.com/components/link/style#structure), this is purely an example to focus on the padding specs.
