### ISSUE TITLE
telemetry of user activity on carbondesignsystems.com

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1536]
Add methods to track user activities on carbondesignsystem.com: user paths, search terms, etc to be determined.

**Comment by designertyler** [comment]
Notes from Tuesdays at 10 discussion translated into user need statements.


As a Carbon team member, I need a way to...

- [ ] Understand what GDPR means for the type of information we can collect so we can stay in compliance while using data to improve our design and not burdening our user with cookie consent banner. 

- [ ] See the number of unique page visits so we can understand the reach of our website.

- [ ] See the number of unique page visits so we can measure the impact of social media, blog posts, and conferences.

- [ ] See the user's entry page so we can understand how users enter the website.

- [ ] See page views so we can know which parts of the site are not being visited.

- [ ] Bounce rate to identify opportunities to improve content. 

- [ ] User flows so we can see pages that are commonly visited together.

- [ ] User flows so we can see the path of the user through the site while trying to complete a task.

- [ ] See the session duration to help our understanding of how users are using the website.

- [ ] Conversion funnel - Entering the site to [taking an action] Need to define actions for conversion.

- [ ] Track events so we can know which functionality the users are using on the site. (links in left nav and component preview, etc.)

- [X] Searched terms that brought no results so we can tailor the content to the user's needs.

**Comment by designertyler** [comment]
No stale`bot`, we still want this
