### ISSUE TITLE
Global nav and tertiary menu items

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#1540]
## Page tabs

I understand there are usability issues with our current page tabs - mostly discoverability. You have to select the page to see what page tabs are available.

Our current page tabs are also inconsistently used, which may be causing usability issues as well.

E.g.:
![image](https://user-images.githubusercontent.com/1691245/56592342-1a376c00-65b0-11e9-989e-d36d98cd737a.png)

I'm bringing this up now because there looks to be development activity to make the page tabs sticky on scroll and stacked on mobile: https://github.com/carbon-design-system/carbon-website/issues/578

## Tertiary side menu items

Would we benefit by sparingly using the page tabs, and moving those navigational links to the side menu as tertiary items?

## Growing site

We're looking add tutorial content (multi-step, possibly multi-framework, possibly multi-discipline). We're looking to add blog content in the future. Regardless if page tabs stay or go, our left nav menu is full and won't scale beyond current "docs" content well.

## Global nav

![image](https://user-images.githubusercontent.com/1691245/56593313-7f3f9180-65b1-11e9-8b8b-da48ef2636a6.png)

What if we added global nav items "Docs", "Tutorial", and eventually "Blog" to our global nav bar? Interaction: no left menu on our home page. When you select "Docs", we show the left menu as it is, defaulting to the top page which happens to be "About".

That would give us an entire left menu for the tutorial, to use as necessary. Same goes for the blog.

It's always best to avoid "nested tabs", especially when top global navigation can feel "tab-like". If we pursue global nav items, that might be one more reason to get rid of our current page tabs.

**Comment by mattrosno** [comment]
@chrisconnors-ibm @jeanservaas @alisonjoseph I just had a conversation with @connor-leech on information architecture, specifically about where our upcoming tutorial should live. Yall probably have had similar conversations, but here is how I see it as I look to how our site could grow over the next few months.

**Comment by alisonjoseph** [comment]
I believe there are already some larger IA discussions going on around the site nav, since this is much bigger than just the Carbon site. @jeanservaas would know more

Questions around how the site would work on mobile if we added a top nav. What are the rules around when a section has its own left nav, etc.

**Comment by chrisconnors-ibm** [comment]
@designertyler =focal here

**Comment by connor-leech** [comment]
stale[not]
