### ISSUE TITLE
Alert colours cannot be found in (.clr) file

### ISSUE THREAD

**Issue by justingodard** [carbon-design-system/carbon-website#1541]
## Detailed description

> Describe in detail the issue you're having.

The `.zip` with the `.ase` and `.clr` files (found here: https://www.ibm.com/design/language/elements/color) do not include the Alert colours shown in: https://www.carbondesignsystem.com/guidelines/color/overview in their palettes.

> Is this issue related to a specific component?

N/A

> What did you expect to happen? What happened instead? What would you like to see changed?

I'd see Yellow, Orange alert colours in the swatch palette.

> What browser are you working in?

N/A

> What version of the Carbon Design System are you using?

N/A

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

N/A

## Steps to reproduce the issue

1. Navigate to: https://www.ibm.com/design/language/elements/color
2. Click on "Color palettes for Adobe (.ase)"
3. Open `.zip`
4. Open `.clr` file

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

- Screenshots or code
- Notes

**Comment by dakahn** [comment]
@carbon-design-system/design 👋 Is this still an issue?

**Comment by shixiedesign** [comment]
Yep!

**Comment by aagonzales** [comment]
If anyone knows how to update or create a crl file we'd appreciate some help.

**Comment by shixiedesign** [comment]
Hi @justingodard the updated `.CLR` file is here as a zip. We are working on getting it into the site so anyone can download it via the official paths. Thank you! 

[IBM_Colors_RGB_HEX_V01.2.clr.zip](https://github.com/carbon-design-system/carbon-website/files/3179257/IBM_Colors_RGB_HEX_V01.2.clr.zip)

**Comment by justingodard** [comment]
Great, thanks!
