### ISSUE TITLE
audit-avt1-gs-design: more than one nav role

### ISSUE THREAD

**Issue by aledavila** [carbon-design-system/carbon-website#1554]
## Environment

> Operating system: Mac
> Browser: Chrome
> AVT :one:
> Page: [Get Started - Design](https://www.carbondesignsystem.com/get-started/design/sketch)
> See more info & solution here: 

## Detailed Description: 

Multiple elements with 'nav' role do not have unique labels or remove nav role 

## What to do: 
Add unique labels to each tab

**Comment by andreancardona** [comment]
PR can be found here in gatsby theme: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1063
