### ISSUE TITLE
Code snippet copy button not working on some pages/components

### ISSUE THREAD

**Issue by lovemecomputer** [carbon-design-system/carbon-website#1558]
copy button for code snippet does *NOT* work on the code snippets on:
- https://www.carbondesignsystem.com/getting-started/developers/vanilla

it *does* work on these kinds of code blocks:
- https://www.carbondesignsystem.com/components/link/code

**Comment by tw15egan** [comment]
We don't ship any copy to clipboard functionality out of the box, so we probably just need to wrap these copy buttons like https://github.com/carbon-design-system/carbon-website/blob/ae1f9ba29d55fe85ebe7aa762229352e855f5c79/src/components/CodeExample/CodeExample.js#L85
