### ISSUE TITLE
Proposal: Get rid of Resources left nav item

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#1568]
## The problem

We now have three of eleven left navigation items pointing to the [same page](https://www.carbondesignsystem.com/resources).

![image](https://user-images.githubusercontent.com/44656921/56919662-cb457700-6a86-11e9-82fe-c02b244b73ac.png)

Not only is this a waste of space in our top-level navigation element, but it's also a single deviation from a pattern established in the left nav (pivoting chevron with dropdown).

## The solution(s)

There are three potential solutions.

1. Connor's favorite: We can move "Resources" to below "Help". We link out to the two most important sections of the page, no need for a top-level item as well.
2. We update the Resources page (should do this anyway) and keep only the Resources item in the left nav, maybe under the divider.
3. We do nothing.

We also have link-out icons next to the links, which isn't accurate anymore as both link to another place on the Carbon site.

**Comment by alisonjoseph** [comment]
I would also add that maybe we should move the Articles to their own page, maybe under Resources? 🤔

**Comment by connor-leech** [comment]
Not stale!
