### ISSUE TITLE
Stacked inline notifications styling missing

### ISSUE THREAD

**Issue by risehgal21** [carbon-design-system/carbon-website#1573]
## Summary
Was curious to know the guidelines for stacked inline notifications. For example, if we need to show multiple inline notifications ( could be about SDK, Kube version upgrade, deprecation etc) and need to stack them, how should we go about it.

**Comment by laurenmrice** [comment]
@risehgal21  For stacking inline notifications vertically, you could use `$spacing-03` (8px) between them. This is how we stack toast notifications. https://www.carbondesignsystem.com/components/notification/usage/#toast-notifications
