### ISSUE TITLE
I am not able to install Carbon 10 in Sketch

### ISSUE THREAD

**Issue by Bellapedreira** [carbon-design-system/carbon-website#1574]
I am not able to install carbon 10 in Sketch

## Detailed description

> Describe in detail the issue you're having.
I've followed all the steps to install Carbon 10 in Sketch and I am receiving these error message in sketch: "Failed to download the update" (for the carbon design system) and "Library version incompatible" (for the IBM Design Language).

> Is this issue related to a specific component?
No.

> What version of the Carbon Design System are you using?
Trying to install version 10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
MyPartnerWorld. Yes, because we are transitioning while it is still in the beginning 

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

- Screenshots or code
<img width="485" alt="Captura de Tela 2019-04-30 às 09 55 52" src="https://user-images.githubusercontent.com/35814771/56964613-e91be600-6b31-11e9-8417-5c581301f358.png">

- Notes

**Comment by chrisconnors-ibm** [comment]
What version of Sketch are you using? Carbon and Libraries require the current version (54.1 as of 4/30/2019)

**Comment by Bellapedreira** [comment]
I just checked and I'm using 52.6. This seems to be the problem.
 
 
Thanks,
                                                                        Isabella Pedreira
                        Intern, Global Business Partners                                                                        isabella.magalhaes@ibm.com
                        +55 (21) 98847 4838                                                                                                                                                                                                                
 
 
----- Original message -----From: Chris Connors <notifications@github.com>To: carbon-design-system/carbon-website <carbon-website@noreply.github.com>Cc: Bellapedreira <isabella.magalhaes@ibm.com>, Author <author@noreply.github.com>Subject: Re: [carbon-design-system/carbon-website] I am not able to install Carbon 10 in Sketch (#1574)Date: Tue, Apr 30, 2019 11:52 AM 
What version of Sketch are you using? Carbon and Libraries require the current version (54.1 as of 4/30/2019)
—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.
