### ISSUE TITLE
[Home page]: add Netlify link per OSS plan requirements

### ISSUE THREAD

**Issue by jnm2377** [carbon-design-system/carbon-website#1576]
### Summary

Netlify Open Source plan [requirements](https://www.netlify.com/legal/open-source-policy/): 

<img width="936" alt="Screen Shot 2019-04-30 at 1 20 44 PM" src="https://user-images.githubusercontent.com/32556167/56984067-cc3fdc80-6b4a-11e9-9cea-dc3b8492c05d.png">

### Justification

We're upgrading our Netlify plan to Open Source team in order to add more collaborators.

### "Must have" functionality

Link to Netlify services somewhere on our main page.

cc: @carbon-design-system/design we'd need to figure out where we want this/what it should look like.

**Comment by designertyler** [comment]
`...or you may create your own link.` Are there any requirements for this or can it simply be a link to Neflify?

The example icons and badges are pretty large and would stand out on the homepage.

**Comment by aagonzales** [comment]
Does main page mean the website home page or like the main carbon repo page? I don't think its normal for people to put devops things on the product homepages.

**Comment by jnm2377** [comment]
@designertyler it can simply be a link to Netlify. 
@aagonzales this means our home page. It's been approved by @kuehndaniel and @shinytoyrobots. They have examples of other sites who use their open source plan and most of them seem to be including the link in the footer.

**Comment by jnm2377** [comment]
Not inactive, this is a Netlify OSS plan requirement we need to address.

**Comment by jnm2377** [comment]
Not stale

**Comment by jnm2377** [comment]
Still needed
