### ISSUE TITLE
Cannot load Sketch IBM Design Language library

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-website#1578]
## Detailed description

I am following the instructions to install Sketch libraries on this page: https://www.carbondesignsystem.com/getting-started/designers

I successfully installed the Sketch White theme:

<img width="1140" alt="Screen Shot 2019-04-30 at 4 10 13 PM" src="https://user-images.githubusercontent.com/12902530/56995033-3d40bd80-6b66-11e9-9412-4268646fdab0.png">

Next, I tried to install the IBM Design Language library. I got this error message:

<img width="1140" alt="Screen Shot 2019-04-30 at 4 10 13 PM" src="https://user-images.githubusercontent.com/12902530/56995129-7f69ff00-6b66-11e9-8d0d-823c1e3dcf2a.png">

It appears that “Get the White theme” and “Get the IBM Design Language library” are using the same link.

Will you please fix the “Get the IBM Design Language library” link?

> Is this issue related to a specific component?

No. The link for loading the Sketch IBM Design language library is wrong.

> What did you expect to happen? What happened instead? What would you like to see changed?

I expected to go to a page to load the Sketch IBM Design language library. Instead, I got an error message because the link was the same as the link to "Get the White theme." Will you please fix the "Get the IBM Design Language library” link on https://www.carbondesignsystem.com/getting-started/designers

> What browser are you working in?

Safari 12.0.3

> What version of the Carbon Design System are you using?

Carbon v10

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

External enterprise application. Trying to convince teammates to use your Carbon Design system.

## Steps to reproduce the issue

See above.

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

- Screenshots or code
- Notes

**Comment by designertyler** [comment]
Thanks for the heads up @lnajjar! We have a PR to fix it right now https://github.com/carbon-design-system/carbon-website/pull/1579

**Comment by lnajjar** [comment]
You guys are doing a great job. Happy to help,

**Comment by aagonzales** [comment]
Fixed!
