### ISSUE TITLE
Redirects fail in Staticfile deployments

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#158]
We're running into a situation where redirects are failing when we serve our site as a static deployment. For example, for contributing we redirect `/contributing` to `/contributing/designers`. However, in `nginx` it tries to look for `/contributing/index.html` but cannot find it. This is preventing our internal deploys to w3 currently.

Some resources that could be helpful:

- https://github.com/gatsbyjs/gatsby/tree/master/examples/using-redirects
- https://github.com/gatsbyjs/gatsby/pull/2633
- https://github.com/gatsbyjs/gatsby/pull/1068

**Comment by alisonjoseph** [comment]
Hardcoded urls for now to stop any failing links. should still look in to redirect fix at some point.

**Comment by alisonjoseph** [comment]
This seems to be working now thanks to @asudoh ! 🎉
