### ISSUE TITLE
Update[Typography page]: Expressive and productive token naming

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1583]
## Update[Typography page]: Expressive and productive token naming

<br>

After a conversation with @vpicone we decided to restructure the typography guidance and token naming architecture to make our system / guidance more intuitive. This change primarily affects the Headings on both the Productive and Expressive tabs.

- [x] On the Productive tab change the names of $heading-01 and $heading-2 to $productive-heading-01 and $productive-heading-02

<br>

- [x] Add a $productive-heading-06 and a $productive-heading-07 (this is covered in another PR to the Elements repo also) but since we're here we might as well make the website update too

https://github.com/carbon-design-system/carbon-elements/pull/512

<br>

- [x] On the Expressive tab change take the word "Fluid" out of all of the H4s under Fluid type sets (i.e. it should just say Headings, Paragraphs and quotes, Display

<br>

- [x] On the Expressive tab move $heading-01 and $heading-02 down under Fluid type sets to be with the other Headings; change their names to $expressive-heading-01 and $expressive-heading-2

<br>

- [x] On the Expressive tab add expressive $expressive-heading-03 in (see spec below) it's missing!

<br>

- [x] On the Expressive tab in the specs for expressive-heading-01 and expressive-heading-02 add 
"(fixed)" next to the token name.

<br>

- [x] On the Expressive tab -- every token under Fluid type sets should have "expressive" in the name ($expressive-quotation-01, $expressive-quotation-2, $expressive-display-01, $expressive-display-02, $expressive-display-03, $expressive-display-04

<br>

![Type Specs_Productive.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/9d25166e-0743-47b2-83be-6c23b6cd11ca)

<br>

![Type Specs_Expressive.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/9581a75b-31fe-4501-b2d5-d7852d596d1c)

**Comment by vpicone** [comment]
Not stale!

**Comment by jeanservaas** [comment]
preemptively still not stale!!!

**Comment by jeanservaas** [comment]
THIS IS NOT STALE!!!

**Comment by jeanservaas** [comment]
WE HAVE THE WRONG TYPE TOKENS UP ON CARBON SITE.

**Comment by jeanservaas** [comment]
Looking much clearer! Thanks for jumping on this so fast! Couple things:

- quick fix on Productive tab, I could also prob do in markdown -- on Productive Headings can we just change the title to "Headings" instead of "Fixed Headings"

<img width="1109" alt="image" src="https://user-images.githubusercontent.com/43144260/62245521-69f3b380-b3a7-11e9-8c6c-dbada1ae37ee.png">


- On Expressive tab order looks good, it's just the breakpoint changer that looks a little off on scroll and sticky position -- I just noticed, it's broken in current Carbon now too!! So no wonder! It would be cool to fix it here cause it's gross, but I could also make another issue.

**current behavior:**

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/43144260/62245709-c525a600-b3a7-11e9-9716-4b95f40d34f8.png">


**desired behavior:**

breakpoint changer sticks at 16px below the sticky tabs on scroll; everything above it is masked.

<img width="1462" alt="image" src="https://user-images.githubusercontent.com/43144260/62246277-e89d2080-b3a8-11e9-84fe-cce59b454be4.png">

**Comment by tw15egan** [comment]
@jeanservaas updated!
