### ISSUE TITLE
Enhancement[Homepage]: Design update including Banner feature tile

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1594]
## Enhancement[Homepage]: Design update including Banner feature tile

See design specs:
https://github.com/carbon-design-system/carbon-website/issues/1424

- [x] Add a feature tile on the homepage banner to accommodate "Start migrating" content; card similar to "Start Designing" and "Start Developing" 

- [x] Card replaces redundant "Carbon Design System" text with a callout to migration; in turn, change "Inclusive, flexible and consistent" to "Carbon Design System"

- [x] Move pause button to accommodate new banner tile and to align with other sites' pause location

- [x] Adjust aspect ratio of all tiles (every tile and featured article image should have an aspect ratio of 2:1 -- no 16:9s (see geometry specs at all breakpoints)

- [x] Adjust vertical height of Start Designing and Start Developing images specific to breakpoints so they don't look wonky while scaling responsively (see geometry specs at all breakpoints)

**Comment by alisonjoseph** [comment]
not stale

**Comment by jeanservaas** [comment]
pre-emptively still not stale

**Comment by jeanservaas** [comment]
THIS IS NOT STALE!!!!!

**Comment by alisonjoseph** [comment]
not stale

**Comment by alisonjoseph** [comment]
> Adjust vertical height of Start Designing and Start Developing images specific to breakpoints so they don't look wonky while scaling responsively (see geometry specs at all breakpoints)

@jeanservaas Do you want specific images for each breakpoint, or do you want to scale the images to a specific aspect ratio at different breakpoints (might end up looking stretched/weird)

The feature tile images are the last outstanding thing I need to figure out for this.
