### ISSUE TITLE
Tutorial Step 1 feedback

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-website#1596]
Nice work on the tutorial! 

As I was going through it, I noticed a few small things:

- [x] No need to start the app again after `yarn add carbon-components carbon-components-react @carbon/icons-react`, as we need to `yarn add node-sass` right after. Could move `yarn start` to right after the `node-sass` installation

- [x] "Start by creating the following files as siblings of the __tests__ folder:" could be reworded as "Create the following inside `src/components/TutorialHeader`"

- [x] "Another important thing to notice is that we’re using React Fragment to return the header components". Could be nice to link to https://reactjs.org/docs/fragments.html

- [x] `<GlobalHeaderBar>` should be `<HeaderGlobalBar>` 

- [x] At the end, we have a line that says "We’re halfway there! Now we need to point our header links to these routes." after we've added the routing. Not sure what this means?

- [ ] I needed to add `aria-label` to `<HeaderGlobalAction />` to get the tests to pass

Let me know if any of these need more clarification or if I just interpreted it incorrectly 😄

**Comment by jnm2377** [comment]
Thanks for the feedback @tw15egan! Ale's gonna work on some changes for this today! 👍
