### ISSUE TITLE
Link 404s in datepicker usage tab

### ISSUE THREAD

**Issue by werdnanoslen** [carbon-design-system/carbon-website#1597]
### Summary

The [documentation](https://github.com/ibm/carbon-components/tree/master/src/components/date-picker) link in the [datepicker's usage tab (content, format section)](https://www.carbondesignsystem.com/components/date-picker/usage#format) 404s.

![image](https://user-images.githubusercontent.com/764090/57231946-9d61b480-6fe9-11e9-8851-59b29731b20c.png)

### Specific timeline issues / requests

No rush

### Available extra resources

Maybe it's supposed to point here? https://github.com/carbon-design-system/carbon-components/tree/master/packages/components/src/components/date-picker

**Comment by tw15egan** [comment]
I think it's supposed to be pointing to `Flatpickr` documentation: https://flatpickr.js.org/localization/

**Comment by tw15egan** [comment]
Oh, nevermind, you're right it should be https://github.com/carbon-design-system/carbon-components/tree/master/packages/components/src/components/date-picker, which then links directly to `FlatPickr`

**Comment by werdnanoslen** [comment]
Oh yeah probably should go directly to the readme since the file list is long: https://github.com/carbon-design-system/carbon-components/blob/master/packages/components/src/components/date-picker/README.md
