### ISSUE TITLE
images failing to load

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#160]
On 
macOS [10.14.6 (18G87)] 
Chrome [Version 76.0.3809.100 (Official Build) (64-bit)]

at
https://www.carbondesignsystem.com/components/form/usage#format and below

images not loading even after browser restart, emptying image cache:
![image](https://user-images.githubusercontent.com/35537391/63701628-e92fa800-c7ea-11e9-9e89-5897d5a9c0c5.png)

**Comment by jendowns** [comment]
Just wanted to confirm that I'm also getting this issue occasionally. Usually on first page load, many images will 404 (and usually if I reload my browser window, some/most images will load).

Screenshot of my console as I was clicking around the site jsut now (I'm using the latest Chrome):
<img width="1363" alt="Screen Shot 2019-09-04 at 10 59 23 AM" src="https://user-images.githubusercontent.com/9057921/64271620-3c98a900-cf03-11e9-9f5c-6355f132d01f.png">

**Comment by alisonjoseph** [comment]
So strange, I'm not able to duplicate this at all. 😭 @jendowns are when you're on the website, what date is showing in the footer? 🤔

**Comment by jendowns** [comment]
@alisonjoseph I had closed out of the website earlier. Just went back to it, and the footer shows:

```
Vanilla Components version 10.4.1
React Components version 7.4.1
Last updated August 16, 2019
Copyright © 2019 IBM
```

This situation is very hard to replicate and seems to happen to me when I least expect it 😅 For example, right now all images appear to be loaded. Even when I opened the website in a private window, everything loaded just fine.

Next time this happens to me I'll ping you so I can show you what I'm seeing. As of right now I'm not sure what the cause could be 🤔 (Timeout?)

**Comment by alisonjoseph** [comment]
@jendowns  I think this might be a caching issue, the website was last updated Sept 4th (today). So if you're seeing the Aug 16th date then the website is trying to look for images that no longer exist. We pushed a huge update to the Carbon site, migrating it to the Gatsby theme, so while it doesn't look any different, its a completely new repo/overhaul of the underlying code. So all the image paths changed. although why it would work sometimes and othertimes not.. I'm not sure.
