### ISSUE TITLE
Add content for usage in experimental iconography page

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#160]
Currently we provide a usage page for iconography here: http://staging.carbondesignsystem.com/guidelines/iconography/usage

Ideally, we would have a matching one for experimental at `/experimental/iconography/usage` when #96 is done. This page should have any updated content that we would want to switch over to in Carbon X.

**Comment by joshblack** [comment]
cc @chrisconnors-ibm

**Comment by chrisconnors-ibm** [comment]
Scope: if appropriate content exists @ ['duo' website](https://duo.w3ibm.mybluemix.net/elements/icons/) migrate it over to augment/increment what's found at http://staging.carbondesignsystem.com/guidelines/iconography/usage
