### ISSUE TITLE
Tab width and padding

### ISSUE THREAD

**Issue by ChrystelPaulson** [carbon-design-system/carbon-website#1603]
Title line template: [Tab width and padding]: Carbon website states that 16 px for right padding should be applied but the pictures included depict contradicting information. 

## Detailed description

Designate if all tabs should be equal widths or have 16px of padding on the right. This is not clearly called out on the website and within the sketch libraries these tabs are not responding to width that follows these directions (particularly in the grouped items)

> What did you expect to happen? What happened instead? What would you like to see changed?
Please designate what the rules should be for sizes and padding within carbon. 

> What browser are you working in?
Chrome and sketch

## Steps to reproduce the issue

https://www.carbondesignsystem.com/components/tabs/usage

<img width="721" alt="Screen Shot 2020-08-24 at 1 20 11 PM" src="https://user-images.githubusercontent.com/62628291/91081386-afb39780-e60c-11ea-83ad-ec51366f1455.png">
<img width="1209" alt="Screen Shot 2020-08-24 at 1 20 16 PM" src="https://user-images.githubusercontent.com/62628291/91081390-b0e4c480-e60c-11ea-9133-ed76058e097e.png">
<img width="1037" alt="Screen Shot 2020-08-24 at 1 20 38 PM" src="https://user-images.githubusercontent.com/62628291/91081394-b215f180-e60c-11ea-868a-04c7fa0d3efc.png">

**Comment by tw15egan** [comment]
FYI there is `16px` of padding on the nav-link. The widths of the tabs are set to `10rem` by default, so there is extra whitespace 
![Screen Shot 2020-08-24 at 11 30 41 AM](https://user-images.githubusercontent.com/11928039/91082303-5b54eb80-e5fd-11ea-8ee0-85d40571688f.png)

**Comment by laurenmrice** [comment]
The image specs for Tabs on our website have been updated to match the code and live demo implementation. 

**Image specs**
https://carbondesignsystem.com/components/tabs/style

**Code**
https://react.carbondesignsystem.com/?path=/story/components-tabs--contained
