### ISSUE TITLE
Carbon motion tokens are incorrect

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-website#1617]
https://www.carbondesignsystem.com/guidelines/motion/basics#duration-tokens
@shixiedesign @connor-leech 

content:
duration--fast-01 
duration--fast-02
duration--moderate-03 
duration--moderate-04 
duration--slow-05 
duration--slow-06 

actual:
duration--fast-01 
duration--fast-02
duration--moderate-01 
duration--moderate-02 
duration--slow-01 
duration--slow-02 

Not sure which is correct.

**Comment by shixiedesign** [comment]
😱 lemme look into this.
