### ISSUE TITLE
Pictogram —> Usage tab: Some images touching (need spacing) and the large images need to span to far right margin

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1627]
https://www.carbondesignsystem.com/guidelines/pictograms/usage#clearance

i.e current:

![Screen Shot 2020-08-27 at 3.46.34 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/2b4af442-5049-4fa4-97db-dac049a0e032)

Reference:

https://www.ibm.com/design/language/iconography/pictograms/usage/

**Comment by alisonjoseph** [comment]
looks like this has been resolved
