### ISSUE TITLE
[Proposal] Guidelines on "Correct usage of selection components"

### ISSUE THREAD

**Issue by dimitrihoffmann** [carbon-design-system/carbon-website#1630]
### Summary

The Carbon Design System should provide some guidance on when and how to use the right selection components. A common problem is the unclarity about when to use checkboxes or toggles. Here is what Material Design does in this regard: https://material.io/design/components/selection-controls.html

### Justification

Many Designers are struggling to decide on when to use the right selection components.

**Comment by connor-leech** [comment]
Hey Dimitri!

I agree, our guidance surrounding selection components isn't clear enough. I'll add this to our content pipeline.

We also welcome and encourage contributions from the community (you!), docs included. Feel free to reach out to me if that process isn't clear.

Thanks!
