### ISSUE TITLE
Link to Box resource  not working

### ISSUE THREAD

**Issue by markbingley** [carbon-design-system/carbon-website#1632]
On this page: 

https://www.carbondesignsystem.com/data-visualization/color-palettes/#categorical-palettes

https://github.com/carbon-design-system/carbon-website/edit/master/src/pages/data-visualization/color-palettes/index.mdx

The link to Resources: "Data visualization color palettes (IBM internal link)" directs to this box link: https://ibm.ent.box.com/s/1rvfetsgovxoj4660suz5sa2tgqizlvy

This link is not accessible to all users.

**Comment by alisonjoseph** [comment]
this link is no longer on the website
