### ISSUE TITLE
fix[component index]: No results body copy width

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1636]
## fix[component index]: No results body copy width

Even though component index it 9 columns wide, the body copy under the "No results found" should be the same width as the body copy on the whole site (which is 8 cols)

![image](https://user-images.githubusercontent.com/43144260/91597180-a424e100-e92a-11ea-9ab9-c67aed1df59f.png)

and "community" is misspelled

![image](https://user-images.githubusercontent.com/43144260/91599060-4b097d00-e92b-11ea-8cc0-68d19acb66ae.png)

**Comment by aagonzales** [comment]
Has been fixed!
