### ISSUE TITLE
spacing and structure definition for helper-text

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#164]
on https://www.carbondesignsystem.com/components/text-input/style/

spacing between label and input seems to be defined in relation to the label itself in the way of a bottom margin of $spacing-03.

if this is the case, then the spacing between the helper-text and the input is not defined.

the picture however shows a 8px margin on the top of the input.

perhaps margin-top $spacing-03 for the input is simply missing from the table?

**Comment by aagonzales** [comment]
Helper text has recently been update but this issue made me realized we forgot to update the website with the new content. We will work on getting this updated asap!
