### ISSUE TITLE
[Tooltip, website] Update tooltip page with new alignment options doc

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#1640]
Recently merged enhancements for tooltip. Now tooltip supports 3 alignment options: start, center, end (previously only center is available). This should be documented in Usage section: 
https://www.carbondesignsystem.com/components/tooltip/usage

Dev isseu: https://github.com/carbon-design-system/carbon/issues/2678
Design kit issue: https://github.com/carbon-design-system/carbon/issues/2768

### Position and alignment
Tooltip maybe positioned `top` or `bottom`, and aligned to `start`, `center` or `end`. Please connect with @laurenmrice for image assets.

**Comment by laurenmrice** [comment]
not stale
