### ISSUE TITLE
Content - Add a section about "migrating your product to Carbon"

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#1650]
Based on feedback from the last playback with Phil.

He suggested that we have a clearly defined section in our navigation, calling out specifically the journey of a non-Carbon product moving to a Carbon UI.

Broadly this seems like a good idea - there are multiple legacy products that have existing interfaces and back-ends that are not "greenfield" development when looking to adopt Carbon. Can we speak directly to that journey?

**Comment by vpicone** [comment]
The upcoming case studies will offer insights into how products can migrate.
