### ISSUE TITLE
[animations] Audit of component and pattern documentation

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1661]
Audit the existing Carbon documentation to identify opportunities for assistive animations:
  - [ ] All component usage pages -- see [Overview](https://www.carbondesignsystem.com/components/overview)
  - [ ] All Carbon-documented patterns -- see [Overview](https://www.carbondesignsystem.com/patterns/overview) 
  - [ ] Can also include competitive analysis of other design system sites

Review with the design team at our weekly design crit.

**Comment by johnbister** [comment]
Heads up that I have to hit pause on this issue. There is an existing effort in to animate ~10 interactions that I am joining.  This first batch of animations will be reviewed with the accessibility team to help shape the way we approach motion moving forward. Based on accessibility feedback, we will have a better idea of when/how to add assistive animations.

**Comment by johnbister** [comment]
https://ibm.ent.box.com/notes/718901071711 - Components
https://ibm.ent.box.com/notes/720069347958 - Audit
