### ISSUE TITLE
[website] All about Carbon > Team pages

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#1665]
This issue captures the work for the All about Carbon pages that relate to the Carbon core team, the steering committee, the board, and projects. 

Defining the groups and the responsibilities, currently in[ this draft PR](https://github.com/carbon-design-system/carbon-website/pull/1651) (steering committee, working groups, board of directors)

**Comment by mjabbink** [comment]
@janchild Is is How Carbon works or How to use Carbon? Or does the how to use come in the Designer/Developer pages?

**Comment by janchild** [comment]
@mjabbink Yes, that's right—the how to use Carbon information is in the Designing and Developing pages.
