### ISSUE TITLE
404 from .clr/.ase Resource Tile link in Prod

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#1667]
Go to https://www.carbondesignsystem.com/guidelines/color/overview#resources

Click `RGB color palettes (.ase and .clr)`
![image](https://user-images.githubusercontent.com/35537391/58342972-e904c280-7e1f-11e9-8c05-732fdb5e25da.png)

expected: downloads zip file
actual: 404
![image](https://user-images.githubusercontent.com/35537391/58343017-05a0fa80-7e20-11e9-8c98-e4a30463dc22.png)

**Comment by jeanservaas** [comment]
PR #1678 did not fix this issue. Sorry guys, I approved too quickly, didn't try out the link. My bad. It still leads to 404 page.

**Comment by alisonjoseph** [comment]
Should be fixed now. 🙏
