### ISSUE TITLE
Tab component clipped by menu

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#1670]
Noticed this while browsing the site on Chrome, steps to repo here: https://ibm.box.com/s/8q1sw04kqg5os3ux5jxg9dl0p8lx3lk7

Basically .it seems like when scrolling up our offset logic is a little off in a certain situation

**Comment by joshblack** [comment]
Added a screenshot since the video link is being weird 🤔 cc @alisonjoseph

**Comment by alisonjoseph** [comment]
Yep, this is a known bug, thanks for making an issue. Related to all the wacky positioning with the sticky nav stuff.

**Comment by alisonjoseph** [comment]
should be fixed in new theme implementation
