### ISSUE TITLE
Add link to enrol to DPO "First Thursday" on the Carbon meetup page

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#1670]
Need a paragraph of content from Operational Excellence team (Chris Hammond / Edmund Chow), and then either an image they supply or one we add ourselves.

First Thursday, while not entirely Carbon specific, features some Carbon content in nearly every single instance.

**Comment by laurenmrice** [comment]
The First Thursday DPO meeting no longer exists, so going to close.
