### ISSUE TITLE
Update[BLM banner]: add voting reminder and close icon 

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1671]
@jeanservaas @aagonzales Can you provide any specs (icon size) and is it G10 or White? Do we use the fill (round icon) on hover? 

@vpicone Can we make sure once closed it does reload on another page but only on another site visit.

![Screen Shot 2020-09-04 at 11.27.33 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/08b9b377-0adc-48f1-b2c2-21fa5779aae8)

![Screen Shot 2020-09-04 at 11.27.43 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/72b947e7-9d1d-4e0f-bdfb-1ee8ef06bb3a)

@aagonzales Hover like this or a square?
<img width="530" alt="Screen Shot 2020-09-04 at 11 51 47 AM" src="https://user-images.githubusercontent.com/32881239/92266005-10f92780-eea5-11ea-9796-63269ada1190.png">

**Comment by mjabbink** [comment]
**Spec.** 
20px icon with no hover.

**Comment by tw15egan** [comment]
Possibly tie this in with changes suggested here? https://github.com/carbon-design-system/carbon-website/issues/1672

**Comment by jeanservaas** [comment]
@vpicone let's make this the issue where we change the content to the voting link:

- [ ] Change banner color to Cyan 80 
- [ ] Change action text (@janchild I took a crack at this but it could be better (the link is https://www.vote.org/ )
- [ ] Add 20px 'x' close icon to the banner to allow people to collapse it if they want to

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/43144260/92511811-dad8e200-f1db-11ea-8bba-6d08bff2b4c2.png">

**Comment by mjabbink** [comment]
how about

Vote. Make sure you’re registered.

Vote America. Confirm you’re registered.

Remember to vote. https://www.vote.org

**Comment by jeanservaas** [comment]
Closed this issue and transferred specs to 

https://github.com/carbon-design-system/carbon-website/issues/1672

(it was a duplicate)
