### ISSUE TITLE
Update website banner to increase 2020 election awareness

### ISSUE THREAD

**Issue by tw15egan** [carbon-design-system/carbon-website#1672]
I'm glad we've used our platform to show support and bring awareness to the Black Lives Matter movement. With election day less than two months away, we should update our messaging towards increasing civic engagement and ensuring people are registered to vote. I've noticed a few websites/apps have already changed their messaging in a similar fashion:

[Microsoft / GitHub](https://github.com/)

![Screen Shot 2020-09-04 at 9 24 40 AM](https://user-images.githubusercontent.com/11928039/92262794-7d1d6080-ee90-11ea-8ca8-269985ec7987.png)

Links to an internal blog post about [civic engagement](https://github.blog/2020-09-01-ready-to-vote-in-the-u-s-2020-elections/)

Discord

<img width="753" alt="Screen Shot 2020-09-04 at 11 47 42 AM" src="https://user-images.githubusercontent.com/2753488/92264820-73055d00-eea4-11ea-86de-3e51520bb9a8.png">

Links to [vote.org](https://www.vote.org/) which has a lot of valuable election day info, like checking to make sure you are registered and letting people sign up to vote by mail.

@vpicone suggested the idea of having it be a different color this time, so people know that the banner has changed 👍

**Comment by alisonjoseph** [comment]
@jeanservaas thoughts on the color of this banner, would we need to keep it blue, or could we change it to a gray 80 or something else?

**Comment by jeanservaas** [comment]
@vpicone @tw15egan  let's make this the issue where we change the content to the voting link:

sorry, I made a duplicate issue (#1672) but I brought the specs over here and closed that one.

- [ ] Change banner color to Cyan 80 
- [ ] Change action text (@janchild I took a crack at this but it could be better (the link is https://www.vote.org/ )
- [ ] Add 20px 'x' close icon to the banner to allow people to collapse it if they want to

<img width="1432" alt="image" src="https://user-images.githubusercontent.com/43144260/92511811-dad8e200-f1db-11ea-8bba-6d08bff2b4c2.png">

**Comment by jeanservaas** [comment]
@janchild these are @mjabbink 's suggestions for copy

how about

Vote. Make sure you’re registered.

Vote America. Confirm you’re registered.

Remember to vote. https://www.vote.org

**Comment by mjabbink** [comment]
Prefer the ones with links so you know where you’re going

Remember to vote. https://www.vote.org

Vote America. https://www.vote.org


Consider efficiency for mobile
