### ISSUE TITLE
Accessibility color blindness chart is a strange size in desktop and mobile.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1679]
@jeanservaas 

- [ ]  The Accessibility color blindness chart is a strange size in desktop and mobile. 

https://www.carbondesignsystem.com/guidelines/accessibility/color#designing-for-color-blindness

![IMG_5751.jpg](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/fe505d07-4d76-40e3-a272-642929e959dd)

—————

- [x]  Some spacing/padding issues here. The space above caption is tight and space after caption too tight

@aagonzales @jeanservaas 
![IMG_5752.jpg](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/d5da7446-b817-406d-a716-f9d40e1d11ee)

**Comment by jnm2377** [comment]
Transferred this issue to the correct repo, and removed comments that already had existing issues or belong in the GTC repo. Let's try to keep issues scoped to one specific thing going forward, it's easier for us to keep track of them that way.

**Comment by mjabbink** [comment]
I’ll do my best

**Comment by jnm2377** [comment]
This is what I'm seeing for desktop. What exactly is wrong about this? I have no idea what the image should look like. :eyes:

<img width="1792" alt="Screen Shot 2020-09-10 at 1 00 15 PM" src="https://user-images.githubusercontent.com/32556167/92796823-2247a580-f377-11ea-8af0-fec6a2d7a80c.png">

And should it just be full screen on mobile or something else entirely? Are we supposed to be using art direction with different images on this?

<img width="693" alt="Screen Shot 2020-09-10 at 1 00 30 PM" src="https://user-images.githubusercontent.com/32556167/92796846-27a4f000-f377-11ea-8a94-35e0d8905230.png">

**Comment by jnm2377** [comment]
@jeanservaas do you know what the correct images should be?

**Comment by mjabbink** [comment]
The width needs to follow the body copy widths. And in mobile it should span margin to margin

**Comment by mjabbink** [comment]
<img width="1193" alt="Screen Shot 2020-09-14 at 6 16 14 PM" src="https://user-images.githubusercontent.com/32881239/93147292-6b209680-f6b6-11ea-9c36-49465c820290.png">

**Comment by mjabbink** [comment]
<img width="376" alt="Screen Shot 2020-09-14 at 6 18 39 PM" src="https://user-images.githubusercontent.com/32881239/93147427-c2266b80-f6b6-11ea-98a9-f6d244351cbb.png">

**Comment by mjabbink** [comment]
<img width="580" alt="Screen Shot 2020-09-14 at 6 20 10 PM" src="https://user-images.githubusercontent.com/32881239/93147498-fa2dae80-f6b6-11ea-8d13-e5c55de43689.png">
