### ISSUE TITLE
Demo: update dropdowns to using "fluid" styles

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#1688]
Labels were added to the dropdown on the component demo in https://github.com/carbon-design-system/carbon-website/pull/1626 but the default style causes type misalignment. The dropdowns should be updated to use the new [fluid input style](https://github.com/carbon-design-system/carbon/issues/5416).

![image](https://user-images.githubusercontent.com/11670886/92757072-65941b00-f35b-11ea-8118-97186c0fb8f1.png)

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
