### ISSUE TITLE
select cursors

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#170]
there is a textual mention of a `not-allowed` cursor for the disabled state select here at the bottom of this section: https://www.carbondesignsystem.com/components/select/style/#interaction-states

however, there is no mention of any other cursor.  I see that the `code` tab implementation uses a `pointer` cursor, so I guess it's missing from the documentation.  Are there any other states that should have custom cursors?

**Comment by aagonzales** [comment]
Related to style tab redesign. Need consistency when talking about cursor.

**Comment by aagonzales** [comment]
Closing this issue in favor of the larger style tab refresh issue.
