### ISSUE TITLE
Enhancement[Do / Don't component]: Icon adornments need to be white (not knocked out) 

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1703]
## Enhancement[Do / Don't component]: Icon adornments need to be white (not knocked out)

The check mark and the 'x' adornment on the Do / Don't component in Carbon are knocked out of the icons... They need to be white, like they are on the DL site in order to avoid accessibility issues on mid-tone backgrounds.

@chrisconnors-ibm just solved this issue for the warning notification icon; we're going to have to do the same thing here by creating new assets for these icons that have layered paths.

### Where

- video do / don't components (motion page)

- do / don't components (all other elements pages)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/290697ae-7d3f-460c-bee6-aa7bd7e0edfb)

**Comment by alisonjoseph** [comment]
moved it back to the website repo 😅
