### ISSUE TITLE
textarea padding

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#172]
https://www.carbondesignsystem.com/components/text-input/style/
lists left and right padding and height for the text-input, however https://www.carbondesignsystem.com/components/text-input/code/ covers both the input and textarea components. 

1) there is no defined padding token for the textarea
2) the top and bottom padding in the example on the `code` tab are `.6875rem` which isn't defined here: https://www.carbondesignsystem.com/guidelines/spacing

**Comment by aagonzales** [comment]
Task:
- [ ] Add style tab content specifically for text area (currently missing)
- [ ] Investigate top and bottom margin. I believe it should be 12px / `spacing-04`

**Comment by aagonzales** [comment]
Padding top of the textarea matches the padding top of text input. Type within a field is always vertically centered and not controlled by a token.
