### ISSUE TITLE
text-input and select disabled state

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#173]
I noticed that the 1px bottom border seems to be removed on disabled state when looking at the examples on `code` tabs but the `style` tabs make no mention of this at all.  Seems like there should be an entry in the `structure` table for this.

https://www.carbondesignsystem.com/components/select/style
https://www.carbondesignsystem.com/components/text-input/style

**Comment by aagonzales** [comment]
Thanks we will take that into consideration when redesigning the style tab pages. We do show it removed in the image.
