### ISSUE TITLE
[Carbon site] Add Motion UX movie in lead space.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1738]
For whatever reasons the animation was left out when migrating this page from IDL. I think this needs to go in. 

Goes under the anchor links

https://www.carbondesignsystem.com/guidelines/motion/basics

**Comment by vpicone** [comment]
@mjabbink moved to the carbon repo. Carbon doesn't have a `basics` page like IDL does. Is this video supposed to go here under the anchor links? https://www.carbondesignsystem.com/guidelines/motion/overview

**Comment by mjabbink** [comment]
@vpicone It’s the same content and the plan was to remove the Motion UI page in IDL once Carbon site had the Motion pages up. IDL is called Basics and Carbon called Overview but the content is like 95% the same but missing the video. Placement is as you described under the anchor links like we do in IDL Typeface, Animation, Icons pages for example.

**Comment by mjabbink** [comment]
This was opened April 20. Let’s please address as soon possible as it’s made it’s slowly creeped out of the top 10 items over a few sprints when I first created it.

**Comment by vpicone** [comment]
@mjabbink systems squad is in charge of the documentation for the Carbon website

**Comment by mjabbink** [comment]
They are not the same. This page was removed from IDL and added to Carbon.

**Comment by tw15egan** [comment]
VIdeo link doesn't seem to work

**Comment by mjabbink** [comment]
FYI @sadekbazaraa

**Comment by sadekbazaraa** [comment]
@mjabbink @tw15egan the link is correct. It's just a private link but the permissions are set to be viewable on ibm.com domains. I've just added carbondesignsystem.com as an additional domain in case that was the culprit.

https://vimeo.com/281513709
