### ISSUE TITLE
For screen reader users component index item tags are buttons with no functionality with additional usability concerns

### ISSUE THREAD

**Issue by dakahn** [carbon-design-system/carbon-website#1744]
The component index item tags denoting framework type, design asset type, and maintainer are using the TooltipIcon component which is a `<div role="button">`. This is problematic for both mouse and screen reader users. 

![image](https://user-images.githubusercontent.com/40970507/93274347-c66a8b80-f77f-11ea-8ec3-d3634d03f0a0.png)
Mouse users see a pointer cursor prompting them to interact with the element, but it does nothing since the information is revealed on hover and there is no other functionality. More generally, it seems strange to hide this information in a tooltip -- since the framework type and asset type isn't additive information, but is instead potentially crucial to selection. 

In my screen reader testing with NVDA on Windows 10 the three tags are described to the user as "buttons", 
> list  with 3 items  Vanilla  Vanilla  button    Vanilla
Sketch  Sketch  button    Sketch
Maintainer  Watson Health  button    Maintainer

This is misleading since they have no functionality (the tooltips are visual affordances only -- the screen reader user relies on the elements programmatic naming). 

We have a unordered list of three elements -- two icon buttons and a "tag" or pill with two different ways of conveying information. 
![image](https://user-images.githubusercontent.com/40970507/93275060-7c82a500-f781-11ea-918b-e469359e191b.png)
The icon buttons let the mouse user discern framework or asset type through iconography OR carefully hovering over a 24px by 24px target area and _perhaps_ discovering that by clicking they can cause the tooltip to persist (a long walk for a magnification user to take), while the third pill lists the name of an internal team hoping the user hovers to find out that this team is the component's maintainer. 

Both screen reader and mouse users could benefit from simplifying things a little here. Spelling out clearly `Vanilla JS`, `Sketch` and `Maintainer: Watson Health` would definitely be more accessible and potentially more usable. _(this is my naïve solution without fully knowing design/implementation constraints)_

**Comment by tw15egan** [comment]
Since it's already being read as a button, I wonder how hard it would be to have it filter by that type when you click on it. So say a user clicks the `React` tag, it would update the index to only show React packages
