### ISSUE TITLE
bad links to sketch?

### ISSUE THREAD

**Issue by mischor** [carbon-design-system/carbon-website#1744]
## Summary
The page https://www.carbondesignsystem.com/resources#theme-libraries  has links that don't work for me (using Chrome browser, on Windows), but can be made to work with a simple modification:

Not Work:
   sketch://add-library/cloud/JaVzz
Work:
   https://sketch.cloud/s/JaVzz

Please consider making all the sketch://  links work for users who do not have sketch installed.

**Comment by alisonjoseph** [comment]
You need to have Sketch in order for these links to work, unfortunately they won't work on Windows.
