### ISSUE TITLE
Data table website live demo, sandbox, link to React code, not working

### ISSUE THREAD

**Issue by andrea-gm** [carbon-design-system/carbon-website#1754]
Found problems with:

1. the[ live demo of Data Table ](https://www.carbondesignsystem.com/components/data-table/code#live-demo), props/options don't work.
2. the [sandbox ](https://codesandbox.io/s/9m9jd) 
3. the React link redirects to Accordion. https://react.carbondesignsystem.com/?path=/story/datatable--with-selection

Question: How can developers see the effect of applying certain props, such as "tall" for the height of rows?

**Comment by ConradSchmidt** [comment]
Hey @emyarod,
please add something like the following part to the sandbox, to get it running right from the start. Maybe as a separate file, to not obfuscate the initial JS file. I use this sandbox a lot and I always need to first paste this part. The DataTable is also an important component, so to see the broken sandbox is not a good experience for the Carbon design system.
```js
      const rowData = [
        {
          id: 'a',
          name: 'Load Balancer 3',
          protocol: 'HTTP',
          port: 3000,
          rule: 'Round robin',
          attached_groups: 'Kevin’s VM Groups',
          status: 'Disabled',
        },
        {
          id: 'b',
          name: 'Load Balancer 1',
          protocol: 'HTTP',
          port: 443,
          rule: 'Round robin',
          attached_groups: 'Maureen’s VM Groups',
          status: 'Starting',
        },
        {
          id: 'c',
          name: 'Load Balancer 2',
          protocol: 'HTTP',
          port: 80,
          rule: 'DNS delegation',
          attached_groups: 'Andrew’s VM Groups',
          status: 'Active',
        },
        {
          id: 'd',
          name: 'Load Balancer 6',
          protocol: 'HTTP',
          port: 3000,
          rule: 'Round robin',
          attached_groups: 'Marc’s VM Groups',
          status: 'Disabled',
        },
        {
          id: 'e',
          name: 'Load Balancer 4',
          protocol: 'HTTP',
          port: 443,
          rule: 'Round robin',
          attached_groups: 'Mel’s VM Groups',
          status: 'Starting',
        },
        {
          id: 'f',
          name: 'Load Balancer 5',
          protocol: 'HTTP',
          port: 80,
          rule: 'DNS delegation',
          attached_groups: 'Ronja’s VM Groups',
          status: 'Active',
        },
      ];
      
      const headerData = [
        {
          key: 'name',
          header: 'Name',
        },
        {
          key: 'protocol',
          header: 'Protocol',
        },
        {
          key: 'port',
          header: 'Port',
        },
        {
          key: 'rule',
          header: 'Rule',
        },
        {
          key: 'attached_groups',
          header: 'Attached Groups',
        },
        {
          key: 'status',
          header: 'Status',
        },
      ];
```
(from: https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/DataTable/stories/shared.js)

----

Maybe you can also fix the link to the react storybook to:
https://react.carbondesignsystem.com/?path=/story/datatable--usage

The [current one](https://react.carbondesignsystem.com/?path=/story/datatable--default) is not available anymore, therefore it opens the `Accordion`

**Comment by emyarod** [comment]
the first point was resolved by https://github.com/carbon-design-system/carbon-website/pull/1960 a few months ago, I will open a PR to address the second and third points
