### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [carbon-design-system/carbon-website#1765]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/carbon-design-system/carbon-website/blob/master/package.json#L60

See https://nodejs.org/api/fs.html

You might want to remove it using `yar remove fs`.

**Comment by DanielRuf** [comment]
Bump.

**Comment by alisonjoseph** [comment]
thanks 👍 this shouldn't be an issue in the new rebuild of the site we're launching next week
