### ISSUE TITLE
checkbox indeterminate style

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#177]
https://www.carbondesignsystem.com/components/checkbox/code/ example shows a disabled an non-disabled checkbox with indeterminate state as having a black fill with white glyph.

https://www.carbondesignsystem.com/components/checkbox/style/ shows an image where the indeterminate state flips glyph and background colors based on disabled state, but the non-disabled conflicts with the code example above

![carbon_checkbox](https://user-images.githubusercontent.com/9935157/63786120-1ba6d700-c8b7-11e9-86c9-f799337cd749.png)

**Comment by aagonzales** [comment]
I just confirmed with the team, the code is correct and the style tab image is wrong.

**Comment by aagonzales** [comment]
Fixed with https://github.com/carbon-design-system/carbon-website/pull/1373
