### ISSUE TITLE
[Plex microsite] Thai Loopless bg mode bug, Gallery/Specs title mismatch, video assets are gone

### ISSUE THREAD

**Issue by mahalisyarifuddin** [carbon-design-system/carbon-website#1775]
I don't know if this is a suitable place to address these kind of problems, but I will address them anyway.

1. Thai Loopless bg mode bug
There is a bug in the Thai Loopless typetester that we can't switch to the darkmode. The darkmode is selected in the screenshot below.
![thai](https://user-images.githubusercontent.com/42148566/93710477-5d18bd00-fb71-11ea-8a3c-ad26f7c28207.png)
2. Gallery/Specs title mismatch
There is a number mismatch in Gallery and Specs page.
![judul](https://user-images.githubusercontent.com/42148566/93710518-c698cb80-fb71-11ea-9801-5fd8c4dd0540.PNG)
3. Video assets are gone
Some video assets like "IBMPlex-TrueType-hinting-a-4.mp4" and "IBM_Plex_Italic-Angles-blue_C23.mp4" can't be showed "because the file is corrupted".

I'm on Windows 7, Firefox 80.0.1. I also do use Edge Chromium 85.0.564.51 and the problem still the same.

Thank you.

**Comment by tw15egan** [comment]
@vpicone do you know where this issue should be moved to?

**Comment by vpicone** [comment]
@tw15egan I do, it's on GHE though. I'll copy it over and close this out.

@mahalisyarifuddin thank you for bringing this to our attention! We're moving it to an internal issue tracker.

**Comment by vpicone** [comment]
https://github.ibm.com/brand/plex/issues/61 for reference
