### ISSUE TITLE
checkbox size

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#178]
https://www.carbondesignsystem.com/components/checkbox/style/

![carbon_checkbox](https://user-images.githubusercontent.com/9935157/63786550-e353c880-c8b7-11e9-98f6-707aa42b50c3.png)

**Comment by aagonzales** [comment]
20px is the correct size. Need to update the table.

**Comment by aagonzales** [comment]
Fixed with: https://github.com/carbon-design-system/carbon-website/pull/1373
