### ISSUE TITLE
checkbox focus border

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#179]
https://www.carbondesignsystem.com/components/text-input/style#structure defines a focus border width for text-input but https://www.carbondesignsystem.com/components/checkbox/style#structure has no such definition.

I'd also point out that the text-input defines it as 2px but the checkbox examples here https://www.carbondesignsystem.com/components/checkbox/code use a 3px outline.

Could use some clarification here

**Comment by aagonzales** [comment]
- Focus outlines should always be 2px.
- Focus for checkbox has recently been updated. Need to update docs to reflect new style and add example.

![image](https://user-images.githubusercontent.com/11670886/87345796-2f324f00-c516-11ea-9373-1730147e8af0.png)

**Comment by aagonzales** [comment]
Fixed with https://github.com/carbon-design-system/carbon-website/pull/1373
