### ISSUE TITLE
Japanese fonts 

### ISSUE THREAD

**Issue by kazumiiinagaki** [carbon-design-system/carbon-website#1795]

**Comment by kazumiiinagaki** [comment]
Please let us confirm the correct Japanese font until IBM Plex will support Japanese. We have 3 questions  

**1)  What is correct your selected font set for Japanese until IBM Plex will support Japanese.**
In Japan  we are using Hiragino Kaku Gothic ProN W3 before June1 2019, following site was updated, for Japanese font 
Based on previous site: https://www.ibm.com/innovate/brand/typography/   Guidance -> Typography -> "What about other languages?
But this pages are updated, your chosen Japanese font is “Noto Sans JP ".
	https://www.ibm.com/design/language/elements/typeface/
We are confusing.  
Is that mean, we cannot use Hiragino Kaku Gothic ProN W3 but we should use "Noto Sans JP” from now on?

2) Usage of your recommended fonts
We are using mixture of 3 kinds of character set, which are Japanese characters, Alphabet and numeric (alphanumeric) characters within in one sentence.

Please let me know which usage is correct?  

a) Use "your chosen font" for all 3 characters for Japanese, Alphabet and numeric characters

b) Use "your chosen font” for Japanese and use "IBM Plex” for Alphabet and numeric character  

I input 4 cases in attached file (Japanesefont.png) , please let us know, which correct font usage is.

**[3)  Documents which were created before this guideline.](url)**
Should we change the fonts set to your chosen fonts (Note Sans JP or Hiragino) which we had already created before this guideline was submitted? 


![Japanesefonts](https://user-images.githubusercontent.com/21253468/60415848-54a82f80-9c17-11e9-83a6-97ecb1a2d331.png)

**Comment by kazumiiinagaki** [comment]
Reopen.

**Comment by alisonjoseph** [comment]
Hi, sorry for the late response, looks like this is documented on the Design Language website. 
https://www.ibm.com/design/language/elements/typeface/#language-support

(scroll down to Asian scripts) and is linked here 
https://fonts.google.com/specimen/Noto+Sans+JP

**Comment by mjabbink** [comment]
For those with interest in IBM Plex Kanji and Kana (Japanese) below are are some samples of early design development:

<img width="1186" alt="Screen Shot 2019-07-22 at 4 19 26 PM" src="https://user-images.githubusercontent.com/32881239/61662526-99663a00-ac9c-11e9-8b5a-29c3aa2db409.png">


<img width="1187" alt="Screen Shot 2019-07-22 at 4 19 39 PM" src="https://user-images.githubusercontent.com/32881239/61662570-ae42cd80-ac9c-11e9-9c1f-f1d24826865a.png">


<img width="1187" alt="Screen Shot 2019-07-22 at 4 19 52 PM" src="https://user-images.githubusercontent.com/32881239/61662585-b3a01800-ac9c-11e9-908d-ecc5da8393c7.png">

**Comment by kazumiiinagaki** [comment]
**Alison** thank you very much for your updates. 
Yes, I also noticed, web site was updated in June 2019 after I input the question. 
For the time being when IBM PlexSans  will support Japanese, I understand we should use Note Sans . 
My question is  when one  sentence ncludes Japanese and English alpha numeric character , how should we use character set for this ?   Which is correct ? 
1) use google Note Sans for all Japanese character and all for alpha numeric character .  
2) use google Note Sans for all Japanese and use IBM PlexSans for alpha numeric .

**Mike** 
Thank you very much.  Those looks  wonderful,  Could you  please tell me when IBM PlexSans for Japanese will be available if you can tell me ?

**Comment by mjabbink** [comment]
@kazumiiinagaki I hope end of 2020 or early 2021. It’s very long timeline due to hinting all the glyphs for PC environments. We will have betas along the way for testing as well as the none hinted versions much earlier.
