### ISSUE TITLE
[Page: form/usage] Image showing wrong validation styling

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#180]
On page https://www.carbondesignsystem.com/components/form/usage/
This image is showing the wrong validation styling. We don't use underline for error. We have a whole red box now. 

![image](https://user-images.githubusercontent.com/15144993/63798468-be6b4f80-c8cf-11e9-8d0c-506d1f623e1e.png)

Should be this style: 

![image](https://user-images.githubusercontent.com/15144993/63798506-d8a52d80-c8cf-11e9-978d-02a8b2ce986a.png)

_Originally posted by @shixiedesign in https://github.com/carbon-design-system/carbon-website/issues/161#issuecomment-525430070_

**Comment by laurenmrice** [comment]
This has been fixed
