### ISSUE TITLE
How to switch color theme in examples?

### ISSUE THREAD

**Issue by NtsDK** [carbon-design-system/carbon-website#1815]
I want to see inline notification examples using other color themes. I don't find theme switch in component itself https://www.carbondesignsystem.com/components/notification/code
, in themes and colors description, in code pen, in frequently asked questions.
Are there any ways to see examples with light theme without installing carbon environment?

**Comment by alisonjoseph** [comment]
Hi @NtsDK this is definitely something we are looking at adding to the website in the future!  In the meantime you can view the components with different themes here, this is just a live demo of our dev testing environment. https://the-carbon-components.netlify.com/?nav=accordion

**Comment by NtsDK** [comment]
@alisonjoseph Thank you for help :) This link is what I looked for :)
