### ISSUE TITLE
Include Carbon Design System icons in Sketch library

### ISSUE THREAD

**Issue by lnajjar** [carbon-design-system/carbon-website#1817]
## Summary

I cannot seem to find the Carbon Design System "notebook" icon in the Carbon Design System Sketch library. When you get a chance, could you please add it? 

I did not cross-check the other icons, so there may be others that are not in the Sketch library. 
## Relevant information

Carbon Design System "Iconography" page with "notebook" icon: [https://www.carbondesignsystem.com/guidelines/iconography/library](url)

Thanks for doing such great work.

**Comment by joshblack** [comment]
Hi @lnajjar! 👋 We're in the process of generating a Sketch Kit that includes all of the icons available on the website. In the interim, the artifact that we have available is the IBM Design Language kit for Sketch available under the resources tile [here](https://www.carbondesignsystem.com/guidelines/iconography/usage#resources). 

Hope this helps!

**Comment by lnajjar** [comment]
Thanks, Josh. Your team is doing a great job.


Lawrence
