### ISSUE TITLE
IBM imagery

### ISSUE THREAD

**Issue by aalacs** [carbon-design-system/carbon-website#1820]
Dear Team, 

is there already an existing image library from where we can download the official photos and vector files? I was unable to find them on the website. 

Thank you in advance, 
Anna

**Comment by jeanservaas** [comment]
Hi @aalacs 

qq which assets are you trying to access? The brand team (specifically Lisa Lind their Executive Producer) owns the masterbrand image library credentials and she's the only one who can add users / share out that link.

IBM's brand center site also has links and resources to get various logo assets 
https://www.ibm.com/brand/resources

The Carbon app icon and Carbon pictogram are available in the masterbrand app icon / masterbrand pictogram .ai files which I think are available on the IDL site. I will double check, if not I can get those files to you. 

If you get me a little more context I'll be able to get you what you need. The Carbon illustrations that we do for our social communications aren't really publicly available, we just keep them on an internal box.

**Comment by aalacs** [comment]
Hi jeanservaas!

Thank you for your reply! 
I am a visual designer in Budapest and as a part of my work I am creating print and online deliverables for IBM sellers. Last week my team had a meeting with Mike Abbink about the Carbon design and he mentioned that his team is now building a library with photographs that can be used for our communication. I have seen on the website these images: 
https://www.ibm.com/design/language/elements/photography
I am not able to download them from the site and wondering whom I should contact to be able to start using the new imagery (if they already can be used). 
When you mentioned Carbon illustrations, were you talking about vector based illustrations or photography or both? Will these be available for other designers in the future? 
Thank you for your reply in advance!
Anna

**Comment by jeanservaas** [comment]
Hi Anna,

Our illustration style is still a work in progress, so there's nothing available yet to download in that department. But as for the images, contact Lisa Lind, the Executive Producer on the brand team to get access to the photo library. Good luck!
