### ISSUE TITLE
Sticky color theme switcher positioning

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#1828]
It's sitting low when you scroll.

![image](https://user-images.githubusercontent.com/1691245/94072109-b32c7100-fdba-11ea-98b7-89a651932c49.png)

**Comment by mjabbink** [comment]
![ezgif com-optimize (1)](https://user-images.githubusercontent.com/32881239/94200720-7c209300-fe80-11ea-9679-a8eea199df09.gif)

**Comment by aagonzales** [comment]
Duplicate issue, I also believe it's already fixed. 
https://github.com/carbon-design-system/carbon-website/issues/1302
