### ISSUE TITLE
FormGroup component in Form doc missing required prop 

### ISSUE THREAD

**Issue by queeniema** [carbon-design-system/carbon-website#1831]
## Summary

Issue here: https://www.carbondesignsystem.com/components/form/usage#live-demo

The code snippet provided is the following:

```
<Form>
  <FormGroup>
    <TextInput
      helperText="Optional helper text here; if message is more than one line text should wrap (~100 character count maximum)"
      id="test2"
      invalidText="Invalid error message."
      labelText="Text input label"
      placeholder="Placeholder text"
    />
  </FormGroup>
...
```

When opening the example in CodeSandbox, I see this error in the Console:

```
Warning: Failed prop type: The prop `legendText` is marked as required in `FormGroup`, but its value is `undefined`.
```

According to the Storybook, `legendText` is in fact required, but the sample code does not include that prop.

<img width="1019" alt="Screen Shot 2020-09-24 at 8 35 19 AM" src="https://user-images.githubusercontent.com/2454818/94167138-00ebbc80-fe41-11ea-8a40-ee9048bb9a52.png">

**Comment by queeniema** [comment]
@tw15egan I see that the `FormGroup` components were removed and I don't see any other references to them on that doc page. In what scenarios should they be used?

**Comment by tw15egan** [comment]
@queeniema Seems like they are mainly used to wrap `RadioButtonGroup` and `Checkbox` so that they have an associated `legend` element to work as a label.
