### ISSUE TITLE
Color —> Usage —> sticky tabs gone wild.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1840]
https://www.carbondesignsystem.com/guidelines/color/usage

The tabs need to behave like the search/dropdown in Icons page:
https://www.carbondesignsystem.com/guidelines/icons/library

FYI: @jeanservaas @aagonzales

**Comment by tw15egan** [comment]
Will be closed with https://github.com/carbon-design-system/carbon-website/pull/1841

**Comment by tw15egan** [comment]
Closing as dup of #1828

**Comment by aagonzales** [comment]
Even older dup issue: https://github.com/carbon-design-system/carbon-website/issues/1302
