### ISSUE TITLE
<ibm-date-picker  cannot show in <ibm-tabs, please fix issue

### ISSUE THREAD

**Issue by klower** [carbon-design-system/carbon-website#1842]
![image](https://user-images.githubusercontent.com/4176873/61957361-b4fd7780-aff1-11e9-957e-5ff4c73044d4.png)

![image](https://user-images.githubusercontent.com/4176873/61957384-c050a300-aff1-11e9-9983-404532e13c17.png)

click calendar input, nothing happened

**Comment by asudoh** [comment]
Hi 👋 is this issue against the Carbon Angular library, or against carbondesignsystem.com site?

**Comment by klower** [comment]
Carbon Angular library

**Comment by alisonjoseph** [comment]
Please open an issue in the Angular repo! https://github.com/ibm/carbon-components-angular
