### ISSUE TITLE
can't open the link of the documentation in storybook

### ISSUE THREAD

**Issue by yongrongwang** [carbon-design-system/carbon-website#1844]
## Summary
Can't open the link of the documentation in storybook, such as `https://angular.carbondesignsystem.com/?path=/story/components-modal--documentation`.
## Relevant information
The page shows `404: File not found. The site configured at this address does not contain the requested file. If this is your site, make sure that the filename case matches the URL. For root URLs (like http://example.com/) you must provide an index.html file. `.

**Comment by joshblack** [comment]
Hey there @yongrongwang! 👋 

Definitely see what you're saying, and it seems like the link does exist in the sidebar.

@cal-smith are we maybe pointing to the wrong page from the Carbon site, or is something else going on here?

**Comment by cal-smith** [comment]
As far as I'm aware those are just internal links between our storybook and our docs site ... All the links changed recently which is why they're 404ing ... @yongrongwang you can still use angular.carbondesignsystem.com/documentation while we update all the links

**Comment by cal-smith** [comment]
@joshblack I believe this can be closed, we have a couple issues on our side to track this 👍

**Comment by tw15egan** [comment]
Thanks, @cal-smith ! 🙏
