### ISSUE TITLE
Tool tips on the progress indicator have bugs 

### ISSUE THREAD

**Issue by davidicus** [carbon-design-system/carbon-website#1845]
Tool tips on progress indicator have a few issues.

## What package(s) are you using?

- [x ] `carbon-components`
- [x ] `carbon-components-react`

## Detailed description

1. When you hover over progress step the tooltip flashes continuously 
2. The placement of the tooltip is right over the step making it impossible to see or click
2. When you wrap the progress indicator in a tool tip it swallows the onClick and onChange event and doesn't allow for the step to progress. Seen in both the carbon react storybook's interactive example and in our own storybook that uses the progress indicator. 

 It is related to the progress indicator component

- Expected tooltip to flash once on hover and stay visible until i moved my mouse away
- Expect to be able to progress the steps

Chrome

Current. This bug is visible in the carbon design system website and storybook

## Steps to reproduce the issue

1. Go to the progress indicator tab in the Carbon design system website
2. Hover at the bottom of a progress step
3. See flashing

1. Go to the interactive example of the progress indicator and try to progress the steps. 
Only the first one will register the onchange. The third one with the tooltip will not. 

## Additional information

![image](https://user-images.githubusercontent.com/1590966/61977581-d09a5b00-afbc-11e9-8fc7-ca6e09a796d6.png)

![ProgressGiphy](https://user-images.githubusercontent.com/1590966/61978066-33402680-afbe-11e9-80fd-faf174c03847.gif)

**Comment by davidicus** [comment]
Thanks @asudoh for the response.

**Comment by davidicus** [comment]
Is there a way to pass the onClick to the tooltip element? currently if you try to render a carbon tooltip as the progress step it will stop bubbling and you will not be able to change step by clicking the label. Is this correct? Thanks for your time.

**Comment by asudoh** [comment]
When I go to http://react.carbondesignsystem.com/?path=/story/progressindicator--interactive, select `<div class="bx--tooltip__label bx--progress-label">` in DOM inspector, put `$0.addEventListener('click', event => { console.log('Event:', event); })` in Console tab, and then click on the 3rd progress step item, I see an event sure is fired. That said, do you want to create a React component that wraps the interactive tooltip, and attach the event listener in DOM level at its `cDM`?

**Comment by davidicus** [comment]
The tool tip fires an onClick but if I try to wrap the tooltip and attach an onClick to the wrapped element the tooltip element calls `stopPropagation()` on the event which will prevent my onClick from firing. 

I was just trying to verify if there was a way that I was missing that would allow me to pass onClicks without attaching listeners on the DOM level. 

Thanks again for the quick reply.
