### ISSUE TITLE
Investigate and resolve any issues with icons in tutorial

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#1846]
We recently received feedback around an issue when working with `@carbon/icons-react` in the tutorial. Unfortunately, this feedback from our survey does not include any additional information.

This issue is to investigate and see what issues individuals doing the tutorial may be running into and resolve any that come up.

**Comment by mattrosno** [comment]
Recent feedback:

> One instruction is either outdated or wrong.. The import of icons component returns error on steps 1 and 4. If you check on the origin code, they were imported with a different code than what is provided on tutorial.

https://ibm-studios.slack.com/archives/GUQ4AAF9P/p1601607040000500

**Comment by rjhenriquez** [comment]
Tutorial referenced: https://www.carbondesignsystem.com/developing/react-tutorial/overview

**Comment by mattrosno** [comment]
@chrisconnors-ibm experienced this error in step 4, from CI:

```
#!/bin/bash -eo pipefail
yarn install --offline --frozen-lockfile
yarn install v1.22.5
[1/4] Resolving packages...
error Couldn't find any versions for "@carbon/icons-react" that matches "^10.21.0" in our cache (possible versions are ""). This is usually caused by a missing entry in the lockfile, running Yarn without the --offline flag may help fix this issue.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.


Exited with code exit status 1
CircleCI received exit code 1
```

**Comment by tw15egan** [comment]
Was able to resolve the lockfile error with `rm -rf .yarn-offline-mirror node_modules && yarn cache clean && yarn install` 

Instructions on tutorial:
https://www.carbondesignsystem.com/developing/react-tutorial/step-4#pull-request-(pr)
