### ISSUE TITLE
Tile links not working

### ISSUE THREAD

**Issue by cassiesharp** [carbon-design-system/carbon-website#1850]
Tile links don't work. They go to a 404 page.

https://www.ibm.com/design/language/elements/app-icons/

![image](https://user-images.githubusercontent.com/22551396/62162967-04d48b00-b2df-11e9-812c-02691d581009.png)

![image](https://user-images.githubusercontent.com/22551396/62163185-78769800-b2df-11e9-843a-4bc66f76ee15.png)

**Comment by alisonjoseph** [comment]
should be fixed with updates launching next week
