### ISSUE TITLE
Patterns status overview design specs - Cupcake

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#186]
Create a vision for a pattern status overview page that can be delivered within the next release schedule.

**Considerations:**
- How breadcrumb navigation can be adapted in our site's UI.
- What does that third level of the site look like?
- W3 login similar to team Able's implementation
- Keeping the same depth of navigation, can dividers be used to separate the experimental patterns vs. the prod ones?

**Requirements** 
- [ ] Review experience roadmap for pattern status overview
- [ ] Filter control on source
- [ ] Create mockups including different states
- [ ] Thumbnail view representing the pattern.
- [ ] Search results on author, source, state
- [ ] Metadata required:
- author
- source (business)
- Version
- state (Experimental, Beta, GA)

**Comment by janchild** [comment]
Closing.
