### ISSUE TITLE
fix[overflow menu icon]: overflow menu icon on color usage tab too small

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1861]
## fix[overflow menu icon]: overflow menu icon on color usage tab too small

Somehow, the overflow icon here got shrunk, this was definitely a regression. 

Icon should be 16px on a 32px background.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/10a9d941-04eb-4892-a905-50049704502c)

**Comment by tw15egan** [comment]
Seems like this has always been `12px`, but regardless we just need to change this line to `16px` 

https://github.com/carbon-design-system/carbon-website/blob/286f035bd9b9589f8fcc88f444aad86cc1d257f2/src/components/ColorTokenTable/color-token-table.scss#L86-L89
