### ISSUE TITLE
OverflowMenu doesn't focus properly when clicked

### ISSUE THREAD

**Issue by Eryk-Jarocki1** [carbon-design-system/carbon-website#1866]
## Detailed description

I am currently implementing vertically scrollable table component with OverflowMenu for each row in the table. The problem is when I open one OverflowMenu, for example in the first row, and then scroll down and open different menu, focus stays on the previously clicked menu. This causes scrollbar to move up. I found the reason why it happens this way. Here is the code sandbox https://codesandbox.io/s/codesandbox-forked-wirx0?file=/src/index.js. You need to open the browsers console first and try above scenario. You will notice that the onFocus prop function of the previously opened OverflowMenu will be triggered as last. This causes focus to be wrongly assigned. The bug was probably introduced in 7.12.0, because in 7.11 focus is correctly assigned to the last clicked menu.

> What did you expect to happen? What happened instead? What would you like to see changed?
focus is properly set on the last clicked menu.
> What browser are you working in?
Chrome
## Steps to reproduce the issue
Checkout the sandbox https://codesandbox.io/s/codesandbox-forked-wirx0?file=/src/index.js

## Additional information

- Screenshots or code
https://codesandbox.io/s/codesandbox-forked-wirx0?file=/src/index.js

**Comment by tw15egan** [comment]
After updating the packages to the latest versions (`10.21.0`/`7.21.0`) I'm not able to reproduce the issue. Can you try updating your packages to the latest and see if your issues are resolved in your application?

**Comment by Eryk-Jarocki1** [comment]
Also checked the issue on newest versions and everything works fine. Thank you!
