### ISSUE TITLE
Tooltip: Live demo is showing incorrect styles for dark themes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1867]
The live demo is currently showing the tooltips trigger button with incorrect colors for the dark themes:

<img width="1143" alt="Screenshot 2023-08-23 at 3 33 05 PM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/2c944e63-5923-4656-bc5f-11b867e47a55">

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
