### ISSUE TITLE
Color Swatch Component for Carbon Site

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#187]
@claycrenshaw commented on [Wed Oct 03 2018](https://github.com/carbon-design-system/issue-tracking/issues/34)

We need a MD-friendly component which will display a solid color swatch at a specified size.

Ideally, the component will be directly linked to the Carbon palette via tokens. Also, would be good to be able to use tokens to specify the dimensions of the rectangle.

So, for example, if I could specify in my MD file that I need a (M) sized swatch of color (Blue-60), the code would generate a rectangle of a pre-specified size and the hex code that is officially linked to “Blue 60”

If the swatch needs to represent a color that falls outside our “official” tokenized palette, then I should be able to specify the color via hex code.

---

@claycrenshaw commented on [Wed Oct 03 2018](https://github.com/carbon-design-system/issue-tracking/issues/34#issuecomment-426672750)

@alisonjoseph

**Comment by alisonjoseph** [comment]
What size options are needed? Can I get a sketch file or screen shot of what it should look like. 

propose to update 

`<color-block>#ff0000</color-block>`

to

`<color-block size="sm">#ff0000</color-block>`
`<color-block size="md">#ff0000</color-block>`

Current color block displays this
<img width="113" alt="screen shot 2018-10-04 at 1 28 14 pm" src="https://user-images.githubusercontent.com/2753488/46494798-63bd9680-c7d9-11e8-9dae-fbd16fa7489a.png">

**Comment by lovemecomputer** [comment]
is there a spec for size/etc in the color block? @claycrenshaw maybe you know? thanks!

**Comment by alisonjoseph** [comment]
Currently the color block displays the hex value to the left, is that something you want to keep or have it as optional for the new component?
<color-block>#3d70b2 </color-block>
currently displays as
<img width="114" alt="screen shot 2018-10-15 at 4 46 04 pm" src="https://user-images.githubusercontent.com/2753488/46980326-d3fdcf00-d099-11e8-9a92-bab11bef23fe.png">

**Comment by lovemecomputer** [comment]
thanks @claycrenshaw !

**Comment by lovemecomputer** [comment]
this issue addressed in https://github.com/carbon-design-system/carbon-website/pull/286 !
