### ISSUE TITLE
Designing: Tutorial page: Videos need additional functionality for scrubbing and playing full screen

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1899]
https://www.carbondesignsystem.com/designing/tutorials

See IDL example. These are in Vimeo to get the video player functionality. We stripped down their player to just the functionality we needed. This includes scrubbing, expand and collapse to full screen and quality controls.
https://www.ibm.com/design/language/typography/typeface

FYI @jeanservaas

**Comment by johnbister** [comment]
@mjabbink just realized I made a duplicate issue for this.  Whoever has access to the vimeo account can turn on playbar and sound. 
<img width="621" alt="96615125-850d5480-12c6-11eb-8132-6edec4792983" src="https://user-images.githubusercontent.com/70543333/96921610-6c42a180-1474-11eb-8350-27decef32984.png">

**Comment by johnbister** [comment]
@mjabbink design tutorial videos should have the additional functionality now. let me know if this looks right 

https://www.carbondesignsystem.com/designing/tutorials

**Comment by mjabbink** [comment]
@johnbister Looks good to me. Exactly what was missing.

**Comment by tw15egan** [comment]
Going to close this as resolved, feel free to reopen if anything else needs to be done 👍
