### ISSUE TITLE
Enhance guidance regarding the form component re placeholder text and helper text

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon-website#1907]
## What the current guidance states: 
For reference, here is the current Carbon [form](https://www.carbondesignsystem.com/components/form/usage/) guidance has to say about helper text and placeholder text: 

![Carbon_form](https://user-images.githubusercontent.com/9316771/96558761-0d362e80-12b4-11eb-99ca-639c7076eccf.png)

From the "Formatting" section ([link](https://www.carbondesignsystem.com/components/form/usage#formatting)):
> Helper text: Provides assistance on how to fill out a field. Helper text is optional.
> Placeholder text: Hints at what goes into a field. Placeholder text is optional.

From the "Content" section ([link](https://www.carbondesignsystem.com/components/form/usage#content)):
> **Helper text**
> Helper text is pertinent information that assists the user in completing a field. Helper text is always available when the input is focused and appears underneath the label. Use sentence-style capitalization, and in most cases, write the text as full sentences with punctuation.

> **Placeholder text**
> Placeholder text provides hints or examples of what to enter. Placeholder text disappears after the user begins entering data into the Input and should not contain crucial information. Use sentence-style capitalization, and in most cases, write the text as a direct statement without punctuation.

## Summary
What this issue relates to:
- The Carbon [form](https://www.carbondesignsystem.com/components/form/usage/) component — and specifically the guidance re helper text and placeholder text.

Who is providing this feedback:
- Tom Waterton, on behalf of the Cloud & Cognitive org Design System Adoption Guild (DSAG).

Why we're raising this issue:
- We are seeing a lot of inconsistency across products in terms of how form field helper text and placeholder text is being used.
- We think that if the form component contained a bit more guidance, this will help teams produce more consistent forms.

## Relevant information
Our understanding of your guidance as it stands today:
With regard to helper text and placeholder text, it seems that the current guidance allows teams to build form fields where:
- the form field has both helper text and placeholder text
- the form field has helper text but not placeholder text
- the form field has placeholder text but not helper text
- the form field has neither helper text nor placeholder text

This seems reasonable, as it accounts for different scenarios and needs. 

However, we are seeing instances that don't strictly comply with any of the above 4 approaches, so we thought we would bring these to your attention to see if some further guidance can be provided.

### Issue 1: People using placeholder text when they should be using helper text.
Reading your guidelines, it seems that helper text is intended for additional information to help the user know how to fill in the field (and this is always available), whereas the placeholder text is more intended for an example (and this disappears when the user starts entering data into the input field). 

**What we understand to be a correct example:**
> **Phone number** — `field label`
> [ e.g. 44 7777 1234567 ] — `form input field, with placeholder text providing an example (disappears when the user starts entering data in the input field)`
> Prefix your phone number with the relevant country calling code. — `helper text (always present)`

But we fairly often see form fields where people have chosen not to use helper text at all, and have instead used the placeholder text to provide additional information about how to complete the field. 

**Example 1a:** 

> **Phone number** — `field label`
> [ Prefix your phone number with the relevant country calling code. ] — `instructional help entered (incorrectly according to your current guidance) as placeholder text`

**Example 1b:**
> ![example_1](https://user-images.githubusercontent.com/9316771/96560583-67d08a00-12b6-11eb-8055-dd38187c2ba8.png)

It is likely that some teams do this because the placeholder text option (which sits within the field) requires no additional space in the form, whereas the helper text site below the inout field and therefore takes up additional space in the form.

If you think this is acceptable, then it would be good to update the current guidance to reflect this. 
If, on the other hand, you don't want people to use placeholder text in this way, then it would be good to explicitly state this. 

### Issue 2: People adding helper text that is not needed / adds no value
Another issue we see regularly is where teams add placeholder text that merely repeats the field label and therefore adds no value. 

**Example 2a:** 
> Email address — `field label`
> [ Add your email address ] — `placeholder text has been added but adds no value`

**Example 2b:** 
> ![Example_2](https://user-images.githubusercontent.com/9316771/96559862-78cccb80-12b5-11eb-9729-63564270b564.png)

Therefore, it would be good if your guidance explicitly said not to do this (i.e. if the field label alone is sufficient, you don't need to add placeholder text or helper text — even if other fields within the same form do require helper text or placeholder text). 

### Issue 3: People using tooltips to contain help information
Sometimes, when teams do need to provide the user with additional help text, they are choosing to add an information (i) hover-help icon next to the field label or making the field label itself a definition tooltip. 

**Example 3a:** 
> Phone number (i)  — `field label with an info tooltip icon`
> [                                          ] — `empty input field`

**Example 3b:** 
> [Phone number](/)   — `field label that has been made into a definition tooltip`
> [                                          ] — `empty input field`

We assume that this is not what you intend teams to do and that in such cases, teams should be using helper text to show the additional information below the form input field? If so, it would be helpful if you covered this explicitly in the guidance.

**Comment by chloepoulterdesign** [comment]
+1 to this issue - actively hitting this discussion every release of our products. Please can we get clearer guidance.

**Comment by godivareisen** [comment]
Agreed—our product consistently encounters issues and inconsistencies with placeholder/helper text in form design.

There could also be some additional clarification on how "info icon" tooltips intersects with helper text. Our product often leans on these "info icon" tooltips to convey information that I expect would be better handled as helper text...so it would be great to get clearer guidance on the do's and don'ts of placeholder text, helper text, and info tooltips.

**Comment by aagonzales** [comment]
Update were made to improve this guidance on the form page. I added updates into an existing [PR](https://github.com/carbon-design-system/carbon-website/pull/3356) open concerning the form component page but it is currently in a staging branch and should be public soon.
