### ISSUE TITLE
header title should be all SemiBold

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1914]
Should be 

**Carbon Design System**

Not 

Carbon **Design System**

**Comment by mjabbink** [comment]
FYI @jeanservaas

**Comment by tw15egan** [comment]
Does this mean all UI Shell guidance + styles need to be updated as well?

https://www.carbondesignsystem.com/components/UI-shell-header/usage#anatomy

**Comment by mjabbink** [comment]
@tw15egan Just for the Carbon site. The guidance above is correct if [IBM] is in front. But in the case of Carbon Design System it should all just be the semibold and not a mix of regular and semibold.
