### ISSUE TITLE
Adding Month picker possibility

### ISSUE THREAD

**Issue by ignaciolavina** [carbon-design-system/carbon-website#1924]
## Adding the possibility of month picker

Currently, the date calendar displayed always shows day-month-year, but sometimes it is only necessary to select a specific month or year.

Would be possible to implement those functionalities?

It would be something like this Vuetify component: https://vuetifyjs.com/en/components/date-pickers-month/#usage

I can see that now is possible to have the month picker functionality when the variant selector is by default, without the calendar dropdown. But Would be nice to have the functionality with the calendar displayed.

Thank you!

**Comment by vpicone** [comment]
At the moment, we're not going to pick this up. We recommend Dropdown or Select with the months as options. If you come up with an implementation, we'd be interested in checking it out. Thanks!
