### ISSUE TITLE
[checkbox] update live demo to show correct disabled state

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1925]
The live demo on the checkbox tab currently shows incorrect disabled state styles. It is currently a bug in the demo, but correct in react.

<img width="1148" alt="Screen Shot 2020-10-27 at 12 30 52 PM" src="https://user-images.githubusercontent.com/43969356/97339270-bfdc3300-1858-11eb-89e7-7b9f3a862060.png">

**Comment by laurenmrice** [comment]
This is still happening but now with the checkbox group header.
<img width="1108" alt="Screen Shot 2022-10-25 at 11 39 26 AM" src="https://user-images.githubusercontent.com/43969356/197819005-455417f1-0f06-4e11-810b-da8316d3ade1.png">

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
