### ISSUE TITLE
step3: process.env is not evaluting

### ISSUE THREAD

**Issue by zoranid** [carbon-design-system/carbon-website#1930]
step3:
src/index.js:

const client = new ApolloClient({
  uri: 'https://api.github.com/graphql',
  headers: {
    authorization: \`Bearer ${process.env.REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN}\`,
  },
});

and 

.env.local:
REACT_APP_GITHUB_PERSONAL_ACCESS_TOKEN=XXXXXXXX 

Error! Network error: Response not successful: Received status code 401

but directly, 

const client = new ApolloClient({
  uri: 'https://api.github.com/graphql',
  headers: {
    authorization: \`Bearer XXXXXXX\`,
  },
});

 works fine.  Any idea?

**Comment by tw15egan** [comment]
Hmm that's strange, everything looks correct to me
