### ISSUE TITLE
[code snippet] live demo has bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1932]
The live demo is showing some bugs for the code snippet component.

----------------------------------------------------------------------------------------------------------------------------

**Inline:**
- When copying the inline snippet, the word in the tooltip also appears in the field. 
![code snippet inline](https://user-images.githubusercontent.com/43969356/97487907-e58a3a80-1933-11eb-928c-6c0b213051d3.gif)

----------------------------------------------------------------------------------------------------------------------------

**Single line:**
- When applying the light modifier, only the copy button is getting the background color change with the light prop. The field should also be getting the background change.
![light prop](https://user-images.githubusercontent.com/43969356/97491828-1456df80-1939-11eb-9177-2beedea0ac42.gif)

----------------------------------------------------------------------------------------------------------------------------

**Multiline:**
- Same bug as single line with the light prop. It is only being applied to the buttons.^

**Comment by NBNARADHYA** [comment]
Hello! @laurenmrice Could I fix this issue ? This issue actually traces back to [this repo](https://github.com/carbon-design-system/carbon). Could I raise an issue there ?

**Comment by laurenmrice** [comment]
Yes, you can fix this issue! 👍🏻

**Comment by NBNARADHYA** [comment]
Sure. I will raise an issue on [this repo](https://github.com/carbon-design-system/carbon) and assign it to myself!

**Comment by NBNARADHYA** [comment]
Sure

**Comment by laurenmrice** [comment]
This actually has not been fixed yet in the live demo on the website.

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
