### ISSUE TITLE
fix[data viz color palette]: light and dark theme palettes are not switching

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1936]
In the pairings switcher, the when users toggle between Light and Dark tabs, the palettes do not change.

The component is displaying the dark theme palette under the Light tab as well as the Dark tab, whereas it should display the Light theme palette when the user selects the Light tab:

![image](https://user-images.githubusercontent.com/43144260/97634991-a1b33600-1a04-11eb-8d72-d7b183a0de1b.png)

![image](https://user-images.githubusercontent.com/43144260/97635066-bdb6d780-1a04-11eb-92d1-756c59b0560f.png)

The same error is happening with the Alert palette switcher, only the light theme palette is showing for both the Light and Dark tabs :

![image](https://user-images.githubusercontent.com/43144260/97635289-15edd980-1a05-11eb-9e64-cceeaf9749b2.png)

![image](https://user-images.githubusercontent.com/43144260/97635294-1c7c5100-1a05-11eb-9d13-1fd543b37233.png)

**Comment by mjabbink** [comment]
@alisonjoseph This needs to be prioritized big time. Not understanding why this is not resolved in 25 days. @jeanservaas and @alisonjoseph please keep me posted on issue. Needs to be closed next week please.

**Comment by tw15egan** [comment]
@mjabbink pr is up to fix the grouped color palettes, but it looks like there is only 1 palette for `alerts` across both themes

https://github.com/carbon-design-system/carbon-website/blob/79071bc7ef6d6fe236d987738af3c59b4d57514c/src%2Fdata%2Fdata-visualization%2Fpalettes.js#L1171-L1192

@jeanservaas is this incorrect?
