### ISSUE TITLE
Production Guidelines for usage images

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#1939]
Issues inside this epic will include the following topics:

* Brief audit of Digital, Brand, PAL and Carbon usage images to determine need and scope of kit and template tooling
* Sync with Anna and Lauren on kit naming conventions and techniques for nested symbols and layer styles (this will include several playbacks/reviews of progress)
* Sync with Jan to determine where the Production Guidelines content can live on the Carbon website
* New topics to be included:
    * A breakdown of the types of usage images used in our ecosystem
    * Guidance on aspect ratios, image sizing, file types, margins and image background colors
    * Guidance on Image components usage/scaling behavior
    * A breakdown of highlighting techniques across image types including:
        * Callouts
        * Opacity and boxing
        * Crops and truncations
        * Exposed grids
* New tooling to be included:
    * Grided, to-scale, Sketch templates for the most common sizes, aspect ratios and use cases
    * Cupcake Sketch kit with key symbols for callouts, annotation marks and cropping

Sync with Jan closely on the content guidelines to make sure there is a consistent approach for what lives where and on any audits of docs images and content. https://github.com/carbon-design-system/carbon-website/issues/859

Sync with Mike closely on styling and include at least one playback to digital / brand team designers

The issues will be as follows:
1. Audit in MURAL of usage images in the PAL ecosystem
2. Tooling including Sketch templates and a symbol library
3. Guidance on the site (2021)

**Comment by mjabbink** [comment]
@mattrosno @shinytoyrobots Getting these production guidelines done is an absolute priority. It’s foundational to our primary offering and the guidance we need to provide. We need to get this done and make it available.
