### ISSUE TITLE
How to implement the focused search?

### ISSUE THREAD

**Issue by OrionBill** [carbon-design-system/carbon-website#1947]
## Summary
How to implement the focused search?

## Relevant information

I reach the page
https://www.carbondesignsystem.com/patterns/search-pattern#focused-search
And the pattern is impressive, but I cannot find a way to implement this. It mentions about `basic search and active search` but I cannot find any option in the source code (https://github.com/carbon-design-system/carbon/blob/master/packages/react/src/components/Search/Search.js) and the doc (https://react.carbondesignsystem.com/?path=/docs/search--default). So is there any doc telling how to implement the pattern "focused search" in React?

**Comment by hugo-dlb** [comment]
I found this thread:
https://github.com/carbon-design-system/carbon/issues/3513
Which is specific to the react library of carbon (I think), and there are no components available for this pattern at the moment sadly.

**Comment by OrionBill** [comment]
Thanks @hugo-dlb 
Yes, seems no component for this pattern.

**Comment by laurenmrice** [comment]
Hi @OrionBill 👋

Our Search pattern does not have a coded component. Our Patterns currently feature recommended visual guidance and best practice solutions. Most of our patterns do not have any code tied to them at the moment. Going to close this issue for now, but re-opeon if you have any other questions.
