### ISSUE TITLE
[live demo] data table bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#1949]
**On the data table live demo**:
- [x] the `zebra strip` modifier not working (in all browsers)
- [ ] the `zebra strip` not working properly in non-white themes
- [x] the `row size` modifiers are not working (in all browsers) 
- [ ] In G90 and G100 theme the hover for sort is coming in the wrong color
   ![image](https://user-images.githubusercontent.com/11670886/98050007-765e8b80-1df6-11eb-81ef-d42b3311766f.png)

**Missing functionality**:
- [ ] Single selection with Radio button
- [ ] Batch expansion

**Comment by aagonzales** [comment]
Related: https://github.com/carbon-design-system/carbon-website/issues/1687

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
