### ISSUE TITLE
remove white vertical line on right side of image

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#1972]
carbon home page 

![Screen Shot 2020-11-11 at 7.48.50 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/a191b833-a8f5-4c01-bf16-eec24b96a12b)

**Comment by mjabbink** [comment]
FYI @jeanservaas

**Comment by jeanservaas** [comment]
Here's the fixed artwork, I'm actually wondering if @shixiedesign needs to update it on medium, since our site pulls in from medium I think. Let me check.

![Medium_article_image](https://user-images.githubusercontent.com/43144260/99001356-56b71980-2500-11eb-92ae-61f4120567a0.png)

**Comment by mjabbink** [comment]
Would be great if @shixiedesign can update.

**Comment by jeanservaas** [comment]
So @shixiedesign updated the image already, but @alisonjoseph it looks like it hasn't fixed the problem. Maybe we can replace the image with the one above on our end. Thanks!

**Comment by alisonjoseph** [comment]
No longer seeing any image issues on the website, please reopen if I missed something.
