### ISSUE TITLE
[live demo] dropdown bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#1987]
The live demo for dropdown has the followings bugs:

---------------------

**Dropdown**
- [ ] missing inline variant prop
- [ ] missing different size variants
- [ ] missing direction prop to open bottom/top
- [ ] missing warning state prop
- [ ] missing invalid state prop
- [ ] When the light prop is applied it is not showing the latest updates of the color changes we made with hover-light-ui token.
- [ ] The dropdown size changes in width depending on the text length of the option you select from the menu. The dropdown should maintain the same width no matter how long the option text entry is.
![Nov-16-2020 13-42-23](https://user-images.githubusercontent.com/43969356/99299965-fd116080-2819-11eb-9578-c9d96836c29d.gif)

---------------------

**Combo box**
- [ ] missing inline variant prop
- [ ] missing different size variants
- [ ] missing direction prop to open bottom/top
- [ ] missing warning state prop
- [ ] missing invalid state prop
- [ ] the close icon should be `icon-01`
- [ ] The field of combobox is showing up empty. The prompt text "Filter..." needs to be shown in the field as`body-short-01` and `text-03`.
<img width="1117" alt="Screen Shot 2020-11-16 at 3 25 01 PM" src="https://user-images.githubusercontent.com/43969356/99310197-a5c6bc80-2828-11eb-9e97-12918a336fb7.png">
- [ ] The text sits too high and is not sitting in the center vertically within the field.
<img width="378" alt="Screen Shot 2020-11-16 at 3 28 02 PM" src="https://user-images.githubusercontent.com/43969356/99310358-eb838500-2828-11eb-92e9-366be5d9a012.png">

---------------------

**Multi-select/Filterable Multi-select**
- [ ] missing inline variant prop
- [ ] missing different size variants
- [ ] missing the direction prop to open bottom/top
- [ ] missing warning state prop
- [ ] missing invalid state prop
- [ ] The option text in the open menu needs to be `text-02` not `text-01` by default. It changes to text-01 on hover or when selected.
- [ ] The number in the tag sits too high. It needs to be center within the tag container.
- [ ] the close icon should be `icon-01`  for the filterable multi-select.

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
