### ISSUE TITLE
[overflow menu] bug in live demo

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#2002]
- The overflow menu in the dark themes should not be high contrast. The background color should be `field-01`.

**Current bug:**
<img width="443" alt="Screen Shot 2020-11-23 at 11 22 23 AM" src="https://user-images.githubusercontent.com/43969356/99994142-4152b280-2d7e-11eb-9ab2-44c5dfd677d1.png">

**Should be:**
![1](https://user-images.githubusercontent.com/43969356/99996035-cb9c1600-2d80-11eb-8dc0-e3ed7be6075c.png)

---------------

- The overflow menu is also getting a partial wrong color inside of the square where the icon sits. The entire square background should be `field-01`. This is happening in all themes.

**Current bug:**
<img width="443" alt="Screen Shot 2020-11-23 at 11 22 23 AM" src="https://user-images.githubusercontent.com/43969356/99994432-9bec0e80-2d7e-11eb-8edd-e55fc2ebe406.png">

**Should be:**
![2](https://user-images.githubusercontent.com/43969356/99996026-c8a12580-2d80-11eb-9dbc-77f9837a9533.png)

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
