### ISSUE TITLE
[live demo] date picker bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2003]
## Live demo bugs

**Simple date picker**
- [x] Missing disabled
- [x] Missing sizes
- [x] Missing invalid

**Single date calendar picker**
- [x] Missing disabled
- [x] Missing sizes
- [x] Missing invalid
- [ ] Calendar appearing in wrong color in the White, G90 and G100 themes
![image](https://user-images.githubusercontent.com/11670886/100019773-40cd1280-2da4-11eb-9b28-dbcde932b512.png)

**Range calendar picker**
- [x] Missing disabled
- [x] Missing sizes
- [x] Missing invalid
- [ ] Calendar appearing in wrong color in the White, G90 and G100 themes
![image](https://user-images.githubusercontent.com/11670886/100268337-77c53480-2f1a-11eb-9c36-c926a47a6050.png)

**Comment by emyarod** [comment]
the calendar color issues should be resolved in https://github.com/carbon-design-system/carbon-website/pull/2262

**Comment by aagonzales** [comment]
The updates are only on the demo in the code tab, they also need to be on the demo on the usage tab as well. 
https://carbondesignsy-git-fork-emyarod-2003-date-picker-demo-bu-3a47e9.vercel.app/components/date-picker/usage#live-demo
