### ISSUE TITLE
Button focus border

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#203]
## Detailed description

https://www.carbondesignsystem.com/components/button/style/ defines a focus border color but no focus border size.

https://www.carbondesignsystem.com/components/button/code/ examples show a 2-tone border on focus with a white 1px border inset inside of a 3px blue border.  Seems strange as it deviates quite a bit from input focus borders.  Is this intended? It does not seem to be documented.

## Additional information

![carbon_button3](https://user-images.githubusercontent.com/9935157/63897649-86d9d180-c9bb-11e9-9811-db35675d6121.png)

**Comment by aagonzales** [comment]
This is as intended all our focus borders should be 2px in that $focus token color. These buttons have to have the extra 1px white border so that the focus and button background are distinguishable.

**Comment by aagonzales** [comment]
We can add more details around the focus state for buttons on the style tab that include this.

**Comment by aagonzales** [comment]
Guidance has been updated.
