### ISSUE TITLE
bug fix[image component]: missing white background

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#204]
bug fix[image component]: missing white background

- many of our guidance images were created as transparent pngs and now the white background that used to be a part of the image component is gone... leaving them without backgrounds

- Do we need to re-save all of our images with white backgrounds now or is there going to be a fix for this?

![image](https://user-images.githubusercontent.com/43144260/63958558-352f5680-ca50-11e9-9b98-b913564e9874.png)

**Comment by alisonjoseph** [comment]
Looks like we are only adding the background to .png images currently. I'll update to cover svgs and gifs.
