### ISSUE TITLE
[file uploader] live demo bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#2046]
## Content
- [ ] Header and description of the component should say the following:
![copy.png](https://images.zenhubusercontent.com/5bbba771387e41362246f3dc/323a1b6e-53b9-4f54-99cc-4b441cbaf3cd)
---
## File uploader
- [ ] For the demo of this story, the width of the file should be 288px. Right now its changing dynamically based on the length of the word. People can edit the size of this if they want to on their end.
![size](https://user-images.githubusercontent.com/43969356/101955696-e6192080-3bc3-11eb-8951-3481de978889.png)
- [ ] There is no modifier to change sizes or change the button to primary vs. tertiary.
---
## Drag and drop
The disabled state is not correct.
- [ ] The header and description need to be `disabled-02`.
- [ ] The container needs to be `disabled-02`.
- [ ] Adding a file does not work.

---
## Upload states
- [ ] The invalid modifier does not work.
- [ ] The status options don't work.
- [ ] The text is not the right color in the dark themes. The text inside the file should be color token `text-01`.

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
