### ISSUE TITLE
Remove header above intro text and increase intro text to appropriate size

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2047]
https://carbondesignsystem-git-content-case-studies.carbon-design-system.now.sh/components/overview

Remove header and make intro text H2. @jeanservaas can confirm type spec if I’m wrong. This currently is the only place this type spec exists and I don’t see a reason for it to be unique. First sentence covers it anyways very directly.

**Comment by mjabbink** [comment]
<img width="901" alt="Screen Shot 2020-12-11 at 6 54 35 PM" src="https://user-images.githubusercontent.com/32881239/101967927-5898f900-3be2-11eb-8351-98d8b52d3eb4.png">

**Comment by janchild** [comment]
@mjabbink we have something similar on the Patterns Overview page too but we can definitely change both to fall in line. 
https://www.carbondesignsystem.com/patterns/overview
