### ISSUE TITLE
Bug: Tab component page opens halfway down the page

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#2051]
When you open the Tabs component page, the focus drops to the Live demo, rather than positioning the user at the top of the page. This is consistent behavior across different browsers: Firefox, Chrome, and Safari. 

https://www.carbondesignsystem.com/components/tabs/usage

@alisonjoseph I can fix if you tell me what to do!

**Comment by tw15egan** [comment]
V weird, also noticed this other fun bug on the Form page  when testing to make sure other pages weren't broken 😱 

![form-tabs](https://user-images.githubusercontent.com/11928039/102369156-9fdc0c80-3f89-11eb-8e10-1df997fc6da8.gif)

**Comment by emyarod** [comment]
this should be resolvable once https://github.com/carbon-design-system/carbon/pull/7410 gets released
