### ISSUE TITLE
404 page - links in wrong theme

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2058]
The links are not showing up on the 404 page. Should be using the link-01 color from the Gray10 theme (aka Blue 60)
https://carbondesignsystem.com/404/

**Comment by mjabbink** [comment]
Yikes! 


————
![image (59)](https://user-images.githubusercontent.com/32881239/104442501-c4141480-555a-11eb-8e97-da8a02ec0255.png)



————
<img width="705" alt="Screen Shot 2021-01-13 at 4 47 54 AM" src="https://user-images.githubusercontent.com/32881239/104442458-b3fc3500-555a-11eb-9cdd-5d30709b17f4.png">

**Comment by tw15egan** [comment]
This was fixed over in the theme (https://github.com/carbon-design-system/gatsby-theme-carbon/issues/1069) and will be fixed here once the theme has a new release.

@sstrubberg any idea when the next release is planned for?
