### ISSUE TITLE
button disabled svg color

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#206]
## Detailed description

https://www.carbondesignsystem.com/components/button/style#primary-button and other style tables on this page specify color tokens for icons (svg) but not for the disabled states.

Looking at the examples on https://www.carbondesignsystem.com/components/button/code, the icon color is always the same as the text except for disabled danger button, which seems to be a mistake.

## Additional information

![carbon_button2](https://user-images.githubusercontent.com/9935157/63974075-b77c4280-ca71-11e9-9dfb-d8357e0eaaa8.png)

**Comment by aagonzales** [comment]
The icon seems to working correctly in code at the moment. I will update the docs to include the icon color for disabled states.
