### ISSUE TITLE
Experimental component feedback

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon-website#206]
## Summary
Some feedback on experimental components. 

## Relevant information
1. Links visited state. http://www.carbondesignsystem.com/experimental/link/code
Visited links can provide a good visual history for a user for where in a website they have been. For web applications, having a visited state for links is less common and I question whether it's the right choice for Carbon. For a web application users visit and interact with regularly they can expect the majority of links to eventually become visited thus providing no useful history. Is it the right choice to have a visited state? When should/shouldn't it be used? Is it appropriate for a breadcrumb when often the purpose of that component is to indicate I've already visited the previous pages?

3. Accordion expand transition. http://www.carbondesignsystem.com/components/accordion/code
This feels clunky, the text transitions in with a small slide, but the entire paragraph appears simultaneously making the actual component open in two distinct motions, one when the accordion opens, and then again as it increases in size as the text slides down. It's most noticeable if you watch the bottom divider line for the area you are expanding.  It doesn't feel smooth. 
![2018-10-04 09 35 15](https://user-images.githubusercontent.com/6569324/46481350-d407f000-c7b8-11e8-8740-c7a6db3991bc.gif)

4. UI Shell http://www.carbondesignsystem.com/experimental/ui-shell/code
The expanding left side panel on the UI shell has some unpleasant behaviour - when a user moves their mouse over one of the icons, the shell slides out, but also expands, which in many cases leaves the user hovering over a different area to the one they moved their mouse into. Perhaps a slower vertical transition could make the experience better, although I'm not sure that would be enough. I think the component has some issues. I think perhaps it ought to be a mouse over to initiate the horizontal slide, and then a click on a subtitle causes the vertical expand, rather than doing both in a single motion. 
![2018-10-04 09 39 54](https://user-images.githubusercontent.com/6569324/46481755-af604800-c7b9-11e8-9784-30461c452f7e.gif)

5. Text inputs http://www.carbondesignsystem.com/experimental/text-input/code
The grey background, grey outline, and grey text makes these look disabled to me. I looked at a few other examples with grey background form fields, and in most there is either a darker border, or darker placeholder text to more strongly indicate it is enabled. The fact that all three are using relatively light greys in the carbon component reinforces the disabled look to me. I think making the placeholder text slightly darker, or the border slightly darker could strengthen the impression they are enabled. 
![image](https://user-images.githubusercontent.com/6569324/46482062-65c42d00-c7ba-11e8-92af-d9c48bf3fccc.png)

**Comment by alisonjoseph** [comment]
FYI @jeanservaas @chrisconnors-ibm @aagonzales

**Comment by alisonjoseph** [comment]
Thanks for the feedback! moved this into our component repo and split into separate issues

https://github.com/IBM/carbon-components/issues/1168
https://github.com/IBM/carbon-components/issues/1167
https://github.com/IBM/carbon-components/issues/1166
https://github.com/IBM/carbon-components/issues/1165
