### ISSUE TITLE
[list] live demo bugs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2064]
- [ ] Order list is not showing the numbers in the list for the live demo.
https://carbondesignsystem.com/components/list/usage#live-demo

![image](https://user-images.githubusercontent.com/11670886/103798346-8de50b00-5017-11eb-90c6-462289af0ee9.png)

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
