### ISSUE TITLE
3 of the 4 main links on the Carbon front page are broken

### ISSUE THREAD

**Issue by RoystonS** [carbon-design-system/carbon-website#207]
## Detailed description

3 of the 4 biggest links on the front Carbon page (http://www.carbondesignsystem.com/): 'Getting Started’, ‘Guidelines’, ‘Components' are all broken: they link to an 'illusive jackalope' page.

![image](https://user-images.githubusercontent.com/19773/46488419-80b69180-c7fa-11e8-9886-7cd2a9f45426.png)

The links go to:

* http://www.carbondesignsystem.com/getting-started
* http://www.carbondesignsystem.com/style
* http://www.carbondesignsystem.com/components/code

which are all broken.

The fourth, Resources, which links to http://www.carbondesignsystem.com/resources, is fine.

Browser: Chrome 69.0.3497.100 on macOS Mojave.

**Comment by lovemecomputer** [comment]
thanks @RoystonS we're on it! we have a PR fix up at https://github.com/carbon-design-system/carbon-website/pull/208, just verifying to make sure the fix points in the right place. the fix should be merged soon into the live site!

**Comment by alisonjoseph** [comment]
fixed in #208 will be live when we deploy the site next
