### ISSUE TITLE
[number input] update usage tab docs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#2083]
Update with the new [component docs template](https://www.notion.so/carbondesignsystem/Template-one-type-ff8e66d78c8f49c6896bdcf2e320828b)

---------------

## Overview
- [x] Content

## Formatting
- [x] Anatomy image and content
- [x] Sizing image and content
- [x] Alignment or Placement image and content

## Content
- [x] Main elements content

## Behaviors
- [x] States image and content
- [x] Interactions
- [x] Clickable areas image and content

## Behaviors
- [x] Modifiers (light prop and mobile variant)

**Comment by laurenmrice** [comment]
Ref #3044

**Comment by thyhmdo** [comment]
Doc update issue https://github.com/carbon-design-system/carbon-website/pull/3246
