### ISSUE TITLE
Add telemetry landing page

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#2089]
Take the logic from the [telemetry package](https://github.ibm.com/carbon/ibm/blob/main/packages/telemetry/src/telemetry.js), and create a landing page that we can link to from the CLI and/or logs.

References:

* https://www.gatsbyjs.com/docs/telemetry
* https://nextjs.org/telemetry

**Comment by mattrosno** [comment]
@joshblack this answers the why, when, where. Can you share notes for what exactly is collected?

- influence Carbon's roadmap and prioritize bug fixes
- if code is running on a CI server
- if not PR being tested on a CI server
- only track Git remote related to IBM or Carbon properties
  - github.ibm.com
  - github.com/carbon-design-system
  - github.com/ibm
- can opt-out by setting CARBON_TELEMETRY_DISABLED=1 in your environment

**Comment by joshblack** [comment]
@mattrosno for exact data that is collected right now:

- Git information (origin remote URL, commit hashes)
- Dependency in formation (package used, what version)

URL for reference: https://github.ibm.com/carbon/ibm/blob/main/packages/telemetry/src/collect/install.js#L13-L36

In the future, we will also collect:

- Components used in files (package, component, file name)
- Component props used in files (package, component, file name, prop name, prop value)
  - The prop value is only tracked when it is serializable to a string

URL: https://github.ibm.com/carbon/ibm/blob/main/packages/telemetry/src/collect/components.js#L47-L66
