### ISSUE TITLE
bug[live demo component]: remove field label from above dropdown

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#2109]
## regression[live demo component]: remove field label from above dropdown

I'm assuming this is a regression of some kind. That field label was never in the spec and it wasn't in the approved merge either. We need to remove it please.

![image](https://user-images.githubusercontent.com/43144260/106073485-c4222180-60cf-11eb-909f-7f037890f12e.png)

**Comment by tw15egan** [comment]
This was added in https://github.com/carbon-design-system/carbon-website/pull/1706 and was approved

@dakahn just making sure removing this label won't cause any a11y issues?

**Comment by tw15egan** [comment]
After removing the label it looks like it does cause an issue with the a11y checker: 

<img width="415" alt="Screen Shot 2021-01-28 at 10 13 47 AM" src="https://user-images.githubusercontent.com/11928039/106180707-849c1980-6151-11eb-8ca1-176e7b9b439a.png">

**Comment by dakahn** [comment]
change was added [here](https://github.com/carbon-design-system/carbon-website/pull/1626). Looks it got two devs to sign off and Kodiak (a bot) just auto merged it 🦊
That's my bad. 

Should have caught that pre-emptive ready to merge tag. We can revert this change, but like @tw15egan mentioned we will fail AVT. An alternative to a distinct visual label is appending the components label like this:
![inline-label-github](https://user-images.githubusercontent.com/40970507/106680270-f0341b80-6583-11eb-8e3e-c8e0b1a76bec.png)

@andreancardona is working on this exact solution for an AVT error on the component index page. Can we just use that here?

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
