### ISSUE TITLE
Bug: React Tutorial, Step 2. (Addresses not correct)

### ISSUE THREAD

**Issue by Robertschv** [carbon-design-system/carbon-website#2129]
I am doing the React Tutorial, step 2. Got stuck. The libraries shown for copying into the app.scss file are not correct.

Compiler picture.

![Captura de pantalla de 2021-02-05 17-10-02](https://user-images.githubusercontent.com/62678042/107090666-ebb37100-67d6-11eb-845e-e31797bc044f.png)

> What browser are you working in?
My browser is Firefox.

## Steps to reproduce the issue
1. Do the "step 2".
https://www.carbondesignsystem.com/developing/react-tutorial/step-2

**Comment by Robertschv** [comment]
fix #2130

**Comment by tw15egan** [comment]
Hmm, strange. Those should still be resolving properly without the underscore. Looks like others are able to import them as is and haven't run into any issues:
[Example 1](https://github.com/carbon-design-system/carbon-tutorial/pull/6910/files#diff-b606cac853277b85a5aa49de291ccc05ef14651b08b1fd1a751d7749e6c62a27)

[Example 2](https://github.com/carbon-design-system/carbon-tutorial/pull/6912/files#diff-b606cac853277b85a5aa49de291ccc05ef14651b08b1fd1a751d7749e6c62a27)

[Example 3](https://github.com/carbon-design-system/carbon-tutorial/pull/6898/files#diff-b606cac853277b85a5aa49de291ccc05ef14651b08b1fd1a751d7749e6c62a27)

Can you provide some more info? What OS? What version of node are you on? What version of yarn? Do you have a link to your PR that has these compiler errors?

**Comment by Robertschv** [comment]
Doing more tests, I realized that the .env file was not in the corresponding folder.

Not having the file, I would need the underscore.
Sorry, I will make a mental note to check the hidden files next time.

**Comment by tw15egan** [comment]
No worries! Glad you were able to figure it out 👍
