### ISSUE TITLE
[docs] Button guidance and image refinements

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#2142]
This issue is to capture work needed for the Button component guidance. 

- Add a new section that covers Button relationships and hierarchy
- Conduct an image review to make sure button placement order is correct and that the guidance is strong. with exceptions clearly marked. 

https://ibm-studios.slack.com/archives/GNU2PE9NU/p1613577764000500
https://ibm-studios.slack.com/archives/GNU2PE9NU/p1612973956000600
https://ibm-studios.slack.com/archives/GNU2PE9NU/p1612975378001300

Here are some screenshots of questions that this update should answer. 

![image](https://user-images.githubusercontent.com/44503588/108252948-d7e50480-711e-11eb-9cc7-f3ef1f5780c9.png)

![image](https://user-images.githubusercontent.com/44503588/108252981-e16e6c80-711e-11eb-8549-3c9b04c4c981.png)

![image](https://user-images.githubusercontent.com/44503588/108252888-c4d23480-711e-11eb-8659-ebdb12d13e7a.png)

![image](https://user-images.githubusercontent.com/44503588/108253062-f9de8700-711e-11eb-8989-9a7fc317f411.png)

**Comment by aagonzales** [comment]
Tacking onto this issue:
- Add guidance on two line of text in button and icon alignment.
- See conversation in [slack](https://ibm-studios.slack.com/archives/G019HG7R2LQ/p1615318227002200).

This is the as-is alignment in code.
![image](https://user-images.githubusercontent.com/11670886/110529688-8f01e980-80e7-11eb-86d1-a6af0ffe0caa.png)
