### ISSUE TITLE
Product design launch page for IDL site

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#215]
Create a launch page in https://w3.ibm.com/design/language that introduces carbon/product design system and links to the carbon site.

**Comment by designertyler** [comment]
![product_launch_page_20181004_tt](https://user-images.githubusercontent.com/19270502/46547065-6af3ab80-c890-11e8-91a1-60a3850308bf.png)

**Comment by designertyler** [comment]
Updates based on feedback and layout and spacing overlay.

![product_launch_page_20181008_layout_tt](https://user-images.githubusercontent.com/19270502/46632616-e2d00900-cb10-11e8-8f85-87bb38a4d532.png)
![product_launch_page_20181008_tt](https://user-images.githubusercontent.com/19270502/46632617-e2d00900-cb10-11e8-9220-f206684a1a9e.png)

**Comment by designertyler** [comment]
![product_launch_page_20181009_layout_tt](https://user-images.githubusercontent.com/19270502/46695283-c5647300-cbd4-11e8-94a4-0a2d215b59b6.png)
![product_launch_page_20181009_tt](https://user-images.githubusercontent.com/19270502/46695284-c5647300-cbd4-11e8-9ff5-1d210870052b.png)

**Comment by alisonjoseph** [comment]
Can this be closed? Should it be tracked in their repo? @designertyler

**Comment by designertyler** [comment]
@alisonjoseph yes, this is tracked in their repo. Closing
