### ISSUE TITLE
Remove “Design only” tag from Tree map illustration + fix link + add demo to advance page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2155]
https://www.carbondesignsystem.com/data-visualization/chart-types#part-to-whole

- [ ] Remove “Design only” tag — link directly to Treemap —> https://www.carbondesignsystem.com/data-visualization/advanced-charts/#tree-maps

<img width="397" alt="Screen Shot 2021-02-23 at 3 20 52 PM" src="https://user-images.githubusercontent.com/32881239/108909980-da49d180-75ea-11eb-98ee-4f29b95a8088.png">

————

- [ ]  Add tree map demo to Advance chart page

**Comment by mjabbink** [comment]
FYI @jeanservaas

**Comment by mjabbink** [comment]
@theiliad @joshblack Can we address the removal of the “design only” tag. The live demo and code is now present/available.

**Comment by theiliad** [comment]
Hey, this should've been closed with my PR #2223

**Comment by mjabbink** [comment]
I see it removed now. I must have needed to clear cache. 👍
