### ISSUE TITLE
Looking for the best solution for large labels for tabs

### ISSUE THREAD

**Issue by Cicko** [carbon-design-system/carbon-website#2156]
## Summary
In our project, we have a quite large tabs labels and we would like, maybe, to make the tabs a bit wider instead of hiding the part of the label.

## Relevant information
As you can see in the following screenshot, if we add a very long label, part of it is hidden:
![Captura de pantalla 2021-02-24 a las 11 44 25](https://user-images.githubusercontent.com/16807198/108989295-b7c0c280-7695-11eb-9913-a75cef57d023.png)

**Comment by tw15egan** [comment]
You can override the default width of `10rem` on `.bx--tabs--scrollable .bx--tabs--scrollable__nav-link` if your Tab titles need more room

**Comment by Cicko** [comment]
@tw15egan Thank you for the answer :) Actually that was my initial solution but I thought there could be maybe, a better one.

**Comment by tw15egan** [comment]
We needed to set a default width to enable truncation, but definitely able to be overridden. Glad that helped! Going to close this but feel free to reach out if you have any other questions 👍🏻
