### ISSUE TITLE
Changes to Steering committee page

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2164]
https://www.carbondesignsystem.com/all-about-carbon/partners#the-peopleobject-object

- [ ]  Replace Wonil Suh with:

Linda Carotenuto
Offering Manager, Carbon for ibm.com,
IBM Cloud and Cognitive Software

or

Linda Carotenuto
OM, Carbon for ibm.com
IBM Cloud and Cognitive Software

- [ ]  Make Tricia Garrett co-chair:
Tricia Garrett
Design Principal, Master Inventor, Watson Health; Co-chair Steering committee

- [ ]  Remove Robin Cannon

FYI: @jeanservaas @alisonjoseph @janchild

**Comment by janchild** [comment]
Complete
