### ISSUE TITLE
Is there an example for Data Table in carbon component react with pagination , I did not found in the storybook 

### ISSUE THREAD

**Issue by Deepaks77** [carbon-design-system/carbon-website#2169]
I am not able to find any working example for  DataTable with pagination of carbon-component-react, at official their storybook https://react.carbondesignsystem.com/?path=/story/getting-started-welcome--welcome,
can anyone help me with it, please

**Comment by laurenmrice** [comment]
We do not have a specific react story for a Data table with pagination but please reference the above example.
