### ISSUE TITLE
Icons: Form input invalid icon needs to be updated with latest C&C icon adoptions

### ISSUE THREAD

**Issue by anibapat** [carbon-design-system/carbon-website#2170]
## Summary
All form input invalid icon need to have an update per the latest C&C icon guidelines. 

## Relevant information
From latest storybook:
<img width="1477" alt="Screen Shot 2021-03-09 at 9 08 10 AM" src="https://user-images.githubusercontent.com/14098997/110509581-1c791580-80b7-11eb-8fda-677d9828d164.png">

Guidlines:
<img width="628" alt="Screen Shot 2021-03-04 at 6 57 57 PM" src="https://user-images.githubusercontent.com/14098997/110509649-2e5ab880-80b7-11eb-8961-a778306d3671.png">

The following components invalid state icons need to be updated - 
1. NumberInput
2. TextInput

3. Any other input filed which has the old invalid state icon.

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by mjabbink** [comment]
☝️

@jeanservaas

**Comment by andrea-gm** [comment]
@Levinson1 is C&CS expecting Carbon to adopt our status icons in their components, like form field validation, error notifications, etc?
