### ISSUE TITLE
fix[live demo]:single and multi line code snippet not displaying correctly

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#2171]
## fix[live demo]:single and multi line code snippet not displaying correctly

- Looks like multiline code snippet content is trying to display in the single line code snippet

- Multiline code snippet is incorrectly centered in the middle of the component instead of being left aligned.

![image](https://user-images.githubusercontent.com/43144260/110525960-3c263300-80e3-11eb-8cc3-c46da809e62a.png)

![image](https://user-images.githubusercontent.com/43144260/110526168-74c60c80-80e3-11eb-91ca-0ddbfcf15edc.png)

## Correct behavior in Storybook

single line

![image](https://user-images.githubusercontent.com/43144260/110526580-f5850880-80e3-11eb-9125-623f3ff3aa61.png)

multiline

![image](https://user-images.githubusercontent.com/43144260/110526622-033a8e00-80e4-11eb-8f00-7d691cd6a56e.png)

**Comment by tw15egan** [comment]
Should be fixed via https://github.com/carbon-design-system/carbon-website/pull/2139 @jeanservaas just needs a visual review
