### ISSUE TITLE
Audit training videos for patterns and best practices  

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#2174]
Do an audit of existing training in the IBM ecosystem and external design system sites to formulate a pattern that can be used for our tutorials. 

Look at:
- [x] Carbon for IBM.com team learning series: https://ec.yourlearning.ibm.com/w3/series/10148614?layout=grid
- [x] Material
- [x] Other research TBD

**Comment by johnbister** [comment]
Closing because we were forced to pivot due to the v11 push and other priorities.
