### ISSUE TITLE
Remove chart demos on “Basic charts” page/ Add new chart demos and mini cards under each remaining demo

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2175]
## Basic charts page updates

https://www.carbondesignsystem.com/data-visualization/basic-charts

- [x]  Add Lollipop to anchor link list
- [x]  Add Lollipop demo (one variant only)
- [x]  Add Bullet to anchor link list
- [x]  Add Bullet demo (one variant only)
- [x]  Add Boxplot to anchor link list
- [x]  Add Boxplot demo (one variant only)

**Anchor link list in alphabetical order:**
Area
Bar (vertical)
Bar (horizontal)
**Boxplot**
Bubble
**Bullet**
Combo
Donut
Gauge
Line
**Lollipop**
Meter
Pie
Radar
Scatter
Step

- [x]  Remove all additional demo variants so only 1 demo per chart type shows up on the page (Anchor links equal one demo)

- [x] Add Storybook icons to standard resource card and mini cards (attached below)*

- [x] Add number of variants in the mini card*

* https://gatsby-theme-carbon.now.sh/components/MiniCard

## Chart types page updates

- [x] add illustrations for new charts to chart types page (Jeannie give svgs to Eliad)

**Comment by mjabbink** [comment]
FYI @jeanservaas

**Comment by mjabbink** [comment]
Current not in alphabetical order:
<img width="622" alt="Screen Shot 2021-03-13 at 3 48 31 PM" src="https://user-images.githubusercontent.com/32881239/111050677-af95b080-8413-11eb-94d4-b9e2b0782b8d.png">

**Comment by mjabbink** [comment]
@theiliad @jeanservaas Maybe under each demo there can be a a mini card to link directly into that chart type in the demo site? that way you don’t need to go back to top of page to click the one resource card. 

https://gatsby-theme-carbon.now.sh/components/MiniCard

**Comment by mjabbink** [comment]
New approach:

<img width="853" alt="Screen Shot 2021-03-31 at 4 17 46 PM" src="https://user-images.githubusercontent.com/32881239/113212720-c70ad100-923c-11eb-801c-4f128c98b633.png">

**Comment by mjabbink** [comment]
- [ ] Update icon in resource card and Mini resource card to use “Storybook” icon.

<img width="824" alt="Screen Shot 2021-03-31 at 4 21 15 PM" src="https://user-images.githubusercontent.com/32881239/113213013-2963d180-923d-11eb-9c9c-f74be7cfbc63.png">

<img width="829" alt="Screen Shot 2021-03-31 at 4 21 25 PM" src="https://user-images.githubusercontent.com/32881239/113213041-3385d000-923d-11eb-932e-2cef6fa30994.png">

**Comment by mjabbink** [comment]
[storybook_icon.svg.zip](https://github.com/carbon-design-system/carbon-website/files/6239617/storybook_icon.svg.zip)

**Comment by mjabbink** [comment]
![Uploading Basic_charts_no_grid.png…]()

**Comment by theiliad** [comment]
pt. 1 of this work is finished

Just merged a PR in Carbon Charts which re-organizes the demos to follow this format https://github.com/carbon-design-system/carbon-charts/pull/992

@mjabbink Also I think we need to rename the cards to say `20 more demos` rather than `20 variants` since not all the other demos are variants of the chart

**Comment by mjabbink** [comment]
@theiliad Go for “20 more demos” — makes sense to me.

**Comment by mjabbink** [comment]
- [ ] Add Circle pack demo  to Complex charts page. 

- [ ] Add thumbnail/mini to the Chart types page @jeanservaas to supply image

**Comment by theiliad** [comment]
> * [ ]  Add Circle pack demo  to Complex charts page.
> * [ ]  Add thumbnail/mini to the Chart types page @jeanservaas to supply image

already being addressed here #2300

**Comment by mjabbink** [comment]
@eliad correct me if I’m wrong but I think all of these issues were addressed.
