### ISSUE TITLE
Link to color palette not working

### ISSUE THREAD

**Issue by rutgerhofste** [carbon-design-system/carbon-website#2184]
On this page:
https://www.carbondesignsystem.com/guidelines/color/overview#resources

the URL is broken:
https://github.com/carbon-design-system/carbon/raw/master/packages/colors/artifacts/IBM_Colors.zip

**Comment by emyarod** [comment]
this should be resolved once https://github.com/carbon-design-system/carbon-website/pull/2166 goes live
