### ISSUE TITLE
Create Support page for website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#219]
We need a section on the website that describes how we support the libraries.  
_A lot of this content already lives in our FAQ section, just need to surface it better._ 

Needs to set expectations for teams that need new features and bugs fixed that some of it falls on them to help contribute back to the library. 

Needs to have links to our slack channels along with correct etiquette that goes along with our channels. 

Needs to have links to twitter, email etc also

Possibly **Getting Started > Support** or **About Carbon > Support**

fyi @kuehndaniel

**Comment by joshblack** [comment]
Going to brain dump some questions that I feel like we should be able to answer through this document (or section) on the site:

- Support
  - "Oh no! I found something wrong with the system, what should I do next?"
    - First, make sure the problem is reproducible (should go into more detail)
    - Once confirmed, head on over to the project and create an issue with the appropriate template (include list showing what each one is used for)
    - After the issue is submitted, you can expect a response from something within **2 days** (this needs to be decided by the team). This response should be one of the following:
      - Need more info, can't reproduce the problem
      - Won't fix, this isn't something we intend to support
      - Confirmed, will add to our roadmap (Carbon team will fix)
      - Confirmed, will accept PRs (need external member to fix)
      - Need to include design to verify this behavior is supported
  - "I can't get something to work, where should I go?"
    - Talk about our Slack communication preferences
      - Mention the channels that we offer support in
      - We try to get to questions as we can throughout our day
      - Slack is **not** meant for bug reports, we should use GitHub issues for those
  - "I think this component isn't accessible", "This component isn't passing DAP, what should I do?"
    - Talk through steps for confirming it is not accessible (needs checklist)
    - Provide guidance on creating a GitHub issue with steps to reproduce for us
    - Communicate that core team fixes a11y issues
  - "Why doesn't this component support feature X, Y, Z?"
  - "How do I do X, Y, Z with a component?"
  - "How do I know what features a component supports?"
- On bug severity and priority
  - We should talk about how we determine bug severity and priority. These factors should funnel into how we prioritize bugs in our work.
  - We should have an easy way to show 
- Questions
  - How can we show what we're working on at a given moment?

**Comment by alisonjoseph** [comment]
https://www.carbondesignsystem.com/help/support
