### ISSUE TITLE
feature[patterns]:modified table for status indicator pattern

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#2199]
## feature[pattern]:modified table for status indicator pattern

We are enhancing and migrating the Status Indicator pattern from the Carbon for Cloud & Cognitive PAL over to the Carbon website. A table like this already exists on that PAL, I've just modified it slightly.

https://pages.github.ibm.com/cdai-design/pal/patterns/status-icons

### Modifications of the C&CC table

- We've removed one of the columns (the status column)
- We added the outlined versions of the status icons
- We increased the width of the g100 strip in the table so that it's on the responsive column grid at all breakpoints
- We are specifying that the rule, when it is on the g100 background pull in the $interactive-02 token (g80), not the $ui-03 token (g20); i.e. the rule will be g20 on the white background and g80 on the dark background, as if the dark area is a dark theme zone.

### Specs and Behavior
The vertical spacing, type hierarchy and horizontal scrolling behavior will operate just like a normal Gatsby table, except this one has a white background. At mobile, the table will scroll horizontally, just like the C&CC table does. 

At the table and mobile breakpoints, the dark logos have been removed so that the table can still fit at 672px and will be more light weight in the mobile experience.

### Full layout (@vpicone the new content is in the file)

![Status icons_table_content](https://user-images.githubusercontent.com/43144260/113765142-8221e700-96e1-11eb-8b51-7119f9ae856f.png)

### 1312

![image](https://user-images.githubusercontent.com/43144260/113063322-bd209980-917a-11eb-8d8e-2374b44ed3ad.png)

<br>

![image](https://user-images.githubusercontent.com/43144260/113063343-c6aa0180-917a-11eb-975c-30a655dfc4df.png)

<br>

### 1056

![image](https://user-images.githubusercontent.com/43144260/113063411-e2150c80-917a-11eb-9ae9-9308dfc47b64.png)

<br>

![image](https://user-images.githubusercontent.com/43144260/113063434-eb05de00-917a-11eb-945f-1234101f96c1.png)

<br>

 ### Tablet

![image](https://user-images.githubusercontent.com/43144260/113063538-1688c880-917b-11eb-9e05-e282f6f70a43.png)

<br>

![image](https://user-images.githubusercontent.com/43144260/113063559-21dbf400-917b-11eb-8fb6-08a1749dd0d1.png)

### Mobile

<br>

![image](https://user-images.githubusercontent.com/43144260/113063623-3e782c00-917b-11eb-9c8b-bf3fa3168ac8.png)

<br>

![image](https://user-images.githubusercontent.com/43144260/113063642-4637d080-917b-11eb-9aab-558a72d0389e.png)

## Sketch file (new)
[032421_CarbonPatterns_IconTable.sketch 4.zip](https://github.com/carbon-design-system/carbon-website/files/6267009/032421_CarbonPatterns_IconTable.sketch.4.zip)

@thyhmdo For future ref this is where these enhancements go and how they get spec'd out more or less.

**Comment by vpicone** [comment]
@jeanservaas do we have content to replace the lorem ipsum yet?

**Comment by aagonzales** [comment]
@vpicone I believe this issue is just about the table not the page content. They have page with additional content on it that they will be adding in a PR

**Comment by jeanservaas** [comment]
@vince I am working on the copy right now, is it needed to build the table? Jan will also have to review it. Or will it be easily editable?

**Comment by jeanservaas** [comment]
@vpicone There has been an addition to this page that I hope won't be too much extra effort. We basically want to use the same table for status symbols that Conrad Ennis is going to create as we're using for status icons.

![image](https://user-images.githubusercontent.com/43144260/116267031-a6ea0700-a741-11eb-99c9-e171b25829ee.png)

## specs

The difference is that the symbol column width only takes up 1 column, vs. the two column width of the status icon table above.

![image](https://user-images.githubusercontent.com/43144260/116268489-fa108980-a742-11eb-90a1-214b8d4a4888.png)

**Comment by jeanservaas** [comment]
Related issue:
https://github.com/carbon-design-system/carbon/pull/8546

From Conrad:

[status glyphs.zip](https://github.com/carbon-design-system/carbon-website/files/6415405/status.glyphs.zip)
