### ISSUE TITLE
Create Docs: UI Shell

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#22]
Write and integrate guidelines for the new UI Shell.

- [x] Determine placement in Carbon IA
- [x] Write draft 1
- [x] Figure out supporting images
- [x] Publish page to staging server
- [x] Gather feedback from stakeholders (Anna, Chris, Tyler)
- [x] Incorporate feedback from internal team, including revised graphics
- [x] Upload new page to Carbon site

**Comment by shinytoyrobots** [comment]
Previous progress in https://github.ibm.com/carbon/issues/issues/879 (internal).

From @alisonjoseph:

New `ui-shell` branch created for docs updates. 

https://github.com/IBM/design-system-website/tree/ui-shell/src/content/ui-shell

http://design-system-ui-shell.stage1.mybluemix.net/ui-shell

_Ignore the "What's New" title_ 🤔

**Comment by shinytoyrobots** [comment]
NB: Need to have documentation / guidance for https://github.com/IBM/carbon-components/issues/1096 (but that issue does not need to be built).

**Comment by claycrenshaw** [comment]
@shinytoyrobots  Latest draft can be found here: http://design-system-ui-shell.stage1.mybluemix.net/ui-shell

Yes, the graphics are a requirement. They are currently being finished up, hence why this issue is blocked. Not ready for a PR until the new images are integrated and a final editorial pass is complete.

**Comment by claycrenshaw** [comment]
Page is up on staging: http://staging.carbondesignsystem.com/experimental/shell/usage

**Comment by alisonjoseph** [comment]
closing for now. we can track any new changes in a new issue if needed.
