### ISSUE TITLE
Add correct pointer to storyboard for v9

### ISSUE THREAD

**Issue by alon24** [carbon-design-system/carbon-website#221]
Carbon is currenly at version 10.

But our team is still on V9, and so we look at [Carbon design V9](https://v9.carbondesignsystem.com/components) for design issues.

Currently the links inside that link for react point to the V10 (carbon react v7) becuase they lead to latest storyboard.

I think we need to have the link sin V9 point to the corect ([V6 Carbon React storyboard]( http://v6-react.carbondesignsystem.com))

This would be MOST helpful for us

**Comment by aagonzales** [comment]
Duplicate: https://github.com/carbon-design-system/carbon-website/issues/418
