### ISSUE TITLE
[treeview] style tab content

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#2211]
- We need to have a tab on the website for `Style` content for the Tree view component. 
- Update: We are doing single selection only for GA (do not include multi-select, this will be added later)

**Comment by laurenmrice** [comment]
Notion document in progress: https://www.notion.so/carbondesignsystem/Style-6ffd3ec0a2a44c34aee3b876ca118ea5

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-website/2211?planning-poker) with ZenHub @laurenmrice @thyhmdo
