### ISSUE TITLE
Data table spacing in expandable and expandable+selected rows don't match website guidelines 

### ISSUE THREAD

**Issue by JohannaSuarezKoval** [carbon-design-system/carbon-website#2222]
## Summary

Spacing between chevron and text or checkbox in expandable rows and expandable+selected rows is not the same in the storybook as shown in the Carbon Website guidelines. The sketch kit follows the guidelines on the website. 

## Relevant information
Storybook:
There is 16px spacing to the left of the checkbox and to the left of the text that doesn't match the guidelines neither the sketch kit
<img width="1668" alt="Screen Shot 2021-04-12 at 11 10 44 AM" src="https://user-images.githubusercontent.com/5809654/114418087-2becf200-9b80-11eb-9cf2-2aa53a294303.png">

<img width="1669" alt="Screen Shot 2021-04-12 at 11 10 16 AM" src="https://user-images.githubusercontent.com/5809654/114418107-2f807900-9b80-11eb-9dfc-97f8c2c5f7b0.png">

Website:
<img width="1191" alt="Screen Shot 2021-04-12 at 11 08 47 AM" src="https://user-images.githubusercontent.com/5809654/114417322-7e79de80-9b7f-11eb-9225-dbfc3ec0a7a6.png">

**Comment by laurenmrice** [comment]
The kit is correct. There is an inconsistency in the chevron+checkbox pairing example (It may not have been accounted for in this related [PR](https://github.com/carbon-design-system/carbon/pull/8080)

There should be 16px spacing to the left and to the right of the chevron icon and checkbox icon when present. The labels in the first cell should fall 16px to the right of the icon that comes before it.

![Artboard 1 30 30 PM](https://user-images.githubusercontent.com/43969356/114462640-f27cac80-9ba8-11eb-988c-942a37767b4c.png)

**Comment by tw15egan** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon/issues/8472 so we can track dev effort
