### ISSUE TITLE
Getting Started / Developers page is 404

### ISSUE THREAD

**Issue by jamesstaylor76** [carbon-design-system/carbon-website#223]
## Detailed description

When I click on the 'Developer' nav item in 'Getting Started' section, I get a 404 error page.
I am using Chrome (latest version)

**Comment by alisonjoseph** [comment]
Likely a caching issue, I believe the nav item name was changed from "developer" to "developers" recently. Sorry about that! 

https://www.carbondesignsystem.com/getting-started/developers/vanilla
