### ISSUE TITLE
Color page. Update with larger mobile swatches

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#224]
@jeanservaas 

Larger swatches more mobile friendly 

Current too small: see color page in IDL mobile

![696DCAFB-3796-47DE-9EE7-41A3E06A62B8](https://user-images.githubusercontent.com/32881239/64132862-b5cbbb00-cda0-11e9-873c-a10c01c757ef.jpeg)

**Comment by jeanservaas** [comment]
We had a pretty comprehensive issue for this in the Carbon website repo back in the day, circa like April... but with the restructuring, it's all gone.

It seems like something that should be addressed in the Gatsby theme -- adaptive images for mobile. Also, not sure how @alisonjoseph handled this situation for IDL as they moved it over to Gatsby... it's the same problem in Carbon, so if it's been solved there we should adopt the solution. 

<img width="732" alt="image" src="https://user-images.githubusercontent.com/43144260/64194105-f0d2fa80-ce43-11e9-8e46-efc30b3b81b4.png">

**Comment by alisonjoseph** [comment]
@shixiedesign we have a component now that easily handles this. 

```
<ArtDirection>
![Mobile image](./mobile.png)
![Tablet image](./tablet.png)
![Desktop image](./desktop.png)
</ArtDirection>
```

or if you just want mobile/desktop
```
<ArtDirection>
![Mobile image](./mobile.png)
![Desktop image](./desktop.png)
</ArtDirection>
```

https://gatsby-theme-carbon.now.sh/components/ArtDirection

**Comment by mjabbink** [comment]
remove duplicate "to" in second sentence



<img width="743" alt="Screen Shot 2019-09-03 at 2 21 19 PM" src="https://user-images.githubusercontent.com/32881239/64198483-4d3f1580-ce56-11e9-8ac8-0d8cc77dffbf.png">

**Comment by mjabbink** [comment]
and yes, there are several places across IDL and Carbon that need some mobile friendly (second) images that will be better for user.
