### ISSUE TITLE
line-height values in productive and expressive examples

### ISSUE THREAD

**Issue by aweell** [carbon-design-system/carbon-website#2249]
## Detailed description

The line-height values provided in productive and expressive examples are set in em units.

Taking `productive-heading-07` line-height as an example:

Size: 54px / 3.375rem
Line-height: 64px / 4em

In order to achieve a 64px fixed value using em units, the line height should be 1.185185185...

64/54= 1.185185185...

Using rem units instead with a root font-size of 16px:

16px * 4 = 64px

## Additional information

<img width="1491" alt="Screen Shot 2021-04-24 at 10 54 25" src="https://user-images.githubusercontent.com/44420072/115953384-7315a400-a4eb-11eb-97a3-9b5473726e26.png">

_productive-heading-07 `line-height` using rem units_

<img width="1360" alt="Screen Shot 2021-04-24 at 10 53 13" src="https://user-images.githubusercontent.com/44420072/115953358-46618c80-a4eb-11eb-9238-c4c8d0348068.png">

_productive-heading-07 `line-height` using em units_

**Comment by speziCola** [comment]
I almost opened the same issue. It's especially unfortunate if you want to take it as an example of how to set up fonts where units are used for the line-height to achieve a X-point-grid-vertical-rhythm.
