### ISSUE TITLE
The website doesn't load on Mac Chrome

### ISSUE THREAD

**Issue by anyav77** [carbon-design-system/carbon-website#2251]
## Detailed description

The website loads fine the first time, however, when I come back, it returns a black screen.  If I open it in an incognito window, it loads fine.
I tried refreshing the page, clearing cache, and doing a hard refresh, but it still doesn't solve the issue.  I'm running the latest Google Chrome (Version 90.0.4430.85 (Official Build) (x86_64))  on Mac 10.12.6.

## Steps to reproduce the issue

1. Open the website on Mac using Google chrome
2. Restart Mac.  Google Chrome will relaunch with the previous page(s) open.

## Additional information

- Screenshots of revisited site
![Screen Shot 2021-04-24 at 11 30 23 AM](https://user-images.githubusercontent.com/1045307/116009236-328e5700-a5cd-11eb-99f6-3e5ae3b40935.png)

- Screenshot of the website opened in an incognito window
![Screen Shot 2021-04-24 at 11 33 04 AM](https://user-images.githubusercontent.com/1045307/116009258-594c8d80-a5cd-11eb-9ba9-6d8d50c9f30f.png)

**Comment by aagonzales** [comment]
@anyav77 Try a hard refresh that normally does the trick. 

> Hold down Shift and click the Reload button. Or Hold down Command, Shift and click the 'R' key

**Comment by anyav77** [comment]
This solution works for the development environment.  However, I would like to use Carbon Design Theme for the live website, and the target audience is not technical pros.  So, I can't rely on this for a live site.
Do you have a better solution?  
Is it a Javascript cookie issue?  Are you planning to fix this bug?
