### ISSUE TITLE
v11: update style tabs with new tokens

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2257]
# Primary task
Update all [component style tab](https://v11.carbondesignsystem.com/components/accordion/usage/) pages in the **v11 branch** to have the new token names. [See Notion doc for full list](https://www.notion.so/carbondesignsystem/Final-List-of-new-tokens-fc5985c7331341baa6546064399d36da). Some component specs with v11 tokens are available [in this other issue](https://github.com/carbon-design-system/carbon/issues/8187) or just reference the notion doc for old -> new tokens migration.

![image](https://user-images.githubusercontent.com/11670886/118180453-27745d00-b3fc-11eb-881d-9110bcfa0bf1.png)

Updates will be made in markdown in the `## Color` section of the style tab. 
![image](https://user-images.githubusercontent.com/11670886/118517751-1cbc0f80-b6fd-11eb-953d-447638b4ac2b.png)

**Optional image updates**
Also is if any one feels inclined to update in out date style tabs in there while you're at it you get super brownie points with me! (not required though but please at least make a note of in correct images)

**Thy**
- [x] Accordion
- [x] Breadcrumb
- [x] Button
- [x] Checkbox
- [x] Code snippet
- [x] Content switcher

**Lauren**
- [x] [Date table](https://github.com/carbon-design-system/carbon-website/pull/2313) 
- [x] [Date picker](https://github.com/carbon-design-system/carbon-website/pull/2330) 
- [x] [Dropdown](https://github.com/carbon-design-system/carbon-website/pull/2333)
- [x] [File uploader](https://github.com/carbon-design-system/carbon-website/pull/2354)
- [x] [Link](https://github.com/carbon-design-system/carbon-website/pull/2357)
- [x] [List](https://github.com/carbon-design-system/carbon-website/pull/2358#pullrequestreview-670236743)

**John**
- [x] [Loading](https://github.com/carbon-design-system/carbon-website/pull/2315)
- [x] [Modal](https://github.com/carbon-design-system/carbon-website/pull/2316)
- [x] [Number input](https://github.com/carbon-design-system/carbon-website/pull/2317)
- [x] [Overflow menu](https://github.com/carbon-design-system/carbon-website/pull/2320)
- [x] [Pagination](https://github.com/carbon-design-system/carbon-website/pull/2328)
- [x] [Progress indicator](https://github.com/carbon-design-system/carbon-website/pull/2329)

**Tracey**
- [x] [Radio button](https://github.com/carbon-design-system/carbon-website/pull/2325)
- [x] [Search](https://github.com/carbon-design-system/carbon-website/pull/2326)
- [x] [Select](https://github.com/carbon-design-system/carbon-website/pull/2341)
- [x] [Slider](https://github.com/carbon-design-system/carbon-website/pull/2327)
- [x] [Structured list](https://github.com/carbon-design-system/carbon-website/pull/2339)
- [x] [Tabs](https://github.com/carbon-design-system/carbon-website/pull/2376)

**Anna**
- [x] [Notifications](https://github.com/carbon-design-system/carbon-website/pull/2345)
- [x] [Tag](https://github.com/carbon-design-system/carbon-website/pull/2346)
- [x] [Text input](https://github.com/carbon-design-system/carbon-website/pull/2348)
- [x] [Tile](https://github.com/carbon-design-system/carbon-website/pull/2350)
- [x] [Toggle](https://github.com/carbon-design-system/carbon-website/pull/2353)
- [x] [Tooltip](https://github.com/carbon-design-system/carbon-website/pull/2363)
- [x] [UI Shell](https://github.com/carbon-design-system/carbon-website/pull/2388)

**Comment by aagonzales** [comment]
Updates can either be made through your local build or you can makes these updates through the GitHub web app by going to "Edit this page on Github" link at the bottom of each page.

1. Go to the page and tab you want to edit. Scroll to the bottom and click on the  "Edit this page on Github" link.
![image](https://user-images.githubusercontent.com/11670886/118527081-87257d80-b706-11eb-9686-bc6d0d23d4fb.png)

2. Edit markdown file with update content
![image](https://user-images.githubusercontent.com/11670886/118524416-c0102300-b703-11eb-834b-e6e03b421fb9.png)

3. After you make all your edits scroll to the bottom of the page and select "create new branch" then hit the commit changes button
![image](https://user-images.githubusercontent.com/11670886/118527336-cd7adc80-b706-11eb-87f4-8eae878eb65c.png)

4. Change base from `main` to `v11` then create your pull request. 
![image](https://user-images.githubusercontent.com/11670886/118527658-1d59a380-b707-11eb-96aa-8a9dc6200fe7.png)

**Comment by thyhmdo** [comment]
Adding Jan's example here to make it easier for reviewers when creating PRs for v11

Title
docs: v11 color token updates for accordion component

Description
This PR updates the color tokens on the Style tab for the accordion component.

**Comment by laurenmrice** [comment]
**Embedded components**
Link out to the guidance for that specific component above the table in the written description. Ref: [Modal](https://www.carbondesignsystem.com/components/modal/style#color)

**Specifying  an inline theme**
Use `$[token]: inline theme` when inline theming is required for a part of the component by default.
