### ISSUE TITLE
v11: update size prop docs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2260]
## Task
Refer to the [audit](https://github.com/carbon-design-system/carbon/issues/8815) to know where sizes are being used. Update any tables or content with the new [size prop names](https://github.com/carbon-design-system/carbon/issues/8370). Follow the "edit this page on github" path that we used for [updating color token](https://github.com/carbon-design-system/carbon-website/issues/2257#issuecomment-842483611). Beware, this task is a lot more hands on with content restructuring and not just about updating tokens. When the update has been made check the "Updated in V11" box in the audit notion doc.

- Update size prop names across existing website guidance. 
- Add size section to components style tabs that have size variants in [code](https://react.carbondesignsystem.com/?path=/story/getting-started-welcome--welcome) but are missing in docs.
- Note any images that have incorrect size names in them

## New size prop names

To migrate name correctly reference the size of the container height to match the name. 

| Name | Size |
|-----|-------|
| `xs` | 24 |
| `sm` | 32 |
| `md` | 40 |
| `lg` | 48 |
| `xl` | 64 |
| `2xl` | 80 |

**Comment by laurenmrice** [comment]
**Style tab**
[Size table audit ](https://www.notion.so/carbondesignsystem/Size-b0dc8c7ed2c94b2f80f1b3a624067ba5)

**Comment by aagonzales** [comment]
# Style tabs

- In the Component / Style page under the Structure section, sizes should be it its own separate `H3` table by themselves.
- Tables should be organized as follows: `| Element | Size | Height (px / rem) |`


**To-do's:**
- Replace `Class` column header with `Element`
- In a row, replace existing `classname` in code snippet to be plain element name, for example `.bx--accordion__heading` should now just be "Heading".
- Remove any `Property` columns
- Remove any `Spacing token` column
