### ISSUE TITLE
[Patterns] Add Card pattern to the Carbon site

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#2273]
## [Patterns] Add Card pattern to the Carbon site

- [x] Audit existing Card pattern and component usage guidance from the PAL community

### AI Apps 

- https://pages.github.ibm.com/ai-applications/design/patterns/dashboard-overview/overview
- https://pages.github.ibm.com/ai-applications/design/components/card/usage

### C&C

- https://pages.github.ibm.com/cdai-design/pal/components/card/overview

### Carbon for IBM.com

- https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/patterns/cards
- https://www.ibm.com/standards/web/carbon-for-ibm-dotcom/components/card
![image](https://user-images.githubusercontent.com/43144260/117020938-80394c80-acbc-11eb-8f50-8c9ce4f2620b.png)

### Gatsby developer resource

- https://gatsby-theme-carbon.vercel.app/components/ArticleCard
- https://gatsby-theme-carbon.vercel.app/components/ImageCard
- https://gatsby-theme-carbon.vercel.app/components/ResourceCard
- https://gatsby-theme-carbon.vercel.app/components/MiniCard

### KPI card

- @dianatran18 will be packaging up some things and sending them over too

- [ ] Consolidate existing usage guidance into the multiple variant pattern template and schedule a review to approve the structure

- [ ] Decide what subset of information would belong in the Tile component usage template and update that content as well (schedule a review to approve the structure)

- [ ] Update certain Gatsby card components (and the instances on the Carbon website) to align with .com guidance (so they don't have to change)

When there is not text, an icon or a logo in the left corner of the card, the launch or arrow icon should appear in the left corner, aligned with the text. 
![image](https://user-images.githubusercontent.com/43144260/117025012-2175d200-acc0-11eb-85dd-8c00271e13e4.png)

- [ ] Determine whether Cards is something we should make a mini kit for... like text toolbar. (building this resource would be a different workstream)

**Comment by kingtraceyj** [comment]
from cloud:
https://pages.github.ibm.com/ibmcloud/pal/components/card/usage
https://pages.github.ibm.com/ibmcloud/pal/layouts/card-layout/code

**Comment by kingtraceyj** [comment]
watson health tiles:
https://pages.github.ibm.com/Watson-Health/components/tile/overview.html
