### ISSUE TITLE
Number Input Documentation Conflict

### ISSUE THREAD

**Issue by NolanCanady** [carbon-design-system/carbon-website#2274]
## Summary
In the documentation for the Number Input field component, the current component in code does not reflect the screen shot provided. This causes confusion for some developers and designers, implying that there is a toggle between the versions.

## Relevant information
https://www.carbondesignsystem.com/components/number-input/usage/

![image](https://user-images.githubusercontent.com/13824734/117026822-b7f6c300-acc1-11eb-8b3a-99a5918f1b54.png)

![image](https://user-images.githubusercontent.com/13824734/117026762-a9a8a700-acc1-11eb-947b-d52717e88b31.png)

**Comment by tw15egan** [comment]
cc @carbon-design-system/design

**Comment by johnbister** [comment]
@NolanCanady thanks for bringing this to our attention. I'll swap this image out as well as the ones in the 'style' tab.

<img width="876" alt="Screen Shot 2021-05-04 at 10 26 09 AM" src="https://user-images.githubusercontent.com/70543333/117044570-6f400980-acc3-11eb-8145-c2c66e3f9a38.png">
<img width="865" alt="Screen Shot 2021-05-04 at 10 25 59 AM" src="https://user-images.githubusercontent.com/70543333/117044574-70713680-acc3-11eb-998b-630c5c244aa6.png">

 I checked the latest sketch kit and it has the correct number input fortunately.  Thanks again!

**Comment by tw15egan** [comment]
Thanks @johnbister!
