### ISSUE TITLE
Accordion arrow is pointing in wrong direction when opened

### ISSUE THREAD

**Issue by ryanarnell** [carbon-design-system/carbon-website#229]
## Detailed description

Accordion arrow is pointing in wrong direction when opened in the image on this page -
https://www.carbondesignsystem.com/components/accordion/usage/

It is pointing down, it should point up. 

## Steps to reproduce the issue
https://www.carbondesignsystem.com/components/accordion/usage/

## Additional information
![accordion-usage-1](https://user-images.githubusercontent.com/4976631/64211766-cb0e1b80-ce6c-11e9-8ab7-754e5a8ac13a.png)

**Comment by xxxle0** [comment]
it was fixed. We can close this issue
![accordion-usage-1](https://user-images.githubusercontent.com/18297839/72658849-64d40080-39e9-11ea-844b-8c8edc8d0518.png)
