### ISSUE TITLE
Time picker: resolve cropped type inside time containers

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#234]
In Safari and Chrome:
https://www.carbondesignsystem.com/components/date-picker/code

@jeanservaas   @joshblack 

<img width="694" alt="Screen Shot 2019-09-04 at 3 24 54 PM" src="https://user-images.githubusercontent.com/32881239/64289574-7339e800-cf32-11e9-9580-2d2720b43b23.png">

**Comment by alisonjoseph** [comment]
this should be resolved with the work Vince is doing on the component demos
