### ISSUE TITLE
Broken links from Carbon home page

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#234]
The links on [Carbon home page](http://www.carbondesignsystem.com/) are broken. Getting started, components, and guideline links are broken

![Screen Shot 2018-10-08 at 9.41.45 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/0c0ab94d-81a4-4fa1-a365-a1021cdac668)

**Comment by aledavila** [comment]
Its been fixed but not pushed to the website.
