### ISSUE TITLE
Tabs need updating

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2356]
https://www.carbondesignsystem.com/data-visualization/color-palettes/#categorical-palettes

These tabs still have the stroke on them

![Screen Shot 2021-05-25 at 1.30.32 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/7c8d043a-263a-4b9f-a4ac-818a4ea14a8a)

related to https://github.com/carbon-design-system/design-language-website/issues/920

FYI @vpicone @aledavila

**Comment by tay1orjones** [comment]
This has been resolved 

![image](https://user-images.githubusercontent.com/3360588/164552759-831adba9-ed18-4df5-b1af-3238b96369b0.png)
