### ISSUE TITLE
Make resource cards three across change heading

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2364]
## update[Other resources page]: Carbon website

https://www.carbondesignsystem.com/designing/design-resources/

- [ ] CHange header title to “Useful resources” or “Valuable resources” FYI @jeanservaas 

- [ ]  Make cards span 3 columns instead of two. see https://www.ibm.com/brand/

![image](https://user-images.githubusercontent.com/43144260/120125714-79004400-c17f-11eb-9a7b-7eea73e92411.png)

![image](https://user-images.githubusercontent.com/43144260/120125543-e6f83b80-c17e-11eb-9a69-f17948996f99.png)

- [ ] Add “Other resources” card as the last card. Card links to: https://www.carbondesignsystem.com/designing/design-resources/

FYI @jeanservaas Let’s discuss quickly

**Comment by jeanservaas** [comment]
@mjabbink 

Are you talking about going three across with all of the resource cards (i.e. changing the gatsby resource component) on the whole site or is this issue just specific to this page?

![image](https://user-images.githubusercontent.com/43144260/120078913-466b2400-c077-11eb-909c-40ab11f59619.png)
