### ISSUE TITLE
Add image production kit resource card to Carbon website

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#2367]
## Add image production kit resource card to Carbon website

- [x] Finish cleaning kit and updating symbols names with @laurenmrice 
- [x] Add production Sketch kit to Sketch Cloud
- [x] Add resource card for production kit https://www.carbondesignsystem.com/designing/design-resources/ *
- [x] ~Change name of "Other resources" section to "Valuable resources"~ Revisit at another time

**Comment by laurenmrice** [comment]
Going to close, this has been added to the website. https://carbondesignsystem.com/designing/design-resources/#image-production-guidelines
