### ISSUE TITLE
v11: update size props in component demos

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2379]
Update the [size props names](https://github.com/carbon-design-system/carbon/issues/8370) in the following component live demos (both on usage and code tabs) on the v11 branch.
- [ ] Button
- [ ] Data table
- [ ] Date picker
- [ ] Search

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
