### ISSUE TITLE
Update dialog pattern with new non-modal content

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2382]
## Stub
- Some of the work being done with disclose component ect. can be added for context to dialog pattern. 
- Topic was talked about on June 3, 2021 in the design crit with @mbgower and @joshblack

**Comment by joshblack** [comment]
Some notes on focus behavior that came up:

- Modal dialog
  - When opened by the trigger element, focus shifts to the first interactive element in the dialog
  - Focus is trapped in the dialog
  - Pressing escape will close the dialog
- Nonmodal dialog
  - When opened by the trigger element, focus shifts to the first interactive element
  - Focus is **not** trapped in the dialog
  - Pressing escape will close the dialog
  - Moving focus out of the dialog will close the dialog

**Comment by aagonzales** [comment]
New notification component could also fall into this category.
