### ISSUE TITLE
Broken images in component pages

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#239]
There are several broken images on multiple component pages (mostly the style pages).
I'm not sure if it's formatting or the images have been moved

![Screen Shot 2018-10-09 at 10.50.54 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/64674dd5-1ae3-4289-95eb-2e0274447c32)

![Screen Shot 2018-10-09 at 10.51.15 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/72552c59-bef0-4d5f-bce7-84eb4b1978ee)

**Comment by alisonjoseph** [comment]
There is an image grid custom component on the old website that didn't get ported over thats causing most of the issues. working on it now.
