### ISSUE TITLE
[pattern] status indicator content fixes

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#2430]
### Content issues:

The Security team pointed out that their guidance around data decorator components directly conflicts with some of what was in the shape status indicator guidance. Their shape status indicators are widely deployed in product and this discrepancy will cause confusion. Changing their shapes to conform to our guidance would also be very costly. We've decided to fold in their risk/severity scale shape indicators into our shape indicator lexicon as they are.

**Security guidance links:**

 https://ibm.box.com/s/mb2dwp56k4rvgl50kwr9tniuqlpbpis7
https://ibm-security.carbondesignsystem.com/?path=/story/components-security-decorator--icons

# To do:

- @conradennis is helping us add two shapes to the library that we're currently missing (the 'Critical' right triangle' and the 'Low severity' square with a stroke for contrast accessibility)
https://github.com/carbon-design-system/carbon/pull/8960

- @vpicone we also need to update the warning major and warning minor assets for accessibility

![image](https://user-images.githubusercontent.com/43144260/124284178-b9eece00-db1a-11eb-9ce8-9cddd922d2d1.png)

- @vpicone we need to add three status shapes into the table I will give you the svgs and the hex

![image](https://user-images.githubusercontent.com/43144260/124182025-50bc7b80-da84-11eb-90e9-1a06b0d0a931.png)

- We need to update the table content in the YAML file (I have content @vpicone if you open the PR and fix the tables, @jeanservaas  can update the YAML in the issue)

- @jeanservaas needs to update the attached images to reflect the real Security product UI (Including the legend image, it's an incorrect example of a legend).

Full new status shape table @cameroncalder for approval

![Status icons_Update](https://user-images.githubusercontent.com/43144260/124181866-16eb7500-da84-11eb-8246-24bd6264fda2.png)

- We also have to update the gray in the status palette 

![image](https://user-images.githubusercontent.com/43144260/124179399-d0e0e200-da80-11eb-90d5-a79c55d45079.png)

----

**- Images to fix:**

<img width="736" alt="Screen Shot 2021-06-29 at 12 25 27 PM" src="https://user-images.githubusercontent.com/43969356/123834156-b7973480-d8cc-11eb-8b92-853ee00b7358.png">

<img width="737" alt="Screen Shot 2021-06-29 at 12 17 16 PM" src="https://user-images.githubusercontent.com/43969356/123833041-908c3300-d8cb-11eb-9bc1-72f72b1a2727.png">

<img width="759" alt="Screen Shot 2021-06-29 at 12 17 34 PM" src="https://user-images.githubusercontent.com/43969356/123833080-9b46c800-d8cb-11eb-8de9-7464fc71ea46.png">

**Comment by mjabbink** [comment]
@vpicone This is a high-priority update to avoid mass confusion.

**Comment by mjabbink** [comment]
Table alignment and grid fixes a must.

**Comment by vpicone** [comment]
Let me know whenever the content is ready, I can update the yaml and add the images.

**Comment by mjabbink** [comment]
@vpicone The content is ready for icon update and color updates. @jeanservaas can confirm but those are Ready to Go Cotton-Eyed Joe.

Grid/Table alignments can happen next sprint I reckon.

**Comment by mjabbink** [comment]
Content is already done and provided above @vpicone

**Comment by jeanservaas** [comment]
@vpicone 

Here are the new svgs, there are screen grabs of where they go in the tables above.

## Status icons updates

### Caution major colors

![image](https://user-images.githubusercontent.com/43144260/124284760-3f727e00-db1b-11eb-8f9e-ac891e203d4c.png)

**Light theme filled Caution major:**

- Stroke, orange 60, Hex # BA4E00
- Fill, orange 40, Hex # FF832B
- exclamation glyph, black # 000000


**Dark theme filled Caution major:**

- Stroke, orange 40, Hex # FF832B
- Fill, orange 40, Hex # FF832B
- exclamation glyph, black # 000000

### Caution minor colors

![image](https://user-images.githubusercontent.com/43144260/124285252-c162a700-db1b-11eb-975b-bcb649bd3607.png)

**Light theme filled Caution minor:**

- Stroke, yellow 60, Hex # 8E6A00
- Fill, yellow 30, Hex # F1C21B
- exclamation glyph, black # 000000


**Dark theme filled Caution minor:**

- Stroke, yellow 30, Hex # F1C21B
- Fill, yellow 30, Hex # F1C21B
- exclamation glyph, black # 000000

## Status shape updates

### Critical severity color

![image](https://user-images.githubusercontent.com/43144260/124286103-99277800-db1c-11eb-863c-cb24a9196693.png)

**Light theme Critical severity:**

- Fill, red 60, Hex # DA1E28

**Dark theme Critical severity:**

- Fill, red 50, Hex # FA4D56

### High severity color

![image](https://user-images.githubusercontent.com/43144260/124286418-ec99c600-db1c-11eb-9c77-a1ff93fc31fa.png)

**Light theme High severity:**

- Fill, red 60, Hex # DA1E28

**Dark theme High severity:**

- Fill, red 50, Hex # FA4D56

### Medium severity colors

![image](https://user-images.githubusercontent.com/43144260/124286568-19e67400-db1d-11eb-8a42-18df2be25ddc.png)

**Light theme High severity:**

- Stroke, orange 60, # BA4E00
- Fill, orange 40, Hex # FF832B

**Dark theme High severity:**

- Stroke, orange 40, Hex # FF832B
- Fill, orange 40, Hex # FF832B


### Low severity colors

![image](https://user-images.githubusercontent.com/43144260/124287013-8c575400-db1d-11eb-85ed-06f41f4a03b0.png)

**Light theme Low severity:**

- Stroke, yellow 60, # 8E6A00
- Fill, yellow 30, Hex # F1C21B

**Dark theme Low severity:**

- Stroke, yellow 30, Hex # F1C21B
- Fill, yellow 30, Hex # F1C21B

[New_status_assets.zip](https://github.com/carbon-design-system/carbon-website/files/6754992/New_status_assets.zip)

**Comment by jeanservaas** [comment]
@vpicone here are the image updates

names are the same so they should pop right in

[image_updates.zip](https://github.com/carbon-design-system/carbon-website/files/6755343/image_updates.zip)

**Comment by vpicone** [comment]
@jeanservaas need the token and usage content
