### ISSUE TITLE
The "nocoffee" Chrome plugin link returns a 404

### ISSUE THREAD

**Issue by johanbove** [carbon-design-system/carbon-website#2438]
## Detailed description

> Describe in detail the issue you're having.

The links to the "NoCoffee" plugin on [this page](https://www.carbondesignsystem.com/guidelines/accessibility/overview/) return a 404.

> What did you expect to happen? What happened instead? What would you like to see changed?

I would expect to see a page with the information about the Chrome plugin.

> What browser are you working in?

Browser independent.

## Steps to reproduce the issue

1. Step one: Visit https://www.carbondesignsystem.com/guidelines/accessibility/overview/
2. Step two: Find mentions of "NoCoffee"
3. Step three: Click the links

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Seems like the extension was removed from the Chrome extension store: https://chrome.google.com/webstore/search/NoCoffee%20Vision%20Simulator?hl=en&gl=US

**Comment by laurenmrice** [comment]
We removed this link from our website. Going to close.
