### ISSUE TITLE
Redesign the Guidance/Color/Usage tab

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2447]
Using the [new tokens](https://www.notion.so/carbondesignsystem/Hybrid-List-of-new-tokens-c507394e43fe4daa9f0cd0eedb25d1e4) update the [Guidance/Color/Usage tab](https://carbondesignsystem.com/guidelines/color/usage) in include the features in Josh's [preview tool](https://deploy-preview-8994--carbon-elements.netlify.app/themes/examples/preview-v11/). The contextual tokens do _not_ need to be included. The layer set tokens should be however. 

**Features include:**
- Token name, value (hex code and IDL name), and role.
- 4 Themes 
- Filters:
   - by token group
   - by token set 
   - by property

**To think about:**   
- Mobile view
- Default view (no filters applied)
- Token group organization. Are interactive state tokens now group with its enabled core token? 
![image](https://user-images.githubusercontent.com/11670886/125312434-414df580-e302-11eb-9829-f1f2a3b1ab2f.png)
![image](https://user-images.githubusercontent.com/11670886/125312476-4c088a80-e302-11eb-86da-abf3a76348dd.png)

**Comment by jeanservaas** [comment]
@aagonzales 

I couldn't finish before vacation but I think it's a good start. Now I think it's about how the content makes the most sense.

Questions/Comments:

- Can we keep it 3 columns and gang up the "property" and "role" information in one column? Or do we need to go four columns with it?
- Can we develop fluid inputs for this?
- Multi-select dropdown works great in terms of design... not so great in terms of good UX... if you select multiple boxes in each category, you'll almost always get zero results... so it seems like not such great functionality
- Didn't really try anything in the way of a side panel with radio buttons (real estate) or disclosure panel (bad experience)


## Sketch file

[color_usage_page_revamp.zip](https://github.com/carbon-design-system/carbon-website/files/6832464/color_usage_page_revamp.zip)

**Comment by aagonzales** [comment]
I think these are the two possible directions:

1. Using fluid input dropdowns
![all_up_4_cols_1312](https://user-images.githubusercontent.com/11670886/127004920-d94a9b90-8575-4ec5-94ff-9772fa71983a.jpg)

2. Using multi-select filters. 
![Multiselect_opts](https://user-images.githubusercontent.com/11670886/127004923-59080ea3-693a-4f51-bc89-d28a9b51dc80.jpg)

**Comment by aagonzales** [comment]
# Final

Sketch file: https://ibm.box.com/s/yrcji9bhdxegagwt3z7879jiovv49bxf
Dev issue:

## Desktop
- Two sections for core and component tokens.
- 4 Columns of content: Token, role, property, and value.
- 4 Filters: Theme, token group, token set, and property. 

![core-tokens+components-1312](https://user-images.githubusercontent.com/11670886/128213911-bb9a049b-e031-44cd-87d1-18c98b765b46.png)

## Mobile
- Two sections for and component tokens
- Columns collapse into single card view with `em` dash separating column content (much like as is mobile view)
- Filters: only the theme filter is available on mobile, other filters are hidden due to space efficiency. 

![tokens-mobile-1](https://user-images.githubusercontent.com/11670886/128213916-e0ba7609-84c0-495c-85ec-74bf85532a59.png)
