### ISSUE TITLE
Searching for an icon and scrolling down causes the page content to disappear 

### ISSUE THREAD

**Issue by ud-ux-thomas** [carbon-design-system/carbon-website#2448]
## Summary
On the icons page, when I search for some icons, then scroll down, the page goes blank.

## Relevant information
1. On an intel-based Mac with all recent updates applied...
2. Using any of the following browsers: Firefox developer edition (latest), Firefox (latest), Google Chrome (latest) or Safari (latest)...
3. Go to the [icons page](https://www.carbondesignsystem.com/guidelines/icons/library/)
4. Search for "circle" (do not include quotation marks).
5. Scroll down using the touch pad, mouse wheel or arrow keys on keyboard.
6. Note that all page content is no longer visible.

I have attached a screen recording:
https://user-images.githubusercontent.com/38993885/125917614-3c87b29f-4d11-47cc-bd33-5aea61f3561e.mov

**Comment by johnbister** [comment]
@ud-ux-thomas Confirming that I get the same bug in Chrome, Firefox, and Safari.

cc @carbon-design-system/developers Anyone know what's causing this issue?

**Comment by tw15egan** [comment]
Also seeing this behavior, not sure what's going on either. @vpicone any ideas?

**Comment by ballefar** [comment]
could it be related to dynamic imports and unstable network on client?

**Comment by theoshu** [comment]
It's an error with the critical-severity/32 icon.

![image](https://user-images.githubusercontent.com/4643524/127492520-c4530f26-ebd1-4490-ad1a-996db5d474f7.png)

**Comment by tw15egan** [comment]
The root of the issue was that some icons are only available in `glpyh` format, and those do not have a `/32` file causing the error. Added a check to see if an icon is glyph-only first before trying to import.
