### ISSUE TITLE
docs: Improvements to the Content > Glossary

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon-website#245]
## Background
After discussions with @janchild and @connor-leech , I have spent some time reviewing the existing Carbon > Content > Glossary page (as well as some other similar glossary / terminology sets at IBM) and have a few proposals. (This issue does not cover the actual terms listed themselves. I'll do that separately.)

Note: I'm happy to do this work and submit the PR, but thought I'd raise this in an issue first, so that others have a chance to comment on these proposals.

### 1) Add an intro sentence or two to explain the intended scope

Rationale: 
- I imagine (and hope) that if we invest some time and effort in updating and enhancing this Carbon Glossary, more and more teams across IBM might start using it. 
- Indeed, if we do a good job, I'd hope that over time people might decide they no longer need to maintain their own local glossaries. 
- However, if more teams use this glossary, we'll no doubt have more people asking us to add more terms. This is all fine - but I think it would be wise to set expectations now re what the scope of the glossary is. 
- I _believe_ that the Carbon Glossary is intended as a lightweight resource for designers and engineers to cover the most common terms that get used across many IBM product UIs (e.g. common action labels). It is therefore not intended to cover endless product-specific technical terms and concepts which might only apply to one or two products. 

So, I propose we add some text to the top of the page. Here are some examples: 

> _The Carbon glossary is intended as a lightweight reference, covering common UI terms._
or
> _The Carbon glossary is intended as a lightweight reference covering terms commonly used in many IBM product UIs. Product-specific terminology should be covered elsewhere, such as in product-specific docs._
or 
> _The Carbon glossary is intended as a lightweight reference covering common UI terms. It’s not intended to cover general computing concepts nor product-specific terminology, which should be covered elsewhere, such as in product-specific docs._  

Thoughts?

### 2. List terms in lowercase
- Carbon guidance is to use sentence case in our UIs (so we don't want people to think that they need to always capitalize these words).
- To support this, I think it would be more helpful to list terms in lowercase by default (as is common in dictionaries, etc.) 
- The only exceptions would be:
  - proper nouns (e.g. Watson)
  - acronyms (e.g. ASCII)
  - initialisms (e.g. IBM, HTML, etc.)

### 3. Remove all instances of the sub-heading "Action labels"
I believe that under each letter section, originally there were two sub-headings: 
- Action labels
- Idioms  

All "Idioms" have since been removed, so there no longer seems any reason to repeat the sub-heading "Action labels" under each letter. 

### 4. Add visual styling to differentiate between other valid terms (which get rendered as links) and "do not use" terms. 

Rationale:
- Wherever we explicitly mention a term _not_ to use (e.g. if on the **close** entry we wanted to write "do not use **dismiss**) it would be good if we could render such "do not use" words in a way that made them visually distinct from all other text. 

- For reference, see the [Hybrid Cloud terminology list](https://hc-design.w3ibm.mybluemix.net/design-system/voice-and-tone?tab=terminology), where a pale red background is applied to such "do not use" terms.
- But I'm happy to defer to the Carbon design term to advise re what the most suitable visually styling might be.

**Comment by janchild** [comment]
We love all of these suggestions, @tomwaterton. Thank you very much. 

I like the idea of making the "do not use" terms visually different in a way that signals not to use those words. Let me chat with the designers about options we have for that, but please feel free to move forward. 

Thanks again!

**Comment by tomwaterton** [comment]
Status:
- [x] 1) Add an intro sentence or two to explain the intended scope
- [x] 2. List terms in lowercase
- [ ] 3. Remove all instances of the sub-heading "Action labels"
- [ ] 4. Add visual styling to differentiate between other valid terms (which get rendered as links) and "do not use" terms

**Comment by tomwaterton** [comment]
All aspects of this issue have now been addressed and all changes delivered and published to the Carbon > [Glossary](https://www.carbondesignsystem.com/guidelines/content/glossary/) page, so I'm now closing this issue.
