### ISSUE TITLE
Searching for "status" in the icon library turns the page black

### ISSUE THREAD

**Issue by half5cat** [carbon-design-system/carbon-website#2454]
## Detailed description

As the title says, when you search for "status" in the icons library, the whole page turns black and becomes unusable: https://www.carbondesignsystem.com/guidelines/icons/library/ 

## Additional information

Tested in Chrome and Safari on a Mac.

**Comment by tw15egan** [comment]
Thanks for reporting! Going to close as a dupe of https://github.com/carbon-design-system/carbon-website/issues/2448
