### ISSUE TITLE
Times new roman is in place instead of Plex Serif (SAFARI:Desktop/mobile)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#248]
https://www.carbondesignsystem.com/guidelines/typography/overview/

@alisonjoseph @vpicone 

<img width="736" alt="Screen Shot 2019-09-05 at 9 15 07 AM" src="https://user-images.githubusercontent.com/32881239/64356154-653aa480-cfd0-11e9-9c49-35578cfe4bce.png">

**Comment by alisonjoseph** [comment]
confirmed this was fixed
