### ISSUE TITLE
Images need correcting on edges as PNG. Recommend exporting these as SVG.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2489]
IN exporting to PNG the edges of the artwork are creating lighter aliasing which is not good when they are on dark backgrounds. It causes little borders to show up which looks amateur.

https://www.carbondesignsystem.com/
https://www.carbondesignsystem.com/whats-happening/news-and-articles/

examples of current

![1_G2OdkbpTc6xbotnyKWyR8Q.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/6caedc33-d06a-4e31-9db6-9e39593dea2a)

![1_mIJ84K3Iazci2fW9xvFR4Q.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/350db851-d479-4d3e-a244-61d599d0133d)

![1_qgWhvGf0kwCaq7nylYm73w.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/1bd39e69-b9b4-4700-96d1-2d720c03e720)

Details

![Screen Shot 2021-08-10 at 12.03.26 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/5eb1ebe0-369e-46a6-aad2-03f67fbb45c0)

![Screen Shot 2021-08-10 at 12.01.26 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/3d9844d4-e1d2-4b42-808a-e0f19562f3ee)

![Screen Shot 2021-08-10 at 12.01.16 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/a5e11886-5fe5-415a-b230-a4565b6f6e42)

![Screen Shot 2021-08-10 at 11.58.33 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/632320e2-d3ef-4931-b541-2fe277dcb550)

![Screen Shot 2021-08-10 at 11.58.17 AM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/b3a398ce-22f0-447e-8b53-2eaae2bd7214)

**Comment by mjabbink** [comment]
@jeanservaas @thyhmdo These images need to be either exported better or corrected in PS so the edges do not have the crappy aliasing OR better yet, these types of images can be SVG since they are vector and will look great.

**Comment by mjabbink** [comment]
@jeanservaas Can you provide Thy with your Ai files for these. I would like to resolve this issue since it looks lame on mobile

**Comment by mjabbink** [comment]
I think these need to be SVGs to avoid this or you all have to pay special attention to the borders of the images once you make them PNGs because it looks like they get compressed which may cause this.

**Comment by thyhmdo** [comment]
Just sent Josh these images for update
https://ibm.ent.box.com/folder/144694477942

**Comment by mjabbink** [comment]
@alisonjoseph @tay1orjones Let’s please get this issue closed this sprint.

**Comment by sstrubberg** [comment]
Reached out to @aledavila and @thyhmdo directly on Slack earlier this week.

Reposting here for clarity the images that we are pulling are coming directly from Medium through the `MediumPosts` component I made for the Gatsby Theme. In other words, we aren't hosting these images, Medium is. The authors of their respective articles will need to update accordingly.

**Comment by sstrubberg** [comment]
We tried to upload the SVG's to Medium and it turns out they aren't supported.. womp womp...
![image](https://user-images.githubusercontent.com/15822070/142657051-d8c7852c-91ee-4e56-b19e-0d3ea7a4ff64.png)

So now we need to make a decision, go back to the old, manual way of updating this content, where we control the source imagery, or do we use the automated component that just pulls in the content automatically at build time with the unfortunate side effect of these artifacts happening.

Is there a way we can still use a PNG and get the same quality? Does it have to be SVG?

**Comment by aledavila** [comment]
I'll surface this again. What is the consensus on this since we cannot upload svgs to medium. 

@mjabbink @jeanservaas @sstrubberg
