### ISSUE TITLE
Typography specs reforming in a bad way in mobile

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#249]
https://www.carbondesignsystem.com/guidelines/typography/expressive

@alisonjoseph @vpicone @jeanservaas 

expected formatting (same as desktop):
<img width="340" alt="Screen Shot 2019-09-05 at 11 30 59 AM" src="https://user-images.githubusercontent.com/32881239/64356380-c8c4d200-cfd0-11e9-827a-9fd089cbd241.png">

.
.
.
current:
<img width="429" alt="Screen Shot 2019-09-05 at 11 30 53 AM" src="https://user-images.githubusercontent.com/32881239/64356402-d11d0d00-cfd0-11e9-9bd4-4608098a1f7a.png">

**Comment by alisonjoseph** [comment]
Tested on mobile view on chrome and on my iphone and am unable to duplicate. IF you are still seeing this please re-open with steps to duplicate.

![Screen Shot 2019-09-13 at 11 07 58 AM](https://user-images.githubusercontent.com/2753488/64877371-e4565b00-d616-11e9-94ae-4dce79b46b8c.png)
![IMG_1695](https://user-images.githubusercontent.com/2753488/64877375-e7514b80-d616-11e9-8e00-22d65eb0ea5d.PNG)
