### ISSUE TITLE
Replace Accessibility content with the content from IDL site

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2490]
The content in the IDL site is better and has a color chart that is more useful. @jeanservaas and @aagonzales can you confirm you agree and how best to duplicate that content.

IDL
https://www.ibm.com/design/language/color#accessibility

Carbon
https://www.carbondesignsystem.com/guidelines/color/overview/#accessibility

**Comment by aledavila** [comment]
@aagonzales Hey is this being worked on in the v11 site ?
