### ISSUE TITLE
update check emoji to carbon icon on tile style page

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-website#2497]
[Proportions for grid table](https://carbondesignsystem.com/components/tile/style#proportions-for-grid) on tile component's style page should be using carbon icons rather then the emoji checks check ✅

![image](https://user-images.githubusercontent.com/20582179/129613764-12096b03-32bd-433c-a938-d1704fbf5d7c.png)

**Comment by jnm2377** [comment]
@kingtraceyj which of the checkmark icons should it use?

<img width="1263" alt="Screen Shot 2022-08-15 at 11 59 45 AM" src="https://user-images.githubusercontent.com/32556167/184680709-b129f79e-488e-459f-a3ec-9d972d09188c.png">

**Comment by kingtraceyj** [comment]
@jnm2377 let's use `<CheckmarkOutline />` in `gray 100`

**Comment by kingtraceyj** [comment]
@francinelucca we are going with `checkmark` in` icon-primary`
![image](https://user-images.githubusercontent.com/20582179/187735870-c4ba420d-1c6c-4dd4-943a-26a034129954.png)
