### ISSUE TITLE
Layout page

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#25]
@shinytoyrobots commented on [Thu Sep 13 2018](https://github.com/carbon-design-system/issue-tracking/issues/4)

I want to have a page addressing Layout that combines these things, in this sequence:
- [ ] Spacing and the CSS Box Model
- [ ] Sizing Fixed Boxes using Size Scales (box equivalent to Type Scales) and Aspect Ratios
- [ ] Sizing Liquid Boxes using Column Grid
- [ ] Layer (Z Index)
- [ ] Page Geometry (Regions)

@alisonjoseph @designertyler (need to add Pete Garvin and Jean Servaas)

**Comment by kuehndaniel** [comment]
For each of the Layout items in the original description above please note the pieces needed for both design and dev:

**Comment by jeoffw** [comment]
Another take.... I need to reconcile this with the ticket description:
- mini unit
- applying mu to CSS box model (padding, margins)
- guidelines for choosing fixed vs. liquid in each dimension
- fixed: choosing sizing scale and aspect ratios
- liquid: using grid columns
- choosing # of columns

**Comment by shinytoyrobots** [comment]
NB: The previously closed issues referenced required development tasks. That is not required in this issue, it is a design guidance page for layout. This can be created as a markdown page and submitted as a PR.

**Comment by aagonzales** [comment]
First iteration is done for TT. Will polish more in future
