### ISSUE TITLE
Improve Iconography page filter and search

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#252]
### Summary

The current iconography page is very large and difficult to navigate and requires knowing the name of the icon to search.

Design can come up with some concepts to improve organization, search, and discovery of icons.

https://w3.ibm.com/design/product/experimental/iconography/library

**Comment by claycrenshaw** [comment]
I set up an epic before I saw this issue: https://github.com/carbon-design-system/issue-tracking/issues/44

We should merge them. . .

**Comment by designertyler** [comment]
Closing this issue. See search specs here https://github.com/carbon-design-system/carbon-website/issues/1094
