### ISSUE TITLE
Autoplaying video on the front page of Carbon Design System Website is an accessibility issue

### ISSUE THREAD

**Issue by eevajonnapanula** [carbon-design-system/carbon-website#2538]
## Relevant information

The Carbon Design System Website has an autoplaying video on the front page. From accessibility perspective it is a bad idea to have auto playing videos (even if they don't have sound on), because surprising movement, especially over a large area, can cause for example nausea or dizziness. Here is [a good article about motion sensitivity and animations/movement on the web](https://alistapart.com/article/designing-safer-web-animation-for-motion-sensitivity/) by Val Head. Also, people with cognitive disabilities might find autoplaying videos or animations distracting or confusing, and those videos might even trigger seizures. 

Why I'm reporting this is because I am one of the people who suffer from this kind of things, and the autoplaying video triggered symptoms for me. This time it meant nausea and dizziness, which took about 30 mins resting before I could continue with my work, which involves using Carbon Design System. 

You might wonder, how do I survive my days with such a condition, and the internet having so much animations and movement? Well, I have the "Reduce motion"-setting on from the operating systems settings. There's a CSS Media Query "prefers-reduced-motion", which let's the websites respect that setting from the operating system. As you're using Gatsby for the website, here's [a good blog post ](https://www.joshwcomeau.com/react/prefers-reduced-motion/)on how to utilize said media query with React by Josh Comeau. So my suggestion would be disabling the autoplay from the video at least for those who prefer reduced motion, but also think if the video is needed at all.

**Comment by sstrubberg** [comment]
Closing as we no longer have a video playing on the homepage
