### ISSUE TITLE
[TT Presentation] Replace side nav arrow with chevron 

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#255]
To decrease transitional volatility between design > language >product 
https://github.ibm.com/Design/w3-design-site/issues/85

To improve consistency we should use the chevron up and down icons in our left nav. The language site uses the 16x16px grey-40 #A4A4A4 chevron.

 ![Screen Shot 2018-10-11 at 10.38.46 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/d02ba165-eacd-4c30-899c-d6e863ac9489)

![Screen Shot 2018-10-11 at 10.38.26 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/5691b27a-2bfc-4345-92c1-81e7c85d7284)

![Screen Shot 2018-10-11 at 10.38.21 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/4dd084a5-cb76-4d5c-9959-60866bc3f765)

**Comment by alisonjoseph** [comment]
This icon?
![screen shot 2018-10-11 at 3 15 42 pm](https://user-images.githubusercontent.com/2753488/46831276-9121bb80-cd68-11e8-9b4e-bc1117e66261.png)

**Comment by designertyler** [comment]
Yep, that's the one. It's another small tweak that could align us a little closer to language.
