### ISSUE TITLE
[Typography] $expressive-heading-03's line height is not changing between xlg and max breakpoints

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#2553]
$expressive-heading-03 has a size change at `max` breakpoint. This means line height should adjust accordingly. Currently on the website, the line height remains at 28px for all breakpoints

https://user-images.githubusercontent.com/15144993/134506681-7b21a1eb-5bab-4442-bf75-6f9fb5f02f4d.mp4

![image](https://user-images.githubusercontent.com/15144993/134506695-157af859-b318-4224-b899-d40ef8bb54b7.png)

**Comment by thyhmdo** [comment]
@shixiedesign Are you seeing this only on the website or just in code?
