### ISSUE TITLE
`Tag` component demo `disabled` knob causes incorrect color classes

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-website#2578]
## Detailed description

[Reported in slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1634243320440500), When the `disabled` knob is selected, then deselected, the wrong class is applied and all the tags turn red.

> What did you expect to happen? What happened instead? What would you like to see changed?

The original colors classnames would return when the `disabled` knob is deselected

> What browser are you working in?

Chrome

## Steps to reproduce the issue

1. Goto the carbon tag page - https://www.carbondesignsystem.com/components/tag/usage/
1. Goto the Live demo
1. (see all the pretty colored tags)
1. select disabled
1. unselect disabled
1. (no more pretty colors)

## Additional information

https://user-images.githubusercontent.com/3360588/137427372-eed7736f-93d7-4f5e-a8e6-0368f639ad41.mov

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
