### ISSUE TITLE
[live demo] modal

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#2590]
- [ ] 2 button modal: buttons needs to span the whole width of the modal.
<img width="1089" alt="Screen Shot 2021-10-21 at 11 26 39 AM" src="https://user-images.githubusercontent.com/43969356/138318840-cad32911-6754-476c-a522-c19ebf806ee7.png">

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
