### ISSUE TITLE
Update site header to align with other w3 design sites

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#262]
To decrease transitional volatility between design > language >product.

Bring our header and nav closer to Language

![Screen Shot 2018-10-11 at 10.38.26 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/5691b27a-2bfc-4345-92c1-81e7c85d7284)

![Screen Shot 2018-10-11 at 10.38.21 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/4dd084a5-cb76-4d5c-9959-60866bc3f765)

**Comment by designertyler** [comment]
Current ideas that explore different levels of alignment.

![1](https://user-images.githubusercontent.com/19270502/46882933-e9fb5d80-ce15-11e8-9df9-804ba0e81efc.png)
![2](https://user-images.githubusercontent.com/19270502/46882934-e9fb5d80-ce15-11e8-82c7-efc63da7a54a.png)
![3](https://user-images.githubusercontent.com/19270502/46882935-e9fb5d80-ce15-11e8-9aef-bda317db4281.png)
![4](https://user-images.githubusercontent.com/19270502/46882936-ea93f400-ce15-11e8-9a3e-fe8b8ef15445.png)
![5](https://user-images.githubusercontent.com/19270502/46882937-ea93f400-ce15-11e8-97e7-8f12cd38a527.png)

**Comment by designertyler** [comment]
Simple tweaks to the existing header that get it pretty close to language. We still need to figure out why the font weight is slightly heavier. 

<img width="1033" alt="screen shot 2018-10-12 at 2 03 47 pm" src="https://user-images.githubusercontent.com/19270502/46889264-b1b14a80-ce28-11e8-928c-acc1b028b5d4.png">

**Comment by alisonjoseph** [comment]
closing for now. will track new work in new carbon x design issue
