### ISSUE TITLE
Add IBM to header

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-website#263]
Should we be using full name "IBM Carbon Design System"?

Should just `IBM` be light font weight?

**Comment by vpicone** [comment]
@mjabbink @alisonjoseph 

@janchild mentioned we might want to be prefixing carbon with IBM for IP/trademark purposes.

**Comment by janchild** [comment]
Note from Jeoff from earlier today. 

![image](https://user-images.githubusercontent.com/44503588/64460573-53d0c580-d0c0-11e9-9333-bd5d086a9c0f.png)

**Comment by mjabbink** [comment]
If we add IBM then...

IBM (regular) Carbon Design System (bold)
