### ISSUE TITLE
Side nav doesn't work in IE11

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#263]
Can't open/close any of the items in IE 11. any ideas @asudoh before Iook into it

**Comment by asudoh** [comment]
Cannot rattle off one, but here are several things that can be done:

1. See if there are any JavaScript errors shown in the console
2. See if there are any recent changes that use new web platform APIs
3. Understand what steps in our code should happen upon the user gesture, and see how far they are done correctly (50%? 25%? 75%?)

**Comment by asudoh** [comment]
My quick run with IE11 tells me that `Promise` polyfill is missing - Though the problem doesn't reproduce with my local env with latest `master`.

**Comment by alisonjoseph** [comment]
My local dev env works also, which makes me think its something that gets changed/missed in the gatsby build step.

**Comment by asudoh** [comment]
Actually the built version works well with latest `master`. I see see `h(this,E,"Promise","_h")` code in `public/app-{hash}.js` in my local machine, whereas it (or any polyfills) cannot be found in https://www.carbondesignsystem.com/app-9ddb8cdb16d732774046.js. It made me wonder when the code was last deployed?

**Comment by alisonjoseph** [comment]
I deployed the latest yesterday, still doesn't seem to be working for me.
