### ISSUE TITLE
[Tag page]: Bug on Live demo section

### ISSUE THREAD

**Issue by sorin-calinescu** [carbon-design-system/carbon-website#2634]
## Detailed description

> On the page for Tag (https://www.carbondesignsystem.com/components/tag/usage/), in the Live demo section: when you select the filter modifier all tags became red. When you select and then unselect the disabled modifier, all tags became red. They do not change back colors unless you reload the page.

> What did you expect to happen? What happened instead? What would you like to see changed?
I expect when I use a modifier the tags to keep their colors.

> What browser are you working in?
Firefox

**Modifiers unchecked**:
![image](https://user-images.githubusercontent.com/72018859/141302948-0138503e-c4c0-43d7-888b-4336218f21f3.png)

**With filter modifier checked**:
![image](https://user-images.githubusercontent.com/72018859/141303213-2679d48f-dd8a-41f4-9f0f-f0c73815fb40.png)

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
