### ISSUE TITLE
Far right content should be on grid column

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#2637]
https://www.carbondesignsystem.com/guidelines/typography/expressive/

and

https://www.carbondesignsystem.com/guidelines/typography/productive

![Screen Shot 2021-11-11 at 5.52.12 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/cbc77e44-79ce-49f1-83e6-bda8a865c687)

**Comment by alisonjoseph** [comment]
Also needs a fix on the IDL site.
