### ISSUE TITLE
Incorrect example shown in the Button component

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon-website#2638]
## Relevant information
Link to the page and section this issue relates to: **[Components > Button > Content](https://www.carbondesignsystem.com/components/button/usage/#content)**

The guidance correctly says that best practice is to use the {verb} + {noun} content formula on buttons (except in the case of common actions like “Done”, “Close”, “Cancel”, “Add”, or “Delete”). 

All well and good. 

Then there is a good and bad example image provided:

![Screenshot 2021-11-12 at 06 19 41](https://user-images.githubusercontent.com/9316771/141419831-30bbc44d-ac66-45bb-9666-837fe4b55f7e.png)

The good example is fine and helpful. 

However, in the case of the bad example, the caption reads
> Do not use only a noun as a button label.

Yet the image does not show a button label with just a noun used. What it shows is a button with the label `Create` (a verb). 

I suggest that we need to do one of the following to fix this: 
- Replace the "bad" example image with an image that shows a button with a label that only used a noun. For example, a button with the label `Dashboard` or `Report` or some such (which clearly would be bad and wrong — in such cases it would appear that a link to another page in the UI was being provided but incorrectly styled as a button)... However, I do question whether we really need to provide a bad example of this type, as I don't remember ever seeing any IBM product where someone had used just a noun on its own as a button label.
- So, the other option would be to just keep the good example and simply remove the bad example.

**Comment by aagonzales** [comment]
Update the button label in the bad image example to say "Resources" instead of "create" to match example text.

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-website/2638?planning-poker) with ZenHub @laurenmrice @thyhmdo
