### ISSUE TITLE
[toggletip] replace static images with gifs

### ISSUE THREAD

**Issue by johnbister** [carbon-design-system/carbon-website#2640]
### Summary

This issue is to track feedback for any gifs that will replace static images in our toggletip docs including:
<img width="666" alt="Screen Shot 2021-11-15 at 8 59 36 AM" src="https://user-images.githubusercontent.com/70543333/141822909-f1f5d783-501d-49d7-b693-cc5317eba49a.png">

**Comment by johnbister** [comment]
here's v1.
![toggletip_v1](https://user-images.githubusercontent.com/70543333/143922559-01a2eb0c-a95f-4ca5-a3bd-d7ca77b902a9.gif)

**Comment by kingtraceyj** [comment]
is looking good! i think the only edit needed is the focus state is active until a user dismisses the toggletip
![toggletip](https://user-images.githubusercontent.com/20582179/146451474-837826fd-3783-4bc1-8f6c-51773ccc9921.gif)
.

**Comment by kingtraceyj** [comment]
this is the pull request that is open for toggletip: https://github.com/carbon-design-system/carbon-website/pull/2619

this gif will replace the double image at the very beginning.
