### ISSUE TITLE
Redirect is not working in Safari

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#2653]
This link is coming from [IBM's training site](https://www.ibm.com/training/badge/9995af49-23f1-4ef1-bec7-4778f654ea75):

https://www.carbondesignsystem.com/tutorial/react/overview?_ga=2.42483491.703470997.1638176874-1770560674.1637151015

It seems to properly redirect to this link when using Chrome:

https://www.carbondesignsystem.com/developing/react-tutorial/overview

But with Safari, it's going to Carbon's 404 page:

https://www.carbondesignsystem.com/404

**Comment by ljcarot** [comment]
This issue appears to have been resolved as I cannot reproduce the 404.  @sstrubberg Can you close issue please?
