### ISSUE TITLE
Improved component page information organization 

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#266]
As a product designer I can discover the usage and behavior guidance for a component so I can reference as I design and validate design decisions with developers.

 
- Improve discoverability of Usage.
- Add more usage and behavior guidance. "Usage is information that I can't get from the design kit"
- Consider how the content will be shared between designer and developer. Anchor links, discoverability, clarity,  "Once we used (Carbon site) to check/validate in a meeting" "If we're fighting on stuff about something, I'll copy and paste code, or show them the React storybook."

**Comment by shixiedesign** [comment]
Examples from competitors: 
https://www.lightningdesignsystem.com/components/avatar/
![image](https://user-images.githubusercontent.com/15144993/52391904-3faee200-2a65-11e9-84ba-f50e90513e4e.png)

https://material.io/design/components/buttons.html
![image](https://user-images.githubusercontent.com/15144993/52391930-666d1880-2a65-11e9-91f4-7453f3f79c0c.png)

**Comment by shixiedesign** [comment]
Requirements @claycrenshaw 's issue: 

Review and propose a new architecture for the content of each component's guidance.

- [ ] Consider possible options for making dev vs. design guidance more clear.
- [ ] Use a more user-focused approach.
- [ ] Consider in-page indexing options.
- [ ] Establish improved standard information scheme for each component in the system.

Deliverable: standard template for a component, including "design" and "develop" content.

**Comment by aagonzales** [comment]
Related:https://github.com/carbon-design-system/carbon-website/issues/407

**Comment by claycrenshaw** [comment]
Closing this to consolidate with #407. @designertyler FYI
