### ISSUE TITLE
Tabs: Update live demo

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-website#2660]
Live demo needs to be updated to reflect v11 changes

**Comment by kingtraceyj** [comment]
Hoping we can structure the live demo a little closer to how we structured our docs:

![image](https://github.com/carbon-design-system/carbon-website/assets/20582179/84c8a3ad-2de4-4cc7-bf0f-3cf5e533de0a)


Visuals:
![image](https://github.com/carbon-design-system/carbon-website/assets/20582179/f6b39b52-1448-4292-854c-e36997070fde)

 Showing icon with size selector for line tabs:
![image](https://github.com/carbon-design-system/carbon-website/assets/20582179/5091e20d-dbf7-42c2-ad86-3bf87acfbdaa)

**Comment by kingtraceyj** [comment]
the original design above is the ideal configuration that follows our current doc structure. it differs slightly from our storybook right now. 

after chatting with @andreancardona, in the short term, we will stick with the current storybook structure and update the live demo component according to priority of the Storybook audit:
https://airtable.com/appOqWyfQBLznbeE7/tbldm9oxL5kMaRFh7/viw2hSBv9swEUJTNt?blocks=hide

Demo with current storybook structure and temporary live demo design:
![image](https://github.com/carbon-design-system/carbon-website/assets/20582179/0d2780e1-423b-4b8f-a5eb-a9f8b683db39)

**Comment by tw15egan** [comment]
Just wanted to point out, the knobs on the right directly map to what props are used in the react components themselves, with the exact naming a developer would use. The above idea of a `kind` with `text & icons` isn't a prop but rather a pattern a user would construct, and could lead to some confusion.
