### ISSUE TITLE
Improved component search and filter

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#267]
As a product designer I can discover and know I found the right component without knowing the component's name or clicking into each component's page. 

User feedback:

- Feels like form elements should be next to each other
- She had no idea that they are alphabetical!!!!
- Q: How were you imagining that it would be? A: IDK? Grouping elements based on form/function

The only way to find a component is by its name.
- Add tags to components so users can filter by: Page type, platform, use case, language, etc.

**Comment by designertyler** [comment]
Following similar search patterns as https://github.com/carbon-design-system/carbon-website/issues/1094

and adding metadata in the same process as https://github.com/carbon-design-system/carbon-website/issues/1117

**Comment by designertyler** [comment]
First mockup with a first pass at categories.
![image](https://user-images.githubusercontent.com/19270502/53100452-6cdfa380-34ed-11e9-8ef8-7f1ebc2fdd7c.png)

**Comment by designertyler** [comment]
Pattern and component categories documented by Lara for Digital.
https://airtable.com/invite/l?inviteId=inv2XFWW2X8xozjX5&inviteToken=070d264e55fe44b0618a50de91f1475c621d7fd408940ce18b18a1faf2a5e5ca

<img width="1380" alt="screen shot 2019-02-22 at 8 54 09 am" src="https://user-images.githubusercontent.com/19270502/53250266-acd69000-367f-11e9-909d-ee05ce4f1202.png">

**Comment by shixiedesign** [comment]
Awesome stuff. Is it possible to save out a copy for us to use for future? @designertyler  Same thing with icon search words data i think. I'm afraid we can't get to implement it right away and forget where to find this wisdom later.

**Comment by designertyler** [comment]
### Component Search
![component_search_1](https://user-images.githubusercontent.com/19270502/53600627-9fce0b00-3b6f-11e9-8464-c1e605acbf2a.png)

### Component Category dropdown
![component_search_2](https://user-images.githubusercontent.com/19270502/53600633-a3fa2880-3b6f-11e9-9a59-85265bba41c7.png)

### Filtered results
![component_search_3](https://user-images.githubusercontent.com/19270502/53600639-a78daf80-3b6f-11e9-8636-ee8c348019b8.png)

### No results
![component_search_no_results](https://user-images.githubusercontent.com/19270502/53600650-aeb4bd80-3b6f-11e9-92e8-67c3e7d266c5.png)
### Mobile and narrow screens
![component_search_sm](https://user-images.githubusercontent.com/19270502/53600664-b6746200-3b6f-11e9-8d59-100e2e1c267f.png)
