### ISSUE TITLE
[Domain guidance] update Cloud & Cognitive to Carbon for IBM Products

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#2679]
- [x] Update the Cloud & Cognitive tile to say "Carbon for IBM Products"

Link can stay the same:
https://pages.github.ibm.com/cdai-design/pal/

- [x] Remove tile that says "Cloud Pattern and Asset Library"

**Comment by ljcarot** [comment]
@jeanservaas Are you able to make this update as part of clean up of Domain Guidance before it gets pulled in to Platform?  If you already have this covered under another issue, cross link and close this.  thx

**Comment by laurenmrice** [comment]
This has been updated. https://carbondesignsystem.com/community/domain-guidance/

Going to close.
