### ISSUE TITLE
To design with Carbon you must have the most recent version of Sketch installed.

### ISSUE THREAD

**Issue by mashinista** [carbon-design-system/carbon-website#268]
## Summary

**Adoption** is listed as the first point under the governance section at https://www.carbondesignsystem.com/get-started/about-carbon

Having a Mac only tool for designers is not going to help with adoption. Some more agnostic approach or a web based tool as Figma should be considered. Nice and well organized project otherwise.

**Comment by aagonzales** [comment]
We have considered other tools but we do not have the resources to build and maintain them. We have added an Axure kit and a beta Adobe kit.
