### ISSUE TITLE
Live demo: add layering component feature 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#2687]
We need to remove the `light` prop feature from the live demos for v11 and it would be nice to replace it with a layering component feature that would also change the background color. This may need some design + dev pairing.

![image](https://user-images.githubusercontent.com/11670886/148838353-65e7e13a-4b42-4b9a-947d-93db2607cbca.png)

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
