### ISSUE TITLE
Layout page[Code tab]: Getting started content

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#273]
Rewrite Getting started content (with attached code) to address multiple entry points for user:

- Happy path: assuming people have carbon-components installed 

- Installing the grid package independently 

Flow diagram:

![image](https://user-images.githubusercontent.com/43144260/64548096-975f4580-d2f3-11e9-9738-1c8b96f65d0b.png)

Note: I haven't started a branch for the grid code tab yet but I will this week.

![Grid_code_tab](https://user-images.githubusercontent.com/43144260/64548191-c2499980-d2f3-11e9-959f-b1b3465fca19.png)

**Comment by joshblack** [comment]
@jeanservaas what timeline were you thinking I need to get this done by?

**Comment by joshblack** [comment]
First take:

---

We provide multiple ways for you to use the grid for the Carbon Design System. By default, the grid code is included when you use `carbon-components`. To get started, you'll need to install this package using `npm`:

```bash
npm install carbon-components --save
```

Or, if you prefer Yarn:

```bash
yarn add carbon-components
```

You can include the grid in one of two ways:

```scss
// If you're including all the styles for Carbon
@import 'carbon-components/scss/globals/scss/styles.scss';

// If you're wanting to import the grid
@import 'carbon-components/scss/globals/grid/grid';
```

If you're hoping to use the 16 column variant of the grid, we recommend enabling the `grid-columns-16` feature flag before including any imports in your Sass files. For example:

```scss
$feature-flags: (
  grid-columns-16: true,
);

// If you're including all the styles for Carbon
@import 'carbon-components/scss/globals/scss/styles.scss';

// If you're wanting to import the grid
@import 'carbon-components/scss/globals/grid/grid';
```

If you're hoping to use the grid without including `carbon-components`, we offer the `@carbon/grid` package. You can install this with `npm`:

```bash
npm install @carbon/grid --save
```

Or, if you prefer Yarn:

```bash
yarn add @carbon/grid
```

You can then include the 16 column grid by doing the following in your Sass files:

```scss
@import '@carbon/grid/scss/grid';
```
