### ISSUE TITLE
Angular13 + Carbondesing datatable [stickyheader]="true" breaks layout

### ISSUE THREAD

**Issue by flor-cames** [carbon-design-system/carbon-website#2744]
## Summary
Hi all! I'm having an issue when trying to use datatable with expanse + sticky header
Everything works fine if stickyheader is set to false. But when I set it to true, the layout seems to broke.
I have a clean project with only carbon components and angular 13 installed. I don't have any additional CSS.
I wasn't able to fix it with css...
Has anyone face this issue before? I did everithing according to the official documentation.

Is this issue related to a specific component?
Yes datatable

What version of the Carbon Design System are you using?
 "carbon-components": "^10.53.0", * angular 13

`<ibm-table   [size]="'sm'" [model]="simpleModel"    [showSelectionColumn]="true" [stickyHeader]="false"
        [striped]="false" [isDataGrid]="false" >

</ibm-table>`

![nosticky](https://user-images.githubusercontent.com/98811749/154920780-2dfd3016-7fa6-42bd-8942-fb1a8dddbdd3.JPG)

![tablestickeheader](https://user-images.githubusercontent.com/98811749/154920812-f6e4f323-74de-4ac4-ae63-dabb0dc072c7.JPG)

**Comment by laurenmrice** [comment]
Hi @flor-cames would you mind submitting this issue in the [carbon-components-angular](https://github.com/IBM/carbon-components-angular/issues) repo? The carbon-website repo is for carbon website-related issues. I would transfer this issue myself but it is in a different org and I do not have access to move it. Thanks!
