### ISSUE TITLE
W3 Product design header type update

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#278]
Based on feedback to make the product design header more similar to the the language and digital leading space.

@alisonjoseph let me know if you have any questions. These fixed sizes are the closest we could get to match the language's fluid type and banner space size. 

- [x] remove 1px letter spacing (should be 0)
- [x] Remove "IBM" (keep it in the top left, though)
- [x] "Product Design" should be 300 weight (Our 300 seems a lot thinner than the language site's 300 for some reason?)
- [x] "Product Design" should be 122px (the size at the Xlg breakpoint for "Type J") 
- [x] Space should be 560px high
![Screen Shot 2018-10-17 at 2.37.06 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/c470032f-080c-4dc3-861d-ddff8cc30a74)

**Comment by alisonjoseph** [comment]
font looks the same to me now? 🤷‍♀️ 

<img width="1079" alt="screen shot 2018-10-17 at 7 01 36 pm" src="https://user-images.githubusercontent.com/2753488/47123056-1f051700-d23f-11e8-8fcf-9913dd3ec4cf.png">
<img width="1347" alt="screen shot 2018-10-17 at 7 01 29 pm" src="https://user-images.githubusercontent.com/2753488/47123057-1f051700-d23f-11e8-8d24-f0b21f1dc700.png">

**Comment by alisonjoseph** [comment]
btw. the font is showing as 138px on the Typeface header.
