### ISSUE TITLE
status indicator pattern tables are broken

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#2884]
The Status indicator pattern tables of icons and glyphs are broken. The column headers do not respond well at breakpoints. https://www.carbondesignsystem.com/patterns/status-indicator-pattern/

<img width="1196" alt="Screen Shot 2022-04-13 at 2 29 38 PM" src="https://user-images.githubusercontent.com/43969356/163246565-63500d0c-499d-45cb-8242-0a8d724b41a7.png">

**Comment by dakahn** [comment]
We had some faulty css precedence in the Gatsby theme. This PR should address the problem 🤠 https://github.com/carbon-design-system/gatsby-theme-carbon/pull/1242
