### ISSUE TITLE
Accessiblity checker:   The 'for' attribute must reference a non-empty, unique 'id' attribute of an <input> element

### ISSUE THREAD

**Issue by SrinivasUiDev** [carbon-design-system/carbon-website#2896]

**Comment by joshblack** [comment]
Hi there @SrinivasUiDev! 👋  Could you provide more information about what you're seeing from Accessibility Checker and how to re-recreate the issue?

**Comment by abbeyhrt** [comment]
We're going to close this due to no response, feel free to message us to re-open!
