### ISSUE TITLE
[CODEOWNERS] List of codeowners is out of date

### ISSUE THREAD

**Issue by jeffchew** [carbon-design-system/carbon-website#2897]
## Detailed description

> Describe in detail the issue you're having.

The list of folks in the `CODEOWNERS` file is out of date and should be updated:
https://github.com/carbon-design-system/carbon-website/blob/main/.github/CODEOWNERS

> What did you expect to happen? What happened instead? What would you like to see changed?

Should be updated to latest list of owners.

## Additional information

- We should figure out who should be the updated owners for some of these and add to this issue.

**Comment by sstrubberg** [comment]
@tay1orjones can we just delete this file? What purpose does it serve?
