### ISSUE TITLE
Create the Map doc under data viz section 

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-website#2903]
### **Project type**
Documenting a new Map pattern for Carbon under the Data Viz section. 

<br>
</br>

**Resource:**
Leverage the  Interactive Maps documentation from AI Application
https://pages.github.ibm.com/ai-applications/design/patterns/maps/overview/
Documentation: https://github.com/carbon-design-system/carbon-website/pull/2906

<br>
</br>

**Things to do** 
- [ ] Update images (Figma)
- [x] Clean up the written documentation 
- [ ] Review by the guild team 
- [ ] Review by the Carbon team

**Comment by aagonzales** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/System-Squad-593830641344b813db10934d/issues/carbon-design-system/carbon-website/2903?planning-poker) with ZenHub @laurenmrice @thyhmdo
