### ISSUE TITLE
Progress Indicator live demo not working as expected

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#2920]
The Progress Indicator live demo has an issue where changing a modifier will cause the component to disappear from the view. This is reproducible at: https://carbondesignsystem.com/components/progress-indicator/usage/ across browsers.

Most likely this issue is coming from a bug in the underlying playground logic when it is attempting to update the props of the component.

This issue is for addressing the issue so that the bug no longer occurs across browsers

**Comment by abbeyhrt** [comment]
Was fixed in https://github.com/carbon-design-system/carbon-website/pull/2933
