### ISSUE TITLE
Document design decisions: text-input 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#294]
Text-input design is solid. The design decisions are captured through out this issue https://github.com/carbon-design-system/carbon/issues/2329#issuecomment-523153733 It would be amazing if we never have to have this conversation again because we forgot things, eg. dropdown cannot have helper text below field, etc etc. I know I myself have forgotten this multiple times and wondered why don't we place the helper text below to be less obtrusive? 

What's the best way to document & present design decisions? FYI @janchild

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
