### ISSUE TITLE
[Icon size section] image showing text in `pt` but should be in `px`

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#2959]
## Detailed description

Icon / Usage / Sizing page, second image & its caption is showing type size labeled with `pt` instead of `px`. 
https://carbondesignsystem.com/guidelines/icons/usage#sizing

<img width="1133" alt="image" src="https://user-images.githubusercontent.com/15144993/170432885-e8c1443b-d81c-4b37-8f1a-bde9d080faf2.png">

1 pt = 1.333 px, so the units are not interchangeable. Correct caption should be: 

> 16px and 20px icons are optimized to feel balanced when paired with ~14pt~ 14px and ~16pt~ 16px IBM Plex. Use 24px and 32px when larger icons are needed.

**Comment by shixiedesign** [comment]
Please note, same issue in the IDL site: https://www.ibm.com/design/language/iconography/ui-icons/usage

**Comment by Kritvi-bhatia17** [comment]
Hi @shixiedesign! Good catch, and thanks for raising the issue.

The icon usage tab link has now been updated. Here's the [updated link](https://carbondesignsystem.com/elements/icons/usage/) where the necessary changes can be applied. The image has already been updated on the [IDL site](https://arc.net/l/quote/ronocmen), so we can use that image and update it in ours as well.
