### ISSUE TITLE
Bump node to v14/16 for carbon-website

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3032]
![Image](https://user-images.githubusercontent.com/15822070/177624234-e5a70c3e-c412-4bf4-8e08-6cb9b0c874ae.png)

**Comment by tay1orjones** [comment]
I already updated it to 16 in https://github.com/carbon-design-system/carbon-website/pull/2970

I'm not sure why it would be in this list. Maybe there's a separate config in the Vercel UI to specify which version is used?

**Comment by tay1orjones** [comment]
Unclear if this was actually still using v12. Found that the vercel UI had a spot to configure a version - that's what may have triggered the email.
