### ISSUE TITLE
[Typography]: code snippet background is white

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#3043]
Code snippet background is white and the page background is also white causing the type in the code snippet to look weirdly indented. You only see the gray 20 background on hover.

Desired behavior:

The ENABLED state of the inline code snippet should have a Gray 20 background.

<img width="1005" alt="image" src="https://user-images.githubusercontent.com/43144260/178590733-6dae0ea8-d7ee-48fc-b0d7-a4654e68c882.png">

**Comment by laurenmrice** [comment]
This has been resolved, going to close.
