### ISSUE TITLE
Date picker Usage and style information needs to be addressed

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon-website#3045]
This issue covers material additional to the two issues specifically opened up for Date picker https://github.com/carbon-design-system/carbon/issues/11805 and https://github.com/carbon-design-system/carbon/issues/11800

A review of the Usage and Style pages was carried out as part of an accessibility review. A number of design and implementation considerations for the Date picker component have been flagged in the [Date picker usage.pdf](https://ibm.box.com/s/d863av8pyed8pj7mwi3ck8oo1npf3t1m) and [Date picker style.pdf](https://ibm.box.com/s/69gitja8716wjikuwmmh6ufhyvme0c23) documents.

These should be opened in Adobe Acrobat Reader (not in a browser) so that all the comments, replies and markings on status can be reviewed. (Any comments that have been addressed through updates to the Accessibility tab are marked as Complete or Resolved).

There are over 50 comments in the Usage document alone, attesting to the variety of considerations necessary for this component, among them:

**Comment by aagonzales** [comment]
My notes on actionable task from Gowers PDFs

## Kits
- Add format by default in helper text (in addition to placeholder or remove placeholder?)


## Website 

**Content edits**
- Images
   -  Update all images with correct helper text placement.
   - Website: clarify variant vs type language (sub-variants are types)
- Intro paragraph:
    -  break apart into two sentences, one for date picker and one for time picker. Better clarity on variants. 
- Overview: 
    - The kind of date or time (exact, approximate, memorable) you request from the user will determine which picker (simple, calendar or time picker) is best to use.
    - When to use: break into two bullet points? (Instead of paragraph)
    - Variants/Calendar: say there are two types of calendar variants (single and range)
    - Hyperlink variant names
- Anatomy: 
    - add date format as a number, include in helper text or label area.
    - Day: Add link out to calendar variants for specific day type
    - Add weekday call out
- Sizes: calcify the sizes are for the input only. Calendar menu remains is a fixed size and does not change with input size.  (Example: show with calendar? Or maybe this is in the calendar variant section).
- Universal behaviors: 
    - Add warning state
- Simple date: when to use: when days of the week are irrelevant 
- Time picker: add time format 24hr vs 12hr and examples
- Modifiers
    - Remove light variant
- Related 
    - Using ind inputs: remove mention of time input, just for date

Style tab
 - Color: add “Day: start range”
 - Typography: add helper text, warning message, and placeholder

**Page structure**
- Combine time and calendar into one section - include general information
- Make time picker is own specific section - move any general content about time picker into that section (anatomy, content ect)
    - Date picker
        - Simple
        - Calendar
            - Single
            - Range
    - Time pickers



## Future fixes/enhancements for development 
- Menu should not open on focus, only opens with a keyboard arrow prompt or when the user interacts with the input with a mouse (similar to dropdown): https://github.com/carbon-design-system/carbon/issues/9865
- Menu should close when focus is removed
- Keyboard cannot interact with anything in the Month/Year control area 
<img width="359" alt="Start date" src="https://user-images.githubusercontent.com/11670886/182675756-84309d24-2155-4390-a570-0152c136b6ec.png">


### Future website
Style tab sections for layers (remove light modifiers from usage page)
