### ISSUE TITLE
Update UIShell header codesandbox examples

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-website#3063]
[Surfaced on slack](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1658926389760739?thread_ts=1658867672.367839&cid=C2K6RFJ1G), These examples need to be updated to use `@carbon/react`. Additionally, the last example needs to be updated to hide the hamburger/close button at large breakpoints. It currently is visible and does nothing since the sidenav is persistent at larger breakpoints.

**Checklist**
- [x] Update the examples to use `@carbon/react`
- [x] Fix the "[Header with sidenav](https://carbondesignsystem.com/components/UI-shell-header/code/#header-with-sidenav)" example to hide the hamburger button at large breakpoints

**Comment by tw15egan** [comment]
All examples have been updated to `@carbon/react`, which also resolved the redundant hamburger icon on the `Header with sidenav` example. I've set the theme to `g100` for all examples to keep the same look but can leave them as default white if we want. Going to close as resolved, though 👍🏻
