### ISSUE TITLE
Content partially covered by left menu in Firefox for Android 

### ISSUE THREAD

**Issue by pointout** [carbon-design-system/carbon-website#3089]
## Detailed description
The left menu is covering the content and makes it unreadable in Firefox for Android.

### What browser are you working in?
Firefox 103.2.0 for Android

## Additional information

![Screenshot_20220811-220358](https://user-images.githubusercontent.com/8960545/184427653-c156de22-60f9-4c30-8472-6a87b0189d1c.png)

**Comment by guidari** [comment]
Worrking as expected
Tested in the lastest version of Firefox in Samsung Galaxy S21 FE.
