### ISSUE TITLE
DefinitionTooltip docs on hover do not match implementation

### ISSUE THREAD

**Issue by tay1orjones** [carbon-design-system/carbon-website#3104]
DefinitionTooltip is unique in that it does not have the option to appear on hover. 

The documentation suggests otherwise:

https://github.com/carbon-design-system/carbon-website/blob/4a0433bfbf8b95186a8a96294ef03bde706617d7/src/pages/components/toggletip/usage.mdx#L71-L72

https://github.com/carbon-design-system/carbon-website/blob/4a0433bfbf8b95186a8a96294ef03bde706617d7/src/pages/components/tooltip/usage.mdx#L337-L340

We need to determine if
1. The implementation is correct and the docs are wrong.
2. The implementation is wrong and the docs are correct.

I think it's the docs that are wrong, but we should make sure by looking back on the flurry of activity on this component leading up to v11.

Checklist:

- [x] Determine if implementation or docs are incorrect
- [x] Depending on the findings, update the docs or update the implementation

**Comment by tw15egan** [comment]
@aagonzales should `DefinitionTooltip` be allowed to open on hover? It currently only opens with a click.

**Comment by tw15egan** [comment]
After talking with @laurenmrice, we should provide a prop allowing a user to open the `DefinitionTooltip` on hover while retaining all keyboard functionality.
