### ISSUE TITLE
[Content update]: Carbon Partners is out of date

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#3128]
There are people on this page who are no longer at IBM or serving in the positions that are listed.

https://carbondesignsystem.com/all-about-carbon/partners/

We need to make these updates:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/613d0e11-acfe-4671-a5b8-b2f2c413a659)

This section is OK as is:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/a52c2d7c-bdfb-4585-91ac-ef6ff6e83c28)

For the moment, until we re-establish it, let's just remove the Advisory section from this page.

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/e4b33b2e-b2b4-4e53-ad4d-b6dd780c1438)

**Comment by laurenmrice** [comment]
Closing, since we changed the [Partners page](https://carbondesignsystem.com/all-about-carbon/partners/) on our website to not include people's images and titles anymore.
