### ISSUE TITLE
Tertiary button color in dark theme

### ISSUE THREAD

**Issue by thefirstartist** [carbon-design-system/carbon-website#3169]
In Buttons, I see the tertiary button color is different from story book when I viewed it in dark theme. Is it a bug or a new design? I don't believe it passes the color contrast ratio requirement so I guess it's most likely a bug.

![image](https://user-images.githubusercontent.com/40870771/191822292-8b1fabdc-1c65-470d-ac44-09915f51aaa1.png)

**Comment by laurenmrice** [comment]
This has been fixed. We have updated our live demo for Button. https://carbondesignsystem.com/components/button/usage/#live-demo
