### ISSUE TITLE
Component index: Align tags and filters with new and changed internal IBM PAL sites

### ISSUE THREAD

**Issue by mzuliani-ibm** [carbon-design-system/carbon-website#3210]
## Detailed description

Internal IBM sites have renamed or merged. Component Index tags and filters are out of sync.

## Steps to reproduce the issue

https://carbondesignsystem.com/community/component-index/

1. Filter by tag

## Additional information

- AI Apps is now Sustainability Software 
- Cloud & Cognitive and Cloud PAL merged into Carbon for IBM Products
- URLs in data may also need to be updated

**Comment by alisonjoseph** [comment]
Component index was removed
