### ISSUE TITLE
Certificate of Originality contact needs to be updated

### ISSUE THREAD

**Issue by kellychurchill** [carbon-design-system/carbon-website#323]
https://www.carbondesignsystem.com/get-started/about-carbon/

On this page, the content for the Certificate of Originality refers to Daniel Kuehn. The contact person needs to be updated.

**Comment by alisonjoseph** [comment]
@mattrosno or @shinytoyrobots who should this contact be?

**Comment by mattrosno** [comment]
I'll take point in figuring out who this needs to be. May have to wait until next week when Robin is back in the office.

**Comment by kellychurchill** [comment]
This appears to be fixed. Closing
