### ISSUE TITLE
UI Shell Left panel guidance missing content, and other considerations

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon-website#3235]
This is a summary of considerations identified from reviews of the Usage and Style content. It provides information different from that described as  bugs for the component listed in https://github.com/carbon-design-system/carbon/issues/12323

- usage topic is missing Live demo, Interaction and References section
- the UI Shell topics are treated as a strange hybrid in the Usage introduction, yet are separate components in the Carbon guidance
- Style page seems to use the same image twice by accident

More details and minor considerations are captured as comments in the [Usage](https://ibm.box.com/s/ick511pn865vipo4ext4mfbu7jleux90) and [Style](https://ibm.box.com/s/damr9ftj6land0ubjj1s1oidca5p36ex) PDF exports.

In addition, a reviews of Figma's left panel shows that diagrams incorrectly use "link" where they are clearly demonstrating an expandable section. As per comments in UI Shell Header, Carbon needs to adopt the best descriptor for this component/behaviour and use it consistently throughout the header/left/right UI Shell material.
![image](https://user-images.githubusercontent.com/14298245/199346875-fe3da765-687c-47e6-96a2-b80e1bd5ce53.png)

**Comment by laurenmrice** [comment]
Closing this to separate the work for this out into two different issues. This issue will be cross-linked and referenced in the issues below:
- [UI Shell left panel: Usage tab](https://github.com/carbon-design-system/carbon-website/issues/3810)
- [UI Shell left panel: Style tab](https://github.com/carbon-design-system/carbon-website/issues/3811)
