### ISSUE TITLE
Dashboard pattern

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#330]
Gather existing dashboard templates or patterns and consolidate into an experimental Dashboard pattern

- [ ]  Look at any existing examples across BU's
https://pages.github.ibm.com/ibmcloud/pal/patterns/dashboard-widgets/usage/
https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/patterns/dashboard-configuration/

- [ ]  Create an outline for a Form pattern page.
- [ ]  Create any supporting images.

**Comment by janchild** [comment]
Decision in Dec 2019 Governance Team meeting not to pursue this topic for the time being.
