### ISSUE TITLE
Search pattern

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#331]
### Abstract
Pattern providing guidance and supporting illustrations for searching within web applications and websites. The guidance covers search's three lowest level distinctions.

Guidance should cover behavior and best practices for the three distinct levels of search:
- [x] Search with a menu item of results per character (no submit),
- [x] Search with a submit and a discrete page of results, or
- [x] Search with a menu item of results per character no submit but a call to action (“See all results”) that takes you to a discrete page of results

Existing guidance:
- [x] [Carbon search component](https://www.carbondesignsystem.com/components/search/usage)
- [x] [Carbon filtering component](https://www.carbondesignsystem.com/patterns/filtering)
- [x] [Watson Health](https://pages.github.ibm.com/Watson-Health/components/search/overview.html)
- [x] [Search pattern exploration](https://ibm.box.com/s/fq2c0qtwa8s8ece8jvqw04txnmut88vb)

### Development activity

- [x] Peer playback, Nov 18
- [x] Outline review with Chris Connors, Nov 18
- [x] SME review of structure (Alex Swain, Maui Francis), Nov 25
- [x] Accessibility review
- [x] Accessibility content drafted
- [x] Feedback from Peter Vachon, Dec 2
- [x] Feedback from Jeff Placer, Dec 3
- [x] Feedback from Diana Tran, Dec 4
- [x] Feedback from Brian Calder, Dec 8
- [x] Dev review with Alison Joseph, Dec 9
- [x] Images with Lauren Rice, Week of Dec 9
- [x] Move into branch, Dec 9
- [x] Image review with Jeannie, Dec 12
- [x] Submit to Governance Board for review, Dec 13
- [ ] Final content review and prep for posting, Dec 18

Work in progress can be viewed here: https://github.com/carbon-design-system/carbon-website/pull/672

**Comment by connor-leech** [comment]
Other IBM patterns:
* https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/68
* https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/20
* https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/40
* https://pages.github.ibm.com/Watson-Health/components/search/overview.html

**Comment by connor-leech** [comment]
https://carbondesignsystem-dw2587ktr.now.sh/patterns/search-pattern

Draft from WH

**Comment by connor-leech** [comment]
Most recent: https://carbondesignsystem.connor-leech.now.sh/patterns/search

**Comment by connor-leech** [comment]
### Path to completion

- [ ] Peer playback, Nov 12

- [ ] Outline review with Chris Connors, Nov 19

- [ ] SME review of outline (Alex Swain, Maui Francis), Nov 20

- [ ] Send for SME review to:

  - [ ] Alex Swain (Nov. 25)
  - [ ] Maui (Nov. 25)
  - [ ] Peter Vachon (Nov. 26)
  - [ ] Diana Tran (Nov. 26)
  - [ ] Luke Firth (Nov. 26)
  - [ ] David Levinson (Nov. 26)
  - [ ] Jeff Placer (Nov. 26)
  - [ ] Lisa Lurie (Nov. 26)

- [ ] Images with Lauren Rice, 12/02

- [ ] Dev review with Alison Joseph, 12/02

### Previews:

[Box](https://ibm.box.com/s/2kz6lrrk4hnulf1foso6gozx1q6cew5f)
[Live preview](https://carbondesignsystem.connor-leech.now.sh)
