### ISSUE TITLE
[Bug] Incorrect color values on the color usage tab

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#3314]
Some of the hover colors show old values. Double-check values across the board with[ elements preview](https://carbon-elements.netlify.app/themes/examples/preview-v11/). See [slack thread](https://ibm-studios.slack.com/archives/C2K6RFJ1G/p1671124706825469)
- White hover
- Gray 10 hover
- Gray 90 hover
- Gray 80 hover

Tasks
- [x] Audit color page
- [ ] Submit PR with updates https://github.com/carbon-design-system/carbon-website/pull/3345

**Comment by thyhmdo** [comment]
White 
`layer-hover` -> Change to `#e8e8e8`
`field-hover` -> Change to `#e8e8e8`

Gray 10 
`layer-hover` -> Change to `#e8e8e8`
`field-hover` -> Change to `#e8e8e8`

Gray 90 
`layer-hover-01` -> Change to `#474747`
`layer-hover-02` -> Change to `#636363`
`field-hover-01` -> Change to `#474747`

Gray 100 
`layer-hover-01` -> Change to `#333333`
`layer-hover-02` -> Change to `#474747`
`layer-hover-02` -> Change to `#636363`
`field-hover-01` -> Change to `#333333`
