### ISSUE TITLE
[Bug] Website incorrectly states that V11 is in Alpha

### ISSUE THREAD

**Issue by fbarroso24** [carbon-design-system/carbon-website#3327]
## Title line template: [Title]: Brief description
Navigating to https://v10.carbondesignsystem.com/whats-happening/v11-release/#release-faqs incorrectly states that `Carbon v11 release is currently in alpha release`.  See screenshot below.
![image](https://user-images.githubusercontent.com/8657768/210386895-5480c9fa-8160-4b55-b62d-7ab391d63f63.png)

**Comment by tay1orjones** [comment]
@aagonzales should we just remove this v11 release page from the v10 site? It's out of date and superseded by the actual v11/current website

**Comment by aagonzales** [comment]
Yeah I think its safe to just remove it from the v10 site. We need to then update a [link](https://v10.carbondesignsystem.com/whats-happening/releases/#carbon-v11) on the v10 "Releases" page to redirect to the [v11 site](https://carbondesignsystem.com/migrating/guide/overview/).

**Comment by sstrubberg** [comment]
<img width="895" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/15822070/485cc6ab-4c12-4cf1-8b64-61ecbc144d71">
