### ISSUE TITLE
Empty state pattern

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#333]
**Summary**
Pattern describes empty state anatomy and best practices for no data to display situations such as first time use and various errors. Also covers alternative approaches for empty states, including educational content and starter content. Some topics will be reference for future authorship.

**Link to preview:**
In staging: https://carbon-website-git-fork-connor-leech-2019-patterns-master.carbon-design-system.now.sh/patterns/empty-state-pattern

**Development activity**
- [x] Peer playback, Nov 12
- [x] Peer review / early SME review, Nov 19
- [x] Image requirements to Lauren
- [x] SME review of outline (Alex Swain, Maui Francis), Nov 19
- [x] Outline review with Chris Connors, Nov 19
- [x] Review with Watson Studio designer, Jolie Durand, Nov 20
- [x] Chris Connors' review, Nov 20
- [x] Image needs review (Jeannie)
- [x] Nicole Roppel, sent Nov 27 -- feedback incorporated
- [x] Luke Firth, sent Nov 25-- feedback incorporated
- [x] Alex Swain, Nov 25
- [x] Maui Francis, Nov 25
- [x] Scott Robinson, Jolie Durand, meeting Dec 3
- [x] Accessibility review 
- [x] David Levinson (post images), Dec 4
- [x] Laura Marshall, IBM Hursley, Dec 4
- [x] Dev review with Alison Joseph, Dec 2
- [x] Mike Abbink re layout guidance, Dec 3
- [x] Images with Lauren Rice, Nov 25-26, Dec 2
- [x] Move into branch (Jan & Connor)
- [x] Image review with Jeannie, Dec 5
- [x] Tom Waterton, IBM Hursley, Dec 4
- [ ] Diana Tran (post images) Dec 6
- [ ] Image refinement with Jeannie, Dec 9
- [ ] Table refinement with Connor, Dec 9
- [ ] Submit to Governance Board for review, Dec 6 (Jan)

![image](https://user-images.githubusercontent.com/44503588/69742486-7e9c4a00-1102-11ea-9cfc-e30df8750a1c.png)

----------
- [ ] Review the existing guidance around empty states in this issue https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/5

**Comment by chloepoulterdesign** [comment]
https://www.carbondesignsystem.com/experimental/empty-state-pattern is now published.

**Comment by janchild** [comment]
**Activity**

- [ ] Dev review with Alison Joseph, Nov 26

- [ ] Send for SME review to:
     - [ ] Nicole Roppel, Nov 25
     - [ ] Luke Firth, Nov 25
     - [ ] Alex Swain, Nov 25
     - [ ] Maui Francis, Nov 25

- [x] Review with Watson Studio designer, Jolie Durand, Nov 20
- [x] Outline review with Chris Connors, Nov 19
- [x] SME review of outline (Alex Swain, Maui Francis), Nov 19
- [x] Peer playback, Nov 12

**Comment by janchild** [comment]
Feedback from Luke Firth -- incorporated 

Luke Firth:truck: 5:14 PM
# Empty states patterns feedback:
Generally this is great and I agree with pretty much everything! :tada:
Here are my super nit-picking critiques:
- I feel with the stack of content there may be some room to condense and distill, there are a lot of sections in here, and I wonder about if a more simple approach would have benefit:
    1- Standard empty states are like X, with these elements and these do’s / don’ts.
    2- Special empty states due to situations like should reflect that and look like: (give examples for each - eg incorrect user permissions)
    3- These are alternatives to empty states you should consider based on X,Y,Z
- Separating out things like educational empty states from standard empty states mostly had me wondering - “why do we have both and when should I use one over the other - why not always educational?“ The use cases seem the same for first time use at least.
    - Feels to me like the logic could be that the primary resource on a page should get educational empty states, where secondary and other content gets standard in order to give as much support as possible to the core workflow, but keep the cognitive load of each page low.
- Alternatives to empty states was interesting - things like starter content. I’ve seen this a lot. I’d love some guidance on why / when these alternatives may make more sense than empty states. What considerations should someone use to determine which is right for them?
- I’ve seen carbon guidance that in general, we should aim to not centre align anything. Empty states are usually an obvious violation of this rule. I’d be interested in knowing if we plan on left aligning them vs keeping them centred.
- A specific example - empty tables.
    - Should containers like tables have a minimum height, so the empty state can be shown? Naturally a table will show the header and then the pagination immediately below if it has no rows. Is there guidance for this minimum height? Or should the whole table be replaced with a different container for its empty state? (Bad side of that would be that the column headers can be quite useful).
    - The primary action to populate an empty container, especially a table is usually the ‘add’ button for whatever resource will go in it. However, things like the table already have a positioned add button in the top right. Do we have a view on if this button should be hidden (well semantically moved to the empty state) or duplicated by the primary add action in the empty state?

**Comment by janchild** [comment]
Feedback from Nicole Rommel: 

https://app.mural.co/t/ibm14/m/ibm14/1574890817438/21b9a0d1237713ad4d8d9bd84f3fb5efcbad6af5

**Comment by Levinson1** [comment]
This is well done. It is very thorough and aligns closely with the ES pattern we had pushed to Carbon Experimental, referenced above by @chloepoulterdesign.
We have gone a step deeper to provide guidance for messaging and image use, but would not expect or even feel it appropriate, to have that specificity at this level.

**Comment by chloepoulterdesign** [comment]
I am hoping Laura Marshall (will try and edit shortly with her Github ID) to review this as she has been driving development of empty state since I put our Experimental version up.

**Comment by lauramarshallibm** [comment]
As @Levinson1 mentioned above, our team has gone further with providing default text for 4 of the different types of empty states, content reviewed by @tomwaterton. As the different types of empty state are clearly drawn out, it could be useful if everyone has some default text to work with. Not sure if its needed in this piece of work, but I am happy to share if is useful for anyone else.

**Comment by janchild** [comment]
Hi @lauramarshallibm, I agree that it would be great to have some default text, especially if reviewed by @tomwaterton. :) I'll reach out to you on Slack. Thank you!

**Comment by tomwaterton** [comment]
Hi @janchild - sorry, was out on an all-day Design Jam on Wed and out of the office yesterday.

Re this empty states pattern, Peter Loveland, Gregor Cowie, @lauramarshallibm and I did discuss different scenarios and came up with the following default text patterns:

### Approach
Empty states can occur for a number of reasons (see next section). 
While each of the scenarios is different, for each one the written content should follow this basic structure: 

- A mandatory heading 
- Sub-text: mandatory in some cases, optional in others, not needed in others.
- A call-to-action button in some case

### The different empty state scenarios

#### a) Deploying
_(Note: the generic loading state covers most situations. We've just included this particular scenario to cover the initial deployment of a new service.)_

- Heading: `We’re currently still deploying.`
- Sub-text: `When we’re finished, you’ll see your <variable> here. [Plus optional extra sentence to describe the resource here, if required.]`

#### b) API error

- Heading: `Uh oh. Something’s not quite working.`
- _(No need for any sub-text)_
- CTA button: [ `Try again?` ] _(Clicking this button would resend the request / refresh the view)_


#### c) No search results
- Heading: `Hmm, your search results didn’t return any results.`
- _(No need for any further text as this is a common user experience. Users know to return to the search box, etc.)_


#### d) There aren’t any objects yet

- Heading: `You don’t currently have any <variable>.`
- Sub-text: `[Optional extra sentence to describe the resource.]`
