### ISSUE TITLE
Add globalization support to website

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#334]
This might be something to tackle post-X, but would be great if we could support globalization for our core site. I think there are a couple of areas that we'd need to update in the project in order to support this, namely:

- Decide on a strategy for how to expose the language of the site
  - Most likely we could do `carbondesignsystem.com/<language>/...`
- Figure out a strategy for how to switch languages for the site
  - Most likely will need something to help detect locale and redirect
  - Should also provide a manual switcher similar to [Jest](https://jestjs.io/docs/es-ES/getting-started)
- Decide on how we want to structure our project to support globalization
  - Easiest path might be that each "leaf" folder where we have our md files has another layer, namely the language folder. For example `getting-started/developers/*.md` becomes `getting-started/developers/<language>/*.md`
- Update the gatsby config to create paths for these nodes to match what we decide on in the first bullet
- Add logic on client boot to suggest locale change, if appropriate.

**Comment by asudoh** [comment]
Ref: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Accept-Language
