### ISSUE TITLE
Add guidance for display of static/read-only dates

### ISSUE THREAD

**Issue by gcate** [carbon-design-system/carbon-website#3370]
Carbon provides localizable date components but does not make any recommendation about how static/read-only dates should be displayed. Because of this, some design teams are referencing [IBM Style](https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=measurement-dates-times) for guidance (which is to use a fixed date format).
It seems that if we have the tech to localize the the date entry field, we should also localize any static date display.
At a minimum I hope for some guidance like this:
>  We recommend that if you localize your date entry fields, then also localize any static dates that are shown in the UI

Our team uses [momentjs](https://momentjs.com/) for date localization and it provides multiple localized formats (long date, short date, etc. ) A bonus would be to include in Carbon what localized format to use in different situations.  Not sure if this kind of guidance would be too much but potentially something like this:
> ![image](https://user-images.githubusercontent.com/4819973/215185130-f4d53f0a-15d2-4855-8150-1b62e24e1b79.png)

**Comment by laurenmrice** [comment]
Hi @gcate 👋

This is good information about recommending how static/read-only dates should be displayed, but the Carbon team has decided this guidance should be added to the [IBM Style](https://ibmdocs-test.mybluemix.net/docs/en/ibm-style?topic=measurement-dates-times) website, not the Carbon Design System website.

When the Carbon team doesn't cover specific content guidance like this on the Carbon site, we direct people to the IBM Style website, which is the corporate reference for all IBM writers and editors. The IBM Style website goes into greater depth than our site on how to write different kinds of content for particular use cases, and adding this guidance to IBM Style would benefit everyone at IBM.

I would reach out to the #[ibm-style](https://ibm-studios.slack.com/archives/C015MLJEYTB) slack channel to ask someone to add this to their guidance on the IBM Style website.

**Comment by gcate** [comment]
Thanks @laurenmrice.  Sorry, I think I should of added a little more context when I wrote this.  
I did talk to @aagonzales about this and she asked me to open an issue.

**Comment by laurenmrice** [comment]
Hi @gcate 

After speaking with our devs about this, for the date picker component specifically, the Flatpickr accepts a date format prop that allows you to change how the date is displayed and accepts a locale prop that allows you to change the language of the calendar. Since we do have this functionality implemented in this component currently, we could add some additional general guidance for this in the [Content section](https://carbondesignsystem.com/components/date-picker/usage/#main-elements) on our date picker component Usage tab. 

I think any other specific content information around dates should be guidance added to the style council.

**Comment by gcate** [comment]
Thanks @laurenmrice.  I think that sounds good.  
Would the guidance would also mention localizing static date display? (dates displayed not using the picker?)
Also, if it's helpful, when you come up with the update, I would be happy to give input on it.
