### ISSUE TITLE
Assistance

### ISSUE THREAD

**Issue by Abeg-gettiat** [carbon-design-system/carbon-website#3379]

**Comment by sstrubberg** [comment]
hey @Abeg-gettiat, happy you found us! Here are some docs that will get you going.

- [React Tutorial](https://carbondesignsystem.com/developing/react-tutorial/overview/)
- [v11 Guide](https://carbondesignsystem.com/migrating/guide/develop#step-1:-install-@carbonreact)

Good luck out there!
