### ISSUE TITLE
Add color token $border-tile to color usage tab

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3388]
Add color tokens `$border-tile-01`,`$border-tile-02`, `$border-tile-03` color tokens to the [Color Usage tab table](https://carbondesignsystem.com/guidelines/color/usage).
- [ ] White theme
- [ ] Gray 10 theme
- [ ] Gray 90 theme
- [ ] Gray 100 theme

------

**Color token values**

`border-tile-01`
| White theme           | Gray 10 theme         | Gray 90 theme         | Gray 100 theme        |
| ------------------- | ------------------- | -------------------- | -------------------- |
| Gray 30 (#c6c6c6) | Gray 40 (#a8a8a8) | Gray 60 (#6f6f6f)    | Gray 70 (#525252) |

`border-tile-02`
| White theme           | Gray 10 theme         | Gray 90 theme         | Gray 100 theme        |
| ------------------- | ------------------- | -------------------- | -------------------- |
| Gray 40 (#a8a8a8) | Gray 30 (#c6c6c6) | Gray 50 (#8d8d8d)    | Gray 60 (#6f6f6f) |

`border-tile-03`

| White theme           | Gray 10 theme         | Gray 90 theme         | Gray 100 theme        |
| ------------------- | ------------------- | -------------------- | -------------------- |
| Gray 30 (#c6c6c6) | Gray 40 (#a8a8a8) | Gray 40 (#a8a8a8)    | Gray 50 (#8d8d8d) |

**Comment by sstrubberg** [comment]
Need to update the Figma kit

**Comment by laurenmrice** [comment]
@sstrubberg I've made a design kit issue for this in the carbon-design-kit repo [#650](https://github.com/carbon-design-system/carbon-design-kit/issues/650)
