### ISSUE TITLE
Accessibility section typos

### ISSUE THREAD

**Issue by tay-aitken** [carbon-design-system/carbon-website#339]
There are several typos throughout the Accessibility section

1. Overview > Main Categories of Disabilities > **popularity** is spelled incorrectly 
2. Color > Low vision > Obstructed visual field > **obstructed** is spelled wrong under visual deficiency

> What browser are you working in?
Chrome

**Comment by chrisconnors-ibm** [comment]
https://www.carbondesignsystem.com/guidelines/accessibility/overview

>Overview > Main Categories of Disabilities > popularity is spelled incorrectly

https://www.carbondesignsystem.com/guidelines/accessibility/color
>Color > Low vision > Obstructed visual field > obstructed is spelled wrong under visual deficiency

neither still in evidence
