### ISSUE TITLE
Toggle Live Demo Small Variant not rendering

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-website#3439]
## Detailed description

> Describe in detail the issue you're having.

When navigating to the Toggle docs in the carbon website and scrolling down to the live demo, the "small" variant story is not working

> What did you expect to happen? What happened instead? What would you like to see changed?

Expect Live Demo to correctly render small toggle [story](https://react.carbondesignsystem.com/?path=/story/components-toggle--small-toggle)

> What browser are you working in?

Google Chrome

## Steps to reproduce the issue

1. Go to https://carbondesignsystem.com/components/toggle/usage/#live-demo
2. Select "Small" variant
3. Notice story is blank

## Additional information

<img width="1203" alt="image" src="https://user-images.githubusercontent.com/40550942/225998623-2f15617a-4e16-4640-ae79-06d868e942e5.png">

**Comment by tw15egan** [comment]
I believe `ToggleSmall` was deprecated; it should be using a `Toggle` with the `size='sm'` prop set.
