### ISSUE TITLE
Progress indicator: Style tab

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3465]
**Ref issue:** https://github.com/carbon-design-system/carbon-website/issues/3362
**Ref boxnote:** [Style tab pdf](https://ibm.ent.box.com/file/1000664254853?s=thgdz6hr423lhdglr72c6hgtgb9i14xl)

## Style tab

- Michael Gower makes an interesting point about what if the completed circle icon is filled in blue with a checkmark instead of an outline to better match the current circle icon. If we choose to do this though we might want to consider changing the error icon to be filled as well.
<img width="873" alt="Screen Shot 2023-05-18 at 3 57 04 PM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/3a9a604c-1a8d-4b1c-8f1a-ab541dbf3255">

- Michael also suggests the icon gets wrapped in focus. 
<img width="889" alt="Screen Shot 2023-05-18 at 3 59 24 PM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/1ab7e8a9-a43d-46ff-acd2-ae9baf545c63">

**Comment by aubrey-oneal** [comment]
A PR has been opened to update the style tab to correct our naming convention and tokens. Note that some of the suggestions in this issue are for code-level changes to the component. A new issue will be opened for devs to explore.
