### ISSUE TITLE
Sketch Maintenance Mode: Site audit research

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3476]
#### Acceptance criteria

- [x] Determine where we talk about Sketch on the site
- [x] Reference the next site https://next.carbondesignsystem.com/designing/get-started
- [x] Playback to the team (probably just the designers will suffice)

**Comment by aubrey-oneal** [comment]
Sketch audit: https://airtable.com/appO4WUF5dDhJkMYx/tblj7m3Ll18YYoKZu/viwTFulsd91f81IEt?blocks=hide

Included are any mentions of Sketch that are on the Carbon site or platform. I've also included an index of all sketch files/plugins that are referenced. We will chat about next steps during design crit.

**Comment by aubrey-oneal** [comment]
Quick audit numbers (also available in this airtable summary)

- 20 pages to update on the [website](https://carbondesignsystem.com/). A total of 37 H2 sections. 
- 6 pages to update on the [platform](https://next.carbondesignsystem.com/). 11 pages will pull updates from the website 🤓
- 24 Sketch resources (libraries, plugins) need to have their status and maintainer updated
- Overall there is a lot of content BUT if we align on a few key phrases the rewrite will be faster. Let's workshop this!
