### ISSUE TITLE
Bug: Data Viz - color swatches missing

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#348]
On `Components > Data Viz > Overview > Color` the swatches are missing. They maybe didn't get ported over with the new website.

Here they are on v8: http://v8.carbondesignsystem.com/data-vis/overview/colors

**Comment by alisonjoseph** [comment]
I checked the latest version of the old website and they aren't there either. Weird. Anyway, I can copy them over from v8 👍
