### ISSUE TITLE
docs: update contained tab disabled state

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3493]
- [ ] Update the contained tab variant disabled state specs on the Style tab to the spec below.

---

**Spec**

<img width="842" alt="Frame 11" src="https://user-images.githubusercontent.com/43969356/230932394-37618e5b-39d0-42b5-ba8d-1b45ae14b9ca.png">

**Comment by kingtraceyj** [comment]
updated: https://carbondesignsystem.com/components/tabs/style#contained-tab-color
