### ISSUE TITLE
Work in progress is outdated

### ISSUE THREAD

**Issue by BCarley** [carbon-design-system/carbon-website#3509]
## Summary

The [Work in progress](https://carbondesignsystem.com/whats-happening/work-in-progress/) page is out of date.

The `TreeView` component listed in the `Components and patterns` navigates to https://carbon-website-git-fork-designertyler-treeview03092020-c-54d75e.vercel.app/components/tree-view/usage/. This is especially confusing as the `TreeView` component has been released so this makes searching for information on the component difficult.

## Relevant information

- Current documentation for [TreeView](https://carbondesignsystem.com/components/tree-view/usage/)

When navigating the user away from the main site, it is not always obvious that the action is taking the user to "external" documentation. This can lead to a frustrating experience when attempting to view the rest of the documentation.

**Comment by sstrubberg** [comment]
hey @BCarley, thanks for bringing this to our attention.

We're actually going to be sunsetting this page. If you want to stay up-to-date with what's happening, check out the Experimental section of [our Storybook](https://react.carbondesignsystem.com/?path=/story/getting-started-welcome--welcome). You can also check out our [Roadmap](https://github.com/orgs/carbon-design-system/projects/51).

**Comment by BCarley** [comment]
Thanks @sstrubberg! I figured it was just stale and need staking down so I thought it would be good to raise.
