### ISSUE TITLE
[Data viz] Dashboard best practices page

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#351]
Cognos shared existing guidance on dashboard best practices. We might be able to complete this page for October. 

From Anne Stevens: 
> Here’s the best practices guide we created internally.  Please treat it as a work in progress, especially the chart section.  See ‘Use ther Right Chart Type for the Data’ that starts on pg 30

Link to PDF: 
[Dashboard Design Checklist - v 1.00_AS.pdf](https://github.com/carbon-design-system/carbon-website/files/3627421/Dashboard.Design.Checklist.-.v.1.00_AS.pdf)

**Comment by shixiedesign** [comment]
## WIP design / content

![image](https://user-images.githubusercontent.com/15144993/65716133-27c3b700-e064-11e9-9dc8-274712be5f7d.png)

**Comment by aagonzales** [comment]
Completed.
