### ISSUE TITLE
Broken webpack config link, outdated getting started information

### ISSUE THREAD

**Issue by francinelucca** [carbon-design-system/carbon-website#3513]
## Detailed description

The "webpack.config.js" link in point 1 in this page https://carbondesignsystem.com/developing/frameworks/react/#getting-started is broken 
<img width="741" alt="image" src="https://user-images.githubusercontent.com/40550942/235242787-d8068f64-c0df-4b29-96a5-5dea9949c80b.png">

## Steps to reproduce the issue

1. Go here https://carbondesignsystem.com/developing/frameworks/react/#getting-started
2. Click on webpack.config.js link
3. Notice 404 error

## Additional information

<img width="1437" alt="image" src="https://user-images.githubusercontent.com/40550942/235242948-95cb67fb-7725-4ebd-945a-bc17fab72b00.png">

I think maybe it should link to here https://github.com/carbon-design-system/carbon/blob/v10/packages/react/webpack.config.js. But also is this information still true? is webpack still needed? I don't see this config file in `main`

**Comment by tay1orjones** [comment]
We need to update this whole page, there's lots of inaccuracies in that screenshot. Some thoughts on how we could approach this:

- Lean into the documentation on the react website about framework choices and setup https://react.dev/learn/start-a-new-react-project
- Mention how to configure styles properly with `@carbon/react`
- Potentially mention vite, parcel, and webpack
- What do other design systems have for getting started? Could we find some inspiration

Keep in mind that anything we link to (webpack docs, etc) could become out of date. Keeping it generic might be the best place to start.
