### ISSUE TITLE
Grid docs: Overview page

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3515]
#### Acceptance Criteria

REF https://www.figma.com/file/mtARocDBevZmtgEMjb1cJs/2x-grid-overview-updates?node-id=0-1&t=3lBAl6bvJUXpW7K4-0

## To do (see spec file above):
- [x] Remove resource section (there are currently no relevant Resource links
- [x] Update copy under Columns and rows > Fixed grid (it's highlighted)
- [x] Update caption under Vertical Rhythm Don't caption (it used to refer to Sketch)

_We removed the Max Plus breakpoint from this issue; it needs it's own work stream_

<img width="996" alt="image" src="https://user-images.githubusercontent.com/43144260/235681730-f1f69eaa-cab0-4e5e-a0ed-5b404642efe0.png">

**Comment by jeanservaas** [comment]
Figma file:

https://www.figma.com/file/mtARocDBevZmtgEMjb1cJs/2x-grid-overview-updates?node-id=0%3A1&t=YQEMZfO7e6XLD4I5-1

The three updates are highlighted in magenta.

Text for the second update (fixed grid)

> Fixed grid
> A fixed grid starts with a fixed unit size from the sizing scale, then tiles and wraps as needed, like text. To employ the 2x concept, once you’ve determined the original box size that you want to use, you can multiply it by two and so forth to create a layout.

Text for the third update (Don't caption)
> In Figma, always use “Auto width” in the Text panel to ensure the text box is fitting with the content. Spacer snaps to the text box.
