### ISSUE TITLE
Medium images: Suite of comms for .com v2 and v2 web components releases

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#3531]
## Summary:

Olivia has filled out a the image request form because they have a series of upcoming images needed for various betas, release canidates, and release announcements.

The hope is that @thyhmdo can create a series of repeatable elements that can be reconfigured and applied to all the images to make them feel a bit like a series — so she doesn't need to make a net new image for every single communication. This is very similar to what we did for the v11 release.

**Image creation request form:** 
https://ibm.ent.box.com/notes/1198232822537

The existing articles are linked in the image request

# Key dates

The first key date is May 22nd 

https://ibm.ent.box.com/notes/1183205585778

**Comment by thyhmdo** [comment]
**Questions**
- [ ] Explore different style vs similar style of V11 Core Carbon?
- [ ] On Platform, we have certain visual for both Core Carbon and Carbon IBM.com, do we want to explore that style also?
- [ ] Some of the articles in the series already have certain style, do we want to break away from that?
- [ ] What's the difference between May 19 vs May 24 sets?

**Next steps:** 
- [ ] Discuss with Jeannie and Olivia about the difference in Web Component and Carbon for IBM.com V2
- [ ] Determine the style for each series
