### ISSUE TITLE
Data Table Row Height

### ISSUE THREAD

**Issue by SpikedKira** [carbon-design-system/carbon-website#354]
## Detailed description

https://www.carbondesignsystem.com/components/data-table/style#structure states:
> The column header row .bx--data-table thead should always match the row size of the table.

However, the image directly below shows varying row sizes all with the same header size.

Additionally, the specification table lists the row sizes as defined by heights but the examples on this page: https://www.carbondesignsystem.com/components/data-table/code actually show that the row sizes are passively defined by text size and padding (allowing for multiple rows of text in a single cell to expand the row height)

Looks like the table needs to be revised to define padding instead of height and a new image is needed for the example.

## Additional information

![data-table-style-3](https://user-images.githubusercontent.com/9935157/65252789-2f60ea00-dabf-11e9-92a1-95ae877d555a.png)

**Comment by aagonzales** [comment]
This has been updated (awhile ago).
