### ISSUE TITLE
[Select] Update Select on the Storybook

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-website#3555]
**Task** : [Select](https://carbondesignsystem.com/components/select/usage) needs to be updated so that it's consistent with the new guidance on the website and Figma kit. 

See Blue text for question for dev
See text in Red box to see the outdated implementation

----

![Select spec](https://github.com/carbon-design-system/carbon-website/assets/77697351/d9d6cc54-7524-4615-9f89-0046f1afe015)

**Comment by tay1orjones** [comment]
Closing in favor of https://github.com/carbon-design-system/carbon/issues/13008
