### ISSUE TITLE
Menu: style tab

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3568]
### Acceptance criteria
- [x] Create content/image documentation for the menu primitive on the style tab.
- [x] Use the [content style template](https://carbondesignsystem.com/contributing/component/#style-template) to create documentation.
---

- Ref [WIP menu docs](https://github.com/carbon-design-system/carbon-website/files/11480936/Action.Menu.Redesign_.Guideline.%2B.Competitive.Analysis.pdf) from contributor, Ramona Sartipi. (DID NOT REVIEW THIS)

**Comment by Huixh111** [comment]
i
