### ISSUE TITLE
Carbon Tutorial Step-3, GraphQL query REPO_TABLE, fails with 502 

### ISSUE THREAD

**Issue by rcbell** [carbon-design-system/carbon-website#3571]
Step-3 of the Tutorial, https://v10.carbondesignsystem.com/developing/react-tutorial/step-3/#query, sets up the following gql query:
```
const REPO_QUERY = gql`
  query REPO_QUERY {
    # Let's use carbon as our organization
    organization(login: "carbon-design-system") {
      # We'll grab all the repositories in one go. To load more resources
      # continuously, see the advanced topics.
      repositories(first: 75, orderBy: { field: UPDATED_AT, direction: DESC }) {
        totalCount
        nodes {
          url
          homepageUrl
          issues(filterBy: { states: OPEN }) {
            totalCount
          }
          stargazers {
            totalCount
          }
          releases(first: 1) {
            totalCount
            nodes {
              name
            }
          }
          name
          updatedAt
          createdAt
          description
          id
        }
      }
    }
  }
`;

```
This fails in the POST to api.github.com/graphql with 502 Bad Gateway.
Using the GraphQL Explorer, the query failed in a similar manner, though the 502 wasn't surfaced there.   Only by removing the releases property,
```
   releases(first: 1) {
            totalCount
            nodes {
              name
            }
          }
```
was I able to get it to work.

**Comment by tay1orjones** [comment]
Hi @rcbell, thanks for reporting this. We fixed this as part of updating the tutorial for v11. The current version of the tutorial can be [found here](https://carbondesignsystem.com/developing/react-tutorial/overview/). Our intent is to deprecate/remove the v10 tutorial soon. Hope this helps shed some light on the situation
