### ISSUE TITLE
[Combobox unique value]: Update website docs with unique value

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3579]
## Acceptance criteria

- Update the Combobox portion of the Usage, Style, and Accessibility tab docs to reflect the new behavior of entering a unique value.
- Determine if it should be called "unique value" or "custom value". It should be the terminology that is the best practice or most widely known in the industry for this feature. Consult with dev.

----

# Usage tab
  
## Combobox

`### Custom value`
- [x] Add a new H3 section heading for entering a custom value. Initial ideas for this name is "Custom value", "Entering a custom value".
- [x] Add new content and images.

#### Keyboard
`Combobox:`
- [x] Add written guidance on how to handle keyboard interactions for this if needed in the combobox section.
     > Since the Keyboard Interactions section has now been moved from the Usage tab to the Accessibility tab, nothing new will be added under that section.

# Style tab
  - [x] Custom value: As far as I can tell, there are no visual differences we need to address on the Style tab for entering a custom value right now, it is more of interaction changes? Need to double check
  - Note: *Eventually there will be an exploration/design spec for improving the visuals of this experience in [this umbrella](https://github.com/carbon-design-system/carbon/issues/16102).

----

## Accessibility tab
- [x] Add written guidance for this under "Keyboard interactions" and provide and image.
- [x] Add written guidance for this under "Development considerations" if needed.
     > Taylor confirmed that there is no need to add any new content.
---

**PR**

- [x] Create PR
- [ ] PR review

**Comment by Huixh111** [comment]
i

**Comment by Kritvi-bhatia17** [comment]
After discussing with the team and reviewing industry standards, where both [Elastic](https://eui.elastic.co/#/forms/combo-box) and [Adobe](https://react-spectrum.adobe.com/react-spectrum/ComboBox.html#custom-value) refer to the feature as **'custom value'**, it seems to be the best choice, as it also aligns with our Storybook documentation.

**Comment by Kritvi-bhatia17** [comment]
[Figma file](https://www.figma.com/design/vAl09cHKWXatx399I6rIQ6/Combobox-(unique-value)?node-id=10-5429&node-type=section&t=8TeEOj3YEDP7jdlr-11)
