### ISSUE TITLE
Color Usage page: content switcher styles are broken

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#3593]
https://carbondesignsystem.com/guidelines/color/usage

<img width="1168" alt="Screenshot 2023-06-12 at 11 30 44 AM" src="https://github.com/carbon-design-system/carbon-website/assets/2753488/b41e3054-8675-41a4-b4d6-a684f016fb5b">

**Comment by tay1orjones** [comment]
I think this was due to the layout token issues we identified on the site last week. We've since rolled back and the site looks correct now.
