### ISSUE TITLE
Documentation sidebar not appearing well on edge screen

### ISSUE THREAD

**Issue by ALWISHARIFF** [carbon-design-system/carbon-website#3594]
![Screenshot_20230614-101407_Firefox.jpg](https://github.com/carbon-design-system/carbon/assets/50083809/a899e395-66d0-4ad3-af9a-7bd3eb61fa43)

This shows that the sidebar is not rightly designed

**Comment by tw15egan** [comment]
Does the page work as expected if you disable the edge screen feature? Does it work in Chrome / any other browser on your phone? I am not able to replicate using dev tools and setting it to a Galaxy S9+ in Firefox or Chrome.

**Comment by ALWISHARIFF** [comment]
![Screenshot_20230614-193506_Firefox.jpg](https://github.com/carbon-design-system/carbon-website/assets/50083809/74b92764-ecc0-4599-9a1e-7310698b49ad)

This is the browser I'm using I tried in a different browser works perfectly

**Comment by ALWISHARIFF** [comment]
![Screenshot_20230614-193937_Firefox.jpg](https://github.com/carbon-design-system/carbon-website/assets/50083809/5644ac5a-254c-4036-957c-8ad8d1259a35)

I updated and still the same

**Comment by tay1orjones** [comment]
We're not able to fix this right now because we're unable to reproduce. If anyone else is interested in trying to reproduce and fix, we'd appreciate it 🙏

**Comment by ALWISHARIFF** [comment]
Works well after the latest Firefox update
