### ISSUE TITLE
Extra guidance needed for Pagination

### ISSUE THREAD

**Issue by thefirstartist** [carbon-design-system/carbon-website#3608]
## Summary
Currently, the [Pagination guidance](https://carbondesignsystem.com/components/pagination/usage/) says:
- Generally, pagination is used if there are more than 25 items displayed in one view.

The provided guideline lacks clarity, leaving it uncertain whether pagination should be included in an empty table or when the total number of items in the table is only a few.

Given that pagination is primarily used in data tables, additional guidance is necessary to ensure consistent implementation across the platform by product teams.

## Sugested edit
Here are some suggested guidelines to consider:

1. Pagination is not necessary when the table is empty.
2. Pagination should be implemented dynamically, appearing only when the total number of items in the table exceeds the default number set by the user.

By incorporating these guidelines, we can ensure a more seamless and user-friendly experience with pagination across the platform.

**Comment by aagonzales** [comment]
Yes, this page is a known issue, and is one of the pages we still have marked for needing a major content update. It is being tracked over in this [issue](https://github.com/carbon-design-system/carbon-website/issues/2085). 

Leaving open for pagination umbrella issue.

**Comment by sstrubberg** [comment]
Closing in favor of tracking via #2085
