### ISSUE TITLE
Audit and Prototype content structure

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3609]
### Acceptance Criteria

- [x] Audit some other design systems of how they are organizing Menu, Combo button, Menu button, and Overflow menu
- [x] Create a prototype or content flow of how it would look like to bucket Combo button/Menu button/Overflow menu under a `Menu` umbrella using our template.
- [x] Playback findings of audit and prototype.

**Comment by thyhmdo** [comment]
After discussing with the design team, we decided to move forward with this direction:
- Build content for Menu including Menu only
- Build content for Menu buttons that including Menu button, Combo button, and Overflow button

----

Lingering concerns when starting to write the doc:
- Naming of Menu and Menu buttons (considering different types of menu) 
- Overflow menu --> Overflow button?
- Defining menu triggers within the system
