### ISSUE TITLE
Icon Library: Replace dumb quotes with proper quotes in search

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#362]
- [x] update with smart quotes

<img width="992" alt="Screen Shot 2019-09-19 at 3 13 37 PM" src="https://user-images.githubusercontent.com/32881239/65280283-a31de980-daf5-11e9-8dcc-f73baec27ec0.png">

**Comment by alisonjoseph** [comment]
confirmed this is fixed on Carbon and just merged the same fix on IDL so will be deploying shortly.
