### ISSUE TITLE
Incorrect Page Title 

### ISSUE THREAD

**Issue by TheAuthority** [carbon-design-system/carbon-website#3626]
## Summary
The page title for https://www.ibm.com/plex/specs/ is incorrect.  Specs is the 6th section on the site progress bar but the title says "05 Specs"

Also, nice IBM Plex logo in the `<head>`

## Relevant information

`<title>05 Specs | IBM Plex</title>`
should be
`<title>06 Specs | IBM Plex</title>`

**Comment by aagonzales** [comment]
![Image](https://github.com/carbon-design-system/carbon-website/assets/11670886/cae62361-36de-466e-93f9-270daa4b4443)
