### ISSUE TITLE
Popover - Wrong link out to React implementation

### ISSUE THREAD

**Issue by jagathgj** [carbon-design-system/carbon-website#3627]
The card link out to React storybook for Popover component in website redirects to the Search Component in storybook page instead of the popover component story.

Correct url: https://react.carbondesignsystem.com/?path=/story/components-popover--auto-align

> What did you expect to happen? What happened instead? What would you like to see changed?
Redirects to Search component in storybook page instead of the popover component story.

> What browser are you working in?
Chrome

## Steps to reproduce the issue

1. Go to https://carbondesignsystem.com/components/popover/code
2. Click on React resource card

<img width="473" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/29351394/4bb25376-ae21-4060-b68a-d20d7db5a64c">

3. Notice you're redirected to the search component storybook page instead of the popover component's story

## Additional information

- Please note that there is no default component story available for popover

**Comment by tay1orjones** [comment]
@jagathgj Thanks for reporting! I've got PR up to fix the link 👍
