### ISSUE TITLE
Structured list Live demo does not match storybook

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon-website#3632]
This is a new issue with structured list beyond that flagged in the [discussion on the row indicator icon and positioning](https://github.com/carbon-design-system/carbon/discussions/11506).

In the [live demo](https://carbondesignsystem.com/components/structured-list/usage/#live-demo) version of selectable structured list on the Usage page of the carbondesignsystem.com site, the table header takes focus. What is the rationale for this? It's not sortable. It's obviously not selectable. Seems like an error

Also, each of the rows is in the tab order (twice), which I think doesn't follow the documented interaction, since this is basically a radio button group. Obviously even if it WAS supposed to navigable by tab, each row should not require two presses of the `Tab` key

![image.png](https://zenhub.ibm.com/images/5cab73f442b8dc5ede7b84cc/bc030f80-1b20-46ac-9882-2c3c5f649f56)

NOTE: the [storybook implementation](https://react.carbondesignsystem.com/?path=/story/components-structuredlist--selection#storybook-preview-wrapper), neither oddity exists (header not navigable, single tabstop for list, with arrow movement between them)

## Steps to reproduce the issue

1. Open https://carbondesignsystem.com/components/structured-list/usage#live-demo
2. Change the Variant selector dropdown to "Selectable structured list"
3. Press Tab to enter the list and continue pressing to verify tab navigation for each row (and that 2 presses is needed to advance)
4. Shift+Tab to the table column header (top row) and confirm the header row takes focus.

**Comment by tay1orjones** [comment]
In the codeblock for this, there's a hardcoded `tabIndex` that needs to be removed. Not sure why that was added there in the livedemo
