### ISSUE TITLE
UI shell header: App switcher icon has a bug on website

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3638]
The App switcher icon is not spaced properly within the UI shell header. It currently looks too low. This also applies to the close icon which takes the place of the application icon when the panel is open.

<img width="1519" alt="Screenshot 2023-07-11 at 1 55 22 PM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/33b0ad58-401a-4a11-87c5-97d1f61b8081">

**Comment by alisonjoseph** [comment]
This was resolved with latest website dep updates.
