### ISSUE TITLE
[Data viz] Add "Develop" page

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#364]
# Add a page for developer getting started

Create this page according below design in draft branch (https://github.com/carbon-design-system/carbon-website/pull/287) and then Eliad will contribute updated content.

### Design: 

![Dataviz-develop](https://user-images.githubusercontent.com/15144993/65298250-6a4f3600-db30-11e9-84a1-62c5117ad935.png)

**Comment by shixiedesign** [comment]
@alisonjoseph Is this something you can help add? Placeholder content is okay, and Cameron's intent for those code snippets are "editable code" but we don't have that, so I think we should just put images (screen grabs) + simple code snippets for those. 

Once we have it Eliad can add the real code snippets and appropriate screenshots.

**Comment by alisonjoseph** [comment]
Empty pages and nav have been added!

**Comment by alisonjoseph** [comment]
@theiliad is content for these pages something you can help with? there is a `data-viz` branch we've been working off of and pushing to.

**Comment by theiliad** [comment]
Yeah definitely @alisonjoseph. I'll take care of that page. Overall I can take care of the dev pages, and some design ones if we need to do that

**Comment by alisonjoseph** [comment]
Awesome, thanks @theiliad! you can see where we're at here https://github.com/carbon-design-system/carbon-website/pull/287 

preview link - https://carbon-website-git-data-viz.carbon-design-system.now.sh/data-visualization/overview/chart-types

**Comment by alisonjoseph** [comment]
@theiliad do you have a time frame of when you'll be able to get this content added?

**Comment by theiliad** [comment]
Hey, hopefully tomorrow I'll push that page. Our target code freeze is still Friday right? I'll have that page before then for sure

**Comment by alisonjoseph** [comment]
Yep, by Friday is great! thanks

**Comment by shixiedesign** [comment]
Done & merged! 🎉 See https://github.com/carbon-design-system/carbon-website/pull/287/commits/cd7f07e6f767b473d4c460cfc8fd5045a22596a9
