### ISSUE TITLE
Data table: live demo shows incorrect type token and alignment in expandable row

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3650]
The data table live demo on the usage tab shows an incorrect type token and alignment for the text in the expandable portion of the row. It should be updated with what we have in the [React storybook](https://react.carbondesignsystem.com/?path=/story/components-datatable-expansion--default). 

Note: I also have an issue against the react storybook for type alignment issues. Ref:[ #14240](https://github.com/carbon-design-system/carbon/issues/14240)

<img width="782" alt="Screenshot 2023-07-18 at 4 04 48 PM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/ce1157fb-ea87-49fe-90ef-97a9a2eec420">

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
