### ISSUE TITLE
Figma theme variables: Medium article

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3653]
Discuss ideas for a medium article about implementing Figma variables into our libraries.

This can be a brief article illustrating that Config dropped these new variables, which is how you have introduced these to the Carbon library. We can also discuss the benefits of including these variables, etc.

- [x] Develop a basic outline of what we want to cover in the article
- [x] Write article content
- [x] #3666
- [x] Make gifs/images to put inside article content
- [x] Review
- [x] Publish

**Comment by laurenmrice** [comment]
Discuss with Juan first to come up with an outline. Have a meeting scheduled for Wed, Aug 2.

**Comment by aagonzales** [comment]
https://github.com/carbon-design-system/carbon-website/assets/11670886/5107cbeb-08dc-4fbc-a69b-b1583b453683

**Comment by aagonzales** [comment]
Done! https://medium.com/carbondesign/introducing-figma-variables-and-a-consolidated-all-themes-library-d4893d1b8920
