### ISSUE TITLE
docs: add missing support color tokens to the token table

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3683]
## Acceptance criteria

**Add missing support color tokens**
- [x] The `$support-caution-major`, `$support-caution-minor`, and `$support-caution-undefined` color tokens need to be added to the tokens table on the Color page > Tokens tab. These are the values per theme below.

<img width="1117" alt="image 17" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/5949a587-2afb-4e51-824d-79f7dc4036e3">

**Change existing color value**
- [x] Change the [$primary-button-hover](url) color to the correct value that we use in [Code](https://react.carbondesignsystem.com/?path=/story/components-button--default) and in [Elements](https://carbon-elements.netlify.app/colors/examples/preview/). The value for all of them themes should be Blue 60 hover: #0050e6

**Comment by Kritvi-bhatia17** [comment]
This has been fixed in this PR #4193!
