### ISSUE TITLE
Caption support for Carbon Website "Image" component

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#370]
Currently, the image component doesn't support captions. We are forced to manually create captions in MD: ![image.png](https://images.zenhubusercontent.com/5ba146414b5806bc2be8c046/0131ab53-773b-44c9-8efc-8378117cc1b1)

Can we integrate the caption into the component itself, so that if changes are made in the future at the component level, the caption won't have to be addressed separately and manually?

**Comment by claycrenshaw** [comment]
@alisonjoseph Do you know if this is duplicated in any other issues?

**Comment by alisonjoseph** [comment]
dev work being tracked here for image component https://github.com/carbon-design-system/carbon-website/issues/683
