### ISSUE TITLE
Menu buttons: Style tab

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3701]
## Acceptance criteria
- [x] Create Style tab content/images for the Combo button and Menu button.
  - Use the [content style template](https://carbondesignsystem.com/contributing/component/#style-template) to create documentation.

----

- Ref existing PAL docs for Combo button and Menu button:
  - [Sustainability PAL](https://pages.github.ibm.com/ai-applications/design/components/buttons/usage)
  - [Carbon for IBM Products PAL](https://pages.github.ibm.com/cdai-design/pal/components/button-guidance/menu-and-combo-buttons/)

**Comment by Huixh111** [comment]
o
