### ISSUE TITLE
Replace live demo with storybook live demo from platform

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#3709]
```[tasklist]
### Tasks
- [x] Move https://github.com/carbon-design-system/carbon-platform/tree/main/packages/mdx-components/src/main/storybook-demo to website repo
- [x] Add to all component Usage and Code pages
```

**Comment by tay1orjones** [comment]
@alisonjoseph I'm 50/50 honestly, whichever you'd prefer.

Maybe someone else has a solid reason for one vs the other, but my first thought is it would be more work to get it into the gatsby theme first. On the flip-side, it might be easier to maintain in the long term w/ the simple(r) environment of the gatsby theme source and example site. I'm honestly not sure if other teams would take advantage of it.

**Comment by alisonjoseph** [comment]
@tay1orjones I'm 50/50 also, I think I'll just bring it into the website, will be simpler/faster, if another team asks for it, it wouldn't be too hard to move it out into the theme later.
