### ISSUE TITLE
[tooltip] live demo has bugs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3712]
**Tooltip live demo bugs**

- The Live demo example on the [usage page](https://carbondesignsystem.com/components/tooltip/usage#live-demo) makes no sense. When the focus lands on the i icon, nothing happens. Then I tab again, and focus remains on the 'i' and suddenly it has a tip. Focus should immediately trigger the tip to appear.

- In the same Live demo section, changing the Variant selector to be definition tooltip also shows an implementation problem. The definition never appears on focus/hover but instead appears exclusively on click/activate. It is implemented as a TOGGLETIP instead of as a tooltip.
  - This implmentation should be optional and not the default interaction which will be fixed with issue [#12921](https://github.com/carbon-design-system/carbon/issues/12921), but it should still be accurate in the live demo.

**Comment by alisonjoseph** [comment]
Replaced with storybook demo https://github.com/carbon-design-system/carbon-website/pull/3716
