### ISSUE TITLE
More information is needed for CodeSnippet

### ISSUE THREAD

**Issue by barbj** [carbon-design-system/carbon-website#3717]
## Summary

No information is given about how to achieve any option for `CodeSnippet` except `single`.

## Relevant information

On https://carbondesignsystem.com/components/code-snippet/usage/ , what are the `type` options for `CodeSnippet`?

There's this:
![image](https://github.com/carbon-design-system/carbon-website/assets/24277731/ba60accd-8719-44f0-a92c-71c681da3cf5)

But this example is on the page:

`<CodeSnippet type="single">node -v</CodeSnippet>`

It would help to give information about how to use the tag instead of making you guess.

**Comment by Huixh111** [comment]
o

**Comment by sstrubberg** [comment]
hey @barbj You can view all the different variants of CodeSnippet in our Storybook.

https://react.carbondesignsystem.com/?path=/docs/components-codesnippet--overview
