### ISSUE TITLE
[Slider] Two Handles Defining the Range: website docs

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3730]
@KevinCamelo

### Usage tab
- [x] Update content and images
- [x] Get design review

### Style tab
- [x] Update content and images
- [x] Get design review

### Accessbility tab
- [x] Update content and images
- [x] Get A11y review

**Comment by KevinCamelo** [comment]
Hello @sstrubberg. I've done a pass at updating the usage and style documentation for range slider. Here is the work (Figma file for now pending any needed changes).

https://www.figma.com/file/Jk3pWNBG6ZWIRoldq2tM1x/Range---Slider-Enhancement?type=design&node-id=824%3A5164&mode=design&t=7NHqXCrz8XhGbmdi-1

As for the accessibility page, is there anyone I can work with to get that to a good point?

**Comment by tw15egan** [comment]
@mbgower, any pointers you can give @KevinCamelo on what we should call out for the two-handle slider on the Accessibility page?

**Comment by tw15egan** [comment]
Great idea 👍🏻

**Comment by sstrubberg** [comment]
[Usage Documentation](https://www.figma.com/file/Jk3pWNBG6ZWIRoldq2tM1x/Range---Slider-Enhancement?type=design&node-id=829-36904&mode=design&t=7NHqXCrz8XhGbmdi-4)
[Style Documentation](https://www.figma.com/file/Jk3pWNBG6ZWIRoldq2tM1x/Range---Slider-Enhancement?type=design&node-id=829-105118&mode=design&t=7NHqXCrz8XhGbmdi-4)
[Component Build](https://www.figma.com/file/Jk3pWNBG6ZWIRoldq2tM1x/Range---Slider-Enhancement?type=design&node-id=824-7675&mode=design&t=7NHqXCrz8XhGbmdi-4)

**Comment by KevinCamelo** [comment]
Works with me! @mbgower I'll cook something up and hopefully it will be close. Will share soon.

**Comment by Huixh111** [comment]
o
