### ISSUE TITLE
Website docs: Champions section

### ISSUE THREAD

**Issue by aubrey-oneal** [carbon-design-system/carbon-website#3753]
We plan to display names of Carbon champions on the /contribute/get-started/ page. Here's why:

Carbon is IBM’s open source design system for products and digital experiences and the system consists of working code, design tools and resources, human interface guidelines, and a vibrant community of contributors. Because we rely so heavily on contributors, we have a Carbon champion program where we celebrate folks that have made a significant impact on the design system. Right now, we simply post in slack or mention these names in quarterly calls. But our hypothesis is that by displaying their names on the website, winners will feel more gratification for their work and this will also encourage others to contribute.

This is the [prototype of our new contribution page](https://carbondesignsystem-git-fork-aubrey-fd4a89-carbon-design-system.vercel.app/contributing/get-started/#carbon-champions) where we will display carbon champion names.

- [x] Draft consent form
- [x] Get form reviewed by Bill Chan in legal
- [x] Add form to [airtable](https://airtable.com/appOVMXJWJgb6dwhX/tblHFlEESn3dqumFn/viw8ZHWRoiQqZvLgm?blocks=hide)
- [x] Collect signature
- [ ] Update contribution/get-started page

**Comment by Huixh111** [comment]
o

**Comment by aubrey-oneal** [comment]
Completed draft received fro Bill:


Here is the draft consent language, where I’ve modified the language you have provided earlier:


I consent that International Business Machines Corporation (“IBM”) can display my first and last name (“Name”) on the Carbon Design System website, [carbondesignsystem.com](http://carbondesignsystem.com/), without charge or compensation and can choose whether or not to display my Name.  I understand that more information on IBM’s processing of my personal data can be found in the IBM Privacy Statement https://www.ibm.com/privacy/us/en/. I also understand I may withdraw my consent to the above use of my personal data by reaching out by email to IBM at [custref@us.ibm.com](mailto:custref@us.ibm.com) or by contacting the Carbon team at [carbon@us.ibm.com](mailto:carbon@us.ibm.com).

 

I am at least 18 years of age and have full authority provide the above consent and permit use of my Name to IBM. If any provision of this consent is found to be unenforceable at law, the remaining provisions shall survive and remain in full force and effect. This consent shall be governed by the laws of the State of New York.

 

[] I agree [] I do not agree

 

[INSERT FIELD FOR PERSON TO TYPE IN NAME]

 

Please review the language and let me know if you have any questions, comments, or if you want any changes to the text.  I am assuming that someone is monitoring the [custref@us.ibm.com](mailto:custref@us.ibm.com) and the [carbon@us.ibm.com](mailto:carbon@us.ibm.com) email addresses to monitor for any consent withdrawals, and that your team has a process to take action on any consent withdrawals to make sure that the name/personal information usage ceases when the consent is withdrawn.

 

I am assuming that this consent language will be displayed conspicuously and not buried in other text (we want to make sure that the person can view the consent and assent clearly) for the third party person to review.  I also suggest inserting a field after the I agree/I do not agree tick boxes for the person to type in their name so that you can track who has given the consent. 

 

I look forward to hearing from you.  Thank you for your time and attention to this matter.

**Comment by aubrey-oneal** [comment]
Final airtable links:
[Live form](https://airtable.com/appOVMXJWJgb6dwhX/shrty3dmUCTKzjSRh)
[Results](https://airtable.com/appOVMXJWJgb6dwhX/tbl3lP11AWB0vfRcC/viw9Rx3jMc8vDvmFo?blocks=hide)
