### ISSUE TITLE
[CLA] Design page flow and get content pass

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#376]
Ref issue: https://github.com/carbon-design-system/issue-tracking/issues/9

- [x] Design pages
- [x] Content pass
- [x] We have all requirements to develop

## Page flow: ##
1. Github bot prompt with link

2. Landing page CLA 

3. Branch to Form for Individual or Corporation

4. Success page after submission and link to github to get started.

Sketch file box link : https://ibm.ent.box.com/folder/66831561872

**Comment by mattrosno** [comment]
![cla-flow](https://user-images.githubusercontent.com/1691245/65449725-28104800-de01-11e9-8fb9-5766fccf7551.png)

This flow diagram assumes we have a backend called "Carbon Platform" used to save CLA submissions and contributor data, a Carbon GitHub App that has a GitHub Status Check that we can install to our organization and use in our repositories, and CLA forms in the Carbon Website that posts submissions to the platform.

Conceptually, does this make sense @joshblack @laurenmrice @connor-leech?

**Comment by vpicone** [comment]
@mattrosno @laurenmrice is this still ongoing?

**Comment by joshblack** [comment]
Gonna close this out in favor of: https://github.com/carbon-design-system/carbon-dco
