### ISSUE TITLE
Bug: experimental date picker calling wrong menu on website.

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#376]
Experimental Date Picker menu is not correct. Not sure why its not calling the correct one. It was correct in the dev environment. 

![image](https://user-images.githubusercontent.com/11670886/48227829-0fbe4880-e369-11e8-8ce7-1220e8ebcec6.png)

Should be: 
![image](https://user-images.githubusercontent.com/11670886/48377686-0f3cef00-e694-11e8-8ab1-050b826e0652.png)

**Comment by alisonjoseph** [comment]
@asudoh can you help fix? I think this is the same issue we had with tooltip?

**Comment by aagonzales** [comment]
The menu is right but there are still some bugs with it:
- year is getting cropped weirdly 
![image](https://user-images.githubusercontent.com/11670886/48429495-ecade300-e732-11e8-9d40-9f3e7836f084.png)

- focus borders are not rendering evenly 
![image](https://user-images.githubusercontent.com/11670886/48429522-fdf6ef80-e732-11e8-8f26-7415d77b08a3.png)
![image](https://user-images.githubusercontent.com/11670886/48429539-0a7b4800-e733-11e8-91a6-d237742a636c.png)

- selected days not rendering properly 
![image](https://user-images.githubusercontent.com/11670886/48429574-1cf58180-e733-11e8-8b79-483f478c7343.png)

- Menu not showing full length of month
![image](https://user-images.githubusercontent.com/11670886/48429647-2bdc3400-e733-11e8-930a-a0adb7a66ff4.png)


**What it should look like:**
(correct in dev staging)

![image](https://user-images.githubusercontent.com/11670886/48429723-51693d80-e733-11e8-8052-9a4f96a64a8e.png)
