### ISSUE TITLE
[Menu buttons] create content for the Accessibility tab

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3797]
### Acceptance criteria
- [x] Create content for the Accessibility tab using the [Accessibility template](https://carbondesignsystem.com/contributing/documentation/#accessibility-template)
- [x]  May need to change the Heading hierarchy of this page to better suit the different menu buttons variants (Combo button / Menu button / Overflow menu)

**Comment by alina-jacob** [comment]
[Figma link](https://www.figma.com/design/9J3QEJ717fLUa7tzlWVMMu/Usage-and-Style-images?node-id=2576-32742&t=yg2sOx6yAFrKkbDx-4)
