### ISSUE TITLE
docs: add character count content to text input docs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3807]
## Acceptance criteria
- We offer the character counter for Text input in code as an optional prop, but we don't have this in our guidance on the website. We need to add it to our website docs.

### Usage tab
- [ ] Add this to the [Modifiers > Character counter section](https://carbondesignsystem.com/components/text-input/usage/#character-counter) and reference we have it for both text area and text input.
- [ ] Update the Character counter image to show both the text area and text input with character counter.

### Style tab

- [ ] Add a structure image for the text input to show the spacing specs of the character counter in the [Structure section](https://carbondesignsystem.com/components/text-input/style#default-text-input-structure)

**Comment by sstrubberg** [comment]
Close via https://github.com/carbon-design-system/carbon-website/pull/3842
