### ISSUE TITLE
"Tile links" on home page are too verbose in screen readers

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon-website#381]
## Problem 1

There are 6 links in section 2 of the [Carbon home page](http://www.carbondesignsystem.com/) that have very long link text (because the paragraph of content inside the anchor is being used for the link text by default). This is problematic for screen reader users who are using a screen-reader-generated list of links to navigate.

![image](https://user-images.githubusercontent.com/3331913/48237158-6fc9e480-e393-11e8-8756-ab82fb07f00c.png)

## Fix 1

Move the `aria-label` on the paragraph up into the anchor. The resulting link text works much better as the name for a link...

![image](https://user-images.githubusercontent.com/3331913/48237470-be2bb300-e394-11e8-95a9-b9e8a9bad0f0.png)

## NVDA's list of links showing Fix 1 for the "Carbon Design Kit" link

- You can get this dialog in NVDA by typing `Ins+F7`.
- A similar dialog exists for VoiceOver in Safari, which you can get with `Ctrl+Option+U` and then `right arrow` to see the list of links.

![image](https://user-images.githubusercontent.com/3331913/48285416-8b36fd00-e430-11e8-85d8-a10853604045.png)

## Problem 2 and Fix 2

...but now the paragraph of content is no longer read when tabbing through the links...
so mark the paragraph up as the _description_ for the link using `aria-describedby` so that it will be read...

![image](https://user-images.githubusercontent.com/3331913/48285157-ac4b1e00-e42f-11e8-8eeb-db48b25fae3d.png)

## Problem 3

...but a sighted voice control user (for example, using Dragon Dictation) will still have a problem activating the link because the user will say "Click Carbon Design Kit" and the link won't activate because its label is actually "Design Kit on Github". Note that the link _will_ activate _if the first part of its label matches what the user says_, so if we change the label to "Carbon Design Kit on Github" then it will work perfectly.  :)

## Fix 3

![image](https://user-images.githubusercontent.com/3331913/48286799-c3d8d580-e434-11e8-866e-c876bce20759.png)

## Summary

Please fix 1, 2, and 3 for all 6 of the links.

**Comment by alisonjoseph** [comment]
closing as this is related to v9 site
