### ISSUE TITLE
Navigation on Carbon site losing scroll position

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#382]
When using the left nav, if I have to scroll to see the item I want, I would expect that scroll position to remain consistent when I click on a link. Instead, the nav scroll position resets on each page, requiring me to scroll again to see the page I am on in the nav. See attached.

[Screen Recording 2018-11-12 at 2.45.45 PM.zip](https://github.com/carbon-design-system/carbon-website/files/2573560/Screen.Recording.2018-11-12.at.2.45.45.PM.zip)

**Comment by alisonjoseph** [comment]
Going to close this as won't fix since we are updating the website to use the new UI Shell component directly and wouldn't make sense to try and figure this out when we are in the middle of updating it.
