### ISSUE TITLE
Suggestion for Component Status page

### ISSUE THREAD

**Issue by carmacleod** [carbon-design-system/carbon-website#383]
It would be nice to have a pill for "Accessible" on the Component Status page: https://www.carbondesignsystem.com/components/component-status

The "Accessible" pill's status could be based on the Component passing automated, manual, and screen reader tests.

(If there is no space for the new pill in the Component Status table, maybe consider deleting the "Updated" pill? It doesn't seem all that useful now, because all Stable components have Updated?)

**Comment by alisonjoseph** [comment]
Linking to this issue where there is some design work on re-working this page being done already. Thanks for the suggestion! https://github.com/carbon-design-system/carbon-website/issues/58

**Comment by joshblack** [comment]
Going to close this one out due to inactivity! Separately, it seems like our status page may have been nixed in a previous update :eyes:
