### ISSUE TITLE
Component Accessibility Status: Table on Accessibility tab

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#3848]
#### Acceptance Criteria

- Build a custom component that can be leveraged on every component's accessibility tab's page.

![image](https://github.com/carbon-design-system/carbon-website/assets/15822070/df4f6938-a427-455f-8e9c-ecbee66300b0)

**Comment by tay1orjones** [comment]
Can be based off this exploration I have open https://github.com/carbon-design-system/carbon-website/pull/3735/files
