### ISSUE TITLE
[Broken link] Carbon for IBM.com

### ISSUE THREAD

**Issue by oliviaflory** [carbon-design-system/carbon-website#3856]
## Detailed description

The link to the Carbon for IBM.com website on the Carbon ecosystem page is 404ing, the URL is outdated

Correct URL: https://www.ibm.com/standards/carbon/

## Steps to reproduce the issue

1. Go to the All about Carbon / [The Carbon ecosystem](https://carbondesignsystem.com/all-about-carbon/the-carbon-ecosystem/#ibm.com) page
2. Scroll to IBM.com
3. Click card

## Additional information

<img width="1574" alt="Screenshot 2023-12-22 at 4 27 08 PM" src="https://github.com/carbon-design-system/carbon-website/assets/45692622/3d2aadb6-80f4-4fea-ad6c-6ca27b4f505a">

<img width="1578" alt="Screenshot 2023-12-22 at 4 32 54 PM" src="https://github.com/carbon-design-system/carbon-website/assets/45692622/80917f6c-9aeb-416d-9baa-dab7441515ae">

**Comment by shubhusion** [comment]
Kindly assign this issue to me @oliviaflory

**Comment by aubrey-oneal** [comment]
This issue was already resolved.
