### ISSUE TITLE
HOW TO REMOVE footer 8bar LOGO

### ISSUE THREAD

**Issue by ansonng30** [carbon-design-system/carbon-website#3868]
8bar logo at bottom edge
How to change it?

**Comment by laurenmrice** [comment]
Hi @ansonng30 could you please provide some more information with supporting screenshots with what you are trying to do.

Are you referring to how to manipulate the footer component to not have the 8bar logo like in this scenario?
<img width="1622" alt="Screenshot 2024-01-08 at 1 38 04 PM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/497942fb-fc02-442b-bfcc-9e66339cee39">

**Comment by tay1orjones** [comment]
Right now this isn't directly configurable, you'd need to [shadow the footer](https://gatsby.carbondesignsystem.com/guides/shadowing).
