### ISSUE TITLE
Focus states of 'Dropdown' component are inconsistent between documentation, live demo and production code

### ISSUE THREAD

**Issue by Jonathan-Bruckbauer** [carbon-design-system/carbon-website#3874]
## Detailed description

> Describe in detail the issue you're having.

Focus states of 'Dropdown' component are inconsistent between documentation, live demo and production code.

Focus states documented in Style tab on Carbon Design System website:
https://carbondesignsystem.com/components/dropdown/style#interactive-states
<img width="2074" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/115161875/07db4ba5-f394-40eb-a4f2-7693a36bdbfe">

Live demos on Carbon Design System website and Storybook:
https://carbondesignsystem.com/components/dropdown/code#dropdown
https://react.carbondesignsystem.com/?path=/story/components-dropdown--default
![Screen Recording 2024-01-09 at 14 15 13](https://github.com/carbon-design-system/carbon-website/assets/115161875/c522354f-18c0-4ace-8e75-55b30543ac0d)

> What did you expect to happen? What happened instead? What would you like to see changed?

Focus states should be consistent between documentation, live demo and production code.

> What browser are you working in?

Chrome

**Comment by laurenmrice** [comment]
Hi @Jonathan-Bruckbauer ,this will be fixed once we complete this issue [#3527 Dropdown: Style tab](https://github.com/carbon-design-system/carbon-website/issues/3527). Thanks!

**Comment by Jonathan-Bruckbauer** [comment]
@laurenmrice I see, so this is a duplicate and can be closed?

**Comment by laurenmrice** [comment]
@Jonathan-Bruckbauer Yes! Thank you for bringing this to our attention though.
