### ISSUE TITLE
`deploy:internal` script aborts due to app size error

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-website#388]
When running the `deploy:internal` script, the `surge` command aborts and throws this error: `Aborted - Unable to publish. Application too large`, but running `deploy:external` throws no errors. The build script finishes with no issues but it looks like surge is not allowing the app to be deployed. Is there a way around this error or should we look into some different deployment strategies?

**Comment by alisonjoseph** [comment]
I think we aren't able to use surge anymore. I have docs added in the v10 branch on how to deploy to a random route. 

https://github.com/carbon-design-system/carbon-website/blob/v10/docs/deployment.md

**Comment by emyarod** [comment]
ah ok I saw that and wasn't sure if it was meant to coexist with the surge scripts, especially since the `deploy:external` npm script was still working. Thanks for clearing that up

**Comment by alisonjoseph** [comment]
Yea I assume at some point we will hit the size limit for the external build also
