### ISSUE TITLE
[Selectable Components: Structured List] Update Component Overview Image

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3906]
## Acceptance criteria
- Need to update the image on the [Component > Overview page](https://carbondesignsystem.com/components/overview/components#components) for Structured List to follow our new selectable design.
- Current image below shows a checkmark icon when selected, but there should be a checked radio button when selected, and empty radio buttons on all other rows. The selectable controls should be on the left of the structured list.
- Jeannie has the file for these images.

   <img width="294" alt="Screenshot 2024-02-08 at 1 24 55 PM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/531d405e-dd85-4fe4-ad88-36743993e4e1">

---

### To do

- [ ] Designer needs to create image

**Comment by tay1orjones** [comment]
@laurenmrice I think this would just be replacing [this .svg file](https://github.com/carbon-design-system/carbon-website/blob/main/src/components/ComponentOverview/images/Structured%20list.svg) - it might be feasible for a designer to do without the help of dev? Happy to help out either way though!
