### ISSUE TITLE
[Homepage] Update resource cards to 3-wide layout

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#3908]
- [x] Span with 3 resource cards across.

`current`
<img width="755" alt="Screenshot 2024-02-09 at 11 21 04 AM" src="https://github.com/carbon-design-system/carbon-website/assets/32881239/8da5ac8e-db55-49e5-8fd5-e2b15a639550">

`expected`
<img width="756" alt="Screenshot 2024-02-09 at 11 20 45 AM" src="https://github.com/carbon-design-system/carbon-website/assets/32881239/7722f1e7-aa75-4b7c-92c9-bb9dd9fda1d8">

**Comment by mjabbink** [comment]
FYI @jeanservaas

**Comment by laurenmrice** [comment]
@mjabbink Are we making this change of 3 resource across to the entire site? Or just to the Homepage?

**Comment by mjabbink** [comment]
**Just the homepage.** 

In the content pages the two site nicely inside the 8-column body text.

**Comment by laurenmrice** [comment]
Closing as this has been implemented https://carbondesignsystem.com/
