### ISSUE TITLE
New accessibility section: Toggle tip Link color bug

### ISSUE THREAD

**Issue by kingtraceyj** [carbon-design-system/carbon-website#3919]
Link in Toggle tip toggle tip should be `$link-inverse` to achieve proper text contrast

Currently:
![image](https://github.com/carbon-design-system/carbon-website/assets/20582179/14fbd7b6-5910-42a8-8c65-c1948d3bb039)

**Comment by alisonjoseph** [comment]
Duplicate https://github.com/carbon-design-system/carbon/issues/13400
