### ISSUE TITLE
[Tabs] Updates images of contained tabs to include panel

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#3929]
We need to add the content panel any contained tabs image to help users understand the relationship of the content panel to the tabs.

<img width="717" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/11670886/2b766197-cb38-4317-9543-a750a9b89a44">

**Comment by laurenmrice** [comment]
After looking at this issue in Issue sizing we have a couple questions to further discuss on this topic in Issue refinement:

- [ ] Michael Gower has also made comments about wanting to include the tab panel in our website docs and react code examples. 
- [ ] It was mentioned would there be any implications if we add the panel background to every contained tab image example on the website, or if it would be better to add a dedicated section with recommended guidance on the tab panel. 
- [ ] In this [related issue (#14443)](#14443): There was a dev concern if we should add this behind a feature flag in code. And if we know if everyone should always be using contained tabs with a panel background, or if there are particular  instances where you don't need a tab panel background change?

**Comment by kingtraceyj** [comment]
tab panel images have been updated and tab panel with the correct layers are live.
