### ISSUE TITLE
 [Dropdown: Combobox & Multiselect]: Update website docs with focus state changes

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-website#3935]
Related [#768](https://github.com/carbon-design-system/carbon-design-kit/issues/768#issue-2146053598)

## Acceptance criteria
Update the Dropdown focus states on website doc with what came out of our [final design solutions](https://github.com/carbon-design-system/carbon-design-kit/issues/768#issue-2146053598).

Ref: [Figma link](https://www.figma.com/file/YAnB1jKx0yCUL29j6uSLpg/(v11)-All-themes---Carbon-Design-System?type=design&node-id=14032-290630&mode=design)

---

### Style tab

- [x] Update all the Images under the Stye tab

---

### Accessibility tab

- [x] Update all the Images under the Accessibility tab

---

### Review

Image review
- [x] Carbon designer (Thy/Lauren)
- [x] Accessibility review (Michael)

PR 
- [x] Create PR
- [ ] PR review

**Comment by thyhmdo** [comment]
Kritvi needs to revaluate this issue

**Comment by thyhmdo** [comment]
Waiting on Benjamin to raise the PRs

**Comment by sstrubberg** [comment]
Update these screens with what needs to be actually changed. @Kritvi-bhatia17 

Remove / replace with only the needed screens.

**Comment by Kritvi-bhatia17** [comment]
Increasing the story points for this issue from 5 to 8, as it required creating and updating all images under both the Style and Accessibility tabs following the latest focus state discussion.
