### ISSUE TITLE
Align Carbon icon thumbnails across YL events

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3940]
### Acceptance criteria

**Ask from Mike Abbink**
- Align Carbon icon thumbnail scales across different YL events to be consistent with the ones we use for Carbon/IDL and Office Hours.
- Reach out to these teams to align artwork
  - [ ] [Carbon for Cloud - Office Hours 2024](https://ec.yourlearning.ibm.com/w3/series/10410067?layout=grid) (Stephanie Cree)
  - [ ] [Carbon for Cloud Office Hours 1H](https://ec.yourlearning.ibm.com/w3/event/10416183) (Stephanie Cree and Jeeyoung Yang)
  - [ ] [Carbon for IBM Products development office hours](https://ec.yourlearning.ibm.com/w3/meeting/10409311) (Elysia Hwang)
<img width="382" alt="Screenshot 2024-02-23 at 8 32 35 AM" src="https://github.com/carbon-design-system/carbon-website/assets/43969356/562e6efa-fa87-4ef2-871b-4042d1ece7cc">

**Comment by sstrubberg** [comment]
YourLearning is sunsetting in favor of something else.
