### ISSUE TITLE
Redirects aren't working

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#3941]
Redirects are no longer working

- Remove https://github.com/carbon-design-system/carbon-website/blob/main/conf.d/rewrite.conf
- Move all redirects to https://github.com/carbon-design-system/carbon-website/blob/f0ab8bc9d896621d25e6f48563c56582e5f85a98/gatsby-node.js

**Comment by tay1orjones** [comment]
@alisonjoseph I think the apache redirects haven't worked since we moved to GitHub Pages. Instead they have to be configured here

https://github.com/carbon-design-system/carbon-website/blob/f0ab8bc9d896621d25e6f48563c56582e5f85a98/gatsby-node.js#L39-L46
