### ISSUE TITLE
Broken link in the Typography page

### ISSUE THREAD

**Issue by thyhmdo** [carbon-design-system/carbon-website#3945]
## Steps to reproduce the issue

- Need to update the broken link from [this section](https://carbondesignsystem.com/elements/typography/type-sets/#overview) 
- Here is the direct link https://carbondesignsystem.com/guidelines/typography/style-strategies

## Additional information

<img width="580" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/77697351/745c0301-7032-4202-b057-604e85a99de9">

<img width="998" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/77697351/62fda0c6-d451-41d9-ba2b-6417b38f8044">

**Comment by laurenmrice** [comment]
This has been resolved
