### ISSUE TITLE
Urgent Follow on work for Pictograms Library

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#395]
refers to https://github.com/carbon-design-system/carbon-website/pull/389

1) we need support a way for people to download individual pictograms from the pictogram library page. their use cases for presentations etc mean orphaning isn’t the problem it is with icons. (we should probably support downloading them all in a .zip too)

2) we need a way for people to DL the master.ai file too from the pictogram library page (and the resources page).

**Comment by alisonjoseph** [comment]
Master ai file is here https://github.com/carbon-design-system/carbon/tree/master/packages/pictograms/master. 

Is there a sketch file showing how the individual download should work per pictogram?

**Comment by chrisconnors-ibm** [comment]
@shixiedesign and @jeanservaas had individual _icon_ dl embodiments for the icon library wedding cake; we can use that here (since we never want people to DL individual icons, but do want them to be able to dl pictograms.)

But this is a 'create design then implement' issue.
