### ISSUE TITLE
[Modal] modal component is out of order in the left nav list

### ISSUE THREAD

**Issue by mbgower** [carbon-design-system/carbon-website#3955]
## Acceptance criteria

In the component list in the left navigation, Modal follows Loading, and is in turn followed by Menu and Menu Buttons.

I believe technically it is the addition of these last two items that were placed in the wrong order (i.e., they should have been placed BEFORE Modal and were positioned after it by mistake.

- [x] Place the Modal component after the Menu buttons component in the left hand nav.

### Steps to reproduce the issue

1. Go to https://carbondesignsystem.com/
2. Expand Components in the left nav
3. Navigate down to the Ms
4. Notice Modal is before Menu in the list

<img width="297" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/14298245/cc6d2170-4369-4ef0-9234-0b189fe27b5f">

**Comment by laurenmrice** [comment]
I split this issue out and put the topic of renaming "Menu buttons" in this issue as a separate topic: #3998
