### ISSUE TITLE
docs: add tag component overflow guidance

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3959]
## Acceptance criteria

- Add documentation for tag overflow content on component tabs.
  - [x] Usage tab
  - [x] A11y tab

**Comment by thyhmdo** [comment]
Should this be blocked because of the code? Is there a Figma file that has this section?

**Comment by laurenmrice** [comment]
Gui currently has a [PR](https://github.com/carbon-design-system/carbon/pull/15959) up for this that is in progress, once he is done with this we can pick this up!
