### ISSUE TITLE
MultiSelect (select all option): Usage tab docs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3973]
## Acceptance criteria
We are adding a new prop for Multiselect (select all) and need to add guidance for this in our docs on the [Usage tab](https://carbondesignsystem.com/components/dropdown/usage/). 

**To do**
- [x] Add new written content and supporting images to the Usage tab of the Dropdown component.
- [x] Create a PR.
- [x] Reviews from design and dev in order to merge.

**Comment by benjamin-kurien** [comment]
Document for usage tab has been updated and PR raised
