### ISSUE TITLE
MultiSelect (select all option): Style tab docs 

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3974]
## Acceptance criteria

- We are adding a new prop for Multiselect (select all) and need to add guidance for this in our docs on the [Style tab](https://carbondesignsystem.com/components/dropdown/style).

**To do**

- [x] Add new written content and supporting images to the Style tab of the Dropdown component.
- [x] Create a PR.
- [x] Reviews from design and dev in order to merge.

**Comment by benjamin-kurien** [comment]
Document for style tab has been updated and PR reviewed
