### ISSUE TITLE
[Feature Flags] Add guidance to Overview Components tab, Feature flag tab, and FAQs page

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3975]
## Acceptance criteria

Create a PR to add general guidance about what feature flags are in the docs on our website to the following places:

**Components > Overview page**
- Components tab
- Feature flag tab

**Help**
- FAQs page

----

# Overview page

## Components tab
- [x] Add the medium-sized feature flag tags to the component cards that have the feature flag property.
       *This will require dev help.

## Feature flag tab
- [x] Create a net new tab under Components > Overview called "Feature flags"
- [x] Move the new tab so that it is the last tab after "Overview" and "Accessibility status" tabs

### Overview section
- [x] Add this section heading
- [x] Add content from your Figma file.

### Components with feature flags section
- [x] Add this section heading
- [x] Add content and table
- [x] Add "Using feature flags / Ways to implement" section with sub sections and imagery for Designers and Developers

### How to implement section
- [x] Add this section heading

`### Code`
- [x] Add this section heading
- [x] Add content from your Figma file.

`### Design`
- [x] Add this section heading
- [x] Add content from your Figma file.
- [x] Add the two images from your Figma file.

# FAQs page

`### What are feature flag components? Where do I find it?`
- [x] Add this section heading
- [x] Add content from your Figma file.

`### What are experimental components? Where do I find it?`
- [x] Add this section heading
- [x] Add content from your Figma file.

`### Where do I find the community asset?`
- [x] Rename the current heading from "Where do I find the Experimental components and patterns?" to say --> "Where do I find a community asset?"
- [x] Add content from your Figma file.

---

**Review**
- [x] Create PR
- [ ] PR reviews

**Comment by sstrubberg** [comment]
Components vs. Variants. How do we surface the feature flags.
