### ISSUE TITLE
MultiSelect (select all option): create usage content

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#3977]
## Acceptance criteria

We are adding a new prop for Multiselect (select all) and need to add guidance for this in our docs. 

**To do**
- [x] Start creating content and imagery that will live on the [Usage tab](https://carbondesignsystem.com/components/dropdown/usage/) of the Dropdown component for the Multiselect (select all) functionality. 
- Think about what sections we need to be adding more guidance around this specific feature in the docs.
  - For example: adding guidance in the [Content](https://carbondesignsystem.com/components/dropdown/usage/#main-elements), [Interactions](https://carbondesignsystem.com/components/dropdown/usage/#interactions), [Multiselect](https://carbondesignsystem.com/components/dropdown/usage/#multiselect), and [Modifiers](https://carbondesignsystem.com/components/dropdown/usage/#modifiers) sections would be good places.
- Collect any link references if they helped guide best practices of this feature during the research phase of this umbrella. They can live in the [References](https://carbondesignsystem.com/components/dropdown/usage/#references) section if there are any.

**Comment by benjamin-kurien** [comment]
Document for usage and accessibility tabs has been updated and PR raised
