### ISSUE TITLE
contribution(pattern): Import the Cloud Data & AI slide over panel pattern into the Carbon website under experimental

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#398]
Import the Cloud Data & AI slide over panel pattern into the Carbon website under experimental.

Source:
https://pages.github.ibm.com/ide-design-guidelines/ide-design-guidelines-v2/bespoke-components/slide-over-panel/usage

**Comment by vikkipaterson** [comment]
@connor-leech do you want us to submit a PR with this?
