### ISSUE TITLE
Pictograms/icons content

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-website#400]
These are the last holdouts of content being duplicated between IDL and Carbon. This is bad for SEO and hard to maintain (need for updating in two places, broken links, etc.)

Usage content in Carbon should refer to the libraries, IDL content should be usage in digital/presentation content. Contribution guidelines should probably live with IDL, we can link out to it from the library page on Carbon.

worst case scenario: someone googles carbon icons and see’s two duplicate pages as the first two results with different URLs

**Comment by mjabbink** [comment]
We should resolve. We first assumed the libraries would be in IDL because v1 IDL had the Icon library. We also assumed IDL because the Pictograms re used by all sorts of designers from marketers to events and IBM to agency partners not all knowing or needing Carbon.

**Comment by shinytoyrobots** [comment]
I think it should be more about differentiation of content, rather than it having to be in one specific place. So, the IDL site should still have the library - as it's a universal resource - and universal guidance, and Carbon's page should link back to that and provide specific guidance for usage in software and digital implementations.

**Comment by vpicone** [comment]
Looks like we're keeping the content and kind of catering to individual audiences? Closing for now.

**Comment by mjabbink** [comment]
These need to be in both sites I think. We have an audience in IDL that is different than Carbon. I thought @alisonjoseph figured a way to have both these libraries come from the same place so not to duplicate.

**Comment by vpicone** [comment]
@mjabbink variations like Carbon missing the Design docs and IDL not including the copy button make it a bit more nuanced. https://github.com/carbon-design-system/carbon-website/pull/906 will take care of this though.

**Comment by mjabbink** [comment]
👍
