### ISSUE TITLE
[Pagination, PaginationNav] update Usage docs

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#4013]
Ref original issue: https://github.com/carbon-design-system/carbon-website/issues/3238
Ref boxnote: [Usage tab](https://ibm.ent.box.com/file/969058349134?s=6ggcperys16fda1xibr3ideh3oezz9eu) PDF a11y comments

-----

## Acceptance criteria

- Update the pagination component Usage tab documentation with the new [content template](https://carbondesignsystem.com/contributing/documentation/#usage-template:-for-components-with-multiple-variants).
- Add pagination nav as another variant.
- Look at Michael Gowers A11y PDF review and resolve any open questions and suggestions.

---

###  Things to address in the current docs
Most of  the A11y considerations were that we have not updated out docs with the new content template. Below are some other comments:

 #### Overview
- Are there exceptions of not displaying pagination if there are more than 25 pages/items of content? (I have removed this guidance because I feel that pagination can be used for different reasons and there is some more nuance than suggesting 25 pages/item is the rule)
- What are the different contexts of where pagination is used?

**Best practices**
- The labeling of the pagination sections could be improved a11y wise. This will need to be updated in code first before changing them here in the docs. I have made a separate issue for this in the mono repo which we need to further refine and tackle https://github.com/carbon-design-system/carbon/issues/16538

- Add a section for "Responsiveness" and how the pagination content should change and respond depending on the breakpoint. Only pertinent information should remain in the pagination component at smaller breakpoints.

**Comment by thyhmdo** [comment]
Roll over the next sprint. The effort seems right, the main goal for rollover is to review.
