### ISSUE TITLE
Reference the experimental version of a component in the prod component page

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#404]
Users can find the experimental equivalent of a component while on that component's v9 page.

This could be a link, card, tile, another tab, or more.

**Comment by designertyler** [comment]
Here are 3 different sketches that show how we could link and reference the experimental equivalent for each v9 component.

### 1. Adding a new tab
The content on this page could be the introduction to experimental (copied from the current about page) and then link to the experimental component.
![new_tab](https://user-images.githubusercontent.com/19270502/49042380-a5d9d780-f18d-11e8-839a-4cca065eb64a.png)


2. Extra link in the component example.
This is the least intrusive, but may be skipped. I added a "new" tag to draw more attention to it.
![link in example](https://user-images.githubusercontent.com/19270502/49042437-cb66e100-f18d-11e8-9868-8099bd4504ee.png)

3. Addition of button at the bottom of the overview page.
Potential for this to get missed. I considered moving it to the top, but I think that would draw too much attention to it.
![button at bottom](https://user-images.githubusercontent.com/19270502/49042564-1a147b00-f18e-11e8-85ed-bfe8db3af48b.png)

**Comment by claycrenshaw** [comment]
My concern with option 2 is that it could be easily overlooked by designers, who wouldn't generally be using that code-switching component. I agree with Anna on #1 and #3 too. . . What about something like this? It could appear on all three tabs, and when clicked, take the user to the corresponding tab in the Experimental section.

![image](https://user-images.githubusercontent.com/20912642/49047157-2a335700-f19c-11e8-8867-8d98705f1046.png)

**Comment by designertyler** [comment]
Good points @aagonzales I would love to have the experimental component on the extra page in 1, but it didn't work since the experimental has different content for usage and style (would those be sub tabs under "experimental"?)

@claycrenshaw Maybe we could have another reference under style? Something like, "See the experimental designs here... experimental usage here..." It would be similar to your sketch where there's a reference on each tab.

When I did these # 2 was my least favorite, but now I'm leaning towards it. Users can still discover experimental in the left nav so it's not critical they find links on the other component tabs.

I'll keep sketching

**Comment by designertyler** [comment]
Revised # 2
![link in example](https://user-images.githubusercontent.com/19270502/49251541-3d863280-f3e7-11e8-9b86-9e7fadcb9fc5.png)

**Comment by claycrenshaw** [comment]
This still gives the impression that "experimental" is another framework option, along with "react" "angular" etc, and that it will take the user to a code-specific page on another site. I really think this link needs to live outside this code component to be effective. . .

**Comment by aagonzales** [comment]
**Sprint 25:** 
- make final decision and open dev task (link here) **ASAP**
- Consult dev about scope.

**Comment by designertyler** [comment]
No longer needed for new timeline. Will need to reevaluate if this is still needed
