### ISSUE TITLE
AI documentation: Move v11 section on homepage out of the banner

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#4058]
## Acceptance criteria

**Design**
- [x] Decide where to move v11 section on homepage out of the banner
- [x] Create image for the large tile
- [x] Review page and image
- [x] Update based on feedback
- [x] Create PR 

----

Something like this: 

<img width="561" alt="image" src="https://github.com/carbon-design-system/carbon-website/assets/11670886/959c3fff-70ae-4272-8db9-dd23c4e6c158">

**Comment by thyhmdo** [comment]
Roll over the next sprint. The effort is right, it just took time to get feedback.

**Comment by thyhmdo** [comment]
Changed the effort to 8
