### ISSUE TITLE
[Structured list] Implement feature flag in live demo

### ISSUE THREAD

**Issue by Kritvi-bhatia17** [carbon-design-system/carbon-website#4064]
## Acceptance criteria 

- [ ] The [Structured List Feature flag implementation](https://react.carbondesignsystem.com/?path=/story/experimental-feature-flags-structuredlist--selection) needs to be added to the [live demo section](https://carbondesignsystem.com/components/structured-list/usage/#live-demo) on the website. This will ensure that users can properly view and interact with the updated feature.

**Comment by tay1orjones** [comment]
Tile and TextInput have some examples of putting "unstable" things in the live demo
