### ISSUE TITLE
AI documentation: Add AI Slug examples to the Live Demo

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#4072]
Add the Slug stories to the Live Demos for the following components. 
Also if there is a better way to show the AI prop with these components that dev can think of let me know. 

- [x] Checkbox
- [x] Data table
   - [x] [Column with sort](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-datatable--column-slug-sort)
   - [x] [Row with selection and expansion](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-datatable--slug-with-selection-and-expansion)
- [x] Date picker
   - [x] [Single with calendar ](https://react.carbondesignsystem.com/?path=/story/experimental-unstable-slug-examples--date-picker)
- [x] Dropdown 
   - [x] Default
   - [x] Combo-box
   - [x] Multiselect 
- [x] Modal
- [x] Number input
- [x] Radio button
- [x] Select
- [x] Tag
- [x] Text area
- [x] Text input
- [x] Tile

**Comment by alisonjoseph** [comment]
@aagonzales What should the name of these examples be in the dropdown for the live demo? 

"Checkbox with AI slug" or "With AI slug"

We seem to have both ways of naming on the website currently for different components. We should probably update things to be consistent.

<img width="383" alt="Screenshot 2024-05-28 at 7 32 41 AM" src="https://github.com/carbon-design-system/carbon-website/assets/2753488/64bd5177-9243-4b35-aeac-9823d3b867e4">
<img width="364" alt="Screenshot 2024-05-28 at 7 32 53 AM" src="https://github.com/carbon-design-system/carbon-website/assets/2753488/c1cac40d-bcc8-4871-92dc-8a33a0291c3e">

**Comment by aagonzales** [comment]
@alisonjoseph @Gururajj77 I like just "With AI slug". It keeps it simple and helps avoid having the specify the variant.
