### ISSUE TITLE
Contribution for Designers: Audit current experience and explore improvements

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#410]
How can we improve the current contribution model for designers in order to increase contributions from IBM product designers?

- [ ] Contribution docs on website
- [ ] Contribution workflow
- [ ] Possible internal campaigns
- [ ] Possible online training?

**Comment by shixiedesign** [comment]
### Current experience: 
Make an issue, and we tell them "don't wait on us! Go ahead and build it!"

### Goal: 
Someone contribute a design, Carbon team will crit and approve it, then publish somewhere, so anyone in the world can pick it up and build it.
