### ISSUE TITLE
docs: add notification tokens to color token page

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#4106]
The notification component tokens are missing from the Color > Tokens page

$notification-background-error
$notification-background-success
$notification-background-info
$notification-background-warning
$notification-action-hover
$notification-action-tertiary-inverse
$notification-action-tertiary-inverse-active
$notification-action-tertiary-inverse-hover
$notification-action-tertiary-inverse-text
$notification-action-tertiary-inverse-text-on-color-disabled

Values should be here https://github.com/carbon-design-system/carbon/blob/main/packages/styles/scss/components/notification/_tokens.scss

Related: We need a way to designate the difference between component tokens on this page. If we don't want to do this [full redesign](https://github.com/carbon-design-system/carbon-website/issues/2476) from a couple years ago, maybe we could revisit and look at the organizational part of it. https://github.com/carbon-design-system/carbon-website/issues/2476

**Comment by sstrubberg** [comment]
> Related: We need a way to designate the difference between component tokens on this page. If we don't want to do this https://github.com/carbon-design-system/carbon-website/issues/2476 from a couple years ago, maybe we could revisit and look at the organizational part of it. https://github.com/carbon-design-system/carbon-website/issues/2476

We could totally do this now that we have fluid inputs.

**Comment by alisonjoseph** [comment]
this is done
