### ISSUE TITLE
Build color page enhancements 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#4110]
Based on several conversations over the last few months, we have concluded the color token page has become too large and hard to navigate. We had an [original color page redesign](https://github.com/carbon-design-system/carbon-website/issues/2476) that was put on ice in favor of a platform that was never fully built, and the time to AEM is too far out to not make this page easier for users.  

We've put together a new design concept using only the components that already exist in Gatsby to make a better token experience. The enhancements include: 
- Multiple H2 sections for Core, Component, and AI tokens 
- Adding H3 anchor links inline with the H3 token headers in tables. 
- Adding H3 mini-anchor link sections for easier navigation. 

[Figma file](https://www.figma.com/design/7ubdj4yYwoI6IAuEmp4vB8/Color-page-updates?node-id=1-8394&t=fl9f2AETbZbPyJo3-1)

![color page update](https://github.com/carbon-design-system/carbon-website/assets/11670886/ff07f93e-62b6-4289-996f-989743a9c7fb)

**Comment by riddhybansal** [comment]
Hey there @aagonzales there is sub category called "notification" under component token but we didn't have it previously , If it should be added now where I can get the data for this ??

**Comment by aagonzales** [comment]
@riddhybansal It would be the component-level tokens under the notification component. I think they are all on this page here:
https://github.com/carbon-design-system/carbon/blob/afb0358b218b893109ca3fd869b0d75fbae2327a/packages/themes/src/component-tokens/notification/tokens.js#L46

- $notification-background-error
- $notification-background-success
- $notification-background-info
- $notification-background-warning
- $notification-action-hover
- $notification-action-tertiary-inverse
- $notification-action-tertiary-inverse-active
- $notification-action-tertiary-inverse-hover
- $notificatio-action-tertiary-inverse-text
- $notification-action-tertiary-inverse-text-on-color-disabled
