### ISSUE TITLE
[BUG] Scrolling fast in icons page cause react to crash

### ISSUE THREAD

**Issue by tekno0ryder** [carbon-design-system/carbon-website#4118]
## Detailed description

> Describe in detail the issue you're having.

When scrolling too fast in [Icons page](https://carbondesignsystem.com/elements/icons/library/) browser crashes with [Minified React error #62](https://react.dev/errors/62?invariant=62)

> What browser are you working in?

Tested on Chrome and Safari

## Steps to reproduce the issue

1. Go to this page: [Icons page](https://carbondesignsystem.com/elements/icons/library/).
2. Scroll too fast.
3. React crashes with [Minified React error #62](https://react.dev/errors/62?invariant=62)

## Additional information

- Screenshots or code

https://github.com/carbon-design-system/carbon-website/assets/8721803/6c112ea9-07b2-437a-9d96-506347a409fb

- Notes

I noticed `useIntersectionObserver()` in `src/components/SVGLibraries/IconLibrary/IconCategory.js` originally used to avoid the crash since not using it will cause the page to crash immediately. It seems fast scroll is the edge case for that solution.

**Comment by alisonjoseph** [comment]
duplicate https://github.com/carbon-design-system/carbon-website/issues/4096
