### ISSUE TITLE
The images under "Notification status" in the Notifications patterns topic don

### ISSUE THREAD

**Issue by lesnider** [carbon-design-system/carbon-website#4126]
## Detailed description

> Describe in detail the issue you're having.

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

## Additional information

- Screenshots or code
- Notes

**Comment by laurenmrice** [comment]
Closing in favor of [#4127](https://github.com/carbon-design-system/carbon-website/issues/4127)
