### ISSUE TITLE
¿Cómo puedo utilizar la alternativa de Plex Sans?

### ISSUE THREAD

**Issue by mikelsec** [carbon-design-system/carbon-website#4138]

**Comment by sstrubberg** [comment]
Translation to english: How can I use the Plex Sans alternative?

**Comment by tay1orjones** [comment]
There isn't a ready-made way to configure a font other than Plex. It's intentionally strongly baked into the system, from the `@font-face` declarations to the various defined [type sets](https://carbondesignsystem.com/elements/typography/type-sets). 

If you want to try, you'll likely have to override all font styling, `@font-face` declarations, etc with your own styles and load the different typeface.
