### ISSUE TITLE
[Website Component] Left nav and layout using the light theme

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#415]
use the light theme for the site's left nav

duplicate https://github.com/carbon-design-system/issue-tracking/issues/69

**Comment by shixiedesign** [comment]
Goal
![image](https://user-images.githubusercontent.com/15144993/49185134-bd989380-f326-11e8-848c-1dbc37e1725f.png)

**Comment by aagonzales** [comment]
**Sprint 25**: 
- figure out what we need to do to get this done. 
- Do we need to open up dev tasks? 
- Can we have a dark nav on the homepage and a light for the rest of the site?

**Comment by shixiedesign** [comment]
Side nav (shell) behavior design is done. This is ready for dev to pick up! 
Sketchfile: https://ibm.box.com/s/kf8vioa1kgtg0ntuy6deyc19sa4qlcer

![image](https://user-images.githubusercontent.com/15144993/49461302-f4542b00-f7b8-11e8-8cd9-b8b7aed72369.png)

**Comment by alisonjoseph** [comment]
moved here https://github.com/IBM/carbon-components/issues/1559
