### ISSUE TITLE
V10 Site: Color page

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#417]
- [x] Are we updating color tokens in the Carbon legacy components too? yes, updating them and tokens are the same
- [ ] For v10, use current color layout to surface the new color values / tokens and leave theme guidance on DL page*
- [ ] Once values for new themes are determined and we settle on how to implement themes in both editorial and product, integrate new tokens and DL Color in UI guidance

* Seems futile to bring DL Color in UI guidance into Carbon until we have the values for other DL themes (i.e. Gray 100, Gray 90, Gray 10). It’s confusing to 1) only discuss the light theme or 2) show themes that we don’t have a way to implement yet.

Since updating guidance content is not a breaking change, seems like it's better to finalize the theming guidance after we figure out.

**Comment by aagonzales** [comment]
- Add experimental tab for experimental palette
- Bring experimental colors in to usage list

**Comment by aagonzales** [comment]
Closing for duplicate issue, tracking further updates here: https://github.com/carbon-design-system/carbon-website/issues/486
