### ISSUE TITLE
Broken links after page refresh for markdown links starting with ../

### ISSUE THREAD

**Issue by mischor** [carbon-design-system/carbon-website#417]
## Detailed description

(Note: fails in "production build" only) 
Several pages on this site use markdown links where the link starts with ../  
If you go to those pages, and use the browser "refresh" button, the link gets an additional segment added, which makes it invalid, and indeed, if you click it, you get a 404.

This is easy to see - go here: https://www.carbondesignsystem.com/get-started/develop/vanilla/ and find the line "our components page".  Click it - it works, but then refresh the page in the browser, then click it, and it fails (gets a 404) 

Both Chrome and Firefox have this faulty behavior.

You can "reset" the bad link back to the good one, by clicking in the left hand nav bar, under Get Started, the Develop link.  This resets the page back to the React tab, so if you now click the Vanilla tab, you are back to the page, but now the links work.  

You can now break them again, by refreshing the page.  

## Workaround

This can be fixed by changing the link to be an absolute (relative to the "pages" directory) link written with a starting "/".  So, for example:

the above link is currently written as ../../components/overview  and the fix would be to write this as /components/overview

## Notes:

Why this is hard to normally see:  When running gatsby in "develop" mode, locally, the error does not happen.  It only happens after you build the site using gatsby build.  Furthermore, the links appear to work until you refresh the page.

**Comment by vpicone** [comment]
@mischor that link is just broken, I don't think its anything more complex then that. That url just doesn't exist. Do you have a different example?

**Comment by mischor** [comment]
Here's the reason it may be more complex.   It works OK, in gatsby develop mode.  It works OK in production mode if you get to the page via the sidebar links.  

Other instances of this in this project under src/pages/ I searched for using a simple search that looked for the string ")[../" and found 2 more instances: 1 more in get-started/develop/vanilla.mdx, and one in guidelines/motion/basics.mdx

I've seen this same issue in other websites, too.  

An improvement would be to (a) allow this to work reliably, or (b) issue an error message when processing this file to warn users that although this appears to work, in some cases, it won't.

**Comment by vpicone** [comment]
@mischor Markdown links shouldn't start with '../' You can't use relative paths since when the site is bundled, those files will no longer be relative to eachother. You should instead just use the path of the page starting with `/`.

**Comment by vpicone** [comment]
You _can_ use relative paths for images and components, but not Links.

**Comment by mischor** [comment]
Thanks.  I had figured that out.  But this is a somewhat common mistake, and hard to see, since it does work in develop mode, and even in production build mode (if you arrive at the page via clicking on the left-hand-side nav bar link).  

Because of this, I suggest that the system be updated to check for this kind of a link and alert the user with a message on how to properly write the link - sort of like "just-in-time-education" :-)
