### ISSUE TITLE
Location of sitemap listed in `robots.txt` file is incorrect

### ISSUE THREAD

**Issue by matthewgallo** [carbon-design-system/carbon-website#4171]
## Detailed description

> Describe in detail the issue you're having.

While working on some web scraping for the WatsonX challenge, our team noticed that the location of the sitemap listed from the `robots.txt` file is incorrect. It is currently listed as: `https://www.carbondesignsystem.com/sitemap.xml` but the location of the hosted sitemap is actually `https://carbondesignsystem.com/sitemap/sitemap-0.xml`.
> What did you expect to happen? What happened instead? What would you like to see changed?

Expected to be able to reach sitemap from location listed in `robots.txt`.
> What browser are you working in?

Chrome
## Steps to reproduce the issue

1. Navigate to https://carbondesignsystem.com/robots.txt
2. See incorrect url for the hosted sitemap

**Comment by alisonjoseph** [comment]
Looks like its located here, but empty https://carbondesignsystem.com/sitemap-index.xml
