### ISSUE TITLE
[Content templates] Style template: for components with multiple variants

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#4180]
## Acceptance criteria
Add a new [Style template](https://carbondesignsystem.com/contributing/documentation/#style-template), for components with multiple variants, with the following structure:

### Multiple variants 

- **Intro**
- **Anchor links**
- **Color**
   - Variant 1 
      - Style A / Style B (optional)
      - Interaction states
   - Variant 2 
      - Style A / Style B (optional)
      - Interaction states
- **Typography**
- **Structure**
   - Variant 1
      - Style A / Style B (optional) 
   - Variant 2
      - Style A / Style B (optional) 
- **Sizes** (optional) 
   - Variant 1
      - Style A / Style B (optional) 
   - Variant 2
      - Style A / Style B (optional) 
- **AI Presence** (optional)
   - Variant 1
      - Style A / Style B (optional) 
   - Variant 2
      - Style A / Style B (optional)

**Comment by Kritvi-bhatia17** [comment]
Hi @aagonzales! This is looking good 🔥

Just confirming a few minor things:
1. Is it "Interactive states" or "interactive states"?
2. Should it be "Sizes" or "Size"?
3. Will we be including a 'Feedback' section on the Style tab?
