### ISSUE TITLE
Supporting Docs (Dev): UI Shell

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#42]
Create dev-specific content for the new UI Shell component(s) to go on Carbon site.

**Comment by shinytoyrobots** [comment]
Related to #22

**Comment by joshblack** [comment]
Could we include this in Sprint 22 @kuehndaniel? Might help to write this after we start chipping away at the React components 👍

**Comment by kuehndaniel** [comment]
Makes sense to me. @alisonjoseph are you okay moving this issue into the backlog to tackle next sprint?

**Comment by alisonjoseph** [comment]
Yep 👍

**Comment by chrisconnors-ibm** [comment]
replaced by https://github.com/ibm/carbon-components/issues/2338
