### ISSUE TITLE
V10 Component - Data Table - Documentation 

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#425]
**Website:**
A user can discover the experimental component on the System site and understand why and how to use it.

- [ ] **Usage Tab**: create/update usage guidance
    - Start with existing component guidelines. 
    - Remove irrelevant or out of date guidance. 
    - Add new guidance or expand on existing guidance 
- [ ] **Style Tab**: create new style specs
    - Start with existing visual spec and make updates, including new tokens, type style tokens, and spacing/sizing.
- [ ] **Images**: update all exhibit images with new styles

**Comment by chrisconnors-ibm** [comment]
Probably still outstanding; @connor-leech you can close if there's a newer dupe issue for this

**Comment by connor-leech** [comment]
This will be taken care of as part of our component usage page push. Closing now.
