### ISSUE TITLE
React storybook example url's are broken for UI-Shell & CheckBox components 

### ISSUE THREAD

**Issue by 2nikhiltom** [carbon-design-system/carbon-website#4291]
The Storybook URLs for the `UIShell` and `CheckBox` components are currently broken

https://carbondesignsystem-git-alisonjoseph-802fb9-carbon-design-system.vercel.app/components/checkbox/code/
https://carbondesignsystem-git-alisonjoseph-802fb9-carbon-design-system.vercel.app/components/UI-shell-header/code/

<img width="788" alt="image" src="https://github.com/user-attachments/assets/b33f1942-a52f-453d-8134-6ed2c88fb248">

**Comment by alisonjoseph** [comment]
Unable to duplicate, assuming this was related to the storybook being down, please reopen with more information if I'm missing something.

**Comment by 2nikhiltom** [comment]
React storybook example url's for `UI-Shell` & `CheckBox` components were broken before storybook went down/ v.11.67 release
