### ISSUE TITLE
[Docs]: Content Switcher Live Demo broken

### ISSUE THREAD

**Issue by sstrubberg** [carbon-design-system/carbon-website#4298]
### Project

https://www.carbondesignsystem.com

### Section

https://carbondesignsystem.com/components/content-switcher/usage/

### Problem

<img width="849" alt="image" src="https://github.com/user-attachments/assets/e3141428-6352-43fe-8f51-adcf91a637bc">

### Suggested Severity

Severity 2 = The documentation is wrong or missing major details. It conflicts with what we are saying in another part of the system.	

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon/blob/f555616971a03fd454c0f4daea184adf41fff05b/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon/issues) for duplicate problems

**Comment by alisonjoseph** [comment]
This was related to the storybook being down
