### ISSUE TITLE
[icon library] Change action for `AI Label` icon

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#4323]
We want to be able to see the AI Label icon along-side the other AI icons in the icon library but ideally we only want people using the [AI Label](https://react.carbondesignsystem.com/?path=/docs/components-ailabel--overview) component and not this icon svg. Therefore on the `AI Label` icon we want to replace the "Download" actions with a "launch" action to view the component in Storybook instead.

![Image](https://github.com/user-attachments/assets/0b8a3c38-42fd-4bdb-98c8-3eea29126e86)

**Comment by tay1orjones** [comment]
This should also be done on the design language website. We can complete this on our website and then open an issue there for them to mirror the change in the IDL site.
