### ISSUE TITLE
[Data table] Style tab - AI Presence image has a bug

### ISSUE THREAD

**Issue by alina-jacob** [carbon-design-system/carbon-website#4324]
**Problem:**
Data table's style tab has an image showing [AI presence](https://carbondesignsystem.com/components/data-table/style/#ai-presence) style spec. This image should only show complete data table generated by AI, it should not show in-line AI label for the data table cells. 

![Image](https://github.com/user-attachments/assets/0d5c7c61-725b-4e4c-8cf5-3b7efe039590)

<br>

**Solution:**
- [x] Replace the current image with this image created in [Figma](https://www.figma.com/design/9J3QEJ717fLUa7tzlWVMMu/Usage-and-Style-images?node-id=2033-35692&t=eeXkkVlg1akBW2hu-4).
- [x] Raise a PR

**Comment by Kritvi-bhatia17** [comment]
Since the image is already created and only needs to be updated on the website and a PR raised, I've reduced the story points for this issue from 3 to 1.
