### ISSUE TITLE
Community assets component index not accessible

### ISSUE THREAD

**Issue by smith558** [carbon-design-system/carbon-website#4343]
## Summary

Hi! 🙂 The community assets component index does not seem to be accessible, how does one access it? I am trying to follow the link from https://carbondesignsystem.com/community/component-index/.

## Relevant information

https://next.carbondesignsystem.com/

![Image](https://github.com/user-attachments/assets/ab8b17bb-cb14-4df4-a658-0700c50674a2)

**Comment by alisonjoseph** [comment]
duplicate https://github.com/carbon-design-system/carbon/issues/17905
