### ISSUE TITLE
Audit of existing experimental patterns against checklist (Markdown template) to determine work required for completion

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#448]
## Goal
Audit existing experimental patterns and determine the work required for completion

### Experimental patterns
- [ ] Cards
- [ ] Chatbots
- [ ] Create flows
- [ ] Dashboard widgets
- [ ] Delete pattern
- [ ] Export pattern
- [ ] Generate and API key
- [ ] Import pattern
- [ ] Login pattern
- [ ] Navigation pattern
- [ ] Order summary template
- [ ] Remove pattern

**Comment by janchild** [comment]
Closing.
