### ISSUE TITLE
Date picker [time picker] component: hh:mm getting cropped

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#454]
<img width="950" alt="Screen Shot 2019-10-07 at 4 11 41 PM" src="https://user-images.githubusercontent.com/32881239/66345913-02199600-e91f-11e9-862b-8fb89a7733cb.png">

**Comment by mjabbink** [comment]
Several other date pickers are broken in mobile

**Comment by alisonjoseph** [comment]
duplicate
