### ISSUE TITLE
V10 Site: website components

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#459]
Design and spec out new website components listed here:https://github.com/carbon-design-system/carbon-website/issues/293

Most should already be done on Design Language site just need to spec for dev.

**Comment by shixiedesign** [comment]
Specs promised in this issue will be tracked in individual pages of the website.

**Comment by aagonzales** [comment]
@designertyler add v10 final designs for any of these components.

**Comment by alisonjoseph** [comment]
I think we can close this? The only things on this list still outstanding are the 404 page and the component pages, and they both have issues opened.
