### ISSUE TITLE
Link back to "About Experimental" from the experimental pages

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#466]
A user can find themselves on an experimental page without first reading the purpose of "experimental".

Reference or link to that content so users understand the purpose of experimental.

https://www.carbondesignsystem.com/experimental/about/overview

**Comment by shixiedesign** [comment]
duplication

**Comment by shixiedesign** [comment]
Part of **Component Page** design #303.

**Comment by designertyler** [comment]
No longer needed
