### ISSUE TITLE
Definition Tooltip example styles are broken

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#467]
<img width="711" alt="Screen Shot 2019-10-08 at 3 44 02 PM" src="https://user-images.githubusercontent.com/2753488/66431897-8bde6780-e9e2-11e9-9c12-a65fe0d32cec.png">

https://github.com/carbon-design-system/carbon/pull/4247 should fix this issue w/ the reset

**Comment by alisonjoseph** [comment]
@asudoh seems this issue is still showing up, did you have time this week to take a look?

**Comment by asudoh** [comment]
Sorry @alisonjoseph noticed this now; Need some refreshment on this topic, Is the missing dotted underline that we want to fix? If so, neither `carbondesignsystem.com` or running latest `master` of `carbon-website` repo locally didn't reproduce the problem. That made me wonder how you saw the problem?
