### ISSUE TITLE
[Pages] general website page style

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#467]
Revisions to https://github.com/carbon-design-system/carbon-website/issues/303 based on feedback.

This issue is meant to solve two issues:
- The legacy components (v9) need to be shown on the light blue #F5F7FA background. This will clash with any light grays used in the language and digital website backgrounds.

- Move to a lighter themed UI shell to match language, digital, and current Carbon sites.

The plan is to have a slightly different theme for experimental and legacy (v9) component pages.

**Comment by designertyler** [comment]
Latest
![white_side_g10_bg](https://user-images.githubusercontent.com/19270502/49235713-4adbf680-f3c0-11e8-98dc-cfec14daa7af.png)
![white_side_white_bg](https://user-images.githubusercontent.com/19270502/49235714-4adbf680-f3c0-11e8-9577-a13b2e91f115.png)

**Comment by alisonjoseph** [comment]
Are these table styles specifc to component pages or site-wide?

**Comment by designertyler** [comment]
@alisonjoseph site wide. Need to confirm with @jeanservaas on the table style's she's using

**Comment by designertyler** [comment]
**h2** - margin bottom 24px 1.5rem, margin top 80px 5rem
**h3** - margin bottom 48 3rem, margin top 16px 1rem
**h4** - margin bottom 48 3rem, margin top 16px 1rem
**paragraph** - margin bottom 24px 1.5rem
**list** - margin bottom 24px 1.5rem

**Comment by alisonjoseph** [comment]
Updated latest local build w/ specs above

**Comment by aagonzales** [comment]
**Sprint 25:** follow up on light side nav
