### ISSUE TITLE
Carbon X Release: Website

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#474]
This epic is for tracking work (content, design and dev) related to all pages of the Website for Carbon X release. 

[Pages]
- The pages already exist in the current Carbon IA but the style needs to mirror the Design Language site wherever possible.
- Completed issue should have a spec'ed sketchfile attached and pngs

[Content] 
- In Content issues, please include a link to the [Pages] issue where this content goes so developers can get the right designs.
- The content needs to both reflect the DL guidance and fill in the gaps when necessary
- Reference @joshblack 's Epic for work specific to Elements: #47

[Website Components]
- This type is here mostly for Devs to track any work needed to build the pages. 
- Issue is complete when designer attaches either sketchfile or a [Pages] issue where a sketchfile can be found. 
- These components were originally identified in #293

**Comment by alisonjoseph** [comment]
closing since the release is done and website will be swapped live today. I've moved any outstanding issues out of this epic.
