### ISSUE TITLE
[Pages] Guidelines: Motion

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#476]
**Elements-Motion**
A designer can discover the new IDL Elements guidance for Motion as it relates to both Product and Editorial, why / how to apply motion to their work.

**Design and Content**

- [x] Overview Tab: redesign layout and create/update and usage guidance
    - Bring over guidance from IDL Motion page 
    - Remove irrelevant or out of date guidance. 
    - Add new guidance or expand on existing guidance 
- [x] Resources Tab: may or may not make v10 release
    - Bring over guidance from IDL Motion page 
    - Remove irrelevant or out of date guidance. 
    - Add new guidance or expand on existing guidance 
- [x] Images: update all exhibit images with new styles / create assets

**Development**

- [ ] Overview Tab: 
    - Make sure we have components built to accomodate this layout (see issue: https://github.com/carbon-design-system/carbon-website/issues/293)

Overlapping issue:
https://github.com/carbon-design-system/issue-tracking/issues/61

**Comment by jeanservaas** [comment]
# Motion Elements v10

**Sketch File**
https://ibm.box.com/s/0yruurkwto8zo6v9tgl86c2l7t9r2ir7

- This is @shixiedesign 's page... I'm moving it from https://github.com/carbon-design-system/issue-tracking/issues/61
- She is still working on the Resources tab... layout coming soon and version will be updated in box

![elements_motion-overview_v10](https://user-images.githubusercontent.com/15144993/49096789-ecccd900-f230-11e8-97be-782defedf01a.png)

**Comment by shixiedesign** [comment]
Resource tab content: 
![elements_motion-resources_v10](https://user-images.githubusercontent.com/15144993/49171066-4998c400-f303-11e8-9a9b-288a1f72546e.png)

Motion page component specs:
![motion page components](https://user-images.githubusercontent.com/15144993/49171078-51f0ff00-f303-11e8-9169-38629e21dde9.png)

**Comment by shixiedesign** [comment]
This is content is live on IDL site, but @claycrenshaw I think you might wanna check it still? I would send a boxnote link but I think the sketchfile has the latest copies.

**Comment by chrisconnors-ibm** [comment]
Is there a good reason why this wouldn't use the same header configuration as every other internal page (smaller header, intro text in the main copy pane)?

**Comment by claycrenshaw** [comment]
![image](https://user-images.githubusercontent.com/20912642/49251316-d10b3380-f3e6-11e8-8718-b332249e2fc4.png)

This caption style feels pretty awkward to me. Does the line length need to be this short?

**Comment by eraymond25** [comment]
@shixiedesign shouldn't the inline code snippet be light, not inverse? See design language (motion site)[https://w3.ibm.com/design/language/elements/motion/]

**Comment by shixiedesign** [comment]
Thanks for the comments guys! 
@eraymond25 yeah I will change that back. I just thought it didn't look good on the cool grey. Do you have that on digital too? The other thing to consider is, we might shift the background of all pages to Gray 20. I can stay on the light theme code snippet, but will need a different color. 

@claycrenshaw I agree that's definitely weird. There might be a dev reason behind why that was like that. But I can change that in design.

**Comment by eraymond25** [comment]
Digital is using what I believe is gray 20 (but old color palette still) https://pages.github.ibm.com/webstandards/northstar-website-external/web/elements/grid-usage.html

**Comment by claycrenshaw** [comment]
@alisonjoseph @shixiedesign I am going to go ahead and convert the copy for this page to MD so I can run edits on it. I'll put placeholders for the images / components for now.

**Comment by alisonjoseph** [comment]
FYI custom video components most likely won't get done in the next week.

**Comment by claycrenshaw** [comment]
Looking more carefully at the content on this page, I wonder if we would be better off back-burnering this page until after v10. The videos and tabbed components are so important to expressing these concepts. It would feel like we are not really telling the whole story if we can't include them in time for launch. @jeanservaas @shixiedesign @alisonjoseph

**Comment by shixiedesign** [comment]
Sorry guys i don't know how I missed all the comments. Catching up now, thanks.

**Comment by aagonzales** [comment]
Sprint 25:
- [ ] finalize content or set release timeframe for motion work
- [ ] upload videos to vimeo

**Comment by jeanservaas** [comment]
# Motion Elements v10 _ REVISED

**Sketch File**
https://ibm.box.com/s/0yruurkwto8zo6v9tgl86c2l7t9r2ir7

**Video & Image Assets**
https://ibm.box.com/s/csmnsqmt6ltqe160kzhatmt9w7jj44oz

- Revised leadspaces to match IDL and digital
- Updated tab component and inline code snippet to match other GL pages
- @shixiedesign is still working on the Resources tab... layout coming soon and version will be updated in box

![elements_motion-overview_v10](https://user-images.githubusercontent.com/43144260/49471193-ea8af180-f7d1-11e8-8293-6d4abbd6304e.png)

![elements_motion-resources_v10](https://user-images.githubusercontent.com/43144260/49471194-ea8af180-f7d1-11e8-9735-b2e64b1778f6.png)

![motion page components](https://user-images.githubusercontent.com/43144260/49471195-eb238800-f7d1-11e8-860c-6c0f45981266.png)

**Comment by shixiedesign** [comment]
# Motion page final design ready for dev
Sketchfile: https://ibm.box.com/s/0yruurkwto8zo6v9tgl86c2l7t9r2ir7
Assets: https://ibm.box.com/s/wyy9df51y4xwljd7xnkl3am3759h49rj

![elements_motion-overview_v10](https://user-images.githubusercontent.com/15144993/50605452-f082f980-0e87-11e9-8235-1f5b716834a1.png)
![elements_motion-resources_v10](https://user-images.githubusercontent.com/15144993/50605457-f2e55380-0e87-11e9-9617-3472675cc699.png)
![motion page components](https://user-images.githubusercontent.com/15144993/50605463-f4af1700-0e87-11e9-9f0b-37ba1f546cdd.png)

**Comment by shixiedesign** [comment]
Closing design issue. Dev issue created #508
