### ISSUE TITLE
[Pages] Guidelines: Iconography

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#477]
**Elements-Iconography**
A designer can discover the new IDL Elements guidance for Iconography as it relates to both Product and Editorial, surface all icons, all sizes with guidance around when / where / how to use.

**Design and Content**

- [x] Library Tab 
- [x] Usage Tab: redesign layout and create/update and usage guidance
    - Remove irrelevant or out of date guidance. 
    - Add new guidance or expand on existing guidance 
- [x] Contribution Tab: redesign layout and create/update and usage guidance
    - Bring over guidance content from Digital site 
- [x] Images: update all exhibit images with new styles / create assets (not including the icons)

**Development**

- [ ] All Tabs: 
    - Make sure we have components built to accommodate this layout (see issue: https://github.com/carbon-design-system/carbon-website/issues/293)
- [ ] Icon svgs: 
    - should be pulling IDL icons now @joshblack and @chrisconnors-ibm have been working on this

**Comment by kuehndaniel** [comment]
Update to the content is a priority and STOP SHIP.

Redesigning the page is a nice to have.

**Comment by shixiedesign** [comment]
**Icon Page** 

Sketchfile: https://ibm.box.com/s/o5qhcg064uzwedl63yimxh1hzx37kcn7
Images: tbd

@claycrenshaw Please double check **Usage** tab content. I added some images that are relevant to the guideline and made edits. I also noticed two places on **Contribution** tab that might be wrong. Will detail it in the content issue (#161)

Some screenshots below: 
![image](https://user-images.githubusercontent.com/15144993/49404561-70953280-f715-11e8-9dac-9daa9c6aeff2.png)
![icon_usage](https://user-images.githubusercontent.com/15144993/49404789-18126500-f716-11e8-884c-7ef10e732ac5.png)
![icon_contribution](https://user-images.githubusercontent.com/15144993/49404792-1a74bf00-f716-11e8-9414-7c0151c00a1a.png)

**Comment by claycrenshaw** [comment]
On the Usage tab, we need to remove all content that is about icon design, rather than how to use icons within the system. This includes Padding, Weight, Perspective, Pixel Grid. All of this guidance is covered by the design language site. Color guidance could probably remain, IF Carbon's official position is that designers can decide what color to use for the icons (I think they can).

So basically, the content strategy for Iconography is that the Carbon site covers details about how to output icons to be Carbon-compliant, how to use icons properly within your product, and the icon library itself. The actual guidance on how to design icons from scratch is owned by the design language team and website. @shixiedesign

**Comment by claycrenshaw** [comment]
I forgot to mention that I LOVE this idea of grouping icons in the library by function. :)

**Comment by claycrenshaw** [comment]
@joshblack Can you (or someone) please review the Dev-focused content on this comp (highlighted in magenta above) for accuracy? Thanks!

**Comment by claycrenshaw** [comment]
@shixiedesign It looks like the only new images we'll end up needing for this page are:  

![image](https://user-images.githubusercontent.com/20912642/49538029-19679d00-f890-11e8-939a-fe4dbb3e7d8a.png)

![image](https://user-images.githubusercontent.com/20912642/49538055-25ebf580-f890-11e8-90d5-a87d12243dc9.png)


![image](https://user-images.githubusercontent.com/20912642/49538078-34d2a800-f890-11e8-9a2e-187ea3654c17.png)


![image](https://user-images.githubusercontent.com/20912642/49538089-4025d380-f890-11e8-965f-c40dfad24ea8.png)

**Comment by joshblack** [comment]
Will do @claycrenshaw!

Notes: (would it be possible to review in a PR as markdown?)

> Using SVG Sprite

This section is incorrect, and would be tied specifically to the implementation (react, vue, angular, etc)

> Using SVG sprite from static assets

This section should not be mentioned. We do not support this strategy anymore, nor is it recommended.

> Inline SVG

We do not suggest that people inline SVG and should not offer this option on our website anymore.

> Main files

This section is outdated

> Accessibility

This section needs improvements both in the code snippet and in the copy.

---

Let me know what's the best way to contribute content for this section! 👍

**Comment by claycrenshaw** [comment]
Hey @joshblack I didn't notice before, but this is the same content that is on the staging site here: https://deploy-preview-542--carbon-website.netlify.com/guidelines/iconography/usage So I guess you could make edits directly to staging. LMK if you have any questions!

**Comment by shixiedesign** [comment]
** Image Exports**
https://ibm.box.com/s/11efxwy2q5pjd4sskvyjj74c65bdjf4k

**Comment by joshblack** [comment]
@claycrenshaw looking to update the develop section, what is our content strategy around usage in multiple frameworks? We would kind of need to branch for each user depending on what they need to use icons in versus providing one path for everyone. In addition, this content for getting started would be available in the `README.md` file of each project. Would it be better to just remove this content from the Iconography usage tab, or call out the different libraries and launch out to those?

**Comment by claycrenshaw** [comment]
@joshblack Would it make more sense to break out the developer content into its own tab under Iconography? Maybe just use that page to help guide developers to the different project readme content?

**Comment by joshblack** [comment]
That could work! I'm unsure what the expected user journey is here so will defer to you for what works best.

**Comment by shixiedesign** [comment]
Icon Card spec
Sketchfile: https://ibm.box.com/s/o5qhcg064uzwedl63yimxh1hzx37kcn7
![image](https://user-images.githubusercontent.com/15144993/49815986-91234500-fd32-11e8-829e-0025f31f1eaf.png)

**Comment by laurenmrice** [comment]
Ready for dev ✅

**Comment by shixiedesign** [comment]
Looks like contents are updated! Along with the correct images. Will create new issues for design review.
