### ISSUE TITLE
Design new favicon for v10 website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#478]
Need to update this
<img width="70" alt="screen shot 2018-11-27 at 3 53 27 pm" src="https://user-images.githubusercontent.com/2753488/49113990-a5f4d880-f25c-11e8-84c8-e45a506318c6.png">

**Comment by alisonjoseph** [comment]
I think that's perfect for now 👍

**Comment by alisonjoseph** [comment]
32x32 png

**Comment by laurenmrice** [comment]
design file for 32x32 png - https://ibm.ent.box.com/file/359705365442

**Comment by aagonzales** [comment]
@laurenmrice can you close this issue if done?
