### ISSUE TITLE
Adding .clr icon in the section to download color pallets

### ISSUE THREAD

**Issue by sarah-the-sweet** [carbon-design-system/carbon-website#479]
## Relevant information

<img width="505" alt="Screen Shot 2019-09-19 at 2 33 05 PM" src="https://user-images.githubusercontent.com/15874450/65275753-e83d1e00-daeb-11e9-90ef-e8e55459aea6.png">

**Comment by aagonzales** [comment]
This has been fixed!

![image](https://user-images.githubusercontent.com/11670886/78912558-5972fd00-7a4d-11ea-8814-636cd0d0deb3.png)

**Comment by aagonzales** [comment]
Never mind, I thought it was talking about the `download` icon. Still an issue.

**Comment by aagonzales** [comment]
At the moment we can only put one icon in the corner, maybe we should put a generic color palette icon there instead so it doesn't exclude either. OR we can make this separate file and tiles all together.
