### ISSUE TITLE
Wire up Skip to content link with HTML on page

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#480]
We currently use a skip to content link, but unfortunately content is not wrapped in a `main` with the corresponding `id` in order for this to work. In addition, I believe we need to set `tabindex="-1"` on `main`. This is currently a bug in UI Shell upstream since I believe `Content` does not use this.

**Comment by alisonjoseph** [comment]
duplicate, in PR in the theme now
