### ISSUE TITLE
[Website Components] Shell behavior for narrow screens

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#481]
The website shell is using a fixed panel side nav that does not expand or collapse until screen width goes below a certain threshold. 

https://w3.ibm.com/design/product/experimental/layout/#grid-behaviors

This task is to define that behavior and produce redlines for the mockups.

![Screen Shot 2018-11-28 at 11.19.56 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/5a9e8a0d-1fe9-4a09-8d9f-073a5f2afe1f)

![Screen Shot 2018-11-28 at 11.20.03 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/97cd95bc-2f06-4f97-9d5e-1ed0bd3ea69d)

![Screen Shot 2018-11-28 at 11.19.45 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/4ab05e00-93dd-477b-8a6c-65391fde0f0e)

**Comment by alisonjoseph** [comment]
do we have any of this defined for UI Shell at all @aagonzales @joshblack ?

**Comment by joshblack** [comment]
I don't know if there are any in-context, but in the Sketch file there is:

![image](https://user-images.githubusercontent.com/3901764/49182182-267c0d80-f31f-11e8-9719-0cf6ccb6cb01.png)

For mobile

**Comment by aagonzales** [comment]
Minimum make sure the navigation works correctly for mobile.

**Comment by shixiedesign** [comment]
Shell behavior spec for v10 site: 
Sketchfile: https://ibm.box.com/s/kf8vioa1kgtg0ntuy6deyc19sa4qlcer
![image](https://user-images.githubusercontent.com/15144993/49462554-f66bb900-f7bb-11e8-9c02-4a9556f769d7.png)

**Comment by shixiedesign** [comment]
Updated behavior after team discussion. Nav will now hide on md breakpoint, instead of lg. Change is updated in the same sketchfile.
