### ISSUE TITLE
[Pages] Guidelines: Layout

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#484]
**Elements-Grid**
A designer / developer can discover the new IDL Elements guidance for the 2x Grid as it relates to both Product and Editorial.

**Design and Content**

- [x] Overview Tab: redesign layout and create/update and usage guidance
    - Bring over guidance from IDL 2x Grid page (actually same guidance as is on Carbon for TT)
- [ ] Code Tab: Work in Progress (will probably be ghosted at launch) 
    - Remove irrelevant or out of date guidance @joshblack 
    - Add new guidance or expand on existing guidance @joshblack 
- [x] Images: update all exhibit images with new styles / create assets 

**Development**

- [ ] All Tabs: 
    - Make sure we have components built to accommodate this layout (see issue: https://github.com/carbon-design-system/carbon-website/issues/293)
    - Nothing should be new here... just structured list and code snippet

**Comment by jeanservaas** [comment]
# Grid Elements v10

**Sketch File**
https://ibm.box.com/s/1s2zg8bdbsufd8usuk0h9kbqhb68ia5n

- This Overview tab content was already updated for Carbon for the TT, it should be almost exactly the same; it's the only elements content that mirrors IDL site exactly
- Grid code page is a work in progress between Chiu and @joshblack; will most likely be an inactive tab for launch

![2x grid ui](https://user-images.githubusercontent.com/43144260/49188212-824e9280-f32f-11e8-8e29-575dc9d20844.png)

![grid code ghosted_wip](https://user-images.githubusercontent.com/43144260/49188213-824e9280-f32f-11e8-8797-789b4c832494.png)

**Comment by shixiedesign** [comment]
### Image Exports
https://ibm.box.com/s/11efxwy2q5pjd4sskvyjj74c65bdjf4k

**Comment by aagonzales** [comment]
[Dev] todo:
- [ ] Take out component spacers (those live on its own page "Spacing")
- [ ] Update images, make sure they are the correct size as spec'ed above
- [ ] Add in video examples

@carbon-design-system/ui
