### ISSUE TITLE
[Pages] Guidelines: Color

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#486]
Need new design.
- [ ] Tab: Swatches
- [ ] Tab: Usage

**Comment by aagonzales** [comment]
Updating content on tokens are the high priority - stop ship.
Design the layout is low priority - nice to have.

**Comment by aagonzales** [comment]
- [ ] **Sprint 25**: update and finalize content. 
   - Add new color tokens
   - Update usage content

**Comment by shixiedesign** [comment]
### For Alpha release:
- [ ] Update colors values for both tabs 

### For Beta release: 
- [ ] Expose all themes
- [ ] Port over Color UI content for Usage tab

**Comment by aagonzales** [comment]
Alpha release content update: https://github.com/carbon-design-system/carbon-website/pull/555

**Comment by alisonjoseph** [comment]
closing in favor of https://github.com/carbon-design-system/carbon-website/issues/621
