### ISSUE TITLE
[Pages] Guidelines: Themes/Tokens

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#487]
### Alpha release requirement:
Need content update. 

### Beta or post production release: 
Re-design Themes page to Tokens page to showcase all tokens in the system.

**Comment by shixiedesign** [comment]
Leaving this as-is for X release. Moving it to Enhancement epic.

**Comment by aagonzales** [comment]
Updating the content is a high priority - STOP SHIP 
Redesigning the page is a low priority - nice to have for X date

**Comment by alisonjoseph** [comment]
The alpha release part of this is done, thanks @aagonzales!  

Do we want to keep this issue open to track updates or close it and open a new issue?
