### ISSUE TITLE
[Page] Components & Experimental Components

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#488]
Need new design. This design should work for both Stable and Experimental components. The design created should also provide:
- [ ] [Website Component]: ComponentExample #491

Need content: 
- [ ] Style tab content #490

**Comment by designertyler** [comment]
For carbon X release the component pages will follow the specs here until https://github.com/carbon-design-system/carbon-website/issues/467

This includes the component example based off the current component with slight visual tweaks (border added for white background)

**Comment by shixiedesign** [comment]
@designertyler we need to look at this issue a bit more before calling it done. . I think solution in #467 works and would be a fast one so it may very well be it. But Jeanie has a suggested change (replacing radio buttons with tabs) - let's look at it together next week? Thanks!

**Comment by designertyler** [comment]
@shixiedesign The page layout and component example were being tracked as two different issues and not dependent on each other to be complete. There's still a lot of work to understanding the component example use cases.

The component example work is being tracked here https://github.com/carbon-design-system/carbon-website/issues/230

**Comment by chrisconnors-ibm** [comment]
Our design freeze was end of last sprint (two weeks ago), so anything beyond #467 is beyond the scope of our current rel./timelines.

**Comment by shixiedesign** [comment]
That's great. Closing this issue and filed #467 under this epic! 
Filing #230 under Enhancement epic.

**Comment by shixiedesign** [comment]
### Beta release requirement
Final style update based on below design. @jeanservaas could you upload final design and spec? Thanks! 
![img_0956](https://user-images.githubusercontent.com/15144993/49703976-31ae2380-fbd2-11e8-8636-852539171e37.jpg)
