### ISSUE TITLE
Searching from landing page leads to black screen

### ISSUE THREAD

**Issue by Fokey** [carbon-design-system/carbon-website#489]
## Detailed description

> Describe in detail the issue you're having.

Beginning a search with the letter s or b breaks the site.

> What did you expect to happen? What happened instead? What would you like to see changed?

Was trying to search spacing token, hit s and yeah. Not sure why it only happens with s or b

> What browser are you working in?

Chrome, latest

## Steps to reproduce the issue

1. Go to https://www.carbondesignsystem.com/
2. Click search bar
3. Type the letter "s" or "b"
4. Observe black screen

## Additional information

- This error pops up in the console 3 times
```
react-dom.production.min.js:4531 TypeError: Cannot read property '_index' of undefined
    at O.Index.query (lunr.js:2001)
    at O.Index.search (lunr.js:1882)
    at GlobalSearch.js:41
    at w (debounce.js:97)
    at debounce.js:107
    at z (debounce.js:171)
    at GlobalSearch.js:91
    at no (react-dom.production.min.js:4601)
    at Cu (react-dom.production.min.js:6399)
    at t.unstable_runWithPriority (scheduler.production.min.js:270)
```

**Comment by Fokey** [comment]
Hitting the spacebar triggers it to break too

**Comment by connor-leech** [comment]
I'm experiencing the same issue in Firefox and Chrome
