### ISSUE TITLE
[Website Component]: ComponentExample

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#491]
Need updated design to this website component: 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/0a7c4cb9-bfa6-43ef-b99a-28d1604aa8f5)

**Comment by designertyler** [comment]
This work is being tracked here https://github.com/carbon-design-system/carbon-website/issues/230

**Comment by shixiedesign** [comment]
Closing this coz the other one has more history.

**Comment by shixiedesign** [comment]
Decided not to re-create new design for V10 release. Will make the following changes to current component: 
- for experimental, use white background
- for stable, adding 1px border
