### ISSUE TITLE
docs(file uploader): V9 images on Code tab, docs missing for drag and drop variant

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#493]
## Issue 1: v9 images remain on Code tab

These images should either be removed or recreated in v10.

<img width="1260" alt="image" src="https://user-images.githubusercontent.com/44656921/66869253-978ed880-ef64-11e9-9f79-c85e963190b1.png">
<img width="1234" alt="image" src="https://user-images.githubusercontent.com/44656921/66869273-a4abc780-ef64-11e9-845e-03ad86b6c12c.png">

## Issue 2: No docs were added for drag and drop file uploader

We need a section containing usage guidance for the drag and drop file uploader as well as design specs. It is missing at the moment.

**Comment by laurenmrice** [comment]
We need to actually show the default file uploader as an example in code before we show drag and drop. Ref: [#4490](https://github.com/carbon-design-system/carbon/issues/4490)

**Comment by connor-leech** [comment]
This was addressed here: https://www.carbondesignsystem.com/components/file-uploader/usage/
