### ISSUE TITLE
[Website Component] Global Search

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#494]
Need design spec for search box and algolia results box
![Screen Shot 2018-11-29 at 8.43.19 PM.png](https://images.zenhubusercontent.com/5667369b638e718c995f3b3e/1d7f7ff1-d933-4cb7-93e2-b5136c867b80)
fyi #299 & #298

**Comment by designertyler** [comment]
Sketch file and redlines here https://ibm.box.com/s/d1x78h9sp5e925wn8cb90hng7dvzkyms

![not selected](https://user-images.githubusercontent.com/19270502/49748618-d3358380-fc6b-11e8-9573-9abfdc2444f5.png)

![no results](https://user-images.githubusercontent.com/19270502/49748627-d761a100-fc6b-11e8-95c8-4724ff400c16.png)


![results](https://user-images.githubusercontent.com/19270502/49748631-da5c9180-fc6b-11e8-9a92-bd935e5aa351.png)

**Comment by shixiedesign** [comment]
Proposed new design: 

![image](https://user-images.githubusercontent.com/15144993/50120152-3f8b2680-021a-11e9-8011-3e71f4800f48.png)
