### ISSUE TITLE
fix[charts & component overview pgs]: cards not sized same at breakpoints

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#508]
## fix[charts & component overview pgs]: cards not sized same at breakpoints

Both the Chart types and the Component Overview page have the same card pattern; at xlg breakpoint they are the same size but at every other smaller breakpoint they are different. Also, both pages are wrong at mobile. Cards should be two up on mobile and bleed full screen.

@alisonjoseph Mike found this last week, not sure who to give it to... not super high priority but it does need to be fixed.

**Xlg breakpoint (same size cards); this is correct:**

![image](https://user-images.githubusercontent.com/43144260/67219196-372cea80-f3ed-11e9-839b-2220a5da6f41.png)

**Large breakpoint (cards are different):**
Should be three up, Component Overview is correct here

![image](https://user-images.githubusercontent.com/43144260/67219276-62afd500-f3ed-11e9-8f07-c9cd65253e3a.png)

**Tablet breakpoint (cards are different):**
Components overview page is correct... should be two up here and the margin is 16px (Chart types margin is wrong, it is 32px)

![image](https://user-images.githubusercontent.com/43144260/67219625-fa152800-f3ed-11e9-86be-fb87cdf0806d.png)

**Mobile (cards are different, both are wrong):**
Cards should be two up on mobile and bleed (like charts page but without the margin)

![image](https://user-images.githubusercontent.com/43144260/67219707-1913ba00-f3ee-11e9-916f-8eaecdb4d31e.png)

**Comment by alisonjoseph** [comment]
tagging @jnm2377 to get this done in support project scope hopefully
