### ISSUE TITLE
[Dev]: Motion Page

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#508]
Page design: https://github.com/carbon-design-system/carbon-website/issues/476
Components: https://github.com/carbon-design-system/carbon-website/issues/473
Reviewed content (optional): https://github.com/carbon-design-system/issue-tracking/issues/78
Vimeo links of video: https://github.com/carbon-design-system/carbon-website/issues/657

Sketchfile: https://ibm.box.com/s/0yruurkwto8zo6v9tgl86c2l7t9r2ir7
Video & image assets: https://ibm.box.com/s/wyy9df51y4xwljd7xnkl3am3759h49rj

### Quick notes: 
1. Video assets have do/don't designs baked in. This is so that only 1 video component is needed for website, and motion videos should not exist outside website without the do/don't coloring. 
2. Removed checklist component. Only using list. That's one less component to develop. 
3. Clay is waiting to review content after Tabs component is build.

**Comment by shixiedesign** [comment]
Note: Content on current design files (#476) are the same content live on IDL site. We can go ahead a build the page with it, and when Clay comes back with reviewed content, we can update.

**Comment by alisonjoseph** [comment]
@lovemecomputer is this something you can tackle this sprint since you are already working on the tab component that's needed for this page?

**Comment by claycrenshaw** [comment]
Please loop me in on this as MD is created so I can do an editorial pass before we publish. Thanks! @lovemecomputer @shixiedesign

**Comment by alisonjoseph** [comment]
@shixiedesign @jeanservaas need vimeo links for this page for @lovemecomputer

**Comment by shixiedesign** [comment]
@alisonjoseph @lovemecomputer all the vimeo links are here: #657

**Comment by lovemecomputer** [comment]
thanks shixie!
