### ISSUE TITLE
[Dev]: App Switcher

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#510]
@claycrenshaw @designertyler @jeanservaas @shixiedesign 

We need specs and content.

Or we can just copy https://w3.ibm.com/design/language/ ?

**Comment by designertyler** [comment]
This is the last I heard:

Switch between the design domains:
IBM Design https://w3.ibm.com/design/
IBM Design Language https://w3.ibm.com/design/language/
IBM Design System https://w3.ibm.com/design/product/

Those three domains would be using the same shell and app switcher. The current site would need a selected state in the switcher.

**Comment by emyarod** [comment]
currently blocked by

https://github.com/IBM/carbon-components/pull/1527
https://github.com/IBM/carbon-components/pull/1528
https://github.com/IBM/carbon-components/pull/1529

**Comment by shixiedesign** [comment]
# Final design for Beta release
Sketchfile: https://ibm.box.com/s/kf8vioa1kgtg0ntuy6deyc19sa4qlcer
![image](https://user-images.githubusercontent.com/15144993/49704042-2e676780-fbd3-11e8-9219-9849fe0ccdd8.png)

**Comment by jeanservaas** [comment]
@alisonjoseph @shinytoyrobots 

Talked to @chrisconnors-ibm during design sprint planning and he confirmed that we do need this component for Think... below are updated design/color specs: 

- [ ] Keep right-side drawer that already exists for Think; just build it in React

- [ ] Nav items will include: IBM Design Language; IBM Digital Design; IBM Product Design; IDM Design; _The site that you are on will not appear in the navigation (so there will be no selected state)

- [ ] Add a rule after to show that IBM Design Language is the parent site

![app switcher_js](https://user-images.githubusercontent.com/43144260/50843767-edc45080-132e-11e9-82ce-4db86b49409b.png)
