### ISSUE TITLE
[Content] Pattern: Loading. Review & consolidate Performance UX page content with it

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#517]
Mike's issue: 
[Performance UX] Remove from DL site (this sprint) and should be included in Carbon 10/v19a (future sprint) 
https://github.ibm.com/duo/website/issues/1262

Carbon current page *Pattern: Loading* contains similar content. Review and consolidate content for post v10 release.

**Comment by designertyler** [comment]
@shixiedesign  I've updated some of the static images, but there are still a few animations that are on this page:
https://next.carbondesignsystem.com/patterns/loading

**Comment by shixiedesign** [comment]
Looks like the page content is still out of date. I will create animation assets for it after we decide what content goes on the page.
