### ISSUE TITLE
Responsive Page: Adjust Breakpoint Behavior

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#52]
At the ~860px breakpoint and narrower, the left-side page content becomes hidden under the left nav. Recommend changing page behavior so that the nav menu gets auto-collapsed at this breakpoint.

Rationale: The user needs to hide this menu anyway in order to see the page content, so we can save the user a step by collapsing it automatically. This is a widespread, standard responsive behavior.

**Comment by alisonjoseph** [comment]
Agreed, was just copying over functionality from the current site, but will look at adding this in the future.

**Comment by alisonjoseph** [comment]
closing this since it won't be an issue in the new site
