### ISSUE TITLE
Duplicate Red 50s in the Gray 100 Theme

### ISSUE THREAD

**Issue by juanencalada** [carbon-design-system/carbon-website#521]
## Description

First I want to start off by saying I wasn't sure how else to report this. I'm also not sure if this is an error or if it's intentional. What I found was that the Red 50 has 2 different hex values assigned to it within the Gray 100 Theme in the Core Color Tokens section of the web page.

Here is a link to the page: https://www.carbondesignsystem.com/guidelines/color/usage/

![image](https://user-images.githubusercontent.com/24463121/67420040-db549400-f59b-11e9-8f8d-6f5ee8203976.png)

![image](https://user-images.githubusercontent.com/24463121/67420088-edcecd80-f59b-11e9-84a1-61101c398208.png)

**Comment by jnm2377** [comment]
@juanencalada thank you for reporting this! This is the right place to open this issue. 👍

**Comment by aagonzales** [comment]
Danger is actually `Red 60` #da1e28. It is properly labeled now.
