### ISSUE TITLE
[Website Component] Tab component on pages

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#526]
Design and spec the Tab component. This component is used on a lot of element pages (eg. motion).

**Comment by jeanservaas** [comment]
# Website Component — Tab component specs

**Sketch File**
https://ibm.box.com/s/34bhwe7u4wd8h01avorvj67m924396v3

- Borrows from IDL tabs but we tweaked color for better usability
- Included a look at fluid sizing / breakpoints
- Need to talk to dev about best way to determine tab width for long titles (language translations etc.)

![tab_component_specs](https://user-images.githubusercontent.com/43144260/49604538-c0f9d380-f953-11e8-93a0-e4b31c32c2ba.png)

![tabs_mobile](https://user-images.githubusercontent.com/43144260/49604631-04ecd880-f954-11e8-909e-1b202433d386.png)
![tabs 672](https://user-images.githubusercontent.com/43144260/49604632-04ecd880-f954-11e8-899f-f9d8bd380064.png)
![tabs 1056](https://user-images.githubusercontent.com/43144260/49604633-05856f00-f954-11e8-9514-03b44844ced3.png)
