### ISSUE TITLE
[Website Component] Breakpoint Changer!

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#527]
We need design & spec for content switcher component for this moment on Type page: 

![image](https://user-images.githubusercontent.com/15144993/49464792-8b24e580-f7c1-11e8-94f0-c3ba8ca4bb7c.png)

**Comment by jeanservaas** [comment]
# Website Component — Breakpoint Changer

**Sketch File**
https://ibm.box.com/s/uwrab23khh326xw4nud1dvkdt9n7ktg6

- Pulls from actual Carbon components: slider and content switcher
- Included a look at fluid sizing / breakpoints

![breakpoint_component](https://user-images.githubusercontent.com/43144260/49660788-0cbc8380-fa0d-11e8-9191-62ace16906b2.png)

![breakpoint 1312](https://user-images.githubusercontent.com/43144260/49660797-1645eb80-fa0d-11e8-919e-d6c31cb8f724.png)

![breakpoint 1056](https://user-images.githubusercontent.com/43144260/49660804-1a720900-fa0d-11e8-8657-6a443006ca03.png)

![breakpoint 672](https://user-images.githubusercontent.com/43144260/49660812-1f36bd00-fa0d-11e8-897d-13d797780345.png)

![breakpoint_mobile](https://user-images.githubusercontent.com/43144260/49660821-2362da80-fa0d-11e8-9e4d-d8bf62e8ba7b.png)

**Comment by shixiedesign** [comment]
This is a **Beta release** deliverable. Design and spec are ready for dev to pick up. @alisonjoseph

**Comment by jeanservaas** [comment]
## Breakpoint Changer (for Expressive Type tab) Specs

https://ibm.box.com/s/uwrab23khh326xw4nud1dvkdt9n7ktg6

- this website component has a sticky behavior as well that is spec'd out below

<br> 

### Specs
![breakpoint_component](https://user-images.githubusercontent.com/43144260/53193340-56f9dd80-35d6-11e9-8842-0a80ecc600c4.png)

<br> 

### Responsive specs

**1312**

![breakpoint 1312](https://user-images.githubusercontent.com/43144260/53193435-8e688a00-35d6-11e9-8343-d5164e12d943.png)

<br>

**1056**

![breakpoint 1056](https://user-images.githubusercontent.com/43144260/53193466-a6400e00-35d6-11e9-8188-261cf7e84217.png)

<br>

**672**

![breakpoint 672](https://user-images.githubusercontent.com/43144260/53193891-c1f7e400-35d7-11e9-8eef-0308860f14d4.png)

<br>

**mobile**

![breakpoint_mobile](https://user-images.githubusercontent.com/43144260/53193935-db009500-35d7-11e9-9c81-0ac5e7019351.png)

### Context of website component

![type specs_expressive](https://user-images.githubusercontent.com/43144260/53194260-8873a880-35d8-11e9-947d-0a8b5f1c49fa.png)

### Sticky behavior
![sticky_behavior_type copy 2](https://user-images.githubusercontent.com/43144260/53194276-9295a700-35d8-11e9-8b5f-a4b41a292252.png)

**Comment by tw15egan** [comment]
@jeanservaas was this meant to be closed?

**Comment by jeanservaas** [comment]
yup, sorry wasn't done writing it:
https://github.com/carbon-design-system/carbon-website/issues/1181
