### ISSUE TITLE
Visited link color on homepage

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-website#536]
Flashes between a bunch of colors:

![flash](https://user-images.githubusercontent.com/4078018/67709837-c6597580-f98c-11e9-8c96-6426b284584a.gif)

**Comment by vpicone** [comment]
Doesn't happen in gatsby theme callout components: https://gatsby-theme-carbon.now.sh/

**Comment by alisonjoseph** [comment]
completely disappears on focus
<img width="298" alt="Screen Shot 2019-11-11 at 4 51 48 PM" src="https://user-images.githubusercontent.com/2753488/68627582-b456f700-04a3-11ea-8023-dcce0e3c2623.png">

**Comment by jendowns** [comment]
I opened a PR in the theme to propose a fix: https://github.com/carbon-design-system/gatsby-theme-carbon/pull/661/files
