### ISSUE TITLE
ui-04 g90 colour is wrong on site

### ISSUE THREAD

**Issue by RoystonS** [carbon-design-system/carbon-website#538]
The g90 theme colour for `ui-04` is listed as 'Gray 60' with a hex code of `#8d8d8d`. As far as I can make out, 'Gray 60' is actually `#6f6f6f`.  (It appears to have been given the 'Gray 50' color, which is `#8d8d8d`.)

https://github.com/carbon-design-system/carbon-website/blob/acad8caae9654b468daa011a67e6c139ded17785/src/data/guidelines/color-tokens.js#L205-L216

**Comment by RoystonS** [comment]
Also ,'Blue 70' is sometimes shown as `#054ada` (as in `$hover-primary-text`) and sometimes as `#0043ce` (as in `$support-04`)

**Comment by xxxle0** [comment]
This issue was fixed (#768)
