### ISSUE TITLE
Guide pattern

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#539]
Create a pattern that covers concepts of guiding a user through a UI including getting started, new features, and more.

**Cloud data and AI**
https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/77

https://pages.github.ibm.com/ide-design-guidelines/ide-design-guidelines-v2/icp4i-patterns/landing-page/usage

https://github.ibm.com/CloudIntegrationDesign/DesignSystemAdoptionGuild/issues/49

**IoT**
https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/patterns/application-setup/

**Security**
https://github.ibm.com/security/isc-patterns/tree/master/components/tearsheet/large

https://github.ibm.com/security/isc-patterns/tree/master/layouts/consoleGettingStarted

**WCE**
http://billboard1.fyre.ibm.com/component-library/whats-new-overview

http://billboard1.fyre.ibm.com/component-library/basic-task-tour

http://billboard1.fyre.ibm.com/component-library/basic-ui-tour

http://billboard1.fyre.ibm.com/component-library/conceptual-tour

http://billboard1.fyre.ibm.com/component-library/help-menu-player-gs

http://billboard1.fyre.ibm.com/component-library/welcome-screen

**WH**
https://pages.github.ibm.com/Watson-Health/components/global-help/overview.html

https://pages.github.ibm.com/Watson-Health/components/in-context-help/overview.html

**Comment by aagonzales** [comment]
Closing for now.
