### ISSUE TITLE
Create new content: Overview for Patterns section

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#546]
I think there needs to be a section to set context for patterns. Right now the section jumps straight into "Common actions", without an option to introduce the concept of Patterns more generally.

![image](https://user-images.githubusercontent.com/825457/49594889-70c34700-f93c-11e8-8450-5f5d746eb143.png)

**Comment by claycrenshaw** [comment]
First draft for feedback:

In Carbon, _patterns_ comprise common user flows and scenarios which are too complex or too universal to be encapsulated in a single component. Individual patterns often include two or more components from the system or apply to multiple components independently. The patterns library is constantly growing, and the Carbon team encourages contributions of UX patterns which can be broadly applicable to Carbon users.

**Comment by aagonzales** [comment]
This page seems a bit bare it would be nice to add like a list and summary of all the patterns or some other sort if index like we did on the component over page.

**Comment by jeanservaas** [comment]
I agree with @aagonzales in that we should communicate visually wherever we can with the site... and since we're setting that precedent with the Overview page, where we have our little visual index, it would be nice to do the same thing here. Obvs. we pressed for time in terms of asset creation, but that would be a nice goal here.

**Comment by claycrenshaw** [comment]
Good idea! I'd be happy to add some visuals whenever they are ready. I think it will be a bit harder to condense these complex patterns into quick-hit visuals, but looking forward to seeing what you guys come up with! @jeanservaas Do you think we should add a visual index to some kind of Elements overview page as well?

**Comment by aagonzales** [comment]
OK we can add this to next sprint. I think we should hold off adding this page to the site until we can do a full design pass it. This section has been up this long without an overpage I think it can wait a little will longer so it has some  polish and looks purposeful.

**Comment by claycrenshaw** [comment]
I'm fine with whatever, but I do see this page as already being purposeful, even without illustrations -- it explains the concept of "patterns" in Carbon, which isn't really covered anywhere else. My reco would be to go ahead and publish with text only for the launch, and add extra visual stuff as we have time post-launch.

**Comment by claycrenshaw** [comment]
Screenshot for reference:

![image](https://user-images.githubusercontent.com/20912642/51409584-e0297a80-1b27-11e9-9f60-26a927642311.png)

**Comment by aagonzales** [comment]
I would really like design to take a pass at layout first. I don't think waiting 1 sprint will hurt. We want to present things in a professional, polished manner even in beta.

**Comment by jeanservaas** [comment]
Yes, agree with @aagonzales let's pause on this for a second and think of all of these things as a marriage (with doves) of design / UX an content always before we push things up. How we present ourselves is a major part of our message. If a bunch of things seem visually unconsidered or inconsistent, we lose trust. This also means thinking about all of our overview content holistically / how we can better integrate it into the flow.

**Comment by claycrenshaw** [comment]
Closing this out since the remaining concerns are captured in #751.
