### ISSUE TITLE
[File uploader] Regular file uploader isnt displayed in code on website

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#547]
For some reason the regular File uploader is not displayed in code on our website. We need to include this as our default before introducing the drag and drop file uploader. 

Our usage and style guidance has this in examples so there should also be a code example. It is in Vanilla.

**Comment by mzuliani-ibm** [comment]
Upvote. Causing confusing for our ELM design and dev. team since it seem to imply there is "only" a drag-and-drop control when first reading the page.

Related to #493 where the Usage tab provides no guidance for the drag-and-drop variant.

**Comment by aagonzales** [comment]
Look like with the new component demos this has been resolved. The website is showing both now. 
https://carbondesignsystem.com/components/file-uploader/code

**Comment by laurenmrice** [comment]
yay!

**Comment by mzuliani-ibm** [comment]
Thanks for the code demos, but the "Usage" page doesn't describe how or when to use the drag-and-drop control and the "Style" page doesn't provide any specs for the drag-and-drop control.

**Comment by laurenmrice** [comment]
yep we are going to work on getting that in next!
