### ISSUE TITLE
Set up process to deploy site & 🚀

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#55]
- [x] Setup automated deployment to staging 
- [x] Need to [Add analytics tracking code](https://www.gatsbyjs.org/packages/gatsby-plugin-google-analytics/) ready to merge in PR #170
- [x] Update cname record to point to github pages for `www.carbondesignsystem.com`
- [x] Update `public/CNAME` to www.carbondesignsystem.com
- [x] Deploy external site! 
- [x] Deploy internal website! 

Ref https://github.ibm.com/Design/w3-design-site/issues/71 (reverse proxy)

**Comment by shinytoyrobots** [comment]
Nice to have - integrate into w3.ibm.com/design (for internal build)

**Comment by alisonjoseph** [comment]
Yes, was just thinking about internal url. do we want internal.carbondesignsytem.com or what about w3.carbondesignsystem.com? 

**Public Site** https://www.carbondesignsystem.com/
_Live version of the site, manually deployed to github pages._

**Internal Site** http://internal.carbondesignsystem.com/ or http://w3.carbondesignsystem.com/ will reverse proxy to be viewable at http://w3.ibm.com/design/system
_Live internal version of the site, Do we want to auto deploy latest internal version here from master?_ 

Staging Site http://staging.carbondesignsystem.com/
_This is automatically deployed with the latest changes merged into the master branch._

**Next Site** http://next.carbondesignsystem.com/
_This is where we will stage anything for the next version/redesign of the website. Not currently active since we haven't started building Carbon X website yet._

**Comment by joshblack** [comment]
Definitely down 👍 Do we need the internal version to only be viewable from behind the firewall?

**Comment by alisonjoseph** [comment]
I would say yes lets keep it internal only, what should the URL be? 

http://staging-internal.carbondesignsystem.com ? and then have the live internal url be http://internal.carbondesignsystem.com 

Do you know what I would need to update the CNAME record to be for the internal urls?

**Comment by joshblack** [comment]
Would we need to deploy to w3 or stage1 then to keep it internal? Definitely not an issue, but we will need to bump the space size i think for CF Apps.

For URLs, I think https://internal.carbondesignsystem.com makes sense. And then https://internal.staging.carbondesignsystem.com, or `internal-staging` I'm up for either!

If we want HTTPS, I can do a wildcard cert for all sub-domains with Lets Encrypt too and then we can just upload it to IBM Cloud. Just have to remember to renew it every 3 months

**Comment by alisonjoseph** [comment]
Yes, we would need to deploy to https://api.stage1.ng.bluemix.net like we currently do for the internal only site. I'm fine with https://internal.staging.carbondesignsystem.com
