### ISSUE TITLE
Please remove the `Carbon Charts core team` notification from Carbon website

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-website#552]
ie. please remove this from all the pages it appears on
![image](https://user-images.githubusercontent.com/14989804/67874196-fb8bd200-fb0a-11e9-9da0-064591dc035a.png)

**Comment by vpicone** [comment]
Hey @theiliad why would we remove this?

**Comment by theiliad** [comment]
Sorry about that Vince I should've closed this issue a long time ago. No longer relevant
