### ISSUE TITLE
Website Content: Carbon Migration Guide

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#556]
Work with @joshblack to integrate his dev migration content from the individual repos into the website.

To-do

- [x] Update Design Kit section of Migration page to support new sync method
- [x] Token migration guidance (type)
- [x] Hide links to Component repos from Migration page until GA
- [x] Confirm that comprehensive migration guides are available on all relevant repos
- [x] Add link to @ carbon/icons repo to Icons section
- [x] Add link to @ carbon/themes repo to themes section
- [x] Make it explicit that pages should be redesigned to use the new grid
- [ ] DEV: publish changelog for carbon-components
- [ ] DEV: publish changelog for carbon-components-react
- [ ] Update to reflect https://github.com/IBM/carbon-elements/pull/397 after it is pushed.
- [x] Update IDL kit to reflect Sketch Cloud integration
- [ ] Edit all references to Beta to reflect Production status

Link to content inventory: https://ibm.ent.box.com/notes/418370289975

**Comment by joshblack** [comment]
Just to clarify, there does not exist migration content yet as we don't know what's been put in the release officially. I think we know for certain that we'll have to create migration docs for the following projects/use-cases:

- Carbon Elements
  - Need to help sponsor users migrate over to the new elements package
  - Need to help `carbon-icons` users migrate over to `@carbon/icons` and sibling packages
- Carbon Components React
  - Will need to provide help to migrate to `@carbon/icons` as the `<Icon>` component will most likely be deprecated (once again, not sure)
  - Other content TBD based on release
- Carbon components
  - Will need migration guides for each component that has changed meaningfully since the previous release
  - Other content TBD based on release
- Carbon icons
  - Will need to deprecate and offer a guide towards moving to `@carbon/icons`

**Comment by claycrenshaw** [comment]
Starter content for this page is ready in a first draft. All of the above details will be incorporated as they become available.

**Comment by claycrenshaw** [comment]
---
title: Migrating to Carbon X
---
- [Intro](#carbon-x-is-near)
- [Rollout Plan](#rollout-plan)
- [Design Kit](#design-kit)
- [Tokens](#tokens)
- [Icons](#icons)
- [UI Shell](#ui-shell)
- [Migration Tooling](#migration-tooling)

## Carbon X is near!
Carbon X, aka v10, is currently in Alpha release. Please use this opportunity to explore and experiment with the new components, elements, layouts, and UI shell. The Alpha release is a work in progress; changes will be frequent and possibly breaking. **This release is not approved for production.** Please explore the system and [provide bountiful feedback](../help/support#github-issues)! 

## Rollout Plan
- January 2019: Beta release
- March 2019: Production release

### Adoption and Activation Sessions
<p>The IBM Design core team is establishing an adoption and activation program. A new <a href="https://w3.ibm.com/design/essentials" target="blank">IBM Design Essentials</a> course is available, and teams will receive either in-person or remote education before the Production release of Carbon X. The Carbon team will share news on Slack, Connections, and in the IBM Design Town Hall as well.</p>

## Design Kit
The Beta release of Carbon X will arrive with a completely revised Sketch design kit, updated for the new IBM Design Language (f.k.a. "Duo"). All components in the kit have been reskinned, and colors, icons, typrography, UI shell, and grid elements will also reflect the new IBM Design Language.

## Tokens
The **type** token architecure has been redesigned for better clarity and flexibility in v10. More detailed guidance on migrating to the new type tokens will be available in early 2019.

The **color** token architecture for v10 is based on the v9 architecture, with some minor updates for the new design language. Carbon v9 users will see automatic, non-breaking color updates when they upgrade to v10.

**Spacing** tokens will see no change from Carbon v9.

## Icons
The iconography in Carbon X has been completely redesigned to align with the new IBM Design Language. 

Coming soon: Carbon X icon migration guide for developers

## UI Shell
The basic UI shell has been completely redesigned for Carbon X. Full documentation on the new shell is available on the Carbon website. 

Coming soon: Carbon X UI shell migration guide for developers

## Migration Tooling

When Carbon X reaches its Production release, specific developer tooling (custom scripts) will be available to help automate the transition. Stay tuned for updates!

**Comment by claycrenshaw** [comment]
Notes from sync with Josh and Anna: https://ibm.box.com/s/3n3r3ak1fo6l565absa8ottrm9dk5mq1

**Comment by asudoh** [comment]
Theme tokens migration guide: https://github.com/IBM/carbon-components/blob/master/src/globals/scss/migrate-to-10.x.md#_theme-tokensscss

**Comment by claycrenshaw** [comment]
Link to master boxnote: https://ibm.box.com/s/1kuhb60j1bz616ly6olk7g0rqvi7gbm5

**Comment by claycrenshaw** [comment]
New Info Architecture

![image](https://user-images.githubusercontent.com/20912642/53655424-c21a6400-3c15-11e9-877f-3b477cbdd3b4.png)

**Comment by claycrenshaw** [comment]
Monday preview: https://deploy-preview-1280--carbon-website.netlify.com/updates/migration/overview

**Comment by alisonjoseph** [comment]
@designertyler @connor-leech can this be closed or are there still outstanding items?
