### ISSUE TITLE
Carbon Site Feedback Loop Overhaul

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#56]
@kuehndaniel commented on [Mon Sep 17 2018](https://github.com/carbon-design-system/issue-tracking/issues/23)

Overhaul of the user feedback loop of the Carbon site. 

Opened by @claycrenshaw  (as an epic):

Hypothesis: A well-designed user feedback loop on the Carbon site will dramatically improve the Carbon team's ability to respond quickly and effectively to the needs of our users.

- As a Carbon user, I can quickly and easily provide feedback on any portion of the Carbon site, without going through the Github new ticket workflow.

- As a member of the Carbon team, I can easily see and address all user feedback coming from the site.

**Comment by shinytoyrobots** [comment]
As an open source project across code and website, why wouldn't we want a Carbon user to use the github issue workflow to provide feedback (at least feedback that requests a change).

Ideally, we would actually want users to be empowered to submit PRs if they saw errors in content.

**Comment by alisonjoseph** [comment]
Agree with @shinytoyrobots that github issues seem to make the most sense.

Somewhat related, I was on some docs site the other day(I'll have to try and find it) that had "edit this page" links on their website that brought you to the code in github where you could edit and submit a PR for content right there if you had updates/feedback.

**Comment by claycrenshaw** [comment]
Opening a github issue adds friction to the process of providing feedback, which discourages said feedback. We may prefer the user to do all the work, but in reality, some users will just want to provide feedback, whether positive, negative, or constructive. That is why this tool will be valuable. Think of the designer who reads a bit of guidance and wants to say "the way this is written is confusing" but may not have a solution at hand.

**Comment by claycrenshaw** [comment]
Also, I am not advocating removing the github functionality, just adding this additional functionality as well.

**Comment by shinytoyrobots** [comment]
Yes - IBM Cloud docs do that.

**Comment by alisonjoseph** [comment]
I could definitely see a benefit to improving the visibility of the "create an issue" link or even renaming it. It's very tiny in the footer right now. However, I'm not sure what the benefit is of adding some other tool to gather feedback would be other than creating more work for ourselves? Adding an issue is one click, very simple, and then its in github and easy to track along with all our other work.

**Comment by mattrosno** [comment]
@alisonjoseph from the slack thread today... here is how gatsby does their "edit this page on GitHub" links. https://github.com/gatsbyjs/gatsby/blob/master/www/src/components/markdown-page-footer.js#L77

i noticed "edit this page" here today too: https://material-ui.com/layout/grid

it looks like the pattern is to just link to the markdown source file and expect the user to know how to proceed with an issue / pull request?

CC @chrisconnors-ibm

**Comment by claycrenshaw** [comment]
This issue is not really about making it easier for a user to actually edit our content directly, but rather making it easier to provide feedback. Per my comment above, sometimes a user may have useful feedback, but not actually have the solution worked out (or know how to handle MD or pull requests). 

For certain parts of the website, I think the "edit this page" functionality makes sense, but I think it is a separate--but related--user problem.

**Comment by chrisconnors-ibm** [comment]
At least we have our new [Help:Support](https://next.carbondesignsystem.com/help/support) content now:
![image](https://user-images.githubusercontent.com/35537391/51212220-e03a3800-18e5-11e9-9dc0-ac56dae34523.png)
…for the folks really committed to making change happen.
