### ISSUE TITLE
[Website Component] Back to top button

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#566]
Need **Back to top** button like below for users to go back up to top of page at any point in the scroll. We can follow DL design exactly.
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/b80a5a34-61b6-4e60-b016-a9ee828462e4)

**Comment by alisonjoseph** [comment]
What icon should we use for this? I only see this one in our library which is different from IDL. 
<img width="152" alt="screen shot 2018-12-12 at 2 44 20 pm" src="https://user-images.githubusercontent.com/2753488/49897709-7deca400-fe1c-11e8-903d-6620c20c8eec.png">
