### ISSUE TITLE
[Pages] Spacing

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#567]
This page does not need dramatic change except an **image update** .

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/ed97dc6b-ed62-451d-a5d5-9104fca74ee2)

**Comment by designertyler** [comment]
SVG here: https://ibm.box.com/s/op9p6b71r8zb2si4blnjf9awda4wl2mx
![spacing_example](https://user-images.githubusercontent.com/19270502/49805096-edc63600-fd19-11e8-8fca-59766005ac93.png)

**Comment by laurenmrice** [comment]
Hey Tyler ! For spacing I have been using the Teal 60 for the handle lines and text. The pink color I usually use for rules specific for a component, containers, or icon specs
