### ISSUE TITLE
[Pages] Component Overview

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#568]
### This is a requirement for Beta release.
This work include:
- [x] design & spec out Component overview card component
- [x] design & export simplified component images
Below is the current design with old components in them. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/598f9113-0fb6-4ebf-a52f-77f407fd87be)

**Comment by laurenmrice** [comment]
Ready for dev

**Comment by jeanservaas** [comment]
Just needed to update two images (these images are attached here, but they've also been updated in the box drive folder:

- Accordian 
- List

Then Approved!!

[Img_updates.zip](https://github.com/carbon-design-system/carbon-website/files/2737961/Img_updates.zip)
