### ISSUE TITLE
[Website Component] ABC..XYZ index for Glossary page

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#569]
ABC..XYZ index on right side of Glossary page. Need design for this component. May be as simple as a color change.

![image](https://user-images.githubusercontent.com/15144993/49704814-85723a00-fbdd-11e8-87e0-e4b065543a6b.png)

**Comment by designertyler** [comment]
Sketch file https://ibm.box.com/s/iufhr8c68701o2xbb3swulqoapx6tecf

![glossary_nav](https://user-images.githubusercontent.com/19270502/49961804-29f3c500-fed9-11e8-93fc-52c81e7c76e1.png)
![specs](https://user-images.githubusercontent.com/19270502/49961805-2a8c5b80-fed9-11e8-8265-6a3bb1c302a4.png)

**Comment by aagonzales** [comment]
@designertyler assuming this is final and ready for dev --> converting to dev issue.

@carbon-design-system/ui ready for dev

**Comment by shixiedesign** [comment]
# Final design
After another round of design review, I made 2 fixes, taking hover container length from 60 down to 32px so the container is a square, and center align type. Although Duo generally advocate for left align type, I think this is a special situation. 
![glossary nav copy.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/dea9aa77-1f5a-4e70-b772-d39a36928e48)
![Specs Copy.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/788f929a-8f55-45c3-b9e6-80a82366d17a)

**Comment by mjabbink** [comment]
@shixiedesign — You were on to something with the large type leading the selected alphabetic zone. Other than it being outlined, blue and maybe too large it’s a good idea. Bringing scale into help a user anchor is always good and in this case visually nice as well. If one did start to scroll those large letters would be useful. I would love to see you explore this one more time with the large letter in black. A bit smaller and reduce some of the spacing around it. Maybe even has a small horizontal rule that spans one or two columns and hangs out to left like the containers do. Could be a nice touch.

Also make sure the beginning of the letter nav is aligning to the type on the left (either "common Actions" or the large letter) in some way. Right now there is no relationship which is a design/typography no no. :wink:

**Comment by mjabbink** [comment]
the alphabet could also be horizontal and be sticky along the top like the sticky labels or sticky content switcher component.

**Comment by shixiedesign** [comment]
@mjabbink made an issue for redesigning this page https://github.com/carbon-design-system/carbon-website/issues/1134
