### ISSUE TITLE
bug fix[Component Code Tab]: Code snippet not displaying 

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#57]
## bug fix[Component Code Tab]: Code snippet not displaying 

<br>

Component Code Tab pulls in a Read me file from Github, as a result, there is no copy / scroll or show more functionality on these code snippets.

- [ ] Is there a way to pull in our Carbon code snippet component in this situation?

**Code snippet on Component Code tab**

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/533387c5-8291-4164-88e8-dac68a34bba6)

<br>

**Correct Carbon Code snippet**

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/7f61941c-d9e8-42b0-82d9-15267b1082b6)

**Comment by alisonjoseph** [comment]
I believe this issue can be closed since we are removing the vanilla docs from the website, so this will be a non-issue once that happens.
