### ISSUE TITLE
[Content] Align **Accessibility: Color** tab content with **Color in UI page** accessibility content. 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#571]
Align **Accessibility: Color** tab content with **Color in UI page** accessibility content. 
Make sure the contents do not contradict each other. Repetition is okay. 
### Any update should be in by Beta release

**Comment by alisonjoseph** [comment]
@claycrenshaw is this what your PRs were for? should this be closed?

**Comment by claycrenshaw** [comment]
@alisonjoseph Yes! Closing now.
