### ISSUE TITLE
[Website Component] Code snippet

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#572]
Code snippet (both block & terminal)  need a style update. This spec specifically applies to the block and the component display window code snippet.

Terminal Code snippet:
- [ ] Still needs the correct copy icon (use same icon block is using)
- [x] Hover state not working in terminal (needs #353535 bkg hover (8px off edge, see block spec below)
- [ ] code coloring theme update (design will provide Monday)
- [x] BUG: terminal code snippets should always match each other in width (somewhere between 1056 and tablet, they are displaying at varying widths — see below)

![image](https://user-images.githubusercontent.com/43144260/51546492-dce50600-1e29-11e9-99fb-c720c689eb2d.png)

Block snippet should have:
- [x] the correct copy icon (Next has the updated icon now; keep it)
- [x] dark background
- [ ] code coloring theme update (design will provide Monday)
- [ ] scroll bar color should match dark theme (check all browsers, this looks good! in Chrome right now; but scroll bar seems to be disappearing in Safari
- [x] no vertical scroll bar when expanded

Feature requests:
- [x] Look at type tokens in the new spec and change accordingly
- [x] add a bottom piece to house "Show more" button;
- [x] move "Vanilla JS" into the code snippet to create space

**Comment by shixiedesign** [comment]
I'm working on the token values for dark theme now. Once that's in, the code snippet dark theme should update just by calling the dark theme.

**Comment by jeanservaas** [comment]
## Design Spec — Component Display Window Code Snippet

Sketch file:
https://ibm.box.com/s/uq0z2ze239txfc441o0v55l1mm15rl6v

- We basically matched our spec to what the digital team did with their component; a nice way to keep the copy icon and the show more button from being on top of the code

<br>

<b>Spec: 1312</b>
![experimental_component_template_overview](https://user-images.githubusercontent.com/43144260/51413380-5fbd4680-1b34-11e9-923e-3d4f86200942.png)

<br>

<b>Spec: 1312</b>

![320 sm 4 columns](https://user-images.githubusercontent.com/43144260/51413377-5a5ffc00-1b34-11e9-9596-abbc919ed270.jpg)
