### ISSUE TITLE
Role of `$field-02` token

### ISSUE THREAD

**Issue by Majavita** [carbon-design-system/carbon-website#575]
`$field-02` role column reads “Fields on $ui-02 backgrounds” . This yields a field the same color as it’s  background.  Seems as if it should read “Fields on $ui-01 backgrounds” instead.

## Steps to reproduce the issue
Visit the Carbon Design System [color usage page](https://www.carbondesignsystem.com/guidelines/color/usage/)

![image](https://user-images.githubusercontent.com/32313977/68619669-85d02080-0491-11ea-9767-e827587d126b.png)

Qs? contact @Maezlin-Avila-Taylor

**Comment by aagonzales** [comment]
This is a content bug. It should read: "Fields on `$ui-01` backgrounds"
