### ISSUE TITLE
Enhancement [sticky tabs]: Top nav and tabs stacking behavior 

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#578]
Mike provided below assets describing Tab's stacking behavior. Digital's site is consistent with this, and we should aim to build it in, if not this release, potentially shortly afterwards.

![nav-tab-stacking-full.gif](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/16f4472c-38b2-4f5b-9c83-f31a5e39bf8d)

See full res videos of above: 
https://ibm.box.com/s/np46yjxa0xa5je1ifqkbh2bigxfhevjo
Sketchfile: https://ibm.box.com/s/yshar9cm6tnbr8zdzjrwvstihf0anhjq

**Comment by alisonjoseph** [comment]
How will this work with more than two tabs? I think this page is the worst on mobile currently https://www.carbondesignsystem.com/getting-started/developers/vanilla

**Comment by alisonjoseph** [comment]
@jeanservaas makes sense, thanks! 

_They don't do that on the site currently because they aren't using the tab component, they aren't technically tabs, they are links to new pages._ 😉

**Comment by jeanservaas** [comment]
Sorry @alisonjoseph -- i realized that I massively needed to provide you a visual on that one. It's an outlier because the banner tabs don't really function like the experimental tab component in that it spans full screen... so it got a little weird at the tablet breakpoint and @shixiedesign and I had to look at it.

sketch file: https://ibm.box.com/s/tmtrrtphiio2g7duvb4uwchbvjd6h8z6

![image](https://user-images.githubusercontent.com/43144260/50614913-10c2b080-0ea8-11e9-8ce5-60803757cafb.png)

**Comment by mjabbink** [comment]
@jeanservaas and @shixiedesign are we going to stick with smaller ones (like current next.carbon) and go upt to three tabs before going to the dropdown. I think it looks good being smaller versus the 50/50. What do you all think?

**Comment by jeanservaas** [comment]
@lovemecomputer 

After mike saw the stacking spec, he wanted a slight pivot in the design... he did not want us to go to 50% of the screen with two tabs at mobile anymore.

- [ ] Two banner tabs will not go 50/50 on the screen at mobile anymore but will stay as they are now on the carbon site

- [ ] Our tab component (the in-page component seen on the motion page) the uses a minimum width to make tabs all equal width if they are under a certain character count; it would be nice to do something like this with our banner tabs as well (or add some light JS)

- [ ] blue highlight is 3px tall (not 2px)

- [ ] at 3 or more banner tabs, they will revert to full screen dropdown in mobile


Here are the updated responsive design specs for the banner tabs:

### Two tabs

<br>

**2 tabs at Desktop**

![2_tabs_desktop](https://user-images.githubusercontent.com/43144260/52741617-64daad80-2f9b-11e9-8053-a44b13f04c7b.png)

**2 tabs at Tablet**
![2_tabs_672](https://user-images.githubusercontent.com/43144260/52741543-31981e80-2f9b-11e9-835f-884940e4287f.png)

**2 tabs at Mobile**
![2_tabs_mobile](https://user-images.githubusercontent.com/43144260/52741544-31981e80-2f9b-11e9-8a70-cfafc624b302.png)

<br>

### Three or more tabs

 **3 tabs at Desktop**
![3 _tabs_desktop](https://user-images.githubusercontent.com/43144260/52741789-d0247f80-2f9b-11e9-9259-1aa32aaae5ed.png)


 **3 tabs at Tablet**
![3_tabs_672](https://user-images.githubusercontent.com/43144260/52741684-92275b80-2f9b-11e9-9767-b4936dfd38f1.png)


**3+ tabs at Mobile**
![3_tabs_mobile](https://user-images.githubusercontent.com/43144260/52741685-92275b80-2f9b-11e9-99fc-7ac8c19a66b2.png)


### Color specs for dark theme dropdown (gulp)

![image](https://user-images.githubusercontent.com/43144260/52742427-5097b000-2f9d-11e9-8f96-c57e2f52777a.png)

(can also get you exact tokens if you need)

**Comment by lovemecomputer** [comment]
currently finishing implementation of this in:
- https://github.com/carbon-design-system/carbon-website/issues/578#issuecomment-486315185
- https://github.com/carbon-design-system/carbon-website/issues/1518

wonder if stalebot shouldn't make issues stale if PRs and issues are referencing them?

**Comment by alisonjoseph** [comment]
not stale

**Comment by mjabbink** [comment]
yes, not stale and has different design specs that I thought @jeanservaas already updated but it looks like this has not. Jeannie did you do this or do we need to do this now. I can have Sadek do this if you’re tapped.

**Comment by mjabbink** [comment]
@alisonjoseph @vpicone @jeanservaas @shixiedesign 
This should not be stale or it should be moved to Gatsby theme. The sticky behavior for desktop and mobile seems to be right but the width of tabs in mobile are too wide. They need to follow the DL mobile specs and have added pattern of horizontal scrolling in mobile. This should be added into Gatsby them to get this done and I believe @jeanservaas spec’d this out?

**Comment by mjabbink** [comment]
did this issue move to Gatsby issues? The tabs should scroll horizontally if more than 3. I think Jeannie spec’d this somewhere? @jeanservaas
