### ISSUE TITLE
Elements: Motion - convert to MD and edit content

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#579]
Convert copy from Sketch file to MD and edit the content. 

Ref https://github.com/carbon-design-system/carbon-website/issues/476

**Comment by shixiedesign** [comment]
Hi @claycrenshaw , the motion page’s content is ready for you to take a pass! I might have to re-render some videos and Audrey and I are still working out some layout and spacing. But if you stick to just the text content, they are all there.
https://github.com/carbon-design-system/carbon-website/pull/801
