### ISSUE TITLE
Docs Edit: User Flow

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#58]
@kuehndaniel commented on [Mon Sep 17 2018](https://github.com/carbon-design-system/issue-tracking/issues/21)

Edit User Flow HIG entry for style and content.

http://hig-review-1.stage1.mybluemix.net/your-product-on-ibm-cloud/user-flow

---

@kuehndaniel commented on [Mon Sep 17 2018](https://github.com/carbon-design-system/issue-tracking/issues/21#issuecomment-422176323)

original issue closed but found here: https://github.ibm.com/carbon/issues/issues/880

---

@claycrenshaw commented on [Tue Sep 18 2018](https://github.com/carbon-design-system/issue-tracking/issues/21#issuecomment-422526837)

[User Flow-CC.md.zip](https://github.com/carbon-design-system/issue-tracking/files/2394298/User.Flow-CC.md.zip)
@alisonjoseph Revised copy for this page is attached. Please let me know how to proceed to get this pushed to the Internal site.

---

@alisonjoseph commented on [Tue Sep 18 2018](https://github.com/carbon-design-system/issue-tracking/issues/21#issuecomment-422548675)

At this point would make sense to add any new content to the Gatsby site, to avoid having to do the work twice. 

You can add the markdown files in that repo and open a PR. 
https://github.com/carbon-design-system/carbon-website-gatsby/tree/master/src/content

How to add content wiki: https://github.com/carbon-design-system/carbon-website-gatsby/blob/master/CONTENT.md .

Let me know if you have any questions. 

---

@claycrenshaw commented on [Tue Sep 18 2018](https://github.com/carbon-design-system/issue-tracking/issues/21#issuecomment-422555708)

@alisonjoseph This content is internal-only. Does that matter in this case?

**Comment by alisonjoseph** [comment]
nope, it’s all one site. The docs explain how to flag a page as internal.
