### ISSUE TITLE
Update the website shell to lighter theme

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#585]
This issue is to add a lighter theme to the website's shell navigation.

The homepage would use the default dark theme and the side nave would change to the lighter theme for the rest of the site. The header bar will use the same values for both themes (always dark). 

Token values based on the ones documented here https://github.com/IBM/carbon-components/tree/master/src/components/ui-shell#header--header-panel

I didn't see a token for the  horizontal rule above "Design Kit". It should be  \$gray-20

Design specs here https://github.com/carbon-design-system/carbon-website/issues/415#issuecomment-442621257

## Header & header-panel

| `#` | Variable/token             | Role                                                                                                                      | Experimental theme value |
| --- | -------------------------- | ------------------------------------------------------------------------------------------------------------------------- | ------------------------ |
| 1   | \$shell-header-bg-01       | Header bar background                                                                                                     | \$gray-90                |
| 2   | \$shell-header-bg-02       | Header-panel background                                                                                                   | \$gray-10                |
| 3   | \$shell-header-bg-03       | Panel Item hover                                                                                                          | \$gray-20                |
| 4   | \$shell-header-text-01     | Primary text in header <br> Tab text <br> Product label                                                                   | \$gray-10                |
| 5   | \$shell-header-text-02     | Primary text in header-panel <br> item text                                                                               | \$gray-90                |
| 6   | \$shell-header-text-03     | Secondary text in header-panel <br> Category label                                                                        | \$gray-70                |
| 7   | \$shell-header-icon-01     | header bar icons                                                                                                          | \$gray-10                |
| 8   | \$shell-header-icon-02     | icons in header-panel                                                                                                     | \$gray-90                |
| 9   | \$shell-header-link        | item link                                                                                                                 | \$blue-60                |
| 10  | \$shell-header-icon-03     | Header icon <br> selected state background                                                                                | \$blue-60                |
| --- | -------------------------  | ------------------------------------------------------------------------------------------------------------------------- | ------------------------ |
| 11  | \$shell-side-nav-bg-01     | Side-nav panel background                                                                                                 | \$white                  |
| 12  | \$shell-side-nav-bg-02     | Selected category background <br> Select L2 flatted item background <br> Item hover background <br> Footer-bar background | \$gray-10                |
| 13  | \$shell-side-nav-bg-03     | Selected L2 nested item                                                                                                   | \$white                  |
| 14  | \$shell-side-nav-text-01   | Primary text in side-nav <br> L2 Flatten item text <br> L2 Nested item text <br> L1 title text                            | \$gray-70                |
| 15  | \$shell-side-nav-text-02   | Secondary text in side nav <br> L2 Category label                                                                         | \$gray-70                |
| 16  | \$shell-side-nav-icon-01   | side-nav icon color                                                                                                       | \$black                  |
| 17  | \$shell-side-nav-accent-01 | item highlight bar                                                                                                        | \$blue-60                |

**Comment by designertyler** [comment]
FYI @joshblack @asudoh @emyarod

**Comment by alisonjoseph** [comment]
duplicate
