### ISSUE TITLE
Implement more Search features

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#588]
Questions have come up from other product teams about what our current search capabilities are:

-What do we do to show applied search terms?
-Can we show tags (like pinterest?)
-Show X of X results (like amazon?) 0 results message guidelines/illo examples?
-Do we have guidelines on what a loading state looks like?
-How do we account for search limitations? (technical)

These kinds of things would be helpful to either implement and/or update content wise in our guidance.

**Comment by alisonjoseph** [comment]
Hey @laurenmrice this is what we are using for our search, https://community.algolia.com/docsearch/

**Comment by claycrenshaw** [comment]
@laurenmrice Is this referring to search on the carbon site, or search for products using the system?

**Comment by laurenmrice** [comment]
thanks Alison, that is helpful!

Clay- this came from some discussion that happened in the Cloud checkin meeting. Some people were asking if the search component (used in product) has some more capabilities implemented. I talked with Josh about it and he thought it would be good to have this documented in a github issue to improve search for the future.

**Comment by claycrenshaw** [comment]
So I get the feeling that @alisonjoseph was talking about the search on the carbon site. . . AFAIK the algolia search is not part of the design system that other teams would use. Right Alison?

**Comment by alisonjoseph** [comment]
should this be moved to carbon-components repo then?

**Comment by laurenmrice** [comment]
ok i will do that
