### ISSUE TITLE
Component variant switcher

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#60]
### User need: 
A user needs to be able to see all the available variants to a component without having to scroll through the whole page. 

### Proposed solution: 

Collapsing all the component example windows into 1, with an added **component variant switcher** in the form of a list of radio buttons to allow users to switch between different variants of the component. This also shortens our component pages significantly, so we avoid the loooong scroll. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/3ce5ad47-7ae3-4d55-b2d8-adc63a170790)

FYI @designertyler @jeanservaas coz the previous issue on Component example window got closed :D

**Comment by alisonjoseph** [comment]
closing, work tracked https://github.com/carbon-design-system/carbon-website/issues/357
