### ISSUE TITLE
Expand the guidance provided within the "Content" section

### ISSUE THREAD

**Issue by tomwaterton** [carbon-design-system/carbon-website#602]
### Summary

_Note: This issue is based on conversations I've already had in detail with @janchild (and to a lesser extent with @connor-leech)._

The aim is to take existing content guidance from the Cloud, Data & AI [voice and tone guide](https://cdai-design.w3ibm.mybluemix.net/design-system/voice-and-tone?tab=guide) and bring relevant sections across to the Carbon website (under the "Content" section).

So, the guidance already exists (and has been well used and tested). This issue is being raised to track the work involved in re-creating the guidance in Carbon. 

### Justification

There is some content guidance already available in the Carbon website, but it is fairly sparse. By contrast, the CD&AI (formerly Hybrid Cloud) voice and tone guide is more extensive and has been used by lots of IBM designers and devs over the last couple of years and has had a lot of positive feedback.

Now that more and more teams are moving to use Carbon, it makes sense to move the fuller content guidance from CD&AI into the main Carbon site so that everybody can benefit from it.

### Available extra resources

@janchild and I aim to do the work ourselves.

The only thing we might need help with is if and when Carbon supports tertiary navigation (which I hear is being discussed), we would want to move from the current tabbed layout to whatever new tertiary navigation style Carbon delivers.

### Other information

Once this work has been completed, I (Tom W.) will sunset my CD&AI voice and tone guide and point people directly to the Carbon > Content guidance.

**Comment by tomwaterton** [comment]
As the existing voice and tone guide is quite extensive, @janchild and I spoke yesterday about how we should structure the material within the Carbon > Content section. 

Our plan is that the Carbon > Content section will evolve from having the 3 sections that it has today:
**Content**
- General 
- Guidance
- Glossary

to have the following 6 sections: 
**Content**
- Content principles
- Punctuation
- Capitalization
- Numbers
- Labels (Nav and button) 
- Glossary

**Comment by tomwaterton** [comment]
I have now finished this work and have just delivered PR #604, which contains the additional content and the restructuring mentioned above.

**Comment by tomwaterton** [comment]
**Addition:**
I had a call with @jeanservaas today about some visual design matters and we discussed the following, which Jean suggested I add to this issue. 

### The request: 
Can we add support for a large (e.g. 12 column width) illustration section at the top of a page.

### Background: 
When we designed the [CD&AI voice and tone guide](https://cdai-design.w3ibm.mybluemix.net/design-system/voice-and-tone?tab=guide) we put a lot of thought into making the guidance as engaging and fun to use as we could so that people would remember it and use it. 
As part of this, we added large, bold quotes and illustrations as section dividers. We've had lots of positive feedback from users that they really like these. 
Here are a couple of examples: 

![Screenshot 2019-12-12 at 20 43 37](https://user-images.githubusercontent.com/9316771/70747669-62aec000-1d20-11ea-9a44-a6992c5d80cd.png)
![Screenshot 2019-12-12 at 20 44 49](https://user-images.githubusercontent.com/9316771/70747717-74906300-1d20-11ea-98d8-c7fec47d9f6d.png)

While these illustrations clearly don't fit with Carbon, we would love to be able to design some new ones - in line with Carbon's illustration guidelines - and be able to add them via a suitable component at the top of a page. 

Discussing this with @jeanservaas today, she suggested that such an illustration component might be best in a marque just below the page header banner. 
![Screenshot 2019-12-12 at 20 30 16](https://user-images.githubusercontent.com/9316771/70748047-1ca62c00-1d21-11ea-9c72-7c08de75bf0e.png)

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
