### ISSUE TITLE
v10 Website Bugs/Updates

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#608]
From @jeanservaas 

## Type tokens/classes and alignment

- H1 size (it's fluid) needs to be **$expressive-heading-04** token (I also just made a PR! for a value change for this token too that @joshblack is aware of); it's not currently fluid now and it's displaying much smaller at the large / xlg breakpoints than IDL

<br>

![image](https://user-images.githubusercontent.com/43144260/50021355-6c330a00-ff9e-11e8-807b-c70a0368c766.png)

<br>

- H2 uses the token **$heading-03** (you have this correct! just letting you know what the token name is for that value)

<br>

- We seem to be missing the H3 size which used the token **$heading-02** (it's the 16px semi-bold). I included a grab for our layout page... _I haven't combed the whole site, but I don't think we're using this style currently... maybe on FAQ page..._

![image](https://user-images.githubusercontent.com/43144260/50021996-6dfdcd00-ffa0-11e8-88f5-3be270bb5a56.png)

<br>

- This ONLY happens on grid page, but these secondary indexes should be calling the **$body-long-02** because they need to be smaller, otherwise it's confusing

![image](https://user-images.githubusercontent.com/43144260/50022565-38f27a00-ffa2-11e8-99d2-59b7b354b55e.png)

![image](https://user-images.githubusercontent.com/43144260/50022540-237d5000-ffa2-11e8-9b81-864b5b165567.png)

_Also, this one should follow the same pattern_

![image](https://user-images.githubusercontent.com/43144260/50022638-748d4400-ffa2-11e8-84a0-a850ae360c2d.png)

![image](https://user-images.githubusercontent.com/43144260/50022590-490a5980-ffa2-11e8-8128-756fd21b7b3f.png)

<br>

- All tokens should be displaying in inline code snippet for consistency, since we're doing it on the Typography page

![image](https://user-images.githubusercontent.com/43144260/50022689-a0a8c500-ffa2-11e8-96bd-16cd764bb5d7.png)

<br>

- We should never be bolding inline links (I found this on the Getting Started Designers page) but we can make that rule across the board

_Also found on: Getting started Developers, Accessibility (a lot), Support and FAQ_

![image](https://user-images.githubusercontent.com/43144260/50022800-f8dfc700-ffa2-11e8-9c67-4c5443a8b619.png)

<br>

Captions are not done in italic now (see layout page for correct treatment) — they pull **$body-short-01**

![image](https://user-images.githubusercontent.com/43144260/50023236-32fd9880-ffa4-11e8-9b82-98824e4dd25d.png)

![image](https://user-images.githubusercontent.com/43144260/50023471-e797ba00-ffa4-11e8-8cad-b7b5ac799281.png)

<br>

## Image sizing

- For most part (with a few exceptions, like the Type page, our 1-up rectangular images should be displayed at the large size (928px at 1312 breakpoint)... right now they're still at 640 from old Carbon.

- I thought @shixiedesign exported new image assets here, if not I will get them to you. These are old images from the TT and they still have the gray 100 background.

![image](https://user-images.githubusercontent.com/43144260/50022166-d482eb00-ffa0-11e8-8ae4-e192fec35208.png)

<br>

## Inline Code Snippet Component

- Always use the gray 20 (#dcdcdc) background highlight for inline code snippet, whether it's on a white background or a gray 10 background it works; I'm seeing a lot of white backgrounds:

![image](https://user-images.githubusercontent.com/43144260/50023191-12cdd980-ffa4-11e8-8f89-a5f6b893ddce.png)

<br>

## Type Spec Component

- those example lines to the right should also be on the grid; so the line lengths for those guys are getting way too long

- code snippet is getting bumped out of alignment (there should also be 16px of padding beneath it)

![image](https://user-images.githubusercontent.com/43144260/50024020-aef8e000-ffa6-11e8-839d-eac8b51210e2.png)

![image](https://user-images.githubusercontent.com/43144260/50024032-b61fee00-ffa6-11e8-980b-e4577c58570a.png)

<br>

## Code Snippet Spec Component

- would like it to have dark theme now that we have values, but if it can't maybe we could have a 1px #dcdcdc line separating it from our type specs. 

- it's not aligning to image

![image](https://user-images.githubusercontent.com/43144260/50024231-5249f500-ffa7-11e8-84c6-fce086454e22.png)

<br>

## Spacing

- I know we don't have fluid spacers figured out yet... but just trying to get consistent margin tops / bottoms for now site wide; sometimes spacing above the H2s are inconsistent:

_Type page examples_

![screen shot 2018-12-14 at 9 54 59 am](https://user-images.githubusercontent.com/43144260/50024434-0186cc00-ffa8-11e8-997b-6669bbe2e866.png)

![image](https://user-images.githubusercontent.com/43144260/50024536-604c4580-ffa8-11e8-848d-a03b323d6069.png)

<br>

## Table (Structured list) Component

- Ideally we want two sizes for this component — a 12 column component and a 6 column component for less information

_it does actually looks like you're using two sizes now... I see the 12 col component on the accessibility page and a shorter one on layout_

**Not ideal** (we want to avoid these long line lengths and make sure the first column has enough space so it doesn't have to break) Examples of these are on the Spacing, Accessibility and Disabled State and Overflow Content pages: 

![image](https://user-images.githubusercontent.com/43144260/50025090-05b3e900-ffaa-11e8-80f9-181a337a17f7.png)

![image](https://user-images.githubusercontent.com/43144260/50025576-a22abb00-ffab-11e8-96fb-d3b8713eb485.png)

**Ideal:**

![image](https://user-images.githubusercontent.com/43144260/50025304-aacec180-ffaa-11e8-9e48-173a0f7ce7f3.png)

- Even if it can't be a shorter width table, we should still follow the grid and clip the line length to follow our guidance

![image](https://user-images.githubusercontent.com/43144260/50025452-36e0e900-ffab-11e8-910a-d16e14510fb3.png)

- The majority of our tables will be the 12 column format, if we had to choose, I would make that one... this from layout is a great example of where 12 column would be better

![image](https://user-images.githubusercontent.com/43144260/50025522-790a2a80-ffab-11e8-97b4-fec2d70aa7e8.png)

**Comment by lovemecomputer** [comment]
hi @carbon-design-system/design / @jeanservaas / @claycrenshaw ! i'm working through the issues in this PR. Have a few requests/feedback/input. More may come in a future comment, but this is a cursory glace at the moment:

---

> We should never be bolding inline links (I found this on the Getting Started Designers page) but we can make that rule across the board

this sounds like a content rule that should have its own Issue/PR, as it can be controlled via editing the markdown file so it isn't just a development issue.

---

<img width="832" alt="screen shot 2018-12-19 at 1 02 54 pm" src="https://user-images.githubusercontent.com/3846271/50241928-771adf80-038e-11e9-84d5-25a1da70c0e9.png">

This is actually not a particular caption, just a paragraph made to be italic? Captions on the Do/Don't Examples were implemented to match the IDL site, but then some last-minute hurried revision kind of broke the implementation.

For proper implementation, we need to see a Github Issue with caption specs and a list of which components we would like captions to be used for

---

<img width="357" alt="screen shot 2018-12-19 at 1 07 13 pm" src="https://user-images.githubusercontent.com/3846271/50242134-09bb7e80-038f-11e9-98a5-e04f19ee3ca9.png">
<img width="288" alt="screen shot 2018-12-19 at 1 07 20 pm" src="https://user-images.githubusercontent.com/3846271/50242138-0c1dd880-038f-11e9-8d03-83bf1f6340b3.png">

this is a bit more complicated of an issue and should be tracked in its own PR. the rectangle with the white background is it's own element that the header margin is pushing away from. we'd need to compile a list of special cases like this and figure out an implementation strategy to make it consistent & easy to get right when editing the markdown file. would rather have that discussion in its own Issue & PR, along with the necessary details to implement!

---

> Table (Structured list) Component
> - Ideally we want two sizes for this component — a 12 column component and a 6 column component for less information

We should also put this into its own Issue with some specification behind what the desired options and implementation should be. table spacing and swapping numbers of columns can be pretty complicated!

---

for now, i'm working on all the more straightforward fixes in this issue. if anything else comes up, i'll add it to the list here. thanks y'all!

**Comment by lovemecomputer** [comment]
all the fixes that i was able to do for now are in https://github.com/carbon-design-system/carbon-website/pull/625 !

**Comment by alisonjoseph** [comment]
- Image sizing - need a separate issue
- code snippet - already has a separate issue
- italic text - markdown/content updates, separate issue or just PR to update
- type spacing - a separate issue
- [x] bold links - fixed in my PR
- [x] typography component spacing - fixed in my PR

@jeanservaas 

https://github.com/carbon-design-system/carbon-website/pull/641

**Comment by alisonjoseph** [comment]
closing this as items have either been addressed or moved to separate issues
