### ISSUE TITLE
[docs] Generate lead art for all component/usage pages

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#61]
Part of the template created in carbon-design-system/carbon-website#1600 will be a lead image. These must be generated for each component usage page.

## Components

- [ ] Accordion
- [ ] Breadcrumb
- [ ] Button
- [ ] Checkbox
- [ ] Code snippet
- [ ] Content switcher
- [ ] Data table
- [ ] Date picker
- [ ] Dropdown
- [ ] File uploader
- [ ] Form
- [ ] Inline loading
- [ ] Link
- [ ] List
- [ ] Loading
- [ ] Modal
- [ ] Notification
- [ ] Number input
- [ ] Overflow menu
- [ ] Pagination
- [ ] Progress indicator
- [ ] Radio button
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Structured list
- [ ] Tabs
- [ ] Tag
- [ ] Text input
- [ ] Tile
- [ ] Toggle
- [ ] Tooltip

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
