### ISSUE TITLE
Website Addons

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#611]
A developer building a website under ibm.com/design/* should be able to use a shared library of components. 

- [x] Header - css
- [x] SideNav - css
- [x] Website Footer
- [x] 404 page
- [x] App switcher
- [x] BacktoTop
- [ ] PageHeader
- [ ] PageTabs
- [ ] CodeSnippet
- [ ] NextPrevious
- [ ] ClickableTile
- [x] Anchor Links
- [ ] WebsiteTabs
- [ ] DoDontExample
- [ ] Row
- [ ] Column
- [ ] IconLibrary
- [x] ImageComponent
- [ ] markdown
- [ ] Video
- [ ] TypeScale
- [ ] TypeSpec
- [ ] TypeWeight
- [x] Breakpoint Changer (currently in IDL, not Carbon)

**Comment by alisonjoseph** [comment]
Yes to all of that. Not sure on the best way to share the gatsby config? (for the /design site I coped the carbon site and stripped out all of the things I didn't need)

**Comment by joshblack** [comment]
@alisonjoseph I wonder if we could have the add-on have the gatsby dependencies and exports a common `gatsby-config.js` file that people can import and do:

```js
'use strict';

const defaultConfig = require('@carbon/addons-website/config';

module.exports = {
  ...defaultConfig,
  myCustomOption: 'foo',
  plugins: [
    ...defaultConfig.plugins,
    'my-custom-plugin',
  ],
};
```

**Comment by alisonjoseph** [comment]
I imagine that would work, just wondering how that might complicate things if someone wants to change certain config settings. (for instance there is a maxWidth setting for images, that is different between the Carbon site and /design site, google analytics plugin has the unique tracking ID.

Wonder if it might make more sense/be easier for someone, to create a "website-starter" with the basics in there pulling from the addons. (just thinking out loud).

**Comment by joshblack** [comment]
@alisonjoseph definitely understand. This is partially why I thought the toolkit project could be interesting, one could do:

```bash
npx toolkit create my-project --preset @carbon/cli-preset-design-website
```

Would basically create a whole new project for them, but instead of being static files it'd basically have this as a dependency. Something like:

```json
{
  "name": "my-project",
  "dependencies": {
    "@carbon/cli-preset-carbon-website": "x.y.z"
  },
  "toolkit": {
    "presets": ["@carbon/cli-preset-carbon-website"]
  }
}
```

So as the package is updated, one could do:

```bash
npx toolkit upgrade @carbon/cli-preset-carbon-website
```

You could also extend it by having the some gatsby plugin for the CLI load the local `gatsby-config.js` in addition to its own.

---

For the other option, I would assume it would happen like:

```js
const defaultConfig = require('@carbon/addons-website');

module.exports = {
  plugins: [
    ...filterConfig(defaultConfig.plugins, ['my-plugin-key']),
    {
      name: 'my-plugin-key',
      options: {
        ...findInConfig(defaultConfig.plugins, ['my-plugin-key']),
        myCustomOption: 'value',
      },
    }
  ],
};
```

**Comment by alisonjoseph** [comment]
@vpicone fyi, these are the list of components we need to get moved to add-ons so we can start re-building out the IDL site
