### ISSUE TITLE
Website_Component_Color_Token_Display

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#618]
## Color Token Display Component for Color Elements Usage page

Sketch file: https://ibm.box.com/s/chioa7y5gzz91i7iaf8oepryw67vgggu

<b>Purpose: </b>

> This component marries up swatch copy functionality of current Carbon with a table of color tokens; it will live under the Usage tab on the Color Elements page. 

> Tokens values change depending on which color theme the user chooses with the Content Switcher component above (spec'd out in issue # XXXX )

> This component is shown at each breakpoint and also uses the right aligned Overflow experimental component 

<b>Specs: </b>

![specs](https://user-images.githubusercontent.com/43144260/50563546-60a44a80-0ce3-11e9-921a-43cca87a8814.png)

![Overflow_specs.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/6e09e94d-fd23-415a-b9b0-8905b99104d1)

<b>Breakpoints: </b>

1584

![color_token_component 1584](https://user-images.githubusercontent.com/43144260/50563553-6ef26680-0ce3-11e9-8550-77a1795606d6.png)

1056

![color_token_component 1056](https://user-images.githubusercontent.com/43144260/50563556-74e84780-0ce3-11e9-90f1-1fe6549e8d96.png)

672

![color_token_component 672](https://user-images.githubusercontent.com/43144260/50563561-7d408280-0ce3-11e9-90b3-4aad51a8d31a.png)

Mobile

![color_token_mobile_revised](https://user-images.githubusercontent.com/43144260/50909482-891dfa00-13f1-11e9-851d-aee1d0fe8344.png)

<br>

<b>Usage tab in context: </b>

1312

![color in ui_swatches_1312](https://user-images.githubusercontent.com/43144260/50563568-8af60800-0ce3-11e9-8175-57a4beea503f.png)

**Comment by alisonjoseph** [comment]
@jeanservaas to update mobile styles

**Comment by jeanservaas** [comment]
@marijohannessen 

Hey Mari, just wanted to let you know that I updated the mobile view of this to a suggestion that @alisonjoseph made to make it a lot more functional. Thanks!
