### ISSUE TITLE
Giph for Inline loading component image on the Style tab.

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#619]
We need to include a giph for the Placement section on the Style tab for the Inline Loading component.
 - [x] Show secondary and primary button next to eachother
 - [x] Show a color change of the user clicking the primary button
 - [x] Show loading animation and confirmation check

Link for reference (bottom of page):
https://www.carbondesignsystem.com/components/inline-loading/style

**Comment by shixiedesign** [comment]
### Finished Gif 
![motion_inline-loading_v10](https://user-images.githubusercontent.com/15144993/50876507-05cdbb80-1393-11e9-9eb4-9d594c7e49c1.gif)

**Comment by designertyler** [comment]
@shixiedesign I added the gif to the page in this [PR](https://github.com/carbon-design-system/carbon-website/pull/754) You can see it here https://deploy-preview-754--carbon-website.netlify.com/components/inline-loading/style#placement

Let me know if this looks ok!

**Comment by shixiedesign** [comment]
Thank you Tyler! Looks great :D Closing this issue.
