### ISSUE TITLE
Carbon X Website — Guideline — Color Page

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#621]
## Color Page Guidance — Content

Right now content pulls heavily from IDL language, with Carbon language folded in around tokens and themes; Copy around interaction states and UI Color Theme zones is especially weak and we will need to talk to dev about how multiple themes can be implemented in one UI before we can write the guidance.

- [ ] Streamline content so it looks like it comes from one source and makes sense; interaction states and guidance around theme zoning need more attention 

- [ ] Make sure that Accessibility content on this page matches accessibility content on the accessibility page (see issue: #571)

- [x] Attach page designs and sketch file for visual reference

- [ ] Finalize image assets and attach them here (possibly need video piece to show zoning) @jeanservaas

**Comment by jeanservaas** [comment]
## Color Page Guidance

Sketch file: https://ibm.box.com/s/claw9cl7qoos8oc420frytpkecrkyg7y

Color Usage values for color themes: https://ibm.ent.box.com/notes/365968650341

**Comment by claycrenshaw** [comment]
@jeanservaas I took a first pass at this; my comments are in purple in the PDF. These are more structural and don't really address the actual wording. Once the page is in MD I'll review and make edits as needed for grammar, style and flow.

PDF: https://ibm.box.com/s/4aduw3krpc1s31uinc758uudv7kqkz44
