### ISSUE TITLE
The breadcrumb sketch symbol doesn't allow for you to change the color state of the page your on

### ISSUE THREAD

**Issue by steviesharp123** [carbon-design-system/carbon-website#625]
The breadcrumb sketch symbol doesn't allow for you to change the color state of the page your on. Changing from the blue text to the black text. The website reflects this pattern but the symbol doesn't allows it

**Comment by aagonzales** [comment]
@steviesharp123  I believe you're referring to the "current page" styling for breadcrumb and it is nested in the states layer.

![image](https://user-images.githubusercontent.com/11670886/76804572-9d564780-67aa-11ea-8b0d-6901087a1afb.png)
