### ISSUE TITLE
Add UI objects / elements examples to Capitalization section

### ISSUE THREAD

**Issue by joshhus** [carbon-design-system/carbon-website#627]
https://www.carbondesignsystem.com/guidelines/content/guidance#capitalization

## Detailed description

There can be hair-splitting confusion among UI designers, devs, writer, and editors, et al., about how, with respect to word capitalization, to both a) refer to object or element names in the UI (capitalize the words or not) and b) how to capitalize them in the UI (sentence, initial, caps etc. )

This confusion especially applies when the word for a UI element is BOTH a general common noun or term outside of a UI, IN ADDITION to being a specific term used in a UI instance. ... For example, the words "type" and "category" can be used as a UI object / element - as heading names for a text entry field or drop-down box - and these should be capitalized as "Type" and "Category" ... afaik.

Then in text / help we can write to "You must select a Category and Type, and click Save." The caps / Proper Noun both identifies the object as a proper noun and indicates to the reader that Category and Type are formally defined objects in the UI. ... 

(In addition to the Save button - and while I have you, afaik we don't refer to the UI object type any more? i.e it's "Click Save" not "Click the Save button"?) thanks.

ALSO need clarity / examples when the UI object heading is MORE THAN ONE WORD, such as "Document Category" and "Document Type" in the same UI page. (I believe that initial caps is correct, rather than sentence style "Document category" and "Document type".)

Thanks for clarifying this with some examples in https://www.carbondesignsystem.com/guidelines/content/guidance#capitalization  !!

**Comment by joshhus** [comment]
Proper noun vs. common noun definition - the difference is referring to a specific instance (proper noun) or rather a general usage (common noun) - https://www.grammarly.com/blog/proper-nouns/

**Comment by aagonzales** [comment]
FYI @janchild

**Comment by janchild** [comment]
Closing. These questions were addressed in recent updates to the capitalization section of the content guidelines.
