### ISSUE TITLE
v10 website 404 page

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#631]
Design issue for the updated 404 page for v10

https://www.carbondesignsystem.com/404/

https://next.carbondesignsystem.com/404/

![Screen Shot 2019-01-03 at 1.29.02 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/5cea3a67-2217-4608-9287-71c49dc17370)

**Comment by alisonjoseph** [comment]
Shouldn't be any issues from a dev perspective building either design out.

**Comment by shixiedesign** [comment]
# Finalized 404 design 

Mike and Sadek gave feedback and we made a few tweaks. Below is finalized for Pre-THINK
**Dark version being the chosen one. Light for future if needed.** 

Sketchfile: https://ibm.box.com/s/l8iovulo9lotvltkti09qna2b471kl1b

![image](https://user-images.githubusercontent.com/15144993/50926665-31948400-141b-11e9-9a37-08f7cdbe2c08.png)

**Comment by shixiedesign** [comment]
Dev issue created #663. Closing this issue.

**Comment by shixiedesign** [comment]
We might potentially bring back diagonal in the future even though diagonal is a "Don't do" in our guideline, to highlight the concept that "things have gone all wrong!"
![image](https://user-images.githubusercontent.com/15144993/50928748-1dec1c00-1421-11e9-8847-0403c21cdce7.png)

**Comment by wonilsuh** [comment]
@shixiedesign this is awesome. The repeating background might be a bit overwhelming. How about Plex mono, since it's a technical thing?

<img width="1312" alt="screen shot 2019-01-19 at 6 03 40 pm" src="https://user-images.githubusercontent.com/1081064/51433260-b69a4d00-1c14-11e9-945d-6bb751db2c5b.png">

**Comment by shixiedesign** [comment]
@wonilsuh right this is a good opportunity to feature mono! I will try a few things after this sprint.
