### ISSUE TITLE
Change MD mapping to correctly render headings on site

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#635]
Our MD mapping seems to be off when it comes to headers. 

[ ] Determine the intended type tokens for 2nd, 3rd, and 4th level headers on site
[ ] Create a table for mapping the hashtags we use in MD to those tokens
[ ] Deliver table of changes to Dev

**Comment by alisonjoseph** [comment]
This is what we currently are using in the site, this was recently updated and confirmed w/ @jeanservaas 

|---	|---	|---	|
|  h2	|  expressive-heading-04  	| `## h2` |
| h3  	|  heading-03 	| `## h3` |
|  h4 	|  heading-02 	|  `## h4` |

**Comment by claycrenshaw** [comment]
Oh awesome, didn't know this was already fixed! Thanks @jeanservaas :)
