### ISSUE TITLE
Data Table -- add guidance for sorting patterns

### ISSUE THREAD

**Issue by mwinsby** [carbon-design-system/carbon-website#64]
## Summary
On the Data Table page, please include a source of recommendations for different data types that correspond to “ascending/up” and “descending/down” arrows, and perhaps even what a suggested default direction would be for said data types.

Even something simple like “A-Z = up arrow” and “newest to oldest = up arrow” (if that’s true) would be helpful. 

Also adding a line for designers that sorting is not included in the code, so they probably need to define sorting behavior for their devs. (As a designer, I assumed there might be some default sorting logic already present in the code for the table, but this is not true.)

Lastly, adding more description of the tri-state-sort behavior that is currently present would be helpful for designers as well. And maybe some reasoning for this odd tri-state-sort behavior (I'd want to see a persistent arrow present for whatever column is currently sorted - to not be able to see a sorted table with no arrows). It's not super clear how the sort arrows work in the code, since the sort examples on the page aren't functional. I did not know this was how the component was written, and I assumed it was a bug when I saw the developed table in our product. 

## Relevant information

The Usage tab on the Data Table page has a tiny section on Sorting, which is the perfect place for the guidelines. https://www.carbondesignsystem.com/components/data-table/usage

**Comment by aagonzales** [comment]
The data table page have been updated to include documentation for sorting. See: https://carbondesignsystem.com/components/data-table/usage#sorting

If this does still not fulfill your needs please comment and we will reopen.
