### ISSUE TITLE
Developer Tutorial

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#640]
In addition to the developer getting started information, it would be nice to have a tutorial that takes you from an empty directory to a functioning application that uses a few components.

It'd be great to do this in a way that doesn't require a lot of maintenance/upkeep for each future Carbon release.

### Questions

(1) Should this be for just Carbon vanilla, React, Angular, or for all current Carbon implementations? If for all, would we have 3 nearly identical tutorials? Or many one tutorial where you can choose vanilla/React/Angular and it'd show relevant instructions and code snippets?

(2) Do we prefer one long tutorial that lives in the Getting Started section? Or, a multi-step (multi-page) tutorial that gets its own top-level Tutorial section between Getting Started and Guidelines?

(3) Do we have sample component copy so the tutorial aligns with the rest of the site? Or, should the tutorial build a web app for a fictitious company?

(4) Any related requests (here, or in Slack channels) that could influence what the tutorial demonstrates?

**Comment by claycrenshaw** [comment]
Hey Matt, great idea on this.

I'll throw in $.02 for your questions. . .

1) If it makes sense from the POV of the developer-user, I think that the second option here would be easier to maintain over time.

2) To me, a tutorial would fit very nicely under Getting Started in the nav. This would not necessarily preclude a multi-page solution, either.

3) To my knowledge we don't have any kind of comprehensive "fictitious company" content established across Carbon (I think we may have bits and pieces scattered around), but it would be a good thing to have! I'd be happy to help with this if you need any. . .

**Comment by shinytoyrobots** [comment]
#1 - Tutorial where you can choose your framework implementation. That then places the onus on teams building other Carbon solutions than vanilla/React to add documentation pieces relevant to their implementation.

#2 - Arguably that can go the other way round - and "getting started" could end up within a broader "docs" section. Gatsby is a good model for this - https://www.gatsbyjs.org/docs/ - has different write ups for different audiences. But need to balance the dev doc vs the design doc.

#3 - I like the idea anyway (and @jeoffw and I have discussed) of sample apps, and that could be the good basis for a tutorial.
