### ISSUE TITLE
update[banner height]: match carbon banner height to IDL banner height

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#643]
## update[banner and leadspace height]: match carbon banner and leadspace height to IDL 

- [ ] **banner**
All of these geometries should match; the Carbon banner looks unnecessarily short; Please match banner height and all relationships within including the H1 and the tabs.

![image](https://user-images.githubusercontent.com/43144260/70178872-a19aa100-16a2-11ea-8c0c-594415cc6810.png)

- [ ] **leadspace**

![image](https://user-images.githubusercontent.com/43144260/70182613-ca726480-16a9-11ea-9bfb-43a1cb06aa03.png)

**Comment by mjabbink** [comment]
We should get this done before years end.
