### ISSUE TITLE
Fix unit spacing across the board

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#644]
There are many many instances on the Carbon site where we refer to pixel sizes like this: (24px). IBM style calls for a space between the value and the unit. The correct way is: (24 px).

Recommend doing a regular expression find/replace on the entire site for all instances of "Xpx" where X is any numeral, and replacing the "X" with "X ".

**Comment by joshblack** [comment]
Is there a way we could get around the style recommendation? Would hate for folks to copy and paste the value and then have to format it in order for their design tool / code to recognize it.
