### ISSUE TITLE
Website: Style tab -- theme switcher designs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#648]
Need designs for how to switch between themes on the style tabs

**Comment by aagonzales** [comment]
Doing default white images for now. Will ideally have a theme switcher in there eventually.

**Comment by aagonzales** [comment]
Blocker: waiting for final theme switcher

**Comment by jeanservaas** [comment]
## Sticky Content switcher spec for Style tab

Sketch file: https://ibm.box.com/s/7wegf03bnnsjmh9vf0bkjprl49cyob6a

- This is basically the same website component with sticky functionality that was spec'd here for the color usage page
https://github.com/carbon-design-system/carbon-website/issues/1186

### Context (Sticky zone)

<br>

![content_switcher_style_tab_context](https://user-images.githubusercontent.com/43144260/53974700-be308b00-40c8-11e9-8aca-4f7d391517ab.png)

<br>

### Theme change visuals

![image](https://user-images.githubusercontent.com/43144260/53974762-f1731a00-40c8-11e9-8ce8-4410b037e92b.png)

![image](https://user-images.githubusercontent.com/43144260/53974816-14053300-40c9-11e9-94bb-b074a49c6a19.png)

![image](https://user-images.githubusercontent.com/43144260/53974884-39923c80-40c9-11e9-959d-e9b6ff9ebc7e.png)

<br>

### Breakpoint specs


<br>

**1312**

![1312_breakpoint](https://user-images.githubusercontent.com/43144260/53975075-a86f9580-40c9-11e9-95b8-ec97468122da.png)

<br>

**1056**


![1056](https://user-images.githubusercontent.com/43144260/53975219-f71d2f80-40c9-11e9-9642-c1f7642db981.png)


<br>

**Tablet**

![content_switcher_component 672 copy](https://user-images.githubusercontent.com/43144260/53975163-d523ad00-40c9-11e9-9e36-3a6c2a40ced4.png)

<br>

**Mobile**

![content_switcher_mobile copy](https://user-images.githubusercontent.com/43144260/53975124-be7d5600-40c9-11e9-941e-c826979d97af.png)

<br>

## Sticky scolling behavior

<br>

**1312**

![style_tab_sticky_behavior](https://user-images.githubusercontent.com/43144260/53975370-44010600-40ca-11e9-932d-d94d0f7adb7b.png)


<br>

**1056**

![content_switcher_component 1056_scroll](https://user-images.githubusercontent.com/43144260/53975321-2c298200-40ca-11e9-8452-4772f55cf0d7.png)

<br>

**Tablet**

![content_switcher_component 672 scroll](https://user-images.githubusercontent.com/43144260/53975444-71e64a80-40ca-11e9-96af-c4f4ca749d82.png)

<br>

**Mobile**

![content_switcher_scroll_mobile](https://user-images.githubusercontent.com/43144260/53975466-81659380-40ca-11e9-8f96-dce2b41220b7.png)
