### ISSUE TITLE
Pictogram and Icon library need an update to latest version

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#649]
The two libraries are not the latest version with sticky search. Should be the same whilst they’re both up I think.

**Comment by mjabbink** [comment]
or remove the Libraries? @jeanservaas I certainly don’t mind duplication but it seems to be a pain to keep up with unless it’s one page pushed out to two sites. I know Connors was of the mind to remove from Carbon. I think it’s useful but get the problem with duplication.

**Comment by chrisconnors-ibm** [comment]
While they both exist, they should be the same. I'm surprised they don't already use the exact same page code.

Whether they both exist longer term is a fair question. @alisonjoseph - what's the traffic look like to 

https://www.carbondesignsystem.com/guidelines/icons/library/
vs
https://www.ibm.com/design/language/iconography/ui-icons/library/

?
