### ISSUE TITLE
Heading pseudo-element is affecting tile click targets

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#649]
In v10 branch, try clicking "complete list of resources" link. You can't because the Carbon Components tile's `h5` expands above the top of the tile. See screenshot.

![image](https://user-images.githubusercontent.com/1691245/50799197-ae4f2300-12a0-11e9-98d6-87425d9a215f.png)

**Comment by mattrosno** [comment]
@alisonjoseph I don't think this is fixed. I just experienced this here, where I could only click the top portion of the "useState" anchor, because the h5 pseudo-element is impeding.

![image](https://user-images.githubusercontent.com/1691245/59218318-9815fd80-8b85-11e9-96db-fb7406fd23e8.png)

**Comment by alisonjoseph** [comment]
not stale

**Comment by alisonjoseph** [comment]
non-issue in updated website using the theme
