### ISSUE TITLE
[docs] Create and add contextual component images

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#65]
Our images for components, specifically variations, just float in space. We've been repeatedly asked for this.

Related to this proposal: https://github.com/carbon-design-system/carbon-website/issues/1587

## Components

- [ ] Accordion
- [ ] Breadcrumb
- [ ] Button
- [ ] Checkbox
- [ ] Code snippet
- [ ] Content switcher
- [ ] Data table
- [ ] Date picker
- [ ] Dropdown
- [ ] File uploader
- [ ] Form
- [ ] Inline loading
- [ ] Link
- [ ] List
- [ ] Loading
- [ ] Modal
- [ ] Notification
- [ ] Number input
- [ ] Overflow menu
- [ ] Pagination
- [ ] Progress indicator
- [ ] Radio button
- [ ] Search
- [ ] Select
- [ ] Slider
- [ ] Structured list
- [ ] Tabs
- [ ] Tag
- [ ] Text input
- [ ] Tile
- [ ] Toggle
- [ ] Tooltip

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
