### ISSUE TITLE
Enhancement[Video Component]: Making video component more robust

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#651]
@shixiedesign commented on [Wed Jan 02 2019](https://github.com/IBM/carbon-elements/issues/216)

- [ ] custom play button
- [ ] caption support
- [ ] need to support mulitple aspect ratios

Dev issue for issue https://github.com/carbon-design-system/carbon-website/issues/473

![image](https://user-images.githubusercontent.com/2753488/50643267-2b8e3700-0f33-11e9-99ce-136a4bb0a8ab.png)

**Comment by alisonjoseph** [comment]
Move from `/src/components/` to `/packages/addons-website/src/`

- [ ] move video component to addons
- [ ] add placeholder "start" image (on IDL site currently)

**Comment by shixiedesign** [comment]
I think we can close for now and we will make bug fix issues if there are more improvements needed.
