### ISSUE TITLE
ui-shell-* documentation goofed up?

### ISSUE THREAD

**Issue by dryhurst** [carbon-design-system/carbon-website#654]
hello. 

the pages for 

https://www.carbondesignsystem.com/components/UI-shell-header/code

https://www.carbondesignsystem.com/components/UI-shell-left-panel/code/

and 

https://www.carbondesignsystem.com/components/UI-shell-right-panel/code/

are goofed up. i don't think the iframes are working properly. im in chrome and i've tried it on both a osx and windows 10 machine. 

i checked the iframe sources and they work fine. dunno what's up with this, but thought you should know 

here's a screenshot: 
![image](https://user-images.githubusercontent.com/1443017/70404076-772c4900-19fe-11ea-92bc-e57fdee9a96d.png)

**Comment by aagonzales** [comment]
It does take a minute for them to load. However, we're also currently working on a new component demo window which will hopefully fix these problems.

**Comment by vpicone** [comment]
Yeah, it just takes a sec for that to load, it's essentially loading 5 different pages at once.
