### ISSUE TITLE
Use "px" instead of "pt" in website documentation

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#66]
The v10 guidance page on iconography uses `pt` in an image and the image's caption. `pt` font unit does not get used in product development. Replace with `px`.

https://next.carbondesignsystem.com/guidelines/iconography/usage

![image](https://user-images.githubusercontent.com/1691245/50981617-01072580-14c1-11e9-95c4-7799507329aa.png)

**Comment by joshblack** [comment]
Should be good to go! Going to close this one out
