### ISSUE TITLE
Codepen Example for mid-line truncation has errors

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#664]
There are alignment issues in the codepen example here.

Should this be removed or updated for v10?

https://next.carbondesignsystem.com/patterns/overflow-content#mid-line-truncation
![screen shot 2019-01-09 at 3 29 34 pm](https://user-images.githubusercontent.com/19270502/50929660-69072e80-1423-11e9-871b-464486218663.png)

**Comment by designertyler** [comment]
@alisonjoseph This isn't high priority but still shows broken on the site. Should I remove this example in the meantime?

**Comment by tw15egan** [comment]
I can fix this today
