### ISSUE TITLE
Components do not appear in website search results

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#667]
![Screen Shot 2019-01-10 at 8.03.29 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/e660e302-4a64-4a54-b961-f276c3d01288)

https://ibm-studios.slack.com/archives/C0M053VPT/p1547046527069400?thread_ts=1546978914.059500&cid=C0M053VPT

![Screen Shot 2019-01-10 at 8.01.26 AM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/9d51b81f-06dc-460b-b504-f106937f5bcb)

**Comment by alisonjoseph** [comment]
Opened another issue https://github.com/algolia/docsearch-configs/issues/756
