### ISSUE TITLE
missing $inverse-link on notification style page

### ISSUE THREAD

**Issue by eraymond25** [carbon-design-system/carbon-website#669]
## Detailed description

Missing information on the [Notification usage page](https://www.carbondesignsystem.com/components/notification/style) of the $inverse-link token needed for the actions on the high contrast. Also, notification is rendering action links not accessible. 

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected the link to be Blue-40, but it looks like it's Blue-60 and there is no information about notification links on the usage page.

> What browser are you working in?
Chrome

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
IBM Cloud Kubernetes. All of Cloud is moving to this soon and we use notiffications a ton!

## Steps to reproduce the issue
https://demo3.console.test.cloud.ibm.com/kubernetes/clusters

## Additional information
<img width="908" alt="Screen Shot 2019-12-11 at 9 25 24 AM" src="https://user-images.githubusercontent.com/12436158/70634838-8971d700-1bf8-11ea-9aa8-783e2bea1e7f.png">

**Comment by abbeyhrt** [comment]
Hi! @eraymond25! Thanks for making this issue! We have addressed and fixed the link color being inaccessible in a notification in https://github.com/carbon-design-system/carbon/pull/4805, so thankfully a solution is in newer version of Carbon. We are updating our component docs now so the missing information should be added soon!
