### ISSUE TITLE
Need solution for stray sentences top of page

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#671]
Either a content or design solution is needed to better contextualize the stray sentences at top of every component page. 

![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/e902495d-24ea-4ca8-bd02-c807665b47b1)

**Comment by alisonjoseph** [comment]
Closing this as I believe we agreed to start each page w/ a heading and not these stray sentences. Feel free to re-open if still an issue.
