### ISSUE TITLE
Spacing page spacer color should be Teal20

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#674]
On Spacing page, spacers squares should have Teal20 instead of whatever it is now. 
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/bfadc2d1-f3c9-4901-b507-fe6dca8a0be6)

**Comment by aagonzales** [comment]
PR: https://github.com/carbon-design-system/carbon-website/pull/858
