### ISSUE TITLE
Elements Package: Color Link Broken

### ISSUE THREAD

**Issue by saint-justin** [carbon-design-system/carbon-website#68]
## Description

> Describe in detail the issue you're having.
The link to the elements package for color is broken.

> What browser are you working in?
Chrome (Current stable build)

1. Visit [/guidelines/color/overview](https://www.carbondesignsystem.com/guidelines/color/overview)
2. Scroll to "Resources"
3. Click "Elements Package: Colors"

**Comment by alisonjoseph** [comment]
confirmed this link has been fixed
