### ISSUE TITLE
Update older dataviz developer instructions

### ISSUE THREAD

**Issue by theiliad** [carbon-design-system/carbon-website#681]
1. Update `BarChart` examples to use `StackedBarChart`
2. Update charting options & data examples

**Comment by theiliad** [comment]
@alisonjoseph How would I self-assign this issue? Not seeing the option to do that

**Comment by alisonjoseph** [comment]
Assigned you, not sure why you couldn't self-assign? Maybe github being weird? Or a setting we need to change?

**Comment by theiliad** [comment]
> Assigned you, not sure why you couldn't self-assign? Maybe github being weird? Or a setting we need to change?

It's a permissions issue, not sure what sort of permission I have on this repo

**Comment by theiliad** [comment]
And thanks 🙂

**Comment by alisonjoseph** [comment]
Invited you to "maintainers" team for Carbon website, should have permissions to assign yourself to issues now I think. 🤞

**Comment by theiliad** [comment]
yes I see the options now, perfect thanks!
