### ISSUE TITLE
Image Component

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#683]
### Image component requirements (revisited by Shixie)

- [ ] Caption support. Ref Jeanie's comment below for spec https://github.com/carbon-design-system/carbon-website/issues/683#issuecomment-454586014
- [ ] Need a way to specify how many columns an image should span. 
We only need 4 options: `lg=12 col` ,`md=8 col`, `sm=6 col`, `xs=4 col` (these are values at max breakpoint. More detail see below image or https://github.com/carbon-design-system/carbon-website/issues/524)
![image](https://user-images.githubusercontent.com/15144993/51349875-57013d80-1a6c-11e9-97c4-7ca17d224fcb.png)

- [ ] An option to turn on-off "on grid". fixed (has a max pixel width and max-width 100%) vs. fluid (scales on grid)

- [ ] Default images in Markdown eg. `![caption](image-url)` should have `md` size if landscape, `sm` size if portrait.

**post-THINK**

- [ ] A way to turn on the ability to "onClick to view large" in a modal
We would need for component spec images coz specs are usually small and hard to read, not necessary for all images). The ideal experience is to expand the image in a modal (instead of in a new Tab because it will be missing background). This is also good in preparation of future iteration of "live spec"

**Comment by jeanservaas** [comment]
Hey @alisonjoseph 

I see the caption support box checked above and I was wondering if you added a caption piece to the images... if so I want to review it here vs. making a new issue for it.

This is your caption update, just a couple of feedbacks:

- token we should be using is $body-short-01 (so it's the 1px at the 18px line height; current line height looks bigger)

- also, we need 8px of padding above the caption (or below the image); right now it is too tight on the image

- Caption color looks a little light right now, it will be #171717 (G100) just like body copy

- and we need to control the line width with some right padding (see example) (line width will match line width of Do / Don't component

![image-4](https://user-images.githubusercontent.com/43144260/51215650-3e1b4f80-18e7-11e9-80bb-f22d8f775d97.png)

**Comment by alisonjoseph** [comment]
@jeanservaas will push up a fix now! thanks for the feedback

**Comment by shixiedesign** [comment]
Reviving this issue because the Image Component turns out to be a big one. Here are the updated list of features needed for <image></image> component: 
- [ ] caption styling
- [ ] sizing support (at max breakpoint, our 4 widths options are `lg=12 col`, `md=8 col`, `sm=6 col`,` xs=4 col`)

**Comment by marijohannessen** [comment]
I made an attempt on this component but I don't know how to get the img URL's from the markdown passed to the custom component and being able to get the right path. Cause if we pass `/images/image-1.png` then that path is wrong when we use it in the custom component. Because of the Patterns work I'm helping out with, I don't know if I will have time to figure this out and make this component after all 😞 Does anyone have an idea of how we could do this? @alisonjoseph @tw15egan

**Comment by alisonjoseph** [comment]
This is something I struggled with when building other custom components, the solution we are using for tiles and the do-dont components is to nest the image inside it and then just reference `{children}` in the component. 

```
<component>

![image](images/image.png)

</component>
```

Definitely not ideal, would be much cleaner to just be able to add the url as a prop.

**Comment by marijohannessen** [comment]
Okay, I can give that a try!

**Comment by marijohannessen** [comment]
That worked! I'm going to assign it to myself again and see if I can get to a good spot today :)

**Comment by alisonjoseph** [comment]
you rock! thank you 🙌
