### ISSUE TITLE
New PAL site page with links

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#687]
We need a page that houses links to all of the internal PAL sites. 

To discuss:
* Live as a standalone page, or 
* Link off from Carbon site (with access control for only internal visitors) 

List of links:
*PAL sites*
* Cloud Integration: https://pages.github.ibm.com/ide-design-guidelines/ide-design-guidelines-v2/
* Cloud PAL: https://pages.github.ibm.com/ibmcloud/cloud-ux-patterns/
* Watson Health: https://pages.github.ibm.com/Watson-Health/index.html
* Watson IoT: https://pages.github.ibm.com/Watson-IoT/IoT-Design-Site/
* Watson IoT (InVision): https://ibm.invisionapp.com/share/U2NYW8D7DFV#/screens/319100255
* Security Experience Guide: https://security-design-guide.stage1.mybluemix.net/
* Hybrid Cloud (Deprecated?): https://hc-design.w3ibm.mybluemix.net/design-system

*Storybooks*
* Security: https://ibm-security.carbondesignsystem.com
* IoT: https://carbon-addons-iot-react.com/?path=/story/getting-started-welcome--about-storybook

### IBM Domain-specific Guidance

This page includes domain-specific guidance for teams building IBM products. The focus of this work is on specific solutions for different domains. 

The goal is to ensure that work is accessible to everyone, and provide an opportunity for teams to share their work.

For universal patterns that apply across all domains, see the [Carbon patterns](https://www.carbondesignsystem.com/patterns/overview).

**Comment by janchild** [comment]
@connor-leech and @alisonjoseph,  I've added the copy for the page in the summary above.

**Comment by alisonjoseph** [comment]
Added a page in a PR here https://github.ibm.com/Design/w3-design-new/pull/306

**Comment by janchild** [comment]
This is now live on the design site: http://design.w3cloud.ibm.com/design/resources/domain/
