### ISSUE TITLE
Broken link on pagination page

### ISSUE THREAD

**Issue by 3dfoster** [carbon-design-system/carbon-website#70]
In the pagination section of the usage tab for data tables there is a link for paginated tables but it is broken. The link points to https://www.carbondesignsystem.com/components/Pagination but the *p* in pagination should not be capitalized so it 404's.

The broken link can be found here: https://www.carbondesignsystem.com/components/data-table/usage#pagination

<img width="857" alt="Screen Shot 2019-08-08 at 2 49 34 PM" src="https://user-images.githubusercontent.com/13704150/62733276-dd22a880-b9eb-11e9-94a7-5d544841a738.png">

**Comment by abbeyhrt** [comment]
Thanks for making this issue! Thankfully, the broken link has been fixed so I'm going to close this issue!
