### ISSUE TITLE
Website H4 class needs margin bottom 

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#704]
## H4 class butting up against images and components

> This most commonly occurrs on all of the Components pages (the grab below is from the Code tab) when the H4 is used in conjunction with the Code Snippet component. This is a problem because it affects the hierarchy and the legibility of all of these pages.

> I don't think this is a bug, this may be because Design did not spec the correct margin bottom for H4

> I'm not sure if this just happens when H4s are used with Code Snippet or if it's across the board.

> This happens in Chrome, Safari and Firefox

> Anna took a grab of this page on the repo and you can see the margin bottoms exist there and the page is much more legible.

<br>

Now:

![image](https://user-images.githubusercontent.com/43144260/51192029-3e95f500-18ab-11e9-85cf-11362b68b0d4.png)

<br>

Spec (whether it's a code snippet or an image, we'd like to see a 16px margin bottom on the H4:

![image](https://user-images.githubusercontent.com/43144260/51191823-d6471380-18aa-11e9-82c9-2f4e24b9e7d2.png)

## Larger grab of repo and page side by side

![image-2](https://user-images.githubusercontent.com/43144260/51191560-499c5580-18aa-11e9-9ae1-9ce4136bbb9c.png)

**Comment by alisonjoseph** [comment]
fix is in a PR, some of these headings are h5s (from our readme files in carbon components) for some reason. Updated to display the same on the site for now. Will have to re-think in future if we end up with a use for h5.

**Comment by jeanservaas** [comment]
Cool! Yeah, right now our system has no H5, so if we're using that class in markdown, we should get that out of there on our end. It was hard to tell where there might be markdown issues and where there were Margin bottom issues with this one.

**Comment by alisonjoseph** [comment]
@jeanservaas the only place we are using it is in the markdown being imported from `carbon-components` for the docs. I'll open a separate PR to fix that in that repo, then will auto update on the website. 

There were also margin-bottom issues, it was only 8px 😉
