### ISSUE TITLE
Website Banners not to Design Spec

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#708]
## Website Banners are not to spec

> There are several issues with the banner (some design, some display) that are happening across browsers, which is why it's getting a higher priority tag

<br>

## Banner update hit list

- [x]  Align tabs correctly: text within tabs need to align to the text on the rest of the site and the tabs need to hang into the gutter

<br>

<b>Spec:</b>

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/b312839c-4baf-4e97-92f3-23854a6b5f4a)

<br>

- [ ]  Mobile banner tabs should follow specs in this issue: https://github.com/carbon-design-system/carbon-website/issues/578#issuecomment-450960617

- [x]  At tablet (Md) breakpoint, the intro sentence at the top of the banners in the Guidelines section are spanning the entire browser); We need right margin padding here like every other breakpoint

<br>

<b>Problem:</b>

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/c350c0d1-0bdc-488f-8585-f29b1299b589)

<br>

<b>Spec @ 672:</b>

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/32b2b357-8c04-4527-8078-e4d69c2f517d)

- [ ]  The banner H1 type should be responsive (use fluid token: $Display-01)

- [x]  Add hover states to unselected banner items (they're not working now in any browser)

<br>

<b>Problem:</b>

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/09a4d2bb-414a-4be9-8f76-4c155de0d042)

<b>Spec:</b>

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/dc4d3c31-d885-4b57-a76c-1e3debb7d8d6)

<br>

- [x]  Fix browser display issue with the banner H1: right now the H1 looks like it's pulling in Plex Extra Light in Firefox and Chrome... it looks right in Safari... I'm wondering if the token change will fix this issue?

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/c37072b2-a016-4a60-a39c-1f57fe3daff9)

- [ ]  Ultimately tabs should be sticky to the top of the browser on scroll (as soon as you begin to scroll up again, top bar appears; This may not be doable until post-THINK

![image](https://user-images.githubusercontent.com/43144260/51214714-563d9f80-18e4-11e9-8621-39eb5afb111d.png)

**Comment by alisonjoseph** [comment]
Items not addressed in PR https://github.com/carbon-design-system/carbon-website/pull/714

- [ ] The banner H1 type should be responsive (use fluid token: $Display-01)
- [ ]  Ultimately tabs should be sticky to the top of the browser on scroll (as soon as you begin to scroll up again, top bar appears; This may not be doable until post-THINK
- [ ] Mobile banner tabs should follow specs in this issue: #578 (comment)

**Comment by alisonjoseph** [comment]
closing inn favor of #578
