### ISSUE TITLE
Certain components should be full screen at mobile (sm) breakpoint 

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#710]
## No margin at mobile breakpoint for these components:

- @alisonjoseph not sure if it's just better to deal with each of these situations in an issue related to that specific component vs. a list like this... if so, you can close this issue we can do it that way (since we do already have issues for a few of these components).

- Type spec component, overview display component, color token display component and code snippet (on certain pages) are all doing this correctly; these are the components that are not:

<br>

- [x] Banner tabs: no margin at mobile (already dealt with in issue #708)

<br>

- [ ] Icon display: no margin at mobile

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/c913535f-e9fe-4228-9695-4a335ce25a81)

<br>

- [x] Component display window / code snippet

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/3046371e-7d11-455d-9060-d3866de6f2f5)

<br>

- [x] Table: component: no margin at mobile

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/d18ef4b1-aa56-457b-8b5d-d0ee2596b75f)

**Comment by alisonjoseph** [comment]
Icon page hasn't been done yet, will leave that for that issue
