### ISSUE TITLE
Common actions pattern update

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#710]
- [ ] Update this pattern to follow the [latest pattern template](https://www.carbondesignsystem.com/how-to-contribute/pattern)

- [ ] Update images to follow the latest image production guidelines.

- [ ] Remove or link to duplicate content that is covered in other patterns (Cancel button, error states in forms_

**Comment by janchild** [comment]
Pattern reorganized into alpha order. Removed categories because they slowed users down.
