### ISSUE TITLE
Filtering pattern update

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#712]
### Next steps
- [ ] Update this pattern to follow the [latest pattern template](https://www.carbondesignsystem.com/how-to-contribute/pattern)
- [ ] Review any existing guidance found in the patterns audit. Also, look for search patterns that may contain filtering patterns. 
- [ ] Incorporate guidance feedback: https://github.com/carbon-design-system/carbon-website/issues/718
- [ ] Include a "When to use" table
- [ ] Tighten up intro paragraph
- [ ] Clean up IA

**Comment by connor-leech** [comment]
Please incorporate relevant content from Solly on the CD&AI team: https://github.com/carbon-design-system/carbon-website/pull/473
