### ISSUE TITLE
Loading pattern update

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#713]
### Next steps for copy cleanup:
- [ ] Update this pattern to follow the [latest pattern template](https://www.carbondesignsystem.com/how-to-contribute/pattern)
- [ ] Include references to Loading and Inline loading components
- [ ] Add reference to pattern to Loading and Inline loading component usage pages.
- [ ] Include a reference to Nielsen Norman documents
- [ ] Clarify the difference between each type of loading covered
- [ ] Define permissions, dependencies, and prereqs and include in When to use
- [ ] Progressive loading includes just loading pieces as they come in without visual placeholders. Include this as valid guidance.

### Follow-ups
- [ ] Talk to Josh about accessibility documentation
- [ ] Conduct an internal audit to confirm full coverage of loading types
- [ ] 

### To be addressed in v2

TBD

**Comment by janchild** [comment]
Work completed. See #814.
