### ISSUE TITLE
Filtering page: Bug report and feedback for revisions

### ISSUE THREAD

**Issue by cardwellrobert** [carbon-design-system/carbon-website#718]
## Title line template: Filtering - Bug report and feedback for revisions
> 1. Bug report.
Error in the "Resetting filters" illustration.

> 2. Feedback on "Filter applied” illustration 2.

> 3. Feedback on "Filter interaction" section.

Page link - https://www.carbondesignsystem.com/patterns/filtering/

## 1. Detailed description - Bug report

> Describe in detail the issue you're having.
I am confused by the illustration under “Resetting filters”. The illustration shows 1 checkbox (BBQ) with the applied filter bubble button with the number “2”. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug.

> What did you expect to happen? What happened instead? What would you like to see changed?
I would expect the applied filter button with the count of “1”. Also, because the illustration uses a skeleton illustration to the right, I cannot explicitly confirm that the criteria displaying is actually “BBQ” rather than BBQ being excluded. 

See also "Multiple categories" illustration uses has a count of “1”. It also uses skeleton results and is not explicitly clear that the criteria is displaying “BBQ” results.

> What browser are you working in?
Firefox

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Micromedex Mobile PWA. No pressing dates.

### Additional information

- Screenshots
https://www.carbondesignsystem.com/static/6463d6bde4072d3236ef35304a23f885/c801a/filter-7.png

See also:
https://www.carbondesignsystem.com/static/b356a7de040357b2d544d028902cd0f4/c801a/filter-3.png

## 2. Detailed description - Feedback on "Filter applied” illustration 2

> Describe in detail the issue you're having.
Second illustration in the “Filter applied” section shows the filter applied number as “2”.

> Is this a feature request (new component, new icon), a bug, or a general issue?
Bug (a suggestion, actually).

> What did you expect to happen? What happened instead? What would you like to see changed?
What I would like to see changed is the illustration showing either 1 or 3 checked boxes, rather than the current 2. Since there are 4 total checkboxes, it is not explicitly clear that the count of 2 is the number of boxes checked or unchecked. This is clear on the page for Dropdown - Multi select section - https://www.carbondesignsystem.com/components/dropdown/code/

> What browser are you working in?
Firefox

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Micromedex Mobile PWA. No pressing dates.

### Additional information

- Screenshots
https://www.carbondesignsystem.com/static/398a3e7dc4339ae3b0058c24dd73f297/c801a/filter-6.png

## 3. Detailed description - Feedback on "Filter interaction" section

> Describe in detail the issue you're having.
I would like to see greater clarity in this section. 

First off, I love that the “Starting state” section states:

- “Filters within each category should start either as all unselected or all selected.” Keep this.

Secondly, I do not think that this page should be a tutorial on faceted search IA and non-mutually-exclusive filters. But ambiguity could be addressed by answering the following questions in the content text:

- Does the checked box indicate that a criteria will display or be hidden?
- What will happen if all checkboxes are unchecked; what will happen of all the checkboxes are checked? (Or at least what is the general rule?).

I understand that these are tricky issues that the authors may have intentionally avoided, especially since “Filters within each category should start either as all unselected or all selected.” Here is an example from the REI e-commerce website:

START ALL UNSELECTED
https://www.rei.com/search.html?q=therm-a-rest+pads&ir=q%3Atherm-a-rest+pads&r=price%3A%240.00%20to%20%249.99%7C%2410.00%20to%20%2419.99%7C%2420.00%20to%20%2449.99%7C%2450.00%20to%20%2499.99%7C%24100.00%20to%20%24199.99

Looking at the example link, if you ignore all non-mutually-exclusive categories (on the left pane) and only look at “Price” (a mutually-exclusive filter), you will notice that the total number of returned results for this example is 13. If I check all checkboxes OR uncheck all checkboxes, the displayed results = 13. Checking all 5 checkboxes puts the applied filters as “Price (5)”. So in this simple example, checking a box causes the criteria to display, and increments the number of applied filters as the total checked boxes in this category. When at least 1 box is checked, any unchecked boxes are hidden on the results page. HOWEVER, if all boxes are unchecked, then all results display (no filter criteria, so the applied filters = 0). 

Addressing this “start all unselected” information may be good enough clarity. 

START ALL SELECTED
In my project, the start is All Selected. This is because I must show drug interactions with 2 or more drugs. My category groups are not parallel so the drug category requires a minimum of 2 checkboxes, whereas all other categories require a minimum of 1 checkbox. Essentially, it is not valid to uncheck all boxes like the faceted filter used by the REI example. So for my project, when all boxes are checked, the “applied filters” bubble button does not display; if one or more boxes are unchecked, then the applied filter displays with the count of all checked boxes. 

Addressing this “start all selected” information may be too much to include. 

> Is this a feature request (new component, new icon), a bug, or a general issue?
General issue.

> What did you expect to happen? What happened instead? What would you like to see changed?
Update the content text to address these issues.

> What browser are you working in?
Firefox

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?
Micromedex Mobile PWA. No pressing dates.

### Additional information

- Screenshots

- Notes

**Comment by emyarod** [comment]
hi @cardwellrobert thank you for opening this issue!

for your first point, the image will likely undergo some changes in the near future as we refresh our documentation for our v11 release!

as for your 2nd and 3rd points, since the pages have gone through some changes since you initially created this ticket, do you still feel confused about the page content and copy?

**Comment by cardwellrobert** [comment]
Hello emyarod:

It has been a while since I submitted this bug report, so I cannot remember
what my 2nd and 3rd points were. But reviewing the page today, I am glad
that the "Filter states" section indicates "each category should start
either as all unselected or all selected."

As for the images, they look better except the last image which has 1
checkmark and "2x" on the filter bubble button. This is confusing compared
to the other image examples on the page:





Thanks,

Robert Cardwell
User Experience Designer, Provider & Payer
IBM Watson Health™
6200 S Syracuse Way, Suite 300, Greenwood Village, CO 80111
303-486-9045 office
402-889-3642 mobile
***@***.***



From:	emyarod ***@***.***>
To:	carbon-design-system/carbon-website
            ***@***.***>
Cc:	cardwellrobert ***@***.***>, Mention
            ***@***.***>
Date:	06/07/2021 10:26 AM
Subject:	[EXTERNAL] Re: [carbon-design-system/carbon-website] Filtering
            page: Bug report and feedback for revisions (#718)



hi @cardwellrobert thank you for opening this issue! for your first point,
the image will likely undergo some changes in the near future as we refresh
our documentation for our v11 release! as for your 2nd and 3rd points,
since the pages have 


hi @cardwellrobert thank you for opening this issue!


for your first point, the image will likely undergo some changes in the
near future as we refresh our documentation for our v11 release!


as for your 2nd and 3rd points, since the pages have gone through some
changes since you initially created this ticket, do you still feel confused
about the page content and copy?

**Comment by emyarod** [comment]
thanks for following up. it's good to know that the page has improved since you first reported these issues and be on the lookout for more substantial changes as we get ready for the next Carbon major version release
