### ISSUE TITLE
Small image issues

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#720]
- [ ] Currently images are not scaling when browser shrinks. Images should flex with grid. We also want to support 4 different image sizes: 
Most images are `lg` (max width 1120px at max breakpoint).
Most do-donts are `xs` (max 352px at max breakpoint). I'm not sure if the best solution here is to wrap the images in a `<grid-wrapper>` (which I tried would work, just bad readability in markdown) or to improve the image component to make it respond the breakpoints. Here are our image sizes:

![image](https://user-images.githubusercontent.com/15144993/51274410-bc81fb00-1994-11e9-8791-8fd26df40288.png)

- [x] Do-don't component has a 4rem padding should be removed:
![image.png](https://images.zenhubusercontent.com/5be09c3a6102900c6d16d991/d0f44cf3-57f3-428f-99e3-20c9f27afdb9)

**Comment by alisonjoseph** [comment]
PR is open to fix the do-don't component. Images will need some more time to find the best solution. Using the grid wrapper doesn't work with captions currently.

**Comment by shixiedesign** [comment]
Tracking the other fix in https://github.com/carbon-design-system/carbon-website/issues/683
