### ISSUE TITLE
No bold in paragraphs, should be semi-bold (600)

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#723]
Bold type in paragraph should not be 700 weight. They should be semi-bold, or 600 weight.

![image](https://user-images.githubusercontent.com/15144993/51276965-d8d56600-199b-11e9-9ef4-4095d6d8dc1d.png)

**Comment by alisonjoseph** [comment]
@joshblack should this be fixed upstream in elements package or should I set `strong { font-weight: 600;` }` in the website?

**Comment by joshblack** [comment]
@alisonjoseph maybe we could include this as part of the reset? https://github.com/IBM/carbon-elements/issues/276
