### ISSUE TITLE
fix[Footer Component]: Align Carbon and IDL footers (form and function)

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#730]
## Align Carbon and IDL footers (Form and function)

- [ ] Add Previous / Next Functionality to homepage (if we don't have this that paragraph on the right looks like it's not aligned to anything else on the page, this is why / design moved the paragraph further to the right to align with the articles)

- [ ] Align spacing between IDL and Carbon (see spec below)

- [ ] make sure to pull $body-long-01 token for links in footer desktop (looks like $body-short-01 now)

Spec (add Prev / Next to homepage):

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/e2bfb5f3-984d-4c9b-8659-ab2f5cf1b887)

Spec (Spacing for **desktop,** Prev/Next spacing in correct, but the bottom needs updating):

![image](https://user-images.githubusercontent.com/43144260/52674609-b9bdeb80-2ee9-11e9-9c66-c15cfe678405.png)

Spec (Spacing for **mobile,** in case you need...):

![image](https://user-images.githubusercontent.com/43144260/52674854-76b04800-2eea-11e9-9d0a-be1f4ea05a04.png)

**Comment by jeanservaas** [comment]
@alisonjoseph @vpicone This something Mike wants alignment on for IDL and Carbon.

**Comment by jeanservaas** [comment]
need to move this over to gatsby theme repo

**Comment by mjabbink** [comment]
@jeanservaas @alisonjoseph does not look like the specs above are what was implemented. Does anyone have the specs/spacing for above the footer type in desktop and in mobile the space above the type between the rules?
