### ISSUE TITLE
docs: feedback for Login pattern

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#731]
Some feedback from Shani Sandy on the Login pattern:

**Feedback for Login**
**Split-screen layout**
Provide clear guidance related to additional content like marketing content that lives in the same screen as the login form otherwise discretion variance may result in content that is distracting, confusing, or off-brand. 
**Title**
To accommodate scalability and readability of Product names in the title “Log in to IBM [Product name].”
Consider alternative. An option: Log in (on one line) and Product name on another line/area in alternative styling
**Best Practices**
I notice that we aren’t extremely prescriptive with layout elements which may be unnecessary here or a moot point with provided code and allows for flexibility, but certain areas may need tighter qualification. Ex: “clear division” or “correctly sized”.  
Edit: Include forgot password and forgot ID ~~buttons~~ **links** near each of their respective text fields, rather than including them both on each page.
Edit: “Don’t make users sign in until it’s necessary.” – Need consistent term use - Log in vs Sign in
**Questions**
Is there supporting guidance on error handling or alerts?
What about instances when login requires designs other than a page layout: a modal? or embedded login like in a header?
Where are the considerations for other login permutations (like social)?

**Comment by aagonzales** [comment]
Work to be done:
   - Incorporate feedback from governance team
   - Updating visuals
   - Content review
   - Publish
