### ISSUE TITLE
Switch themes in component demos

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#74]
Dependent on https://github.com/carbon-design-system/carbon-website/issues/1736, implement the theme switcher.

Could also be dependent on how we support custom properties, if we rely on runtime theming to modify the component examples instead of having to set theme class names or CSS swapping.

**Comment by alisonjoseph** [comment]
closing in lieu of https://github.com/carbon-design-system/carbon-website/issues/357
