### ISSUE TITLE
Website component [color themes]: DL add-on for color overview page

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#740]
## Color Theme Component

This is basically the same structure as the icon display component -- it needs to be a component rather than an image because it has type inside of it that we don't want to scale down when the image scales.

<b>Spec: </b>

<br>

**1312**
![image](https://user-images.githubusercontent.com/43144260/53844374-1b162f00-3f6b-11e9-8ac0-c2606b4dab2b.png)

**1056**
![image](https://user-images.githubusercontent.com/43144260/53844525-94158680-3f6b-11e9-9619-de8368bddb72.png)

**Tablet**

![image](https://user-images.githubusercontent.com/43144260/53845486-f1f79d80-3f6e-11e9-9fe0-6a4a4f46338e.png)

**Mobile**

![image](https://user-images.githubusercontent.com/43144260/53845861-5109e200-3f70-11e9-8637-8055f9a52f08.png)

you can see it in context here:

https://w3.ibm.com/design/language/elements/color-ui/

**Comment by jeanservaas** [comment]
not stale @vpicone would this be considered a global element? IDL needs it and so does Carbon

**Comment by jeanservaas** [comment]
not stale

**Comment by jeanservaas** [comment]
Not stale

**Comment by jeanservaas** [comment]
This is not stale @alisonjoseph this is an IDL component

**Comment by alisonjoseph** [comment]
oooh I built this for IDL https://design-language-website.netlify.com/elements/color-ui#themes

we should be able to port it over
