### ISSUE TITLE
CLI Copy Button Problem

### ISSUE THREAD

**Issue by chuckderosier** [carbon-design-system/carbon-website#744]
## Copy button for the CLI copies the "$"

In the Step 1 of the Carbon Tutorial the copy button for CLI git commands copies the "$" so that when it is pasted into the CLI terminal the command does not work. I did not notice this until it was time to "git remote add upstream https://github.com/carbon-design-system/carbon-tutorial.git" as all the previous entries I had typed in manually.

**Comment by alohr51** [comment]
Noticed this same problem on the website with the [getting started install section](https://www.carbondesignsystem.com/get-started/develop/react#install). The copy icon copies the `$` in `$ npm install --save carbon-components-react carbon-components carbon-icons`
