### ISSUE TITLE
ComponentDemo enhancements

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#746]
This issue is to track what needs to be updated with the component demo windows.

**Comment by aagonzales** [comment]
- [ ] Button missing the feature to add an icon.
![image](https://user-images.githubusercontent.com/11670886/71852152-a980a300-309d-11ea-9740-d714ac1ced30.png)
![image](https://user-images.githubusercontent.com/11670886/71852164-b69d9200-309d-11ea-837a-27aece1583a2.png)

**Comment by aagonzales** [comment]
- [ ] Accordion `bx--accordion__content` is not using the correct font size in the demo but it is correct in the react story book. The title and content should be the same size, the content is appearing larger. 
![image](https://user-images.githubusercontent.com/11670886/71852382-31ff4380-309e-11ea-8007-b1772d040e3b.png)

**Comment by aagonzales** [comment]
### Checkbox

- [ ] **Enhancement**: Can we add at least one more in the list to show how they would stack.

**Comment by alisonjoseph** [comment]
We also need to add back the links to Angular/Vue/Vanilla (and maybe our React storybook & codepen) to these pages. 

@aagonzales would we just want those links similar to how they are now next to the "Edit in codesandbox" links?
<img width="492" alt="Screen Shot 2020-01-23 at 11 13 25 AM" src="https://user-images.githubusercontent.com/2753488/73007061-62025280-3dd1-11ea-95c0-126ddccafaf7.png">

**Comment by aagonzales** [comment]
Yeah that works or we can add a table under the demo, but without other content the table may feel out of place. 

![image](https://user-images.githubusercontent.com/11670886/73010357-e8219780-3dd7-11ea-9403-6c8e825dff86.png)

**Comment by vpicone** [comment]
@alisonjoseph let's open a seperate issue for that and use this one for content so @andreancardona can tackle it.

**Comment by vpicone** [comment]
@andreancardona In addition to the updates @aagonzales gave above, we need to just go ahead and implement out the initial content for all components not using the new component demo.

**Comment by vpicone** [comment]
## Dropdown concerns

We want to make sure we're accommodating all the Dropdown variants. Specifically, preventing jank when selecting items in Multiselect: https://github.com/carbon-design-system/carbon-website/issues/865

**Comment by aagonzales** [comment]
**General demo bug:**
Section dividers are missing between categories

**As-is:**
![image](https://user-images.githubusercontent.com/11670886/73480762-25e66900-4360-11ea-9284-6269125deed0.png)


**To-be:**
![image](https://user-images.githubusercontent.com/11670886/73480719-0fd8a880-4360-11ea-8d31-c6c29a28ad25.png)

**Comment by aagonzales** [comment]
Related: https://github.com/carbon-design-system/carbon/issues/4988

**Comment by aagonzales** [comment]
- [ ] Add full page feature
The option to expand the demo window to take up the full screen is missing. 
https://github.com/carbon-design-system/carbon-website/issues/357#issuecomment-538528000

![image](https://user-images.githubusercontent.com/11670886/73777729-98d05500-474f-11ea-80af-c3deab747b11.png)

**Comment by vpicone** [comment]
@aagonzales there's need for a new section for "alternates" or "variants". This would be the Storybook equivalent of 'stories', although we don't need to be nearly exhaustive with the variants we expose.

![Screen Shot 2020-02-04 at 2 57 02 PM](https://user-images.githubusercontent.com/4078018/73786378-c375da00-475e-11ea-80a6-1a973a7d3801.png)

These would be for essentially swapping out the playground code for entirely new code. This would be useful for compound components and components with related purposes but distinct markup:
- Datatable
- Dropdown/Multiselect/Combobox
- DatePicker
- Skeletons

I know we wanted to avoid dropdowns in this component, but I feel like it'd be useful here to have a meaningful ux difference between a "knob" that toggles a single prop and a "variant" which swaps out the code entirely.

**Comment by jnm2377** [comment]
> ### Accordion
> * [ ]  **Bug**: `bx--accordion__content` is not using the correct font size in the demo but it is correct in the react story book. The title and content should be the same size, the content is appearing larger.
>   ![image](https://user-images.githubusercontent.com/11670886/71852382-31ff4380-309e-11ea-8007-b1772d040e3b.png)

@aagonzales regarding the content type: it seems like the actual type styles are only being applied to `p` inside of the content. Which is not something we give any guidance on. We either need to add some docs about how anything inside the accordion item should be wrapped in a p tag, or we should apply that style to the accordion content selector and not the paragraph inside it (this would be something resolved in the monorepo, not the carbon website, if that's the case). For now, I'll just wrap the text in a `p`.

https://github.com/carbon-design-system/carbon/blob/f1bfad63dbd4ca88fa3a285dee34d3e32fc69949/packages/components/src/components/accordion/_accordion.scss#L96-L115
