### ISSUE TITLE
Accessibility — 3px top bars instead of 2px on Do / Don't component & Tabs

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#749]
## 3px top bars instead of 2px on Do / Don't component & Tabs

> Mike noticed that we pulled our spec for the 2px top bar on Banner tabs, website tabs and Do / Don't components from an old Duo file... the updated spec is a 3px top bar because people were having difficulty noticing it when it buts up against the browser window (for instance, when the banner tabs are sticky) or when there is photographic content in the Do / Don't component.

> This is a design enhancement related to accessibility

> The components affected are the Do / Don'ts; the website tab component and the banner tabs

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/4f722f86-8cd6-410b-9bcf-77d697aaf912)

**Comment by lovemecomputer** [comment]
<img width="743" alt="screen shot 2019-01-18 at 11 46 40 am" src="https://user-images.githubusercontent.com/3846271/51403753-02ff6300-1b17-11e9-8a87-74ce50c30214.png">

spacing token table has two of the small tokens equating to 2 or 4 pixels—curious if we want to set design guidelines to stick with these existing tokens? sounds like @jeanservaas is confirming.

**additionally—** should we incorporate accessibility guidance as content on the site, on the Spacing page, and/or on the Accessibility page?

**Comment by lovemecomputer** [comment]
does this guidance for the 3 px width also apply to `Tabs` or any other components? https://next.carbondesignsystem.com/components/tabs/code

If so, that would need a separate issue in the `carbon-components` repo. i just bring it up here in case this is something we need to universally document and make a special token for!

**Comment by lovemecomputer** [comment]
addressing this issue in `WebsiteTabs` in https://github.com/carbon-design-system/carbon-website/pull/699
