### ISSUE TITLE
request: Header and spec image for Modal

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#75]
### Request

1. I need a header image representative of a "modal." This does not have to be any specific variant, but representing a common use case is best.
2. I need a spec image to include in an "anatomy" section. The page currently has a format section. We will be switching to/creating "anatomy" sections for component pages. The [shell docs](https://deploy-preview-1679--carbon-website.netlify.com/components/UI-shell-header/usage) have good examples of a spec image.

![image](https://user-images.githubusercontent.com/44656921/58836435-744f3680-861e-11e9-86dc-c2799841a41e.png)

**Comment by aagonzales** [comment]
@connor-leech do you still need this? Which page is it for?

**Comment by aagonzales** [comment]
Ok I'm guessing since it's almost from a year ago that this isn't need anymore. @connor-leech re-open if you still need it.
