### ISSUE TITLE
[Page] Patterns overview: designs needs

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#751]
**Patterns overview page:** https://github.com/carbon-design-system/carbon-website/issues/546
Need to polish and add perhaps a visual index to this page that matches what we are doing on the [components overview ](https://next.carbondesignsystem.com/components/overview)page.

We should NOT push this overview page until we have designs for it.

**Comment by aagonzales** [comment]
Do a bare essentials design pass. Can add in more visuals later.

**Comment by designertyler** [comment]
We've updated the patterns overview to a table layout. Is that enough to close this issue to meet "a bare essentials design pass".

We can open another if/when we get more patterns and want to do a more visual layout similar to the components overview page.

![image](https://user-images.githubusercontent.com/19270502/53446641-0ec52b80-39d9-11e9-99f6-ad982f03a3a4.png)
