### ISSUE TITLE
ensure "universal experiences" content from IDL site are reflected in our current guidance.

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#755]
make sure that the content here:
https://www.ibm.com/design/v1/language/experience/

is represented, covered by our current guidance.

**Comment by emyarod** [comment]
given that the v1 IDL page has been removed we no longer have a visible reference to the content. if the current Carbon website still does not contain this information, feel free to provide an updated link to the missing content in a separate issue

**Comment by chrisconnors-ibm** [comment]
Current Universal Experiences content lives here: https://design.w3cloud.ibm.com/design/universal-experiences/
