### ISSUE TITLE
Editorial Pass: Guidelines

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#756]
Review every page under Guidelines for style, clarity, grammar. Publish changes in batches as appropriate.

- [x] Accessibility: Overview
- [x] Accessibility: Color
- [x] Accessibility: Keyboard
- [x] Accessibility: Developers
- [x] Content: General
- [x] Content: Guidance
- [x] Content: Glossary (not including the glossary component itself)
- [x] Color: Overview (on hold pending updates from @jeanservaas )
- [x] Color: Usage
- [x] Iconography: Library
- [x] Iconography: Usage
- [x] Iconography: Design and Contribution
- [x] Layout
- [x] Motion (awaiting page markdown https://github.com/carbon-design-system/carbon-website/issues/508)
- [x] Spacing
- [x] Themes
- [x] Typography: Overview
- [x] Typography: Productive
- [x] Typography: Expressive

**Comment by claycrenshaw** [comment]
Accidentally added a dependency. And now I can't find a way to remove that. . .

**Comment by chrisconnors-ibm** [comment]
please ensure ample opportunity for review of these changes prior to this content being in the PR stage, especially if page structure/interactions change, whether that's design crit or a specific review mtg

**Comment by claycrenshaw** [comment]
Preview link for cleaned up A11y pages: https://deploy-preview-764--carbon-website.netlify.com/

**Comment by claycrenshaw** [comment]
@chrisconnors-ibm re: "PR stage": Under the current build, we have to do a PR in order to generate a staging link, so the convention is to add "WIP" to PRs that are posted for review but not "ready to pull" yet.
