### ISSUE TITLE
[Global typography]: Extra line spacing added to bullets should be removed.

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#761]
Bullets (both the ones with en dashes and numbers) should not get extra line spacing. Should follow normal body specs. Exception being if the bullet list are a series of links in mobile.

**Comment by mjabbink** [comment]
@jeanservaas

**Comment by shixiedesign** [comment]
Hi @mjabbink  we've got this issue to over-hall all the spacing problems on the site. Secondary anchor link index is one of the things we will be looking at to be fixed (see last two items in description): 
 https://github.com/carbon-design-system/carbon-website/issues/739
