### ISSUE TITLE
[Global]: Most svgs are defaulting to Times New Roman in mobile

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#765]
![img_2234](https://user-images.githubusercontent.com/32881239/51503202-c7c79300-1da7-11e9-8bc7-88f7ab0af8a5.jpg)

**Comment by mjabbink** [comment]
![img_2245](https://user-images.githubusercontent.com/32881239/51503209-d0b86480-1da7-11e9-9142-eb994774a9c0.jpg)
![img_2244](https://user-images.githubusercontent.com/32881239/51503210-d150fb00-1da7-11e9-8319-2dcb8537acd1.jpg)

**Comment by alisonjoseph** [comment]
These svgs will have to be recreated without actual text, or the font will need to be embedded inside the svg.

**Comment by mjabbink** [comment]
I think the ones in IDL have the fonts outlined. We have back up with live text in case we need to edit or update.

**Comment by aagonzales** [comment]
The only draw back to outlining the font is that it can't be translated. It will always say "download" etc for other languages. Which is fine if the captions are good or the information is written somewhere else.

**Comment by designertyler** [comment]
The images in the components tabs and patterns pages will be converted at 2x pngs instead of svg. We're int he process of getting those exported and in there. It will be done by the end of this sprint.

**Comment by mjabbink** [comment]
@aagonzales That’s cool. How many languages does Carbon get translated into? I guess location specific but can we look into serving Plex for all languages Plex covers. That’s over 100 languages in extended Latin alone and if we include non- latin we include (Arabic, Cyrillic, Devanagari, Greek, Thai). Would totally be cool for type package to cover those languages with Plex. Great job for Vince and @joshblack to look into!

**Comment by shixiedesign** [comment]
replaced with traced SVG or PNGs
