### ISSUE TITLE
Hamburger icon too 16px too far from "Carbon Design System" in mobile

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#767]
## Hamburger icon too 16px too far from "Carbon Design System" in mobile

Design feature request: 

- [x] Move "Carbon Design System" 16px to the left in mobile to match IDL

- [x] Can we also make "Design"  of "Carbon Design System" semibold to match IDL and digital (this may be a markdown issue that we can do... if so sorry)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/22e40ffd-ca44-4da5-aebb-a39e3006fc20)

**Comment by alisonjoseph** [comment]
The spacing fix needs to be made in add-ons so we can apply to Design site also. The bold text isn't in markdown so a dev can update.

**Comment by mjabbink** [comment]
yes, we should roll with IDL or Carbon but they should all be the same in all instances with the lil burger.

**Comment by mjabbink** [comment]
I think IDL works best as when the hover is not there it seems a comfortable space. Carb has more space and looks too far away when no hover involved. 

Separately I wonder if we need the hover state on the burger at all? Does anyone have knowledge, expertise or opinions on that?
