### ISSUE TITLE
fix[Type scale exhibit]: Not to design spec

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#769]
## fix[Type scale exhibit]: Not to design spec

- [x] Need 16px top margin before "rem" and "px" start

- [x] "Px" column needs to be moved to the left (32px distance from end of "rem" column per IDL spec

- [x] All type in these exhibits should be Gray 100 ( # 171717)

- [x] Space out the scale and cap align the the rem with the example to the right. (i.e. more line height to match IDL example below) 

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/89efc8d0-35e9-4b60-8388-a2f5dd7488a4)

<br>

This type should also be Gray 100:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/eb35104e-52e5-4581-b1ea-751f98abe58f)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/dde2cb1e-99ea-4ad1-98e3-6347254db8e4)

<br>

Cap alignment:
![image](https://user-images.githubusercontent.com/43144260/52134504-54285000-2609-11e9-8d88-60c7ed1dcf10.png)

**Comment by jeanservaas** [comment]
@alisonjoseph thanks for doing this

I just realized there is weirdness happening with the scale, because on IDL, it is fluid (my bad!!!!) I gave you a fixed 32px distance between the rem and the px column... when on IDL that distance changes as the browser scales.

Here it is at breakpoints... not sure if we can do it this way... but this is how they implemented theirs.


Typescale_1312 (doesn't change for max)

<br>

![Screen Shot 2019-04-17 at 2 56 00 PM](https://user-images.githubusercontent.com/43144260/56316982-50dd3480-6121-11e9-9585-061f2167858a.png)


Typescale_1056

<br>

![Screen Shot 2019-04-17 at 2 56 36 PM](https://user-images.githubusercontent.com/43144260/56317007-63576e00-6121-11e9-9c39-a00b12d661bd.png)


Typescale_tablet

<br>

![Screen Shot 2019-04-17 at 2 57 24 PM](https://user-images.githubusercontent.com/43144260/56317030-74a07a80-6121-11e9-9877-ac9fba422b26.png)


Typescale_mobile

<br>

![Screen Shot 2019-04-17 at 2 58 20 PM](https://user-images.githubusercontent.com/43144260/56317051-808c3c80-6121-11e9-855d-655df630c910.png)

**Comment by alisonjoseph** [comment]
Updated in the PR @jeanservaas with the spacing at different breakpoints.
