### ISSUE TITLE
request: Getting started for OMs

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#77]
Throughout the Carbon site, our content speaks to two audiences: Designers and developers. A third audience we've failed to speak to is offering managers and product owners. 

Our content should address OMs, beginning with a Getting started for OMs page.

This page should include:

1. A value prop for OMs considering adopting Carbon
2. An explanation of how teams can leverage Carbon now and in the future to boost UX and product experience, as well as development efficiency.

**Comment by connor-leech** [comment]
@janchild @shinytoyrobots Is this still something we want to live on the website?

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
