### ISSUE TITLE
Component: inline loading not centered. (iOS)

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#778]
When spinning in place the center point is not consistent therefore the spinning loader is moving/bouncing

https://www.carbondesignsystem.com/components/inline-loading/code

[https://app.zenhub.com/files/181062037/db9479e7-bc4b-45b0-94ff-87bb2165b277/download](https://app.zenhub.com/files/181062037/db9479e7-bc4b-45b0-94ff-87bb2165b277/download)

**Comment by vpicone** [comment]
looks like this resolved itself with the Carbon update

**Comment by mjabbink** [comment]
No this still exists here:
https://www.carbondesignsystem.com/components/inline-loading/code

**Comment by mjabbink** [comment]
Also the link I posted up too showed it do not sure why you don’t see it?

**Comment by alisonjoseph** [comment]
confirmed this is still happening, only seeing it in ios though.

**Comment by mjabbink** [comment]
looks resolved now. Should this close?
