### ISSUE TITLE
[Content] add sections, content for Offering Management

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#78]
We currently address two constituencies: Designers and Developers. at IBM and other organizations, a third constituency has a major impact on putting feature schedules on hold to adopt carbon- Offering Management.

We need to present this constituency with the value proposition in their language, and ideally tools to help them make the case to expend project points - make the investment - to put their teams roadmap on hold for some amount of time to refactor their UIs adopting our frameworks/system.

Propose an MVP Getting Started: Offering/Product Management

Then add some boilerplate of the value props for them to use in meetings, emails, presentations; presentations they can use.

We could also use this content in outreach/roadshow directly to these communities.

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
