### ISSUE TITLE
Need clarity on proper nouns 

### ISSUE THREAD

**Issue by joshhus** [carbon-design-system/carbon-website#785]
Hello, there's some discussion about capitalizing words as proper nouns with respect to what words, terms and phrases constitute proper nouns within the context of a product. So we look to Carbon in order to follow Carbon. And request some added clarity on correctly identifying proper nouns, through examples and expanded discussion in your docs pages please. Without specific examples and discussion, teams might interpret the capitalization rules differently, thanks! See below for detailed discussion and examples:

Generally, a proper noun is a specific person, place or thing. Within a software or service offering, opinions can differ as to whether the term "email address" attribute, or the term "my network" module, for example, are proper nouns within a specific product environment (UI, database, network, etc.). ... e.g. "email address" used generally is not a proper noun, but when we don't mean any email address, we mean the one specific email address registered / used within the product, is it then a proper noun - "Email Address". ... Likewise, when we don't mean "my network" as a network that someone owns, but instead a specific sub-component / feature of a product, called "My Network" is the phrase then a proper noun (both / all words initial-capped). 

For writers, it adds clarity to readers and users if these specific things are capitalized as proper nouns, when they are not meant to be read as general concepts. .... Consider, e.g. "Enter your email address to be notified of alerts." vs. "Enter your Email Address to be notified of alerts." The latter usage indicates that Email Address is a proper noun (both words capitalized) and thus a specific thing within this context - the email address the user has defined or registered in this product or  environment, and not any one of their multiple real-world email addresses. Likewise for my network, e.g. "Navigate to my network to view your products." vs. "Navigate to "My Network" to view your products." .. Here the latter indicates that My Network is a proper noun and a specific thing in this product - i.e. a sub-component of the product, and not a reference to the author's network or someone's network. These are just two examples of cases where general words / terms are specific things in a specific product context.

Admittedly getting into the weeds here a bit, but the general rule to use sentence style capitalization is clear and direct. Not as clear is when UI elements, sub-components, code attribute names, product modules, user property names, etc. - any formal component of a product - are proper nouns, and should therefore have All Words Initial Capped to indicate a formal entity / specific thing. 

Example and reference below:

e.g. Capitalize "name, email, and company prefix" in the following screenshot as proper nouns? Here we refer to a specific string that defines the email and the name to use in this context, not a name or email with any different characters than those defined in this context:
![image](https://user-images.githubusercontent.com/16542757/72473950-d0358c80-37b5-11ea-92e3-6a9f3a82d237.png)

Reference - when a proper noun, all words are capitalized: 

Common Nouns and Proper Nouns - Grammar Revolution
https://www.english-grammar-revolution.com › proper-nouns
 Since these nouns are naming specific things, they always begin with a capital letter. Sometimes, they contain two or more important words. If this is the case, both important words are capitalized, and the whole thing is still considered to be one noun even though it's made up of more than one word.

**Comment by janchild** [comment]
@joshhus In the cases you have shown here, the Carbon recommendation would be “My network” and “Email address” following the sentence case rule. This would also apply to “Contact name” and “Contact email”. We would not recommend using title case in any of these situations. They are not considered proper nouns. 

Carbon does not consider UI elements proper nouns. Therefore, use sentence case capitalization for all text elements in the UI (headings, sub-headings, navigation labels, field labels, button labels etc.).

Nor does Carbon support a concept of "important words" as it's subjective and would result in inconsistencies across the board. 

If you are referring to a UI element, use the same capitalization as used in the UI. For example, if an input field is labeled “Name” then you refer to this as the Name input field. Similarly, if a drop-down menu has the label “Country” next to it, then it is correct to refer to the Country drop-down menu.

Capital letters are reserved for the following:
* “Carbon” or the “Carbon Design System” (i.e. the name of IBM’s official design system)
* “IBM” or any other company or organization name
* Any official, trademarked product or service (whether from IBM or not) - unless they intentionally use a lowercase letter at the beginning, such as the iPhone
* Any initialisms (e.g. BBC, HTML, etc.) or acronyms (e.g. NASA, NATO, etc.)
* Any people
* Any country / place names
* When referring to any UI labels that are themselves capitalized (e.g. if an input field is labeled “Name” then you refer to this as the Name input field.)

If it’s not in the list above, it should not be capitalized.

I understand from your earlier messages that you have different feelings about this but this is the Carbon position. As mentioned earlier, this guidance will be further clarified in the Content guidelines section of Carbon later this month.

**Comment by joshhus** [comment]
@janchild ... That's fine as I said I just want to follow Carbon. I only ask that you clarify the last bullet above (Name field e.g.) to include UI labels that have multiple words, such as - Email address vs. Email Address ... And also clarify the first bullet, which suggests to capitalize any official company "system" but uses the example of Carbon instead of stating the rule to follow.

**Comment by joshhus** [comment]
Please post link to the updated rules. 
In particular, when other things that are not an official products or services, like Carbon Design System ? are initial capped. Like app names, e.g.

**Comment by janchild** [comment]
@joshhus this is still a work in progress. It will be published when reviewed and ready.

**Comment by janchild** [comment]
This work has been completed and published.

**Comment by joshhus** [comment]
This looks like a giant step forward, thanks, will LYK if we encounter any more gaps ... https://www.carbondesignsystem.com/guidelines/content/guidance/#capitalization
