### ISSUE TITLE
Change H5 from the components' READMEs to paragraphs

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#791]
H5 from the components' READMEs should just be rendered as paragraphs. Token should be `$body-long2`. Design & content can make the change (remove H5s from component repo) but **just need dev guidance on how to do it properly** (shixie tried. Didn't work).

![image](https://user-images.githubusercontent.com/15144993/51709275-8de6ce80-1feb-11e9-8ac1-f11d6b205419.png)

**Comment by alisonjoseph** [comment]
this needs to be moved to carbon-components repo
