### ISSUE TITLE
All pages in Carbon site need to open with an H2 heading

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#795]
## All interior pages in Carbon site need to open with an H2 heading, (not a paragraph with no heading)

> The opening paragraph convention is a leftover from Carbon and seems marooned with the new design; "collateral damage" @chrisconnors-ibm  called it that can easily be fixed minor content tweaks. _Originally we tried to solve this issue by styling the paragraph (making it larger) but it did not work, the larger sizing interfered with our anchor link styling and caused some hierarchical confusion._

> Opening content is inconsistent at the moment; in some cases there is: 1) only an opening paragraph (No H2) , 2) an H2 that says "Introduction" and 3) there is a purposeful H2... It should be  the latter in every instance.

> Components are slightly different, in that we will have to come up with a standard H2 for all components that is not redundant (i.e. No more "Dropdown" "Dropdown" double headers)

Here is what I propose:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/65432f02-5935-47e8-8b58-a48d1a511938)

Here is another option that would also work:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/cc626073-9e77-4ca1-b9e0-598c79bb862f)

**Comment by claycrenshaw** [comment]
Is the intent here to change all "code" tabs to "overview" tabs? @jeanservaas

**Comment by jeanservaas** [comment]
Closing this issue, it is covered here:

https://github.com/carbon-design-system/carbon-website/issues/792
