### ISSUE TITLE
1px Left nav border visible on mobile 

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#796]
- [ ] When the left nav is hidden at tablet/mobile the 1px border is still visible, needs to move left 1px to be completely hidden. 
- [ ] update in website-addons and publish package

**Comment by marijohannessen** [comment]
I'm not seeing this anymore, can you confirm that it's still there @alisonjoseph ?

**Comment by alisonjoseph** [comment]
This was fixed! I think there might have been duplicate issues so this one never got tagged.
