### ISSUE TITLE
[ Notification Icon ] yellow: exclamation mark should be black

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#797]
White on Yellow not accessible

<img width="263" alt="screen shot 2019-01-26 at 10 48 35 am" src="https://user-images.githubusercontent.com/32881239/51789942-c3f79000-215c-11e9-8a10-b1e4fcebfff9.png">

**Comment by alisonjoseph** [comment]
Need to see if this is a website bug or a component bug.

**Comment by emyarod** [comment]
The old warning icon from `carbon-icons` did not have black exclamation marks when imported directly from the package, so the black exclamation mark was originally hard coded in the old notification component. [It appears that the new icon from `carbon-elements` also leaves the exclamation point transparent by default like its predecessor from `carbon-icons`](https://github.com/IBM/carbon-elements/blob/master/packages/icons/src/svg/16/warning--alt--filled.svg). The modified, accessible hard coded icon was removed when it was swapped out for the new default warning icon here: 
https://github.com/IBM/carbon-components/commit/f9ba9b5177fe4796bc07f84f276f1fee550e5eed#diff-ecc9cad80729a4efa44ffbb02ab80f49L16

**Comment by asudoh** [comment]
CC @joshblack per above comment

**Comment by mjabbink** [comment]
It has to be included because write icon on yellow is no accessible

**Comment by joshblack** [comment]
@mjabbink is the icon considered as content or is it a decoration? If it's a decoration then it wouldn't need to hit contrast requirements, right? 

If it's considered as content, wouldn't we need the contrast between the fill and the background color to be 4.5:1?

Was looking at: https://www.w3.org/WAI/GL/low-vision-a11y-tf/wiki/Informational_Graphic_Contrast_(Minimum) for reference

**Comment by jeanservaas** [comment]
@mjabbink and @joshblack 

yeah, i think josh is right, because we have text saying what the issue is right next to it, i don't think it needs to be contrast accessible.

**Comment by mjabbink** [comment]
you bring up a good point as a requirement but I think if it’s going to be there it should deliver it’s purpose. We should not have decoration because then it can just go away. I think if we’re to have an icon with a piece of type inside it it should be legible.

**Comment by mjabbink** [comment]
Bo might want to chime in on this too but I’m fine with it as I can read it but my worry is IBM preaches a big game in accessibility which means we have to consider all these details despite if we can get away with keeping this way and technically not getting dinged.

**Comment by dakahn** [comment]
The way I think about it is -- if I removed the "decoration" from the design. Would it communicate _as clearly_. True decorations are just artistic flourishes meant to make the page more aesthetically appealing. 

This I don't think qualifies as a decoration. If we remove this icon from the component then we're relying on color to communicate intent and severity and you shouldn't do that either. 🐅

**Comment by joshblack** [comment]
@dakahn I agree that the component should provide two ways to indicate status, most likely that would be color and either text saying "warning" or a textured background/side pattern, right?

With an icon, we'll have to make sure that it is visible in high contrast mode which would not pass regardless of the filled black ! as the overall icon doesn't meet 4.5:1 contrast ratios with its background, I thought. Let me know if I'm missing something here 😄

**Comment by chrisconnors-ibm** [comment]
The exclamation is if anything the quaternary encoding of the information. 'warning' here is encoded as-  

Primary: Label (Notification title)
Secondary: shape (triangle)
Tertiary: color (yellow)
and _maybe_ Quaternary : the exclamation point. 

I don't have any concerns about the contrast accessibility of the quaternary encoding method.

**Comment by chrisconnors-ibm** [comment]
The question of the accessibility (color contrast value) of the `!` vs its background in an icon matters _only_ in the case where the icon itself is the only encoding of the information. in this case the `!` is the _4th_ level of encoding. so the rule is not in force.

The _shape_ is the second encoding, so making two of them (`error` and `warning`) circles would be a problem.

**Comment by chrisconnors-ibm** [comment]
@dakahn that's bc the `!` is a single pixel width shape centered on an 8x8 pixel grid on @1x displays

**Comment by mjabbink** [comment]
Guys, it’s not about passing some requirement for a single instance but rather... is it smart, a good decision, clear, the move of a guide, logical to have a white  exclamation on a yellow background for anyone, anytime, ever? I think you know the answer. White on yellow has never been a good idea (at that scale and in digital) for just about anything. One would not do that in book, magazine, logo, signage, data viz or infographic.

**Comment by mjabbink** [comment]
I meant white as a general statement. I definitely know that it’s knocked out. The point I’m making is we need to have a solution that can allow a few icons to have that "knockout" be black or if it’s a black "exclamation" on top of a solid yellow circle. We will only need this in a handful of icons or maybe only this one. Not for the entire icon strategy.

**Comment by mjabbink** [comment]
I said it was never a good idea. I did not say it’s never done. That link with white icons on yellow is a perfect example of bad decisions so thanks for including it. It just proves my point on how white on yellow does not work.  and yes we should never do that. It’s poor design 100%. Why are we defending a bad design move rather than figuring out how we can solve for a black exclamation on yellow in our system. I’m sure you’re not advocating we pursue the light exclamation on yellow as the right choice, or are you?

**Comment by chrisconnors-ibm** [comment]
>we need to have a solution that can allow a few icons to have that "knockout" be black or if it’s a black "exclamation" on top of a solid yellow circle. We will only need this in a handful of icons or maybe only this one.

We can definitely do this! Thanks Mike.

**Comment by emyarod** [comment]
couldn't find a ticket open for this fix in `@carbon/elements`. do we need to create one or is it being tracked elsewhere?

**Comment by alisonjoseph** [comment]
I believe we need an issue created in elements if there isn't one @emyarod

**Comment by joshblack** [comment]
Yeah, definitely make one and cc @chrisconnors-ibm and he can help coordinate how to get it added 👍

**Comment by chrisconnors-ibm** [comment]
https://github.com/IBM/carbon-elements/issues/360
