### ISSUE TITLE
App scan security vulnerabilities

### ISSUE THREAD

**Issue by lokeshv21** [carbon-design-system/carbon-website#799]
Hi All, 

we are using carbon component framework version 9 for our application.  We have done app scan for our application carbon has thrown lot of vulnerabilities.  As per the recommendations we upgraded to latest carbon components  i.e., version 10. Even it has lot of security violations. Any body has idea on this ? Will carbon team release new version with app scan issue free.

Regards,
Lokesh V

**Comment by joshblack** [comment]
Hey there! :wave:

The vulnerabilities may be coming from the development dependencies of Carbon, versus what you ship to end-users. Could you share the result of your app scan that note carbon as having security violations?
