### ISSUE TITLE
Spacing guideline FAQ broken

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-website#803]
Could maybe use accordion?
![Screen Shot 2020-01-17 at 2 14 00 PM](https://user-images.githubusercontent.com/4078018/72643179-b457f500-3933-11ea-923b-4ad920154804.png)

**Comment by jnm2377** [comment]
I changed these to h4 in my PR to fix the spacing. But also accordion might be a good option too.

**Comment by jnm2377** [comment]
https://github.com/carbon-design-system/carbon-website/pull/868
