### ISSUE TITLE
Content: Add details about when to use which text justification in data tables

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#808]
Add guidelines to data table usage or style (not such which is more relevant) tab to instruct users when to use left versus right justification in **rows and column headers.** 

- Left  justified: default text content
- Right justified: only for numbers or icons
   - right justifying numerical data is [standard practice](https://medium.com/mission-log/design-better-data-tables-430a30a00d8c) (look at financial reports or excel etc)
   - our designs style requires icons to be sticky to the right most edge of a table row.

**Example of right justification:**
![image](https://user-images.githubusercontent.com/11670886/51853028-f2a47080-22ec-11e9-8670-6a6bef7c1970.png)

As per slack discussion:
![image](https://user-images.githubusercontent.com/11670886/51852778-66924900-22ec-11e9-98c8-49cd4a48538a.png)

**Comment by claycrenshaw** [comment]
PR: https://github.com/carbon-design-system/carbon-website/pull/1196
