### ISSUE TITLE
[Contribution] Map users, tasks, and contribution interactions

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#81]
### Overview

Capture the framework that identifies users, all contribution tasks, and methods of interaction.

**Link to MURAL board:** https://app.mural.co/t/ibm14/m/ibm14/1560281476326/f960d923343b785fe9b0cbdeb5725e44311913e3

### The details

Identify the following in a grid:
* the users (who)
* tasks (what)
* how they are interacting/contributing

Use this to map out all the flow scenarios.

**Comment by aagonzales** [comment]
@janchild is this still something we want to pursue and add to the backlog?

**Comment by janchild** [comment]
Closing. This was addressed in updates to the How to contribute section on the site in 2019.
