### ISSUE TITLE
[token] add new $text-error token to color usage page

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#810]
Add new token `text-error` to color usage page on the website.

![Screen Shot 2020-01-20 at 12 20 18 PM](https://user-images.githubusercontent.com/43969356/72749337-61727d80-3b7f-11ea-8034-c9e49c222a9a.png)

**Comment by laurenmrice** [comment]
Also need to update values of the existing `support-01` token

Gray 90
Red 40 - #ff8389

Gray 100
Red 50 - #fa4d56

**Comment by xxxle0** [comment]
hi @laurenmrice, can you give me the hex of Red-30 ?

**Comment by xxxle0** [comment]
hi @laurenmrice, i think we have a support-01 with the color looks like text-error. Can you confirm it ?

**Comment by laurenmrice** [comment]
hey @xxxle0 
![Screen Shot 2020-01-21 at 9 18 19 AM](https://user-images.githubusercontent.com/43969356/72817189-fc766080-3c2e-11ea-9303-ecfa52bf8ecb.png)

we changed the support-01 value for Gray 90. It went from Red 50 to Red 40.

**Comment by xxxle0** [comment]
yep i got it @macguirerintoul

**Comment by xxxle0** [comment]
https://carbon-website-git-fork-xxxle0-duytran-810-add-color-to-237194.carbon-design-system.now.sh/guidelines/color/usage you can review it here

**Comment by laurenmrice** [comment]
thanks! do you have a link to a pr i can review?

**Comment by xxxle0** [comment]
👍
