### ISSUE TITLE
Filtering pattern refresh

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#813]
### Overview

The body of this pattern is high quality and the guidance is largely is accurate. The images are also detailed enough to offer the necessary visual context for each subsection, though they are somewhat overcomplicated.

The page IA will need to be significantly reworked.

At the moment, each section discusses a function of filtering in a vacuum, resulting in a scattered reading experience that does little to prepare the reader to create an intuitive filtering experience.

Filtering on its own is a colossally complicated UX challenge, and the length and detail of [Patternfly's document](https://www.patternfly.org/v4/design-guidelines/usage-and-behavior/filters) is just one example of how detailed you can get.

Outside of a rework, we will want to prioritize filtering for research and exploration among products to collect product examples and ensure the pattern is comprehensive.

### Next steps

- [x] Update this pattern to follow the latest pattern template
- [x] Meet with Jan and Jillian to collect and review feedback
- [x] Work in Jan's copy edits
- [x] Add captions to all images
- [ ] Check capitalization in images
- [x] Confirm alt text reflects image
- [x] Change "Filtering states" header to "Filtering states and resetting"
- [x] Elevate resetting filters to a higher H level.
- [x] 'When to use' table
- [x] Triggering is an interaction type, not a type of filter. Adjust copy to reflect this.
- [x] Change intro paragraph: "Filtering allows a user to add or remove..."
- [x] IA is off. Reorganize hierarchy.

### Future steps (v2)

- [ ] Meet w/ Josh for accessibility content
- [ ] Check capitalization in images
- [ ] Confirm accuracy of states and styles in images (Anna or Lauren)
- [ ] Research composing a page with multiple types of progress indicators.
- [ ] Include development advice for loading order/orchestration.
- [ ] Contact SMEs for product examples and feedback.
- [ ] Talk to SMEs (Peter Vachon) about product examples
- [ ] Meet with Jan and Jeannie to review example images. Some are unnecessarily complex.

**Comment by janchild** [comment]
@connor-leech, closing this issue for now. Opening a new issue for the v2. Thanks!
