### ISSUE TITLE
Unexpected MD behavior with numbered lists

### ISSUE THREAD

**Issue by claycrenshaw** [carbon-design-system/carbon-website#814]
Numbered list in markdown starts over at 1 after this code snippet component.

![screen shot 2019-01-28 at 3 26 05 pm](https://user-images.githubusercontent.com/20912642/51867687-b59ea500-2311-11e9-89c5-808ca9f94a8b.png)
<img width="820" alt="screen shot 2019-01-28 at 3 26 17 pm" src="https://user-images.githubusercontent.com/20912642/51867689-b59ea500-2311-11e9-8228-4ebb19877c55.png">

## Detailed description

> Describe in detail the issue you're having.

> Is this issue related to a specific component?

> What did you expect to happen? What happened instead? What would you like to see changed?

> What browser are you working in?

> What version of the Carbon Design System are you using?

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
2. Step two
3. Step three
4. etc.

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

- Screenshots or code
- Notes

**Comment by claycrenshaw** [comment]
Update: Audrey found a workaround that _almost_ works :) But now the scss color coding is missing. . . 
<img width="702" alt="screen shot 2019-01-28 at 3 42 38 pm" src="https://user-images.githubusercontent.com/20912642/51868345-707b7280-2313-11e9-892d-0dc5e3dca904.png">

**Comment by tw15egan** [comment]
I'm guessing this is happening because each code snippet is rendered in its own row, so the lists don't know they are actually a continuation (without the work around)

**Comment by alisonjoseph** [comment]
+1 to what TJ said. I don't think there is an easy fix here.
