### ISSUE TITLE
(pattern) Common actions

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#815]
### Overview

The alternative structure of these patterns is something we should consider retaining with cleanup. Most of these patterns simply state Carbon's perspective on common actions and we risk overcomplicating them if we work to expand the sections. 

Certain patterns (Edit, refresh) need more detail, but that can come in a future iteration of the page.

We also need to reorganize it, as the current grouping of "progressive" and "regressive" is difficult to decipher without prior knowledge of the page's contents. We could consider borrowing the structure of GOV.UK's system and group by what a user is trying to do broadly (help a user...).

In general, we need more intuitive grouping of our patterns. We can start with the overview page, grouping the patterns by table depending on the type of action they can take.

### Next steps

- [x] Update this pattern to follow the latest pattern template
- [x] Meet with Jan and Jillian to collect and review feedback
- [x] Work in Jan's IA feedback
- [x] Check capitalization in images
- [x] Confirm alt text reflects image
- [x] Get rid of subgroupings and add all anchorlinks at top.
- [x] Move to H2s.
- [x] Order page in alphabetical order and run by Jan.
- [x] Clean up copy, especially on Delete pattern
- [x] Peer review from Jan
- [x] Peer review from Jillian
- [ ] Dev review

### Steps for v2

- [ ] Meet w/ Josh for accessibility content
- [ ] Check capitalization in images
- [ ] Confirm accuracy of states and styles in images (Anna or Lauren)
- [ ] Research composing a page with multiple types of progress indicators.
- [ ] Include development advice for loading order/orchestration.
- [ ] Contact SMEs for product examples and feedback.

**Comment by janchild** [comment]
Work is complete
