### ISSUE TITLE
Slow complie time for sass during development

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#818]
Takes ~20 seconds every time an update to a sass file is made. Is there a way to speed this up.

**Comment by asudoh** [comment]
Our vanilla codebase has a similar problem with `sass:dev` Gulp task, which seems to be caused by a custom Sass importer. WebPack's `sass-loader` uses custom Sass importer, too. Reducing nested `@import`s seems to make 20s to 10s.

**Comment by designertyler** [comment]
Is this issue ready to be closed?

**Comment by tw15egan** [comment]
We just need to bump the version of carbon components for the website, I'll make a PR for that now
