### ISSUE TITLE
[arrow anchor links] Too much spacing between arrow and text

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#819]
In both sizes. @jeanservaas 

<img width="545" alt="screen shot 2019-01-28 at 11 59 15 pm" src="https://user-images.githubusercontent.com/32881239/51885357-156c6e80-2359-11e9-898f-5da8df4d1e2a.png">

**Comment by mjabbink** [comment]
applies to slash design site as well.

**Comment by mjabbink** [comment]
<img width="416" alt="screen shot 2019-01-29 at 12 02 50 am" src="https://user-images.githubusercontent.com/32881239/51885397-451b7680-2359-11e9-94a7-d52a6f9eaf08.png">

**Comment by tw15egan** [comment]
<img width="242" alt="screen shot 2019-01-29 at 3 46 18 pm" src="https://user-images.githubusercontent.com/11928039/51942577-0deea900-23dd-11e9-85d4-e7867c3c8e61.png">

Currently, it is 16px between them. What should it be reduced to?

**Comment by mjabbink** [comment]
hmm, try 8 but if that is too tight we may need to 12px. Or just use two spaces in the keyboard using the fonts spacing.

**Comment by jeanservaas** [comment]
@tw15egan was going to hit you up for this tomorrow. Sorry, it's my fault; i signed off on it.

**Comment by jeanservaas** [comment]
- Yup agree with Mike -- it looks like 8px in my file too, but we can eyeball and and go with 12px if it's tight.

![image](https://user-images.githubusercontent.com/43144260/52069021-8a9b9780-2543-11e9-8d3e-799cb44ef25b.png)


- also, wondering if we can tackle this issue at the same time if it's a quick fix:

https://github.com/carbon-design-system/carbon-website/issues/758

This is an example of the two columns working on IDL
https://w3.ibm.com/design/language/elements/type-basics/

**Comment by mjabbink** [comment]
8px does not bother me.

**Comment by tw15egan** [comment]
Pushing up the fix now, including #758 with it

![screen shot 2019-01-31 at 11 22 03 am](https://user-images.githubusercontent.com/11928039/52072375-7a3aeb00-254a-11e9-9372-915bfe1741e2.png)

**Comment by jeanservaas** [comment]
NOICE!!!!!!
