### ISSUE TITLE
Get started - Design page is redirecting

### ISSUE THREAD

**Issue by csabasipos** [carbon-design-system/carbon-website#825]
## Detailed description

[Get started > Design](http://www.carbondesignsystem.com/get-started/design/sketch) page is redirecting too many times.

## Steps to reproduce the issue

1. Open Carbon site
2. Click on `Get started > Design` in the menu

**Comment by xxxle0** [comment]
this issue relate to nginx config -> please check the proxy rule in nginx config

**Comment by aagonzales** [comment]
I think this is fixed with: https://github.com/carbon-design-system/carbon-website/pull/827
The site only redeploys once a day so we'll have to wait until tomorrow it see if it worked.

**Comment by csabasipos** [comment]
It works, thank you.
