### ISSUE TITLE
Weird inner shadow on website

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#826]
I'm getting a weird inner shadow/gradient on the right side of the v10 site in chrome and firefox.

![screen shot 2019-01-29 at 4 20 56 pm](https://user-images.githubusercontent.com/19270502/51944635-27462400-23e2-11e9-95c2-03edbc02d6a9.png)

![screen shot 2019-01-29 at 4 20 23 pm](https://user-images.githubusercontent.com/19270502/51944643-2d3c0500-23e2-11e9-868a-015da78fb9a6.png)

![screen shot 2019-01-29 at 4 20 16 pm](https://user-images.githubusercontent.com/19270502/51944648-3036f580-23e2-11e9-8eed-ad254f5cc7bf.png)

**Comment by alisonjoseph** [comment]
pretty sure this is the shadow from the switcher when closed. fix will need to be made in the addons css

**Comment by shixiedesign** [comment]
Addressed.
