### ISSUE TITLE
Number input alignment is off on website

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#827]
<img width="822" alt="screen shot 2019-01-29 at 4 38 44 pm" src="https://user-images.githubusercontent.com/2753488/51945990-eb14c280-23e5-11e9-8c7c-3da8f5b376b9.png">

**Comment by emyarod** [comment]
I think the fix for this has been ready in https://github.com/IBM/carbon-components-react/pull/1654 ever since https://github.com/IBM/carbon-components/pull/1622 was merged
