### ISSUE TITLE
[Contribution] Identify contribution must haves 

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#83]
### Overview

1. Identify everything that is required for a contribution to make it through. (Full Monty) 
1. Identify minimum requirements.
1. Identify partial contributions, if they exist.

### The details

**Full Monty contribution is as follows:**
* Working code
* Design spec that includes:
  * spacing & size
  * typography tokens
  * color tokens
  * states
  * interactions
* Design symbol/asset
* Documentation

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
