### ISSUE TITLE
Migration content refinements for tokens

### ISSUE THREAD

**Issue by joshblack** [carbon-design-system/carbon-website#832]
Looking at: https://next.carbondesignsystem.com/updates/migrating-to-carbon-x#tokens we might want to make a couple of tweaks for the copy.

> The type token architecture has been completely redesigned for better clarity and flexibility in v10, moving from a “class-name” approach to a more standard token architecture.

We didn’t move from a class-name approach in Carbon, right? We had one, but that was separate and still exists. We just never had type tokens before.

> The iconography in Carbon X has been completely redesigned to align with the new IBM Design Language, with hundreds of new icons added to the system.

We already introduced IDL icons in v9, we are just adding more through a new package setup.

> The basic UI shell has been completely redesigned for Carbon X, though it is still considered experimental.

Might be better to have this read as: “we’re introducing an experimental component: UI Shell” most will not know about this as it has not been publicized.

RE: Spacing, did we switch to a spacing scale? cc @jeanservaas

**Comment by designertyler** [comment]
Tagging @claycrenshaw here too
