### ISSUE TITLE
Site width exceeds browser window width

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#835]
I can scroll slightly to the left and right of the site, which will hide pixels at the edges of the browser window. All of the computed widths seem correct on inspecting the styles.

Chrome 71 on OSX.

![image](https://user-images.githubusercontent.com/825457/52012671-d0535400-24a0-11e9-9293-930ce7d91580.png)

![image](https://user-images.githubusercontent.com/825457/52012689-dd704300-24a0-11e9-832d-4211bfdaac24.png)

For extra weirdness, if you drag and hold to the left far enough, can make visible strange visual artifact that looks like a repeating nav column...

![image](https://user-images.githubusercontent.com/825457/52013431-a69b2c80-24a2-11e9-8389-eaabd075e3db.png)

Do not have this problem on Firefox or Safari.

**Comment by alisonjoseph** [comment]
I believe this was fixed, feel free to reopen if you are still seeing it.
