### ISSUE TITLE
[contribution] Production guidelines (page templates for each of our pages) 

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#84]
### Overview

As we seek to boost community contribution and interaction, high-quality documentation will be critical. The best way to ensure documentation is consistent with existing Carbon content, we need to determine our documentation production rules and provide templates for each page type.

### The details

Define high-level writing and content guidelines for the Carbon website. This will resemble a style guide but pared down substantially.

We will also generate a template for the following page types:

- [ ] Component usage
- [ ] Component style
- [ ] Pattern
- [ ] Getting started

**Comment by aagonzales** [comment]
Related: https://github.com/carbon-design-system/carbon-website/issues/488

**Comment by aagonzales** [comment]
(oops thought this was for visual production guidelines not content.

**Comment by joshblack** [comment]
Going to close this one out due to inactivity!
