### ISSUE TITLE
Add small pagination variation to pagination page

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#85]
The small pagination variation needs to be added to website: 
- [ ] Example + code
- [ ] Style tab content
- [ ] Usage tab content

https://github.com/carbon-design-system/carbon/pull/1812

![image](https://user-images.githubusercontent.com/11670886/60128144-93da0a80-9757-11e9-8a1f-a39ebb583b67.png)

**Comment by alisonjoseph** [comment]
closing, this has been added
