### ISSUE TITLE
Theme switcher jumps at the larges size

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#850]
The theme switcher on the Color/usage page jumps off the grid when it floats on the largest break point.

Steps to recreate:
Go to:
https://carbondesignsystem.com/guidelines/color/usage/

Make sure the browser width is 1584px or larger

Scroll down and watch the theme switcher

Tabs the same width as the color token table:
![image](https://user-images.githubusercontent.com/19270502/73196015-7d809c80-40f4-11ea-9008-2188b91bc897.png)

Tabs become narrow when they float
![image](https://user-images.githubusercontent.com/19270502/73196046-8a04f500-40f4-11ea-93ba-93677c78c4dd.png)

**Comment by jnm2377** [comment]
good catch! hadn't noticed that.
