### ISSUE TITLE
Sort Codepen not working in Chrome

### ISSUE THREAD

**Issue by 3dfoster** [carbon-design-system/carbon-website#86]
## Detailed description

> Describe in detail the issue you're having.

In the table sorting example on Codepen, clicking the sort buttons don't sort the contents of the table. This issue affects Google Chrome. Sorting works on Firefox and Safari. The link to the codepen can be found on this Carbon Design page: https://www.carbondesignsystem.com/components/data-table/usage

> What browser are you working in?

Google Chrome

> What version of the Carbon Design System are you using?

10.4.1

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

Platform Unification

## Steps to reproduce the issue

1. Go to https://codepen.io/tjegan/pen/PjjyVN on Google Chrome
2. Click on the Table headers. The arrows will animate but the table contents does not sort

**Comment by aagonzales** [comment]
The code pen example has been removed and we now direct the user to our React storybook for an example that works correctly.

https://carbondesignsystem.com/components/data-table/usage#sorting
