### ISSUE TITLE
[component demo] add repo links

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#860]
Add links to component demo window 
- React: http://react.carbondesignsystem.com/
- Angular: http://angular.carbondesignsystem.com/
- Vanilla: ??
- Vue: http://vue.carbondesignsystem.com/

![image](https://user-images.githubusercontent.com/11670886/73298243-91023500-41d2-11ea-8cce-615724b7b3ce.png)

![image](https://user-images.githubusercontent.com/11670886/73307517-f4e12980-41e3-11ea-8a73-ec993137f847.png)

### Spec:

![image](https://user-images.githubusercontent.com/11670886/73309846-b69a3900-41e8-11ea-975b-67018528b243.png)

**enabled**
text color: `$inverse-01`
icon color: `$inverse-01`

**hover**
text color: `$inverse-01`
icon color: `$inverse-01`
underline: `$inverse-01`

**focus**
border: `inverse-focus-ui`

**Comment by alisonjoseph** [comment]
`Vanilla` should link to https://vanilla.carbondesignsystem.com (currently https://the-carbon-components.netlify.com/)

blocked by https://github.com/carbon-design-system/carbon/issues/5205
