### ISSUE TITLE
Cupcake: Site feedback loop

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#862]
We can do a cupcake experience for the feedback loop mentioned in this issue https://github.com/carbon-design-system/carbon-website/issues/56

A visitor to the Carbon website can propose changes to the page's content without contacting team members directly or reaching out on slack channels.

Proposed idea: Link to each page's .md file in github.

**Comment by aagonzales** [comment]
Need:
- where it should go
- what we want it to look like on the page
- docs on making a PR through github (https://github.com/carbon-design-system/carbon-website/wiki/Creating-a-PR-through-github.com-UI)

**Comment by chrisconnors-ibm** [comment]
here's hod Cloud Docs do it (`Edit in Github` link): 
https://cloud.ibm.com/docs/apps/tutorials/tutorial_starter-kit.html#create_starterkit

![image](https://user-images.githubusercontent.com/35537391/52374813-d490eb80-2a23-11e9-9435-f25e7e84c64a.png)

**Comment by shixiedesign** [comment]
### Button design: 

Proposing this button to be always sticky to top right corner, under top nav. Button stays 50% opacity until user hovers near it. In Mobile, button looses copy, and behave the same.  

![image](https://user-images.githubusercontent.com/15144993/52489579-3a968380-2b88-11e9-942c-d424e323efb0.png)

![image](https://user-images.githubusercontent.com/15144993/52489750-af69bd80-2b88-11e9-8962-5e73d5833176.png)

**Comment by aagonzales** [comment]
It seems very prominent. What about putting it at the bottom of the page?

**Comment by chrisconnors-ibm** [comment]
I agree w @aagonzales  - Cloud docs showing that at the top of their page seemed aggressive. I bet they get random edits. :) I bet that link as shown but somewhere at the bottom of the page is sufficient.

**Comment by shixiedesign** [comment]
### Updated design: 

![image](https://user-images.githubusercontent.com/15144993/53447948-eb4fb000-39db-11e9-86c1-fb8b8a36fd83.png)

**Comment by chrisconnors-ibm** [comment]
Perfect!

**Comment by designertyler** [comment]
Closing this design issue. I opened the dev issue here https://github.com/carbon-design-system/carbon-website/issues/1216
