### ISSUE TITLE
Multi-select dropdown changes widths when items are selected

### ISSUE THREAD

**Issue by tomlroach** [carbon-design-system/carbon-website#865]
## Title line template: [Title]: Brief description
When items in the multi-select dropdown are selected, the appearance of the numerical indicator and X causes the width of the dropdown to change, which causes layout issues. 
Perhaps this is just a carbondesignsystem website issue, but as the exemplar site, it probably should not change width,

## Detailed description
> Describe in detail the issue you're having.

![2019-09-04 15 03 35](https://user-images.githubusercontent.com/6569324/64287631-cce7e580-cf25-11e9-9592-53e8990a846f.gif)

As items in the dropdown are selected, the width dynamically changes. This causes layout issues and causes the click targets to move. Ideally the width of the dropdown would remain static, either the space for the numerical indicator already being accounted for in the original width, or the label would be truncated to make space, rather than change the width of the dropdown. 

> Is this issue related to a specific component?
Multi-select dropdown

> What did you expect to happen? What happened instead? What would you like to
> see changed?

Dropdown width remains static, and if necessary the label is moved and truncated to make room. 

> What browser are you working in?
Chrome

> What version of the Carbon Design System are you using?
Carbondesignsystem website https://www.carbondesignsystem.com/components/dropdown/code

**Comment by vpicone** [comment]
We're in the process of migrating all the Code pages to use our new [component demo](https://www.carbondesignsystem.com/components/button/code).

I'm going to close this issue in favor of the larger migration issue and make a note of it there: https://github.com/carbon-design-system/carbon-website/issues/746
