### ISSUE TITLE
[Website component] No results for Icon search

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#866]
![Screen Shot 2019-02-01 at 1.28.32 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/9cd5ade5-c582-4523-b49c-2102f952ed5e)

**Comment by alisonjoseph** [comment]
would probably be good to add this to the main Iconography issue so it doesn't get lost, that page hasn't been started by dev yet thats why this is wrong.

**Comment by alisonjoseph** [comment]
closing this. added a comment to the main Iconography issue so it doesn't get missed https://github.com/carbon-design-system/carbon-website/issues/249

**Comment by designertyler** [comment]
I'm reopening since #249 was closed and this page still needs work.

**Comment by alisonjoseph** [comment]
Can we get an updated design for the "no results" for this page 🙏

**Comment by designertyler** [comment]
"No results" design specs are part of the issue here https://github.com/carbon-design-system/carbon-website/issues/1094
![image](https://user-images.githubusercontent.com/19270502/56373451-956edb80-61c6-11e9-942a-81a59c511874.png)
