### ISSUE TITLE
Getting Started: Designers need image updates

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#868]
Update screenshots for getting started: Designers.

- [x] Remove/crop drop shadow and white border around images.
- [x] Use latest version of the sketch kit, sketch, and repo in the examples.

![Screen Shot 2019-02-01 at 2.18.04 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/36b04253-2779-40c0-be4e-93e7e7c5b95e)

**Comment by aagonzales** [comment]
**Blocker:** need to have new kit first to repo
