### ISSUE TITLE
[ComponentDemo]: Create pathway for other libraries to use the ComponentDemo and migrate to theme

### ISSUE THREAD

**Issue by vpicone** [carbon-design-system/carbon-website#870]
- Carbon for IBM.com would really like this
- It's also been asked for in the theme https://github.com/carbon-design-system/gatsby-theme-carbon/issues/695

**Comment by QuicheSama** [comment]
I'm really excited for ComponentDemo to be usable by other libraries. How may I contribute to this happening?

**Comment by vpicone** [comment]
@QuicheSama we're still iterating on this component internally for the Carbon website. We want to make sure we're able to make breaking changes if we need to. Making this component usable outside the website has taken a backseat to that effort for for the moment.

**Comment by JennySanchez** [comment]
@vpicone Hooray!!!

**Comment by vpicone** [comment]
@JennySanchez no plans yet! There’s been so many changes to that component that would have been breaking. It’s still not great to use and is missing some features that carbon devs would like so I don’t think making it universal should be a priority as we’re iterating on it.

It’s actually 100% fully functional for any react components, so long as they don’t need the props panel. Making a nice abstraction for that is a significant undertaking.

**Comment by tay1orjones** [comment]
We're also very interested for this for the ai-applications (formerly iot-design) website for our `carbon-addons-iot-react` library.

Even without the props panel this would provide a significant boost in experience on the website.

**Comment by JennySanchez** [comment]
@vpicone Any new updates you can share, Vince?
