### ISSUE TITLE
UI Shell tile in Component Overview page

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#870]
There is a UI shell tile in the component overview page.

We could:
- Leave the tile, add an illustration, and indicate that it is "experimental"
- Remove it and say any future experimental components aren't shown on this page

![Screen Shot 2019-02-01 at 2.30.01 PM.png](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/c218dc3d-0558-41b0-b704-3c9242ebae3f)

**Comment by aagonzales** [comment]
Raise it to "experimental components" - what do they look like on this page. Are they in a different sections? Does it get a badge?

**Comment by designertyler** [comment]
We have the updated artwork. Did we still want to add an indicator or a section for experimental? Here's it as its own section. It seems weird now being only 1 experimental component, but hopefully works better when there are more.

![experimental overview mockup](https://user-images.githubusercontent.com/19270502/52796307-927a3200-3041-11e9-9aac-29a87647e367.png)

**Comment by jeanservaas** [comment]
Can we just leave it where it is for the moment or remove it? It's weird because it has it's own nav section under experimental, not sure why it needs representation here too.

**Comment by aagonzales** [comment]
Decision to include like this: https://github.com/carbon-design-system/carbon-website/issues/870#issuecomment-463665071

If more than 3, start and experimental overview page.

**Comment by aagonzales** [comment]
@jeanservaas or @designertyler make sure this is implement like so.

**Comment by designertyler** [comment]
Let's icebox this for now. The Shell component is being broken out into its own components and there's an ongoing conversation about how add-ons could be surface on the site and will change the need for this section in the component overview page.

Revisit once we have new requirements for experimental and add-ons.
