### ISSUE TITLE
Workshop materials for Feb 17 Patterns class

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#875]
**Rework workshop materials**
- [ ] New angle for content throughout is how to use a design system, rather than how to use Sketch
- [ ] Explain what a token is in the introduction
- [ ] Introduce micro exercises after every section
- [ ] Add more content as needed

**Micro-lessons are as follows:**
- Grid presentation
   - [ ] Task on learning the grid
- Type section — Add some content to add more to the type token section
   - [ ] Task: how to apply type tokens
- UI palette section
   - [ ] micro task for this section
- Icons
   - [ ] micro activity, such as switch out an icon

**Additional questions to address:**
- [ ] Are there any other micro tasks that you can see that should be included?
- [ ] Determine if you want to have individual activities, or make one example that you're building on with each micro class.
- [ ] If there is time for a holistic design activity, they can recreate a page on their own. Your discretion about this. 

**Schedule of playbacks, allowing time for revision:**
- [ ] Playback concepts for tasks in Design check-in — add date
- [ ] Full playbacks to team to test content and timing — add dates
- [ ] Deliver to the Patterns class on Feb 17

**Comment by aagonzales** [comment]
Keynote file: https://ibm.box.com/s/w9wnbzp72od4y0bshqlbzz4yorpqladi

**Comment by janchild** [comment]
work is complete
