### ISSUE TITLE
[Color page] Update content for token values on Usage tab

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#88]
Need to update some content for color values and add a new token on the Usage tab of the Color page on the website.

------------------------------------------------------------------------------------------------

Add `inverse-link` color token

**White theme**
Blue 40
6ea6ff

**Gray 10 theme**
Blue 40
6ea6ff

**Gray 90 theme**
Blue 60
0062ff

**Gray 100 theme**
Blue 60
0062ff
`interactive-02`
**Light themes**
Gray 80
3d3d3d

**Dark themes**
Gray 60
6f6f6f

------------------------------------------------------------------------------------------------
Add `inverse-hover-ui` color token

**White theme**
Gray 80 hover
4c4c4c

**Gray 10 theme**
Gray 80 hover
4c4c4c

**Gray 90 theme**
Gray 10 hover
e5e5e5

**Gray 100 theme**
Gray 10 hover
e5e5e5

------------------------------------------------------------------------------------------------

`interactive-02`
**Light themes**
Gray 80
3d3d3d

**Dark themes**
Gray 60
6f6f6f

------------------------------------------------------------------------------------------------

`hover primary text`
**Dark themes**
Blue 30
97c1ff

------------------------------------------------------------------------------------------------

`highlight`
**Gray 10 theme**
Blue 20
c9deff

**Gray 90 theme**
Blue 70
054ada

**Gray 100 theme**
Blue 80
0530ad

**Comment by creckling** [comment]
All of the color values on the Usage page need to be updated for the new IDL palette. I can do the work if no one else is right now. Let me know.

**Comment by laurenmrice** [comment]
Hey  @creckling ! Actually, the new colors are on the usage tab now https://www.carbondesignsystem.com/guidelines/color/usage. This was the pr for reference: https://github.com/carbon-design-system/carbon-website/pull/322. My comments above have been updated.

**Comment by creckling** [comment]
I'm still seeing Blue 60 as '#0f62fe and similar for other colors. That doesn't seem to match the IDL palette which has it at '#0062ff

**Comment by laurenmrice** [comment]
#0f62fe is the from the new color palette . #0062ff is from the old color palette. IDL needs to update their page

**Comment by laurenmrice** [comment]
I'm going to close this and open a new issue for IDL to update their color page if they dont have one already 👍

**Comment by laurenmrice** [comment]
Issue for IDL: https://github.com/carbon-design-system/design-language-website/issues/272
