### ISSUE TITLE
Update v9/v10 banners

### ISSUE THREAD

**Issue by alisonjoseph** [carbon-design-system/carbon-website#881]
Add clear documentation to the website around v9/v10 components with a link to the v9 site. The v10 website is launching before we release v10 carbon-components so this is super important.

**Comment by aagonzales** [comment]
The banners are slightly different for each site. Used the v9 button for the v9 site and a v10 button for the v10 site. Hope that's ok/preferred.

bar height: 48px
text: 14px, regular

Sketch file: https://ibm.box.com/s/pxjarp8zdpqlyw6alek26ucqq3e6iq9g

## v9 site
![image](https://user-images.githubusercontent.com/11670886/52238023-a7f89a80-2890-11e9-9a42-1688faa9e1a5.png)


## v10 site
![image](https://user-images.githubusercontent.com/11670886/52237997-98795180-2890-11e9-8b39-ef39f320e3f0.png)

**Comment by claycrenshaw** [comment]
for v9: 

"Carbon X has arrived! Check out the v10 beta site and all-new carbon-components library."
CTA: "Go to beta site"
(rationale: "is here" at first glance could be read as "is here, on the page you are reading")

for v10:

"Carbon v10 is currently in beta; for production-ready components, use Carbon v9."
CTA: "Go to v9 site"

Just a note: esp. on the new site, the button on the banner is so far from the related text that it seems like it would be easy to miss it. . . Also not sure if there is an easy fix for this. Possibly just make the banner text clickable as well?

**Comment by shixiedesign** [comment]
Talked to Anna about V10 site banner. The white is merging into the browser controls above it. So we made a new design...many many apologies for this late design change. If it makes it that will be awesome, it not it's not the end of the world. 🙏 thanks!!! 

Top line is the design. Bottom line is spec'ed design.

![image](https://user-images.githubusercontent.com/15144993/52362618-989b5d80-2a06-11e9-958f-e4f501219b95.png)

**Comment by alisonjoseph** [comment]
- [ ] Need to update banner on v9/v10 site to not be sticky
- [ ] Update banner on v10 site to use updated design

**Comment by alisonjoseph** [comment]
Can/should we keep the banner on the next site at 48px high on mobile also now that we are hiding text and it will fit at that height?

**Comment by alisonjoseph** [comment]
Fix is in this PR https://github.com/carbon-design-system/carbon-website/pull/917
