### ISSUE TITLE
docs: update to A11y Number Input, Tabs, Slider and Content Switcher docs to include screen reader results and compliance information

### ISSUE THREAD

**Issue by snidersd** [carbon-design-system/carbon-website#881]
Please update the following documents with A11y compliance info and added screen reader results:

- Number Input  - https://pages.github.ibm.com/IBMa/Carbon_Integration/Doc/NumberInput-doc.html
- Tabs - https://pages.github.ibm.com/IBMa/Carbon_Integration/Doc/Tabs-doc.html
- Slider - https://pages.github.ibm.com/IBMa/Carbon_Integration/Doc/Slider-doc.html
- Content Switcher -https://pages.github.ibm.com/IBMa/Carbon_Integration/Doc/ContentSwitcher-doc.html

**Comment by mbgower** [comment]
All these topics have had their accessibility info updated since this issue was opened.
