### ISSUE TITLE
Usage guidelines for form needs animation and update

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#882]
- [x] The guidelines don't seem to match the animation.

- [x] Update the animation

The guidance says:
"The validation should appear when the user has clicked away from the text field. Once the user corrects the errors within the text field, the validation should disappear once the data is rendered as valid."

The animation does not show validation happening when clicked away from text field. It only happens when they try to submit.

https://www.carbondesignsystem.com/components/form/usage#form-validation

![form-usage-3-62a7c5c5840aa569df41b1a299d06b5d.gif](https://images.zenhubusercontent.com/583dd918b9dc3c622022afbf/fa72dc82-041b-49c7-bcbc-30a4cc5be232)

**Comment by claycrenshaw** [comment]
@designertyler Do we know which is correct? The animation or the guidelines?
