### ISSUE TITLE
Incorrect font-size for expressive-header-04

### ISSUE THREAD

**Issue by TacticalSneeze** [carbon-design-system/carbon-website#885]
#721  Title line template: [Title]: The font-size at XLG for expressive-header-04 on https://www.carbondesignsystem.com/guidelines/typography/expressive/ is incorrect. 

## Detailed description

In the Carbon type package (@carbon/type), in _styles.scss, the settings are: 

$expressive-heading-04: (
  font-size: carbon--type-scale(7),
  font-weight: carbon--font-weight('regular'),
  line-height: 129%,
  letter-spacing: 0,
  breakpoints: (
    xlg: (
      font-size: carbon--type-scale(7),
      line-height: 125%,
    ),
    max: (
      font-size: carbon--type-scale(8),
    ),
  ),
) !default;

This says that at XLG the font-size is type scale 7, which is 1.75 rem, or 28px. I expect the website to display the same settings, but it doesn't. The website lists expressive-heading-05 on XLG as type scale 7, which is 28px. 

To correct, I believe you would adjust both the website and the Design Language Kit v2 to have XLG at scale 7, 1.75. 

Either that or @carbon/type is broken.

**Comment by alisonjoseph** [comment]
@jeanservaas just wanted to check if the website or package had to correct value here? Assuming its likely the package and we just need to update the website?

**Comment by joshblack** [comment]
Hey there! Going to close this issue out due to inactivity. Feel free to comment and I can re-open!
