### ISSUE TITLE
Tag component body / text size is too large on carbondesignsystem.com

### ISSUE THREAD

**Issue by vsnichols** [carbon-design-system/carbon-website#887]
## Tag component body / text size is too large on carbondesignsystems.com. 

It is also affecting the CloudPAL site and is making it difficult to troubleshoot design updates to the component.

## What package(s) are you using?

It seems to be happening in vanilla JS? The React storybook for tags looks correct/

## Detailed description

This is related to the Carbon v10 tag component. It is showing up incorrectly in prod for IBM Cloud currently, as well as on the carbondesign website. 

Actual:

<img width="1674" alt="Screen Shot 2020-01-24 at 11 42 47 AM" src="https://user-images.githubusercontent.com/39408106/73090858-cb03cc00-3e9e-11ea-8af1-27c7c6483b83.png">

Expected:

<img width="1674" alt="Screen Shot 2020-01-24 at 11 43 16 AM" src="https://user-images.githubusercontent.com/39408106/73090862-cfc88000-3e9e-11ea-888c-6d72e096554c.png">

## Steps to reproduce the issue

1. Go to https://www.carbondesignsystem.com/components/tag/code

**Comment by xxxle0** [comment]
This bug will be fixed with the next release.

**Comment by vpicone** [comment]
closing, per above.

**Comment by mjabbink** [comment]
Tags are Not showing up correctly in Carbon site in desktop or mobile

**Comment by mjabbink** [comment]
Mobile:

![D7A95A6D-CD18-43A4-8505-9DE036DDB24D](https://user-images.githubusercontent.com/32881239/75093097-6fcc0480-5544-11ea-8bb4-d0f19816f8ba.jpeg)


![8C5C90B5-1487-4F96-844C-660F8C516936](https://user-images.githubusercontent.com/32881239/75093098-7195c800-5544-11ea-9eab-37da7695bf46.jpeg)

**Comment by mjabbink** [comment]
Desktop:

![090B9900-E986-4089-87F7-07184BBCD205](https://user-images.githubusercontent.com/32881239/75093109-8bcfa600-5544-11ea-8ead-bcbead1f39b2.jpeg)


![93B7F7FC-59A1-422C-8DA1-D0659FA9DC3A](https://user-images.githubusercontent.com/32881239/75093110-8d00d300-5544-11ea-9c10-6cde3fd07b9f.jpeg)

**Comment by mjabbink** [comment]
<img width="1120" alt="Screen Shot 2020-02-22 at 7 27 32 AM" src="https://user-images.githubusercontent.com/32881239/75093138-d18c6e80-5544-11ea-86ba-62f8d1e22dbb.png">

**Comment by mjabbink** [comment]
both in Chrome and Safari

**Comment by vpicone** [comment]
@mjabbink I’m also frustrated, there’s other issues waiting release as well. They had an issue that delayed the release cycle.

**Comment by mjabbink** [comment]
@vpicone any news on this release?
