### ISSUE TITLE
Image component adds too much padding on larger images

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#890]
To avoid the image floating outside the container when scaled down there is padding added around the image.

Possible solutions:
- **The height of the PNG determines the height of the white container. The PNGs are already exported with a 80px margin around all artwork. Could it be possible to fix the heigh of the container to the image and let the width scale?** (leaning towards this one)
- Re export all images without that 80px margin around all artwork and see if that decreases the amount of whitespace added in the site.
- See if it's possible to reduce the amount of top/bottom padding that is added and not run into an issue with the image floating outside the container. 
- Anything else?

Some examples:
https://next.carbondesignsystem.com/components/link/style

<img width="1789" alt="screen shot 2019-02-04 at 3 23 49 pm" src="https://user-images.githubusercontent.com/19270502/52238757-6cf76680-2892-11e9-8008-6c1496cb80ac.png">

<img width="1789" alt="screen shot 2019-02-04 at 3 18 36 pm" src="https://user-images.githubusercontent.com/19270502/52238707-4e916b00-2892-11e9-9c49-29c6f4d66382.png">

**Comment by shixiedesign** [comment]
@designertyler I just took a look at Link images, they are 1088x846 (2x png), so not the correct size...we only want default = 1472px wide (732x2) or large = 2240px wide (1120x2). Looks like half of the Style tab images are the right size, half of them are not. The 1472px wide images are displaying correctly.

**Comment by designertyler** [comment]
@shixiedesign ah, that's right. Some of the images were not updated to the new width yet. Let's hope that fixes the problem.

**Comment by designertyler** [comment]
Is `default` supposed to be 720px or 736px? https://github.com/carbon-design-system/carbon-website/issues/524#issuecomment-444556982

<img width="1243" alt="screen shot 2019-02-05 at 3 53 15 pm" src="https://user-images.githubusercontent.com/19270502/52306852-a5647680-295e-11e9-8f00-469f6a9a7b07.png">

It looks like the image is being set at 720px as max size and the white background is allowed to scale beyond that.

**Comment by marijohannessen** [comment]
Sorry, I'll fix the `fixed` error today! So if it's `fixed="default"` the image should be 720px and `fixed="large"` will be 1120px. The white background around it follows the grid and will take up 12 columns. The image will never get bigger than 720px or 1120px.

**Comment by designertyler** [comment]
Closing. Issue was resolved in https://github.com/carbon-design-system/carbon-website/pull/898
