### ISSUE TITLE
docs: Create detaild guidance regarding the use of code snippets in body copy

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#892]
We aren't consistent in the way we use code snippets to emphasize certain words and UI elements in body copy. This should be explored in upcoming style audits conducted on the site.

### Example

On the glossary page we use code snippets to emphasize UI elements that aren't hyperlinks. If this is acceptable usage, we should do a once-over across the site to be sure that approach is implemented consistently.

<img width="759" alt="image" src="https://user-images.githubusercontent.com/44656921/74252253-0120b880-4cb3-11ea-8b14-4e9b01b68b54.png">
<img width="707" alt="image" src="https://user-images.githubusercontent.com/44656921/74252294-1564b580-4cb3-11ea-8078-76616e67bca4.png">

**Comment by joshblack** [comment]
Hey there! Going to close this issue out due to inactivity. Feel free to comment and I can re-open!
