### ISSUE TITLE
Component [Tag] & component status type size should be 12px (label-01) in tag

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#895]
Type size too big (16px currently) should be pulling component with 12px)

https://www.carbondesignsystem.com/components/tag/code

![Screen Shot 2020-02-05 at 4.40.36 PM.png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/bf2e4bc1-dc1b-4ba0-bc29-b8bf999da6d3)

https://www.carbondesignsystem.com/components/component-status

![image (43).png](https://images.zenhubusercontent.com/5b8a10c6501b696007018606/33f84355-11df-4468-87b2-341a6deaf265)

**Comment by vpicone** [comment]
This was fixed up stream in Carbon, when it releases this week, we'll get the fix automatically.

**Comment by mjabbink** [comment]
Is there a reason this is not deployed? It was opened 24 days ago. Let’s get this released immediately please

**Comment by vpicone** [comment]
@mjabbink its not ours to release this is the system’s team tag component. They’ve implemented their fix and have a release pending. There’s nothing more we can do now than 18 days ago when I closed this issue.
