### ISSUE TITLE
fix[data viz]: multiple errors in color docs 

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#896]
## fix[data viz]: multiple errors in color docs 

A quick sweep reveals multiple errors in the hex codes on data viz color palettes ... here are just a few.

- [ ] update colors to the correct hexes and swatches on the website

- [ ] update colors to correct hexes and swatches in the data viz palettes sketch file

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/39f06e0a-c34b-4029-9830-0d535b253b5c)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/24caf2b5-85d7-4a68-aaa7-f9cbb6680dbd)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/54f59cd2-0ccc-4e1f-9cbe-71dc1ad3d8f1)

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/2577b84b-1051-4400-b40a-1ca1465389c0)

**Comment by jnm2377** [comment]
cc: @theiliad

**Comment by theiliad** [comment]
mostly looking to design on updating those files, can I be of any help?

**Comment by jeanservaas** [comment]
Someone on Carbon or brand team just needs to do a content sweep here and make sure everything's using the correct hexes and correct swatches are shown etc.

**Comment by jeanservaas** [comment]
sorry @xxxle0 there are multiple errors not sure which color you're referring to... 

I want to clarify that the full palette with all of the correct hex colors is available in the Carbon Sketch kit (not the data viz Sketch kit)... you can download that here:
 
https://www.carbondesignsystem.com/get-started/design/sketch#get-the-kit

The Carbon Data viz color page and the data viz kit need to be updated because there are several errors.
