### ISSUE TITLE
Provide code examples

### ISSUE THREAD

**Issue by james-gardner** [carbon-design-system/carbon-website#901]
## Summary
The explanations are great but they provide imagery instead of solid code examples.

## Relevant information
It would be helpful to see actual code snippets to replace the images that you can copy and paste to tinker with. The snippets would use the grid in conjunction with the necessary components from the design library.

**Comment by jnm2377** [comment]
Hi @james-gardner, I'm not sure what you mean. We have code examples for each component in the `Code` tab. The other pages have images because they are meant more as UX and style guidance for each component.

**Comment by james-gardner** [comment]
Hi @jnm2377 

I've seen the code example for components and they're great. However, I've not seen them used in conjunction with your grid implementation without you adding in your own margins etc. In particular I was interested as to how you might center the login form and more detail on which components are used. 

While I agree with these pages being for guidance purposes it's not immediately clear how much effort I have to put in to build something using your library.

**Comment by vpicone** [comment]
>it's not immediately clear how much effort I have to put in to build something using your library.

This is a really hard goal to hit, as people use Carbon differently across many frameworks and products. Your effort determines how many or how few features you wish to use. All of our Component demos are getting live, editable, [code snippets](https://www.carbondesignsystem.com/components/button/code). Is that what you had in mind @james-gardner

**Comment by james-gardner** [comment]
@vpicone Pretty much, just more composite examples. The login dialog is an over-simplified example but it would be good to see how you would use the to grid to put that together with niche things like horizontal/vertical centering. In more complex patterns which components would be applicable.

**Comment by james-gardner** [comment]
I'd add to this and say that the UX guidance for Login doesn't cover things like the unhappy paths, how 'invalid credential' scenarios should be displayed etc. When you move over to the form guidance different margins are used when there's text below the header and so on.

**Comment by vpicone** [comment]
@james-gardner We're not providing code for specific patterns at this time as there's a variety of possible methods with various frameworks. We want to avoid a scenario where folks interpret our code examples as the canonical method for employing a specific pattern. This is something that's on our roadmap for when we have have subsystems and component sharing more aligned in the styling approach.

If you have a specific issue with the ux guidance, definitely open an issue so that can be addressed!
