### ISSUE TITLE
[Website component bug] Do / Don't component has added padding 

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#903]
Need to remove forced padding on Do / Don't component so that it is optional / not true by default:

- please also make top bar 3px tall (it is 2px now)

See example of forced padding causing an issue on the Color overview page:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/64dced00-21d0-4c3f-a39a-baf4cfd65e2a)

**Comment by claycrenshaw** [comment]
Here is what's happening with text-based do/don't component:

![screen shot 2019-02-07 at 10 22 50 am](https://user-images.githubusercontent.com/20912642/52425956-b201df80-2ac2-11e9-848c-c02dbfc31818.png)
