### ISSUE TITLE
[UX enhancement] Website code snippet needs "Show more" button; update color tokens

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#908]
Show more option is missing on the block code snippet on the site; it can only be seen on hover so I think it's pulling in the wrong color tokens.

**This is happening on:**
Getting started > Developers
Accessibility > Developers
Guidelines > Themes page

- [x] "Show more" is disappearing due to website theme override of the component; it's still pulling in a white theme show more button; update color tokens (see spec)

![image](https://user-images.githubusercontent.com/43144260/52888050-d18ead00-313f-11e9-8bc7-c55c6a2d2517.png)

- [x] Need copy icon here (not copy file icon) added this issue to the component repo

https://github.com/IBM/carbon-components/issues/1680

- [ ] The scroll bar is showing up black on black in Chrome and Safari; the user can't really see it

## What's happening now

**Show more not visible except on hover**
![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/027142d6-9cc6-46dc-af2a-fb41af24438e)

<br>

**hover**
![image](https://user-images.githubusercontent.com/43144260/52886424-da7c8000-3139-11e9-83a1-b6bd08fbb222.png)

**Comment by alisonjoseph** [comment]
The show more button is there, it just has the wrong colors and padding.

view on hover
<img width="596" alt="screen shot 2019-02-06 at 8 02 08 pm" src="https://user-images.githubusercontent.com/2753488/52386101-1d5b9b00-2a4a-11e9-90aa-9ec24de89602.png">

**Comment by jeanservaas** [comment]
this is an add-on that we adopted from the digital team because the extended horizontal code was running under the show more button and the code snippet icon... it looked messy and the smaller the code snippet got, the worse the experience was.

**Comment by alisonjoseph** [comment]
gotcha 👍 so something we should probably move to website-addons then

**Comment by jeanservaas** [comment]
Icon issue captured here in components repo too:
https://github.com/IBM/carbon-components/issues/1680

**Comment by jeanservaas** [comment]
Hey @alisonjoseph sorry, this is the last one I'll move, but this one is a bit more urgent too in that the Show more is not showing up at all except on hover... so it looks broken. It may not make it into the next sprint, but I just don't want it to be lumped in with the more "aspirational" issues. 

It's happening on a few tabs of Getting started Developers, on the Accessibility page and all over the Themes page

**Comment by alisonjoseph** [comment]
👍 agreed this should get fixed soon. Totally forgot about it

**Comment by alisonjoseph** [comment]
@jeanservaas this is in a PR, except the scrollbar color, that's a chrome default right now.
