### ISSUE TITLE
Left nav loses selected state when following a direct link

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#909]
The left nav doesn't show the selected parent if you've navigated by following a link

This shows that behavior:

- copy link to a component page
- open new tab
- paste and go
- see that the parent `Components` is not selected.

![Feb-13-2020 15-25-33](https://user-images.githubusercontent.com/19270502/74479716-47257a00-4e75-11ea-861a-d7827c95e78e.gif)

Here is correct behavior showing the parent getting the selected state after it's collapsed. 

![Feb-13-2020 14-42-30](https://user-images.githubusercontent.com/19270502/74479837-805dea00-4e75-11ea-9d55-ec5ee622912a.gif)

**Comment by jnm2377** [comment]
hmm.. this is strange. It's working totally fine on the gatsby site. Need to dig some more to see what we're doing different on the carbon site. cc: @vpicone would you have any ideas?

**Comment by vpicone** [comment]
@jnm2377 did we release your fix and update the carbon website to use that release?

**Comment by alisonjoseph** [comment]
confirmed this is working correctly now
