### ISSUE TITLE
missing icon errors on Icon Library page

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#912]
on https://www.carbondesignsystem.com/guidelines/icons/library/

Interactions
Nominal
Ordinal
 
Are listing "Error: no component found for Interactions"
![image](https://user-images.githubusercontent.com/35537391/74573468-b4590e00-4f4e-11ea-9d16-75107cea4b27.png)

16/interactions.svg
16/nominal.svg
16/ordinal.svg
32/interactions.svg
32/nominal.svg
32/ordinal.svg

are all present in the repo, and seem to have correct entries in packages/icons/metadata.yml and packages/icons/categories.yml

They are also missing from the Sketch Plugin:
![image](https://user-images.githubusercontent.com/35537391/74573610-1580e180-4f4f-11ea-92b4-3b941ded376d.png)

**Comment by xxxle0** [comment]
https://github.com/carbon-design-system/gatsby-theme-carbon/issues/665 duplicated

**Comment by chrisconnors-ibm** [comment]
Since those same icons are missing from the Sketch library I suspect this is not an issue with the gatsby theme.

**Comment by chrisconnors-ibm** [comment]
But if https://github.com/carbon-design-system/gatsby-theme-carbon/issues/665 will fix both problems feel free to close as a duplicate

**Comment by vpicone** [comment]
@chrisconnors-ibm issue is with metadata upstream: https://github.com/carbon-design-system/carbon/issues/5224
