### ISSUE TITLE
Need bigger offset for anchor link scroll

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#918]
Due to adding banner, anchor link scroll now need a bigger offset so headers are not cut off. See giphy:

![feb-06-2019 22-47-03](https://user-images.githubusercontent.com/15144993/52391105-42a7d380-2a61-11e9-8552-577182ef3c5e.gif)

**Comment by alisonjoseph** [comment]
We need a better way of doing the offset. Currently we are adding a margin-top to the before attribute of the heading, however if anything is above the heading then we run in to issues with overlap. I'm worried adding an additional 40px will cause issues. cc @carbon-design-system/ui

**Comment by alisonjoseph** [comment]
@vpicone fixed this
