### ISSUE TITLE
[content] text-input: icons in field

### ISSUE THREAD

**Issue by aagonzales** [carbon-design-system/carbon-website#92]
Add guidelines around when/how to add icons into a `text-input` field.

Scenarios include:
- date picker
- show/hide password [#3512](https://github.com/carbon-design-system/carbon/issues/3512) 
- delete 
- edit/non-editable [#3018](https://github.com/carbon-design-system/carbon/issues/3018)

Slack convo:
https://ibm-cloudplatform.slack.com/archives/C0M053VPT/p1564420553139000

**Comment by joshblack** [comment]
Hey there! Going to close this one out due to inactivity. Feel free to comment and I can re-open!
