### ISSUE TITLE
[pictograms] same picto being called for two tiles on website

### ISSUE THREAD

**Issue by laurenmrice** [carbon-design-system/carbon-website#924]
The same artwork is being shown for two different pictograms on the Pictogram Library page. https://www.carbondesignsystem.com/guidelines/pictograms/library
<img width="602" alt="Screen Shot 2020-02-17 at 7 03 07 PM" src="https://user-images.githubusercontent.com/43969356/74784265-2a21ea00-526d-11ea-8c29-fab159a7d701.png">

--------------------------------------------------------------------------------------------------

They seem to be correct in the repo, just need to update it on our website. Should be:
![Screen Shot 2020-02-18 at 9 53 42 AM](https://user-images.githubusercontent.com/43969356/74784363-589fc500-526d-11ea-9228-10bcce3178fa.png)

**Comment by tw15egan** [comment]
Still seems to be an issue

**Comment by laurenmrice** [comment]
Closing, this has been fixed.
