### ISSUE TITLE
Broken links for Design resources (Icons, Themes)

### ISSUE THREAD

**Issue by kinueng** [carbon-design-system/carbon-website#940]
## Detailed description

> Describe in detail the issue you're having.

There are broken links on the website regarding Icons and Themes.  The broken links are of the format `sketch://add-library/cloud/*`

Places where you can find examples of the broken links
https://www.carbondesignsystem.com/resources#design-resources
https://www.carbondesignsystem.com/guidelines/icons/usage/

> What did you expect to happen? What happened instead? What would you like to see changed?

I would like for the links to take me to a page where I can get more details on Icons and Themes.

> What browser are you working in?

Chrome Version 80.0.3987.116 (Official Build) (64-bit)

## Steps to reproduce the issue

1. Go to page https://www.carbondesignsystem.com/resources#design-resources
2. Click on a card like 
![image](https://user-images.githubusercontent.com/31117513/75168165-0e469a00-56ec-11ea-8fe6-e26b71e7deaa.png)

3. Observe nothing happens from the click
4. Hover curser over the card and notice the card's `href="sketch://add-library/cloud/Onwv2"`

**Comment by aagonzales** [comment]
Those are the correct links. The links should automatically prompt you to open the libraries in Sketch. I have just tried them all and they work for me.

This is what should happen when you click on a tile (taken today so they are working)
![Mar-04-2020 14-11-49](https://user-images.githubusercontent.com/11670886/75918956-494e7900-5e22-11ea-80dd-64fbf770727e.gif)


@kinueng We need to do a little trouble-shooting for why they won't work for you. 
- Do you have Sketch installed?
- Do you have an add blocker in active?

**Comment by aagonzales** [comment]
It also sounds like the cards aren't broken but didn't do what you expect. 

You can find additional information about themes and icons under the guidelines section of the website.
- https://www.carbondesignsystem.com/guidelines/color/overview
https://www.carbondesignsystem.com/guidelines/icons/usage

Any time you see a tile with the Sketch logo (yellow diamond) on it, the tile will be a prompt to open the design asset in Sketch and not be linking you to further documentation on the website.

**Comment by kinueng** [comment]
Hi @aagonzales,

- Do you have Sketch installed? **No**
- Do you have an ad blocker active? **Yes**

Interesting... I might be the wrong audience for the links.  I had assumed that those links would give me some kind of downloadable archive (i.e. `*.zip` files) where I could expand and view files on my local machine.

I do not have a design background, so I do not use design tools like Sketch and Adobe Illustrator.  I'm from a software engineering background.  

I had blindly assumed the Sketch links were some kind of `*.zip` containing all the icons from this page https://www.ibm.com/design/language/iconography/ui-icons/library.  Given shallow knowledge of Sketch, I did not realize the yellow diamond is Sketch's logo.

I would agree to have this issue closed as `work as intended`.

**Comment by kinueng** [comment]
I assumed `Get the IBM Icons` link was a shortcut that allowed me to download the icons rather than going to the GitHub repository and download it from there.

**Comment by mjabbink** [comment]
@aagonzales should this close?

**Comment by aagonzales** [comment]
Yes, the links will only work if you already have Sketch installed. Those theme kit files also would not contain the icon assets you were looking for, those icons assets would be a part of these files (which you still need Sketch to download). https://www.carbondesignsystem.com/resources#color-grid-and-icons

![image](https://user-images.githubusercontent.com/11670886/81948803-c1c27a80-95c7-11ea-81ca-aba15309d2eb.png)


If you're only looking for icons and don't have Sketch then you can download them individual from the library page:
https://www.carbondesignsystem.com/guidelines/icons/library

Or download the folder from repo:
https://github.com/carbon-design-system/carbon/tree/master/packages/icons/src/svg
