### ISSUE TITLE
Tab component missing 16px padding

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#943]
Bug with motion page tabs component
- [ ] missing 16px padding all around
- [ ] missing background behind images
- [ ] clicking on a tab for some reason scrolls back to top of page

![image](https://user-images.githubusercontent.com/15144993/52457691-d9879500-2b20-11e9-8b6b-e84475c4772b.png)

**Comment by lovemecomputer** [comment]
this issue addressed in https://github.com/carbon-design-system/carbon-website/pull/1010
