### ISSUE TITLE
The search input has an incorrect icon in Carbon X

### ISSUE THREAD

**Issue by asudoh** [carbon-design-system/carbon-website#944]
Copied from: #IBM/carbon-components#1740 and IBM/carbon-components#1750.

## Detailed description
The clear button shows the magnifying glass instead of x

## Steps to reproduce the issue

1. Type something into a search field

- Screenshots or code
![image](https://user-images.githubusercontent.com/15086604/52427139-484ff880-2af7-11e9-8a6c-9fb8cc4c65c2.png)

**Comment by alisonjoseph** [comment]
I think we just need to copy over latest experimental html from carbon-components for this to work
