### ISSUE TITLE
Audit of PAL and BX sites  

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#944]
Conduct a PAL site audit.

Details regarding questions to be answered and structure here: https://www.notion.so/carbondesignsystem/PAL-and-BX-audit-c68a5c15ea6444ee85d1c5a83ef3235c

**Comment by connor-leech** [comment]
Audit here: https://www.notion.so/carbondesignsystem/PAL-Audit-c9b8c10b0332409a8345b6894c4d059e
