### ISSUE TITLE
QA: Tables flow off page in mobile view

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#948]
## Detailed description

> Describe in detail the issue you're having.
When viewing the [Tables: Code](http://localhost:8000/components/data-table/code) page on mobile (Firefox), the tables flow off the page on both sides.

> Is this issue related to a specific component?
Tables

> What did you expect to happen? What happened instead? What would you like to see changed?
Expected the table to resize dynamically

> What browser are you working in?
Firefox

> What version of the Carbon Design System are you using?
10 (Beta)

> What offering/product do you work on? Any pressing ship or release dates we should be aware of?

## Steps to reproduce the issue

1. Step one
Collapse browser to most narrow to emulate mobile browser
2. Step two
Scroll down and view tables

> Please create a reduced test case in code sandbox
> https://codesandbox.io/s/r4zxq9pvq

## Additional information

- Screenshots or code
- Notes

**Comment by tw15egan** [comment]
Tested and can verify that it is fixed by wrapping all `table` elements on the component pages in a container div, and then setting an `overflow-x: auto` on the container.
