### ISSUE TITLE
[docs] Clarify toggle component labeling options

### ISSUE THREAD

**Issue by janchild** [carbon-design-system/carbon-website#95]
### Summary
Improve the guidance for the large and small toggle options by:
* clarifying the labeling options that are available, and 
* including the reasoning behind the design decision to help users make the right choice.

Page to update: 
https://www.carbondesignsystem.com/components/toggle/usage

Per Slack conversation: 
https://ibm-studios.slack.com/archives/C0M053VPT/p1563300070300200

**Comment by laurenmrice** [comment]
Closing, because this has been resolved in our docs
