### ISSUE TITLE
forward/next controls on / incorrect

### ISSUE THREAD

**Issue by chrisconnors-ibm** [carbon-design-system/carbon-website#959]
## Homepage forward/next incorrect

-->

## Expected
on https://www.carbondesignsystem.com/ 'previous page button' shouldn't have a value or be active (this is 'page 1'); next page control should be "**Getting started: About Carbon**"

## Actual
 'previous page button' is **Home**; next page control is "**Getting started: Design**"
![image](https://user-images.githubusercontent.com/35537391/75484811-7b219480-5977-11ea-9db8-2375cdc8123a.png)

**Comment by sstrubberg** [comment]
@vpicone is there something special about the Carbon site regarding this bug? All of our other sites are exhibiting [this issue](https://github.com/carbon-design-system/gatsby-theme-carbon/issues/746) on the homepage.

**Comment by vpicone** [comment]
@sstrubberg yeah, we specify a special title `Homepage` while the theme is looking for `Home` in order to hide it. Looking at the git blame for the title, it got migrated with the initial commit so not intentional.
