### ISSUE TITLE
/components/ routing wrong

### ISSUE THREAD

**Issue by shixiedesign** [carbon-design-system/carbon-website#959]
https://next.carbondesignsystem.com/components/ is routing to 
https://next.carbondesignsystem.com/components/code which doesn't exist, landing in 404. 
Should route to 
https://next.carbondesignsystem.com/components/overview

**Comment by alisonjoseph** [comment]
This is because whoever updated these never changed the file name. `code.md` needs to be `overview.md` inside each folder.

**Comment by tw15egan** [comment]
After talking with @shixiedesign, https://next.carbondesignsystem.com/components/ doesn't exist so it does correctly 404. If anything, this is an enhancement but not pressing at the moment.
