### ISSUE TITLE
Iconography Page

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#96]
@chrisconnors-ibm to update based on sprint planning meeting comments on scope

**Comment by shinytoyrobots** [comment]
Comprises https://github.com/carbon-design-system/carbon-website-gatsby/issues/75 and https://github.com/carbon-design-system/carbon-website-gatsby/issues/76 (which will be closed)

**Comment by shinytoyrobots** [comment]
Blocked by https://github.com/IBM/carbon-elements/issues/19

**Comment by claycrenshaw** [comment]
Below are the rough user stories for Iconography on Carbondesignsystem.com today. Will all of these stories need to be covered in this sprint for the new Duo icons? Are there any additional ones? @chrisconnors-ibm @kuehndaniel @jeanservaas 

## Library Tab

- [ ] As a user, I can scan all icons visually to find the one I need by image or name (thumbnail grid)
- [ ] As a user, I can search all icons by keyword to find the one I need (search function)
- [ ] As a user, I can instantly see the token for any icon in the set (no interaction needed)
- [ ] As a user, I can copy the code for any icon with a single click (copy icon button on rollover)
- [ ] As a user, I can download the .svg for any icon with a single click (download button on rollover) 

## Usage Tab

As a user, I can find documentation on the proper usage of Carbon Icons, including:
  

- [ ]   Links to IDL icon library, icon GH repo and design kit
- [ ]     Visual usage
  - [ ]         Sizing
  - [ ]         Background
  - [ ]         Padding
  - [ ]         Color
  - [ ]         Weight
  - [ ]         Pixel Grid
- [ ]     Developer Usage
  - [ ]         Using SVG Sprite
  - [ ]         Using SVG Sprite from static assets
  - [ ]         CSS
  - [ ]         Inline SVG
  - [ ]         Main Files
  - [ ]         Accessibility

        
## Contribution Tab

As a user, I can learn how to contribute icons to Carbon, including guidance on:

- [ ] Designer Guidelines
  - [ ]         Adding icons via pull request or GH issue
  - [ ]         Exporting SVG’s from Sketch and Illustrator
- [ ]     Developer Guidelines
  - [ ]         Naming SVG files
  - [ ]         Prepping SVG XML code
  - [ ]         Submitting new SVG's
  - [ ]         Testing SVG's

**Comment by claycrenshaw** [comment]
Basically blocked on this until we can get the requirements established.

**Comment by chrisconnors-ibm** [comment]
ASAP but before the TT, this page:

http://design-system.stage1.mybluemix.net/style/iconography/library

…needs to display current glyphs and the new 32x32 icons (union of our 32x32 and the new ones from cameron) as found in a sensibly named src directory in the carbon-elements package. That's it.

**Comment by claycrenshaw** [comment]
Transferring to Connors based on scope as discussed with him.

**Comment by joshblack** [comment]
http://staging.carbondesignsystem.com/experimental/iconography/library staging link for page 👍
