### ISSUE TITLE
Include data table action bar example on component/data-table/code/ page

### ISSUE THREAD

**Issue by marceltrautmann** [carbon-design-system/carbon-website#967]
https://www.carbondesignsystem.com/components/data-table/code

Include a working example of the "Multi-select / batch action" since it is a commonly used pattern

This used to be included v9 and has surprised a number of designers that it's no longer represented.

https://ibm-studios.slack.com/archives/C0M053VPT/p1582910901101800

**Comment by tw15egan** [comment]
Might also be helpful to have a blurb that lets users know there are more variations shown on the Storybook page: https://react.carbondesignsystem.com/?path=/story/datatable--default
