### ISSUE TITLE
Hint text for icon library should not have "pencil"

### ISSUE THREAD

**Issue by designertyler** [carbon-design-system/carbon-website#968]
We suggest searching for the term "pencil" in the search field, but it does not return any results.

<img width="1321" alt="screen shot 2019-02-08 at 11 41 11 am" src="https://user-images.githubusercontent.com/19270502/52495596-d6c78700-2b96-11e9-895a-b0f7a19a9531.png">

<img width="1368" alt="screen shot 2019-02-08 at 11 43 21 am" src="https://user-images.githubusercontent.com/19270502/52495600-da5b0e00-2b96-11e9-8417-29ad522d6540.png">

**Comment by shixiedesign** [comment]
Design and content can help with creating the meta data. But could dev please help/advice on how to set it up, where meta data should live, etc...

**Comment by mjabbink** [comment]
@shixiedesign Need a no results design.

**Comment by designertyler** [comment]
Changing the title back to the original intent of the issue. There's already an issue to improve searching for icons with meta data tags https://github.com/carbon-design-system/issue-tracking/issues/44

There have already been two issues to address the icon no results page, but they were closed without that issue being resolved. Let's make sure we're in sync before changing or closing an issue to make sure the work is still being tracked.

**Comment by shixiedesign** [comment]
@designertyler this instance of the experience being broken is not the real issue though. It will not be an issue once we add meta data. If you'd like to keep this one as is, I can make a new issue for it.

**Comment by shixiedesign** [comment]
@mjabbink designs for the icon page is fully fleshed out already here: https://github.com/carbon-design-system/carbon-website/issues/1094
