### ISSUE TITLE
QA [Icon usage page] — svg rendering poorly in "sizing" section

### ISSUE THREAD

**Issue by mjabbink** [carbon-design-system/carbon-website#969]
<img width="965" alt="screen shot 2019-02-08 at 11 40 09 am" src="https://user-images.githubusercontent.com/32881239/52495620-ec3cb100-2b96-11e9-93ec-853ed34b67f6.png">

<img width="886" alt="screen shot 2019-02-08 at 11 39 54 am" src="https://user-images.githubusercontent.com/32881239/52495629-f199fb80-2b96-11e9-9758-20a4902e266f.png">

**Comment by chrisconnors-ibm** [comment]
**issue:** Image in the 'Sizing' section of https://next.carbondesignsystem.com/guidelines/iconography/usage (and https://www.ibm.com/design/language/elements/icons) has off the pixel grid elements, meaning the 16 and 32 px size examples are anti aliased when they should be crisp.

Screen shot:
![image](https://media.github.ibm.com/user/1852/files/b571e41e-2f8e-11e9-9a59-d2c28abeb4f0)

Source SVG: 
https://next.carbondesignsystem.com/iconography-usage-sizing-1-50afa2ff637154079e04f1f7aec837ee.svg

**Expected:** Image is crisp and not antialiased examples for 16 and 32 sizes, minimally anti aliased for 20 and 24 sizes.

**Actual:** all sizes are not on the pixel grid and are anti-aliased

**Comment by chrisconnors-ibm** [comment]
problem is SVG not correct. first step is to create this correctly
![image](https://media.github.ibm.com/user/1852/files/69b25b4c-2f90-11e9-9d1d-73ccdd7bad23)

**Comment by shixiedesign** [comment]
![image](https://user-images.githubusercontent.com/15144993/52742827-41fdc880-2f9e-11e9-904b-0e38e9746613.png)

**Comment by conradennis** [comment]
just in case @chrisconnors-ibm sent me an SVG version with updated icons and I reformatted it to match Chiu's original: https://ibm.box.com/s/nzzpxr9bdpqt221v4dqymkzb1jsyh44r

**Comment by chrisconnors-ibm** [comment]
@shixiedesign at least part of the problem was the source SVG had shapes off the pixel grid - the file @conradennis refers to above fixes that at least.

**Comment by shixiedesign** [comment]
I understand what you are referring to. The pixel grid doesn't align. We cannot make sure pixel grid align because the size of the icon there is not a real 32px, and that is because the image at `max` breakpoint is 1120px wide. The icon falls on pixel grid perfectly when site is at `xlg` breakpoint, but we cannot export image for `xlg` breakpoint because our site doesn't know how to scale svg up. Hope that make sense.... @chrisconnors-ibm @conradennis

**Comment by mjabbink** [comment]
I’m certainly not an expert but here is my observation. I viewed this on my laptop (retina) and it was ranked on Carbon. You saw the image. I tried it in LG break point and also janked and was medium breakpoint. I checked the DL site and all fine. Nice and crispy in all breakpoints. This leads me to believe there are other issues beside off pixel business (which does not really show up in retina displays). It looked and felt like compression of sorts but hell if I know.

**Comment by mjabbink** [comment]
the top image above in this thread is much more than "off pixel." Does not even look like an svg. Seems more png with compression or scaled up too much.

**Comment by mjabbink** [comment]
oh, and at mobile we use a new svg in a square 1:1 container.

<img width="502" alt="screen shot 2019-02-13 at 8 36 17 pm" src="https://user-images.githubusercontent.com/32881239/52756390-2ced5d80-2fcf-11e9-8cf8-fbf2ffac3331.png">

**Comment by shixiedesign** [comment]
Hmm.. lemme just grab the DL site image and see if that fixes the problem.

**Comment by chrisconnors-ibm** [comment]
With an SVG we can guarantee (assuming Asset width does not exceed breakpoint) an asset will be on the grid at 100% size and at 50% size on @1x resolutions, 100%, 75%, 50%, and 25% @2x resolutions. any breakpoints between that all bets are off.

Rendering it as a PNG likely makes this worse at all scales/breakpoints, fwiw.

**Comment by shixiedesign** [comment]
Made new issue for adding mobile image #1124
