### ISSUE TITLE
IE11: Images aren't taking up space

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#973]
![image](https://user-images.githubusercontent.com/1691245/52495924-a46a5980-2b97-11e9-80e0-ca4004de5d90.png)

Expecting:

![image](https://user-images.githubusercontent.com/1691245/52495946-adf3c180-2b97-11e9-94e6-09c4d5454e69.png)

**Comment by asudoh** [comment]
Just looking at https://next.carbondesignsystem.com/getting-started/designers#download-the-kit-from-github - @mattrosno Do you think the problem still reproduces? Thanks!

**Comment by asudoh** [comment]
Nevermind, sorry - Realized that this report is specific to IE.
