### ISSUE TITLE
IE11: Page navigation on Accessibility page isn't showing dark background

### ISSUE THREAD

**Issue by mattrosno** [carbon-design-system/carbon-website#977]
![image](https://user-images.githubusercontent.com/1691245/52496286-923ceb00-2b98-11e9-90cf-55f75b033d51.png)

But it's working on other pages like Developer (still IE11):

![image](https://user-images.githubusercontent.com/1691245/52496360-bac4e500-2b98-11e9-91c9-938fd28a2101.png)

**Comment by asudoh** [comment]
@mattrosno Just looking at https://next.carbondesignsystem.com/guidelines/accessibility/overview now - Do you think the problem still reproduces? Thanks!

**Comment by asudoh** [comment]
Nevermind, sorry - Realized that this report is specific to IE.
