### ISSUE TITLE
Create a persuasive "why you should use Carbon" document

### ISSUE THREAD

**Issue by shinytoyrobots** [carbon-design-system/carbon-website#978]
### Summary

A document on the Carbon website that makes the clear argument "why use Carbon"; highlighting the benefits both short-term and long-term.

Analogous to the kind of "Persuade your boss" letters that many conferences put on their website (e.g. https://smashingconf.com/sf-2019/convince-your-boss).

Target audience - OM and Eng leaders within IBM.

### Justification

Targets our OKR of enthusiastic adoption. Addresses specific question and blockers that come up often.

### Desired UX and success metrics

- Clear summary (a "one or two-pager").
- Backed up by data, as that data becomes available.
- A focus on "why Carbon?" rather than "why a design system?"

### Must-have functionality

- Specifically address the balance between up-front implementation cost versus long-term benefit

**Comment by joshblack** [comment]
Hey there! Going to close this out due to inactivity, feel free to comment and I can re-open and keep helping out!
