### ISSUE TITLE
Definition Tooltip: Outdated visual spec

### ISSUE THREAD

**Issue by janhassel** [carbon-design-system/carbon-website#981]
## Detailed description

The image showing the visual spec of the definition tooltip seems to be out of date. The sketch kit, react storybook and written spec above the image (on this page: https://www.carbondesignsystem.com/components/tooltip/style) all state the top and bottom padding is using `$spacing-03`.

## Additional information

Image on Carbon website
![image](https://user-images.githubusercontent.com/28265588/75994457-4bd0d180-5efb-11ea-8bb1-2aaa2f14f876.png)

Written spec on Carbon website
![image](https://user-images.githubusercontent.com/28265588/75994496-5be8b100-5efb-11ea-961c-48e5640911aa.png)

Screenshot from react storybook
![image](https://user-images.githubusercontent.com/28265588/75994527-660aaf80-5efb-11ea-8fe4-5715850e2b5f.png)

**Comment by tw15egan** [comment]
@carbon-design-system/design can you confirm what is correct and what should be updated?

**Comment by laurenmrice** [comment]
The bottom padding should be $spacing-03 (8px/.5rem) so the style table and react storybook are right. The style image needs to be updated to reflect this.

**Comment by laurenmrice** [comment]
**Update:** We have changed our guidance to use `spacing-02` (4px) for definition tooltip. This is an update we have made in v11 and is correct across the website, code, and sketch kit.

Website: https://v11.carbondesignsystem.com/components/tooltip/style#structure
Code: https://carbon-react-next.netlify.app/?path=/story/experimental-unstable-tooltip--definition
Sketch kit:
<img width="818" alt="Screen Shot 2022-02-09 at 3 43 31 PM" src="https://user-images.githubusercontent.com/43969356/153295142-63ff0f75-3f6a-4fcf-b2d5-987791c49f3c.png">
