### ISSUE TITLE
Not enough spacing between multiple component examples

### ISSUE THREAD

**Issue by emyarod** [carbon-design-system/carbon-website#982]
Number input

![image](https://user-images.githubusercontent.com/8265238/52496689-a03f3b80-2b99-11e9-9437-f55a6e355ad4.png)

Text input

![image](https://user-images.githubusercontent.com/8265238/52496583-5e15fa00-2b99-11e9-9992-8810c8df5f80.png)

**Comment by jnm2377** [comment]
It also seems that the number input arrows are off.

**Comment by emyarod** [comment]
@jnm2377 are you referring to my screenshot only, or is it still present on the live website?

the number input arrow positioning should have been addressed in https://github.com/IBM/carbon-components/pull/1764

**Comment by jnm2377** [comment]
@emyarod it's still present on my localhost but it may be that the html or the carbon-components package hasn't been updated for this.

**Comment by emyarod** [comment]
@jnm2377 it looks like the website markup is not identical to the example markup in the docs. manually adding the wrapper div from https://github.com/IBM/carbon-components/pull/1622 and https://github.com/IBM/carbon-components/pull/1764 resolves the issue

I'm not sure how the examples are being generated in the new website but they aren't matching the component docs
