### ISSUE TITLE
QA [Website image component] Fixed component images are malfunctioning in mobile

### ISSUE THREAD

**Issue by jeanservaas** [carbon-design-system/carbon-website#983]
Component images are extending beyond the canvas in mobile:

![image.png](https://images.zenhubusercontent.com/5b96e742f28d730b01a470c0/e7316804-c1c6-46b9-9534-6aabd2ea1724)

**Comment by tw15egan** [comment]
Seems to only be happening in Safari

**Comment by tw15egan** [comment]
Seems to be resolved /shrug
