### ISSUE TITLE
docs: Copy edit and standardization needed for icon, pictogram contribution docs

### ISSUE THREAD

**Issue by connor-leech** [carbon-design-system/carbon-website#999]
## Overview

Our copy and guidance pages for icon and pictogram contributions need some love.

#### Carbon

* [Icons](https://www.carbondesignsystem.com/guidelines/icons/contribute)
* [Pictograms](https://www.carbondesignsystem.com/guidelines/pictograms/contribute)

#### IDL

* [Icons](https://www.ibm.com/design/language/iconography/ui-icons/contribute)
* [Pictograms](https://www.ibm.com/design/language/iconography/pictograms/contribute)

We also have some icon contribution content [on GitHub](https://github.com/carbon-design-system/carbon/tree/master/packages/icons) that should maintain parity with the website.

**Comment by joshblack** [comment]
Hey there! Going to close this out as I think this was addressed, feel free to comment and I can re-open!
